import type { DomainModule } from '@/lib/domains/types';

const demographicsModule: DomainModule = {
  definition: {
    id: 'demographics',
    label: { fr: 'Démographie', en: 'Demographics' },
    description: {
      fr: 'Dynamiques démographiques : fécondité, vieillissement de la population, urbanisation et croissance démographique.',
      en: 'Demographic dynamics: fertility, population aging, urbanization and population growth.',
    },
    icon: '👥',
    group: 'society',
    active: true,
    seedSources: [
      'https://population.un.org/wpp/',
      'https://data.worldbank.org/indicator/SP.DYN.TFRT.IN',
      'https://data.worldbank.org/indicator/SP.URB.TOTL.IN.ZS',
    ],
    indicators: [
      {
        id: 'fertility_rate',
        label: { fr: 'Indice de fécondité', en: 'Fertility rate' },
        unit: 'ratio',
        unitLabel: { fr: 'enfants/femme', en: 'children/woman' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 2.1, good: 1.8, fair: 1.5, poor: 1.2 },
        minValue: 0,
        maxValue: 7,
      },
      {
        id: 'median_age',
        label: { fr: 'Âge médian', en: 'Median age' },
        unit: 'years',
        unitLabel: { fr: 'ans', en: 'years' },
        direction: 'lower_is_better',
        weight: 2,
        thresholds: { excellent: 30, good: 37, fair: 43, poor: 48 },
        minValue: 15,
        maxValue: 55,
      },
      {
        id: 'urbanization_rate',
        label: { fr: 'Taux d\'urbanisation', en: 'Urbanization rate' },
        unit: 'percent',
        unitLabel: { fr: '% population', en: '% population' },
        direction: 'higher_is_better',
        weight: 1,
        thresholds: { excellent: 85, good: 72, fair: 58, poor: 40 },
        minValue: 0,
        maxValue: 100,
      },
      {
        id: 'population_growth',
        label: { fr: 'Croissance démographique', en: 'Population growth' },
        unit: 'percent',
        unitLabel: { fr: '%/an', en: '%/yr' },
        direction: 'higher_is_better',
        weight: 2,
        thresholds: { excellent: 1.0, good: 0.5, fair: 0.0, poor: -0.5 },
        minValue: -3,
        maxValue: 5,
      },
    ],
  },
  seedData: [
    // ── Europe de l'Ouest ──────────────────────────────────────────────────
    { geoCode: 'FR', geoName: 'France',         dataYear: 2023, values: { fertility_rate: 1.80, median_age: 42, urbanization_rate: 81, population_growth: 0.3 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2023, values: { fertility_rate: 1.53, median_age: 45, urbanization_rate: 77, population_growth: 0.2 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2023, values: { fertility_rate: 1.56, median_age: 40, urbanization_rate: 84, population_growth: 0.5 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2023, values: { fertility_rate: 1.25, median_age: 47, urbanization_rate: 71, population_growth: -0.2 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2023, values: { fertility_rate: 1.19, median_age: 44, urbanization_rate: 81, population_growth: 0.5 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2023, values: { fertility_rate: 1.40, median_age: 45, urbanization_rate: 67, population_growth: 0.1 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2023, values: { fertility_rate: 1.62, median_age: 42, urbanization_rate: 92, population_growth: 0.6 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2023, values: { fertility_rate: 1.60, median_age: 41, urbanization_rate: 98, population_growth: 0.5 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2023, values: { fertility_rate: 1.47, median_age: 43, urbanization_rate: 59, population_growth: 0.6 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2023, values: { fertility_rate: 1.67, median_age: 41, urbanization_rate: 88, population_growth: 0.5 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2023, values: { fertility_rate: 1.73, median_age: 42, urbanization_rate: 88, population_growth: 0.4 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2023, values: { fertility_rate: 1.32, median_age: 43, urbanization_rate: 85, population_growth: 0.2 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2023, values: { fertility_rate: 1.56, median_age: 40, urbanization_rate: 82, population_growth: 0.7 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2023, values: { fertility_rate: 1.78, median_age: 37, urbanization_rate: 64, population_growth: 1.1 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2023, values: { fertility_rate: 1.34, median_age: 45, urbanization_rate: 80, population_growth: -0.4 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2023, values: { fertility_rate: 1.52, median_age: 43, urbanization_rate: 74, population_growth: 0.8 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2023, values: { fertility_rate: 1.45, median_age: 39, urbanization_rate: 92, population_growth: 1.8 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2023, values: { fertility_rate: 1.94, median_age: 37, urbanization_rate: 94, population_growth: 0.9 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2023, values: { fertility_rate: 1.13, median_age: 42, urbanization_rate: 95, population_growth: 3.2 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2023, values: { fertility_rate: 1.32, median_age: 38, urbanization_rate: 67, population_growth: 1.5 } },
    // ── Europe de l'Est & Balkans ────────────────────────────────────────────
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2023, values: { fertility_rate: 1.29, median_age: 41, urbanization_rate: 60, population_growth: -0.3 } },
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2023, values: { fertility_rate: 1.71, median_age: 43, urbanization_rate: 74, population_growth: 0.3 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2023, values: { fertility_rate: 1.52, median_age: 41, urbanization_rate: 54, population_growth: 0.0 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2023, values: { fertility_rate: 1.52, median_age: 43, urbanization_rate: 72, population_growth: -0.3 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2023, values: { fertility_rate: 1.48, median_age: 44, urbanization_rate: 58, population_growth: -0.5 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2023, values: { fertility_rate: 1.60, median_age: 43, urbanization_rate: 54, population_growth: -0.6 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2023, values: { fertility_rate: 1.56, median_age: 45, urbanization_rate: 76, population_growth: -0.7 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2023, values: { fertility_rate: 1.60, median_age: 44, urbanization_rate: 55, population_growth: 0.1 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2023, values: { fertility_rate: 1.41, median_age: 42, urbanization_rate: 69, population_growth: -0.4 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2023, values: { fertility_rate: 1.38, median_age: 44, urbanization_rate: 68, population_growth: -0.8 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2023, values: { fertility_rate: 1.36, median_age: 44, urbanization_rate: 68, population_growth: -0.6 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2023, values: { fertility_rate: 1.48, median_age: 43, urbanization_rate: 57, population_growth: -0.6 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2023, values: { fertility_rate: 1.23, median_age: 43, urbanization_rate: 50, population_growth: -0.7 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2023, values: { fertility_rate: 1.36, median_age: 38, urbanization_rate: 63, population_growth: -0.5 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2023, values: { fertility_rate: 1.40, median_age: 39, urbanization_rate: 58, population_growth: -0.2 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2023, values: { fertility_rate: 1.28, median_age: 38, urbanization_rate: 43, population_growth: -1.3 } },
    // ── Amérique du Nord ──────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',  dataYear: 2023, values: { fertility_rate: 1.66, median_age: 38, urbanization_rate: 83, population_growth: 0.5 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2023, values: { fertility_rate: 1.44, median_age: 41, urbanization_rate: 82, population_growth: 1.8 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2023, values: { fertility_rate: 1.83, median_age: 29, urbanization_rate: 81, population_growth: 1.1 } },
    // ── Amérique Centrale & Caraïbes ──────────────────────────────────────
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2023, values: { fertility_rate: 2.70, median_age: 23, urbanization_rate: 52, population_growth: 1.8 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2023, values: { fertility_rate: 2.37, median_age: 24, urbanization_rate: 59, population_growth: 1.5 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2023, values: { fertility_rate: 1.82, median_age: 28, urbanization_rate: 74, population_growth: 0.5 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2023, values: { fertility_rate: 2.30, median_age: 26, urbanization_rate: 59, population_growth: 1.1 } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2023, values: { fertility_rate: 1.48, median_age: 33, urbanization_rate: 81, population_growth: 0.7 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2023, values: { fertility_rate: 2.30, median_age: 30, urbanization_rate: 68, population_growth: 1.5 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2023, values: { fertility_rate: 1.45, median_age: 42, urbanization_rate: 77, population_growth: -0.2 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2023, values: { fertility_rate: 2.22, median_age: 28, urbanization_rate: 83, population_growth: 1.0 } },
    { geoCode: 'HT', geoName: 'Haiti',          dataYear: 2023, values: { fertility_rate: 2.84, median_age: 24, urbanization_rate: 58, population_growth: 1.2 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2023, values: { fertility_rate: 1.93, median_age: 30, urbanization_rate: 56, population_growth: 0.3 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2023, values: { fertility_rate: 1.63, median_age: 37, urbanization_rate: 53, population_growth: 0.3 } },
    // ── Amérique du Sud ──────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2023, values: { fertility_rate: 1.75, median_age: 33, urbanization_rate: 87, population_growth: 0.7 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2023, values: { fertility_rate: 2.25, median_age: 32, urbanization_rate: 93, population_growth: 0.9 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2023, values: { fertility_rate: 1.55, median_age: 35, urbanization_rate: 88, population_growth: 0.7 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2023, values: { fertility_rate: 1.83, median_age: 31, urbanization_rate: 81, population_growth: 1.0 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2023, values: { fertility_rate: 2.15, median_age: 30, urbanization_rate: 78, population_growth: 1.0 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2023, values: { fertility_rate: 2.18, median_age: 29, urbanization_rate: 88, population_growth: 0.3 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2023, values: { fertility_rate: 2.20, median_age: 28, urbanization_rate: 64, population_growth: 1.3 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2023, values: { fertility_rate: 2.65, median_age: 25, urbanization_rate: 71, population_growth: 1.4 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2023, values: { fertility_rate: 2.45, median_age: 26, urbanization_rate: 62, population_growth: 1.3 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2023, values: { fertility_rate: 1.51, median_age: 35, urbanization_rate: 96, population_growth: 0.3 } },
    // ── Océanie ───────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2023, values: { fertility_rate: 1.63, median_age: 38, urbanization_rate: 86, population_growth: 2.0 } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2023, values: { fertility_rate: 1.61, median_age: 37, urbanization_rate: 87, population_growth: 1.8 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2023, values: { fertility_rate: 3.50, median_age: 22, urbanization_rate: 13, population_growth: 2.0 } },
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2023, values: { fertility_rate: 2.70, median_age: 28, urbanization_rate: 57, population_growth: 0.5 } },
    // ── Asie de l'Est ───────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2023, values: { fertility_rate: 1.20, median_age: 49, urbanization_rate: 92, population_growth: -0.4 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2023, values: { fertility_rate: 0.72, median_age: 44, urbanization_rate: 82, population_growth: 0.1 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2023, values: { fertility_rate: 1.09, median_age: 39, urbanization_rate: 65, population_growth: 0.0 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2023, values: { fertility_rate: 0.87, median_age: 42, urbanization_rate: 79, population_growth: 0.0 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2023, values: { fertility_rate: 2.84, median_age: 28, urbanization_rate: 69, population_growth: 1.5 } },
    // ── Asie du Sud-Est ─────────────────────────────────────────────────
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2023, values: { fertility_rate: 1.04, median_age: 42, urbanization_rate: 100, population_growth: 1.5 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2023, values: { fertility_rate: 2.28, median_age: 29, urbanization_rate: 58, population_growth: 1.0 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2023, values: { fertility_rate: 1.34, median_age: 39, urbanization_rate: 52, population_growth: 0.3 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2023, values: { fertility_rate: 2.01, median_age: 31, urbanization_rate: 38, population_growth: 0.9 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2023, values: { fertility_rate: 2.77, median_age: 24, urbanization_rate: 47, population_growth: 1.5 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2023, values: { fertility_rate: 1.82, median_age: 30, urbanization_rate: 78, population_growth: 1.8 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2023, values: { fertility_rate: 2.17, median_age: 29, urbanization_rate: 31, population_growth: 0.7 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2023, values: { fertility_rate: 2.40, median_age: 26, urbanization_rate: 25, population_growth: 1.4 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2023, values: { fertility_rate: 2.56, median_age: 24, urbanization_rate: 37, population_growth: 1.4 } },
    // ── Asie du Sud ─────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2023, values: { fertility_rate: 2.01, median_age: 28, urbanization_rate: 36, population_growth: 1.0 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2023, values: { fertility_rate: 3.52, median_age: 22, urbanization_rate: 38, population_growth: 2.0 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2023, values: { fertility_rate: 2.04, median_age: 28, urbanization_rate: 39, population_growth: 1.2 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2023, values: { fertility_rate: 1.90, median_age: 33, urbanization_rate: 19, population_growth: 0.5 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2023, values: { fertility_rate: 2.05, median_age: 25, urbanization_rate: 21, population_growth: 1.2 } },
    { geoCode: 'AF', geoName: 'Afghanistan',    dataYear: 2023, values: { fertility_rate: 4.53, median_age: 17, urbanization_rate: 26, population_growth: 2.8 } },
    // ── Asie centrale ───────────────────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2023, values: { fertility_rate: 2.77, median_age: 31, urbanization_rate: 58, population_growth: 1.4 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2023, values: { fertility_rate: 2.88, median_age: 28, urbanization_rate: 50, population_growth: 1.6 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2023, values: { fertility_rate: 2.67, median_age: 27, urbanization_rate: 53, population_growth: 1.4 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2023, values: { fertility_rate: 3.10, median_age: 26, urbanization_rate: 37, population_growth: 1.7 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2023, values: { fertility_rate: 3.25, median_age: 22, urbanization_rate: 28, population_growth: 2.1 } },
    // ── Moyen-Orient ──────────────────────────────────────────────────────
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2023, values: { fertility_rate: 2.30, median_age: 30, urbanization_rate: 84, population_growth: 1.7 } },
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2023, values: { fertility_rate: 2.90, median_age: 30, urbanization_rate: 93, population_growth: 2.0 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2023, values: { fertility_rate: 1.68, median_age: 32, urbanization_rate: 77, population_growth: 1.2 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2023, values: { fertility_rate: 1.88, median_age: 33, urbanization_rate: 77, population_growth: 1.1 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2023, values: { fertility_rate: 1.40, median_age: 33, urbanization_rate: 87, population_growth: 0.8 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2023, values: { fertility_rate: 1.82, median_age: 33, urbanization_rate: 99, population_growth: 1.0 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2023, values: { fertility_rate: 2.10, median_age: 34, urbanization_rate: 100, population_growth: 1.3 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2023, values: { fertility_rate: 1.86, median_age: 32, urbanization_rate: 90, population_growth: 1.0 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2023, values: { fertility_rate: 2.65, median_age: 31, urbanization_rate: 87, population_growth: 1.8 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2023, values: { fertility_rate: 2.72, median_age: 24, urbanization_rate: 91, population_growth: 1.4 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2023, values: { fertility_rate: 2.07, median_age: 30, urbanization_rate: 89, population_growth: -0.5 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2023, values: { fertility_rate: 3.50, median_age: 20, urbanization_rate: 71, population_growth: 2.3 } },
    { geoCode: 'YE', geoName: 'Yemen',          dataYear: 2023, values: { fertility_rate: 3.80, median_age: 19, urbanization_rate: 39, population_growth: 2.3 } },
    // ── Ex-URSS (hors Asie centrale) ──────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2023, values: { fertility_rate: 1.42, median_age: 40, urbanization_rate: 75, population_growth: -0.2 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2023, values: { fertility_rate: 1.22, median_age: 42, urbanization_rate: 70, population_growth: -1.5 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2023, values: { fertility_rate: 1.38, median_age: 41, urbanization_rate: 80, population_growth: -0.3 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2023, values: { fertility_rate: 1.72, median_age: 38, urbanization_rate: 60, population_growth: -0.3 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2023, values: { fertility_rate: 1.58, median_age: 36, urbanization_rate: 63, population_growth: -0.2 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2023, values: { fertility_rate: 1.69, median_age: 33, urbanization_rate: 57, population_growth: 0.6 } },
    // ── Afrique du Nord ──────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2023, values: { fertility_rate: 3.10, median_age: 24, urbanization_rate: 43, population_growth: 2.0 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2023, values: { fertility_rate: 2.36, median_age: 30, urbanization_rate: 64, population_growth: 1.2 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2023, values: { fertility_rate: 2.86, median_age: 29, urbanization_rate: 74, population_growth: 1.6 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2023, values: { fertility_rate: 2.07, median_age: 33, urbanization_rate: 70, population_growth: 0.8 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2023, values: { fertility_rate: 2.30, median_age: 29, urbanization_rate: 81, population_growth: 1.2 } },
    { geoCode: 'SD', geoName: 'Sudan',          dataYear: 2023, values: { fertility_rate: 4.40, median_age: 19, urbanization_rate: 36, population_growth: 2.5 } },
    // ── Afrique de l'Ouest ───────────────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2023, values: { fertility_rate: 5.30, median_age: 18, urbanization_rate: 53, population_growth: 2.5 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2023, values: { fertility_rate: 3.62, median_age: 21, urbanization_rate: 58, population_growth: 2.1 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2023, values: { fertility_rate: 4.45, median_age: 19, urbanization_rate: 52, population_growth: 2.5 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2023, values: { fertility_rate: 4.30, median_age: 19, urbanization_rate: 49, population_growth: 2.7 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2023, values: { fertility_rate: 5.90, median_age: 16, urbanization_rate: 44, population_growth: 3.0 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2023, values: { fertility_rate: 4.80, median_age: 17, urbanization_rate: 32, population_growth: 2.5 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2023, values: { fertility_rate: 6.89, median_age: 15, urbanization_rate: 17, population_growth: 3.7 } },
    { geoCode: 'GN', geoName: 'Guinea',         dataYear: 2023, values: { fertility_rate: 4.57, median_age: 18, urbanization_rate: 38, population_growth: 2.4 } },
    { geoCode: 'BJ', geoName: 'Benin',          dataYear: 2023, values: { fertility_rate: 4.86, median_age: 18, urbanization_rate: 49, population_growth: 2.7 } },
    { geoCode: 'TG', geoName: 'Togo',           dataYear: 2023, values: { fertility_rate: 4.22, median_age: 19, urbanization_rate: 43, population_growth: 2.3 } },
    { geoCode: 'SL', geoName: 'Sierra Leone',   dataYear: 2023, values: { fertility_rate: 4.07, median_age: 19, urbanization_rate: 43, population_growth: 2.1 } },
    { geoCode: 'LR', geoName: 'Liberia',        dataYear: 2023, values: { fertility_rate: 4.15, median_age: 19, urbanization_rate: 53, population_growth: 2.3 } },
    { geoCode: 'MR', geoName: 'Mauritania',     dataYear: 2023, values: { fertility_rate: 4.40, median_age: 20, urbanization_rate: 57, population_growth: 2.7 } },
    // ── Afrique de l'Est ─────────────────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2023, values: { fertility_rate: 3.52, median_age: 20, urbanization_rate: 29, population_growth: 2.3 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2023, values: { fertility_rate: 4.20, median_age: 19, urbanization_rate: 22, population_growth: 2.6 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2023, values: { fertility_rate: 4.72, median_age: 18, urbanization_rate: 37, population_growth: 3.0 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2023, values: { fertility_rate: 4.60, median_age: 16, urbanization_rate: 26, population_growth: 3.0 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2023, values: { fertility_rate: 3.90, median_age: 19, urbanization_rate: 17, population_growth: 2.4 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2023, values: { fertility_rate: 3.92, median_age: 19, urbanization_rate: 39, population_growth: 2.5 } },
    { geoCode: 'MW', geoName: 'Malawi',         dataYear: 2023, values: { fertility_rate: 4.10, median_age: 17, urbanization_rate: 18, population_growth: 2.6 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2023, values: { fertility_rate: 4.72, median_age: 17, urbanization_rate: 38, population_growth: 2.7 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2023, values: { fertility_rate: 4.35, median_age: 17, urbanization_rate: 46, population_growth: 2.8 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2023, values: { fertility_rate: 3.48, median_age: 19, urbanization_rate: 32, population_growth: 2.0 } },
    { geoCode: 'SO', geoName: 'Somalia',        dataYear: 2023, values: { fertility_rate: 6.31, median_age: 16, urbanization_rate: 47, population_growth: 3.1 } },
    // ── Afrique centrale ─────────────────────────────────────────────────
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2023, values: { fertility_rate: 5.90, median_age: 17, urbanization_rate: 46, population_growth: 3.2 } },
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2023, values: { fertility_rate: 4.42, median_age: 18, urbanization_rate: 58, population_growth: 2.5 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2023, values: { fertility_rate: 5.25, median_age: 17, urbanization_rate: 68, population_growth: 3.2 } },
    { geoCode: 'TD', geoName: 'Chad',           dataYear: 2023, values: { fertility_rate: 5.65, median_age: 16, urbanization_rate: 24, population_growth: 3.0 } },
    { geoCode: 'CG', geoName: 'Congo',          dataYear: 2023, values: { fertility_rate: 4.25, median_age: 19, urbanization_rate: 68, population_growth: 2.4 } },
    // ── Afrique australe ─────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2023, values: { fertility_rate: 2.46, median_age: 28, urbanization_rate: 68, population_growth: 1.2 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2023, values: { fertility_rate: 2.65, median_age: 25, urbanization_rate: 72, population_growth: 1.8 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2023, values: { fertility_rate: 3.17, median_age: 22, urbanization_rate: 54, population_growth: 1.8 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2023, values: { fertility_rate: 1.40, median_age: 37, urbanization_rate: 41, population_growth: 0.1 } },
  ],
  seedDataPrev: [
    // ── Europe de l'Ouest ────────────────────────────────────────────────── (Sources: World Bank SP.DYN.TFRT.IN, SP.URB.TOTL.IN.ZS, SP.POP.GROW 2022; UN WPP 2022 median age)
    { geoCode: 'FR', geoName: 'France',         dataYear: 2022, values: { fertility_rate: 1.79, median_age: 42, urbanization_rate: 78.8, population_growth: 0.50 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2022, values: { fertility_rate: 1.46, median_age: 46, urbanization_rate: 81.8, population_growth: -0.02 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2022, values: { fertility_rate: 1.56, median_age: 40, urbanization_rate: 83.1, population_growth: 0.92 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2022, values: { fertility_rate: 1.24, median_age: 48, urbanization_rate: 69.5, population_growth: -0.20 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2022, values: { fertility_rate: 1.16, median_age: 46, urbanization_rate: 80.0, population_growth: 0.72 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2022, values: { fertility_rate: 1.43, median_age: 46, urbanization_rate: 61.1, population_growth: 0.70 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2022, values: { fertility_rate: 1.49, median_age: 42, urbanization_rate: 95.0, population_growth: 0.95 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2022, values: { fertility_rate: 1.53, median_age: 42, urbanization_rate: 87.5, population_growth: 0.81 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2022, values: { fertility_rate: 1.41, median_age: 44, urbanization_rate: 69.0, population_growth: 0.96 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2022, values: { fertility_rate: 1.53, median_age: 41, urbanization_rate: 88.4, population_growth: 0.68 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2022, values: { fertility_rate: 1.55, median_age: 42, urbanization_rate: 88.4, population_growth: 0.79 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2022, values: { fertility_rate: 1.32, median_age: 43, urbanization_rate: 73.7, population_growth: 0.27 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2022, values: { fertility_rate: 1.41, median_age: 40, urbanization_rate: 83.0, population_growth: 0.90 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2022, values: { fertility_rate: 1.54, median_age: 39, urbanization_rate: 63.9, population_growth: 1.98 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2022, values: { fertility_rate: 1.32, median_age: 46, urbanization_rate: 78.6, population_growth: -1.26 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2022, values: { fertility_rate: 1.39, median_age: 44, urbanization_rate: 84.9, population_growth: 0.83 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2022, values: { fertility_rate: 1.31, median_age: 39, urbanization_rate: 94.8, population_growth: 2.02 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2022, values: { fertility_rate: 1.59, median_age: 37, urbanization_rate: 94.2, population_growth: 2.51 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2022, values: { fertility_rate: 1.13, median_age: 42, urbanization_rate: 94.8, population_growth: 3.50 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2022, values: { fertility_rate: 1.33, median_age: 38, urbanization_rate: 66.8, population_growth: 1.68 } },
    // ── Europe de l'Est & Balkans ────────────────────────────────────────────
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2022, values: { fertility_rate: 1.29, median_age: 42, urbanization_rate: 59.8, population_growth: -0.43 } },
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2022, values: { fertility_rate: 1.64, median_age: 44, urbanization_rate: 72.7, population_growth: 1.57 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2022, values: { fertility_rate: 1.57, median_age: 42, urbanization_rate: 53.2, population_growth: -0.28 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2022, values: { fertility_rate: 1.56, median_age: 44, urbanization_rate: 70.2, population_growth: -0.27 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2022, values: { fertility_rate: 1.53, median_age: 45, urbanization_rate: 57.0, population_growth: -0.60 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2022, values: { fertility_rate: 1.71, median_age: 45, urbanization_rate: 52.2, population_growth: -0.39 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2022, values: { fertility_rate: 1.78, median_age: 45, urbanization_rate: 73.5, population_growth: -0.65 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2022, values: { fertility_rate: 1.58, median_age: 45, urbanization_rate: 55.5, population_growth: 0.12 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2022, values: { fertility_rate: 1.41, median_age: 42, urbanization_rate: 68.2, population_growth: -0.38 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2022, values: { fertility_rate: 1.50, median_age: 44, urbanization_rate: 67.0, population_growth: -0.90 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2022, values: { fertility_rate: 1.37, median_age: 44, urbanization_rate: 68.5, population_growth: -1.05 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2022, values: { fertility_rate: 1.49, median_age: 44, urbanization_rate: 56.1, population_growth: -0.82 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2022, values: { fertility_rate: 1.20, median_age: 43, urbanization_rate: 49.5, population_growth: -0.77 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2022, values: { fertility_rate: 1.38, median_age: 37, urbanization_rate: 62.4, population_growth: -0.42 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2022, values: { fertility_rate: 1.45, median_age: 39, urbanization_rate: 58.2, population_growth: -0.11 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2022, values: { fertility_rate: 1.30, median_age: 38, urbanization_rate: 42.6, population_growth: -1.52 } },
    // ── Amérique du Nord ──────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',  dataYear: 2022, values: { fertility_rate: 1.66, median_age: 38, urbanization_rate: 80.0, population_growth: 0.58 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2022, values: { fertility_rate: 1.33, median_age: 42, urbanization_rate: 82.4, population_growth: 1.80 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2022, values: { fertility_rate: 1.94, median_age: 30, urbanization_rate: 79.2, population_growth: 0.75 } },
    // ── Amérique Centrale & Caraïbes ──────────────────────────────────────
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2022, values: { fertility_rate: 2.80, median_age: 23, urbanization_rate: 51.8, population_growth: 1.85 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2022, values: { fertility_rate: 2.45, median_age: 24, urbanization_rate: 58.7, population_growth: 1.56 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2022, values: { fertility_rate: 1.86, median_age: 28, urbanization_rate: 73.5, population_growth: 0.48 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2022, values: { fertility_rate: 2.35, median_age: 26, urbanization_rate: 59.0, population_growth: 1.15 } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2022, values: { fertility_rate: 1.52, median_age: 33, urbanization_rate: 80.8, population_growth: 0.72 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2022, values: { fertility_rate: 2.35, median_age: 30, urbanization_rate: 67.5, population_growth: 1.55 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2022, values: { fertility_rate: 1.50, median_age: 42, urbanization_rate: 77.2, population_growth: -0.18 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2022, values: { fertility_rate: 2.28, median_age: 28, urbanization_rate: 82.5, population_growth: 1.02 } },
    { geoCode: 'HT', geoName: 'Haiti',          dataYear: 2022, values: { fertility_rate: 2.90, median_age: 24, urbanization_rate: 57.5, population_growth: 1.22 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2022, values: { fertility_rate: 1.95, median_age: 30, urbanization_rate: 55.8, population_growth: 0.28 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2022, values: { fertility_rate: 1.65, median_age: 37, urbanization_rate: 52.5, population_growth: 0.32 } },
    // ── Amérique du Sud ──────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2022, values: { fertility_rate: 1.63, median_age: 34, urbanization_rate: 87.4, population_growth: 0.36 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2022, values: { fertility_rate: 1.48, median_age: 32, urbanization_rate: 92.1, population_growth: 0.21 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2022, values: { fertility_rate: 1.26, median_age: 36, urbanization_rate: 88.6, population_growth: 0.50 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2022, values: { fertility_rate: 1.66, median_age: 32, urbanization_rate: 78.1, population_growth: 1.07 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2022, values: { fertility_rate: 2.18, median_age: 30, urbanization_rate: 77.5, population_growth: 1.05 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2022, values: { fertility_rate: 2.22, median_age: 29, urbanization_rate: 87.8, population_growth: 0.25 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2022, values: { fertility_rate: 2.25, median_age: 28, urbanization_rate: 63.5, population_growth: 1.35 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2022, values: { fertility_rate: 2.70, median_age: 25, urbanization_rate: 70.5, population_growth: 1.42 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2022, values: { fertility_rate: 2.50, median_age: 26, urbanization_rate: 61.5, population_growth: 1.35 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2022, values: { fertility_rate: 1.53, median_age: 35, urbanization_rate: 95.5, population_growth: 0.28 } },
    // ── Océanie ───────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2022, values: { fertility_rate: 1.63, median_age: 38, urbanization_rate: 87.3, population_growth: 1.29 } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2022, values: { fertility_rate: 1.66, median_age: 37, urbanization_rate: 83.9, population_growth: -0.06 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2022, values: { fertility_rate: 3.55, median_age: 22, urbanization_rate: 13.2, population_growth: 2.02 } },
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2022, values: { fertility_rate: 2.75, median_age: 28, urbanization_rate: 56.5, population_growth: 0.48 } },
    // ── Asie de l'Est ───────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2022, values: { fertility_rate: 1.26, median_age: 49, urbanization_rate: 92.0, population_growth: -0.44 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2022, values: { fertility_rate: 0.78, median_age: 45, urbanization_rate: 81.2, population_growth: -0.19 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2022, values: { fertility_rate: 1.03, median_age: 39, urbanization_rate: 65.2, population_growth: -0.01 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2022, values: { fertility_rate: 0.87, median_age: 44, urbanization_rate: 79.0, population_growth: -0.17 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2022, values: { fertility_rate: 2.90, median_age: 28, urbanization_rate: 68.5, population_growth: 1.52 } },
    // ── Asie du Sud-Est ─────────────────────────────────────────────────
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2022, values: { fertility_rate: 1.04, median_age: 39, urbanization_rate: 100,  population_growth: 3.31 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2022, values: { fertility_rate: 2.15, median_age: 31, urbanization_rate: 57.5, population_growth: 0.75 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2022, values: { fertility_rate: 1.22, median_age: 41, urbanization_rate: 59.7, population_growth: 0.01 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2022, values: { fertility_rate: 1.93, median_age: 32, urbanization_rate: 37.6, population_growth: 0.75 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2022, values: { fertility_rate: 1.93, median_age: 25, urbanization_rate: 54.8, population_growth: 0.76 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2022, values: { fertility_rate: 1.80, median_age: 30, urbanization_rate: 77.2, population_growth: 1.82 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2022, values: { fertility_rate: 2.15, median_age: 29, urbanization_rate: 31.2, population_growth: 0.72 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2022, values: { fertility_rate: 2.45, median_age: 26, urbanization_rate: 24.5, population_growth: 1.42 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2022, values: { fertility_rate: 2.60, median_age: 24, urbanization_rate: 36.8, population_growth: 1.38 } },
    // ── Asie du Sud ─────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2022, values: { fertility_rate: 1.99, median_age: 29, urbanization_rate: 34.8, population_growth: 0.79 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2022, values: { fertility_rate: 3.66, median_age: 22, urbanization_rate: 38.4, population_growth: 1.75 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2022, values: { fertility_rate: 2.18, median_age: 29, urbanization_rate: 31.7, population_growth: 1.02 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2022, values: { fertility_rate: 1.92, median_age: 33, urbanization_rate: 18.7, population_growth: 0.52 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2022, values: { fertility_rate: 2.10, median_age: 25, urbanization_rate: 20.6, population_growth: 1.25 } },
    { geoCode: 'AF', geoName: 'Afghanistan',    dataYear: 2022, values: { fertility_rate: 4.60, median_age: 17, urbanization_rate: 26.0, population_growth: 2.85 } },
    // ── Asie centrale ───────────────────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2022, values: { fertility_rate: 3.05, median_age: 31, urbanization_rate: 61.4, population_growth: 1.46 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2022, values: { fertility_rate: 2.92, median_age: 28, urbanization_rate: 49.8, population_growth: 1.62 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2022, values: { fertility_rate: 2.70, median_age: 27, urbanization_rate: 52.5, population_growth: 1.42 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2022, values: { fertility_rate: 3.15, median_age: 26, urbanization_rate: 36.5, population_growth: 1.72 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2022, values: { fertility_rate: 3.30, median_age: 22, urbanization_rate: 27.5, population_growth: 2.15 } },
    // ── Moyen-Orient ──────────────────────────────────────────────────────
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2022, values: { fertility_rate: 2.14, median_age: 32, urbanization_rate: 84.1, population_growth: 4.42 } },
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2022, values: { fertility_rate: 2.89, median_age: 30, urbanization_rate: 91.5, population_growth: 1.97 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2022, values: { fertility_rate: 1.70, median_age: 33, urbanization_rate: 76.3, population_growth: 1.20 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2022, values: { fertility_rate: 1.63, median_age: 33, urbanization_rate: 89.0, population_growth: 0.98 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2022, values: { fertility_rate: 1.39, median_age: 33, urbanization_rate: 87.0, population_growth: 0.82 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2022, values: { fertility_rate: 1.84, median_age: 33, urbanization_rate: 99.2, population_growth: 1.05 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2022, values: { fertility_rate: 2.15, median_age: 34, urbanization_rate: 100, population_growth: 1.35 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2022, values: { fertility_rate: 1.88, median_age: 32, urbanization_rate: 89.3, population_growth: 1.02 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2022, values: { fertility_rate: 2.68, median_age: 31, urbanization_rate: 86.5, population_growth: 1.85 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2022, values: { fertility_rate: 2.76, median_age: 24, urbanization_rate: 90.5, population_growth: 1.45 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2022, values: { fertility_rate: 2.10, median_age: 30, urbanization_rate: 88.5, population_growth: -0.55 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2022, values: { fertility_rate: 3.55, median_age: 20, urbanization_rate: 70.5, population_growth: 2.35 } },
    { geoCode: 'YE', geoName: 'Yemen',          dataYear: 2022, values: { fertility_rate: 3.85, median_age: 19, urbanization_rate: 38.5, population_growth: 2.32 } },
    // ── Ex-URSS (hors Asie centrale) ──────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2022, values: { fertility_rate: 1.42, median_age: 41, urbanization_rate: 74.9, population_growth: -0.35 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2022, values: { fertility_rate: 0.90, median_age: 44, urbanization_rate: 69.4, population_growth: -7.62 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2022, values: { fertility_rate: 1.40, median_age: 41, urbanization_rate: 79.5, population_growth: -0.32 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2022, values: { fertility_rate: 1.75, median_age: 38, urbanization_rate: 59.8, population_growth: -0.28 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2022, values: { fertility_rate: 1.60, median_age: 36, urbanization_rate: 62.5, population_growth: -0.18 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2022, values: { fertility_rate: 1.72, median_age: 33, urbanization_rate: 56.5, population_growth: 0.62 } },
    // ── Afrique du Nord ──────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2022, values: { fertility_rate: 2.75, median_age: 24, urbanization_rate: 42.6, population_growth: 1.49 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2022, values: { fertility_rate: 2.26, median_age: 30, urbanization_rate: 62.5, population_growth: 1.01 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2022, values: { fertility_rate: 2.90, median_age: 29, urbanization_rate: 73.5, population_growth: 1.62 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2022, values: { fertility_rate: 2.10, median_age: 33, urbanization_rate: 69.5, population_growth: 0.82 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2022, values: { fertility_rate: 2.35, median_age: 29, urbanization_rate: 80.5, population_growth: 1.22 } },
    { geoCode: 'SD', geoName: 'Sudan',          dataYear: 2022, values: { fertility_rate: 4.45, median_age: 19, urbanization_rate: 35.5, population_growth: 2.55 } },
    // ── Afrique de l'Ouest ───────────────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2022, values: { fertility_rate: 4.55, median_age: 18, urbanization_rate: 61.4, population_growth: 2.09 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2022, values: { fertility_rate: 3.68, median_age: 21, urbanization_rate: 57.5, population_growth: 2.12 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2022, values: { fertility_rate: 4.50, median_age: 19, urbanization_rate: 51.5, population_growth: 2.52 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2022, values: { fertility_rate: 4.35, median_age: 19, urbanization_rate: 48.5, population_growth: 2.72 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2022, values: { fertility_rate: 5.95, median_age: 16, urbanization_rate: 43.5, population_growth: 3.02 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2022, values: { fertility_rate: 4.85, median_age: 17, urbanization_rate: 31.5, population_growth: 2.52 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2022, values: { fertility_rate: 6.95, median_age: 15, urbanization_rate: 16.8, population_growth: 3.72 } },
    { geoCode: 'GN', geoName: 'Guinea',         dataYear: 2022, values: { fertility_rate: 4.62, median_age: 18, urbanization_rate: 37.5, population_growth: 2.42 } },
    { geoCode: 'BJ', geoName: 'Benin',          dataYear: 2022, values: { fertility_rate: 4.90, median_age: 18, urbanization_rate: 48.5, population_growth: 2.72 } },
    { geoCode: 'TG', geoName: 'Togo',           dataYear: 2022, values: { fertility_rate: 4.28, median_age: 19, urbanization_rate: 42.5, population_growth: 2.32 } },
    { geoCode: 'SL', geoName: 'Sierra Leone',   dataYear: 2022, values: { fertility_rate: 4.12, median_age: 19, urbanization_rate: 42.5, population_growth: 2.12 } },
    { geoCode: 'LR', geoName: 'Liberia',        dataYear: 2022, values: { fertility_rate: 4.20, median_age: 19, urbanization_rate: 52.5, population_growth: 2.32 } },
    { geoCode: 'MR', geoName: 'Mauritania',     dataYear: 2022, values: { fertility_rate: 4.45, median_age: 20, urbanization_rate: 56.5, population_growth: 2.72 } },
    // ── Afrique de l'Est ─────────────────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2022, values: { fertility_rate: 3.26, median_age: 20, urbanization_rate: 31.4, population_growth: 1.92 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2022, values: { fertility_rate: 4.08, median_age: 20, urbanization_rate: 22.7, population_growth: 2.62 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2022, values: { fertility_rate: 4.78, median_age: 18, urbanization_rate: 36.5, population_growth: 3.02 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2022, values: { fertility_rate: 4.65, median_age: 16, urbanization_rate: 25.5, population_growth: 3.02 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2022, values: { fertility_rate: 3.95, median_age: 19, urbanization_rate: 16.8, population_growth: 2.42 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2022, values: { fertility_rate: 3.98, median_age: 19, urbanization_rate: 38.5, population_growth: 2.52 } },
    { geoCode: 'MW', geoName: 'Malawi',         dataYear: 2022, values: { fertility_rate: 4.15, median_age: 17, urbanization_rate: 17.5, population_growth: 2.62 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2022, values: { fertility_rate: 4.78, median_age: 17, urbanization_rate: 37.5, population_growth: 2.72 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2022, values: { fertility_rate: 4.40, median_age: 17, urbanization_rate: 45.5, population_growth: 2.82 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2022, values: { fertility_rate: 3.52, median_age: 19, urbanization_rate: 31.5, population_growth: 2.02 } },
    { geoCode: 'SO', geoName: 'Somalia',        dataYear: 2022, values: { fertility_rate: 6.38, median_age: 16, urbanization_rate: 46.5, population_growth: 3.12 } },
    // ── Afrique centrale ─────────────────────────────────────────────────
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2022, values: { fertility_rate: 5.95, median_age: 17, urbanization_rate: 45.5, population_growth: 3.22 } },
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2022, values: { fertility_rate: 4.48, median_age: 18, urbanization_rate: 57.5, population_growth: 2.52 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2022, values: { fertility_rate: 5.30, median_age: 17, urbanization_rate: 67.5, population_growth: 3.22 } },
    { geoCode: 'TD', geoName: 'Chad',           dataYear: 2022, values: { fertility_rate: 5.70, median_age: 16, urbanization_rate: 23.5, population_growth: 3.02 } },
    { geoCode: 'CG', geoName: 'Congo',          dataYear: 2022, values: { fertility_rate: 4.30, median_age: 19, urbanization_rate: 67.5, population_growth: 2.42 } },
    // ── Afrique australe ─────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2022, values: { fertility_rate: 2.23, median_age: 30, urbanization_rate: 63.5, population_growth: 1.41 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2022, values: { fertility_rate: 2.68, median_age: 25, urbanization_rate: 71.5, population_growth: 1.82 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2022, values: { fertility_rate: 3.22, median_age: 22, urbanization_rate: 53.5, population_growth: 1.82 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2022, values: { fertility_rate: 1.42, median_age: 37, urbanization_rate: 40.5, population_growth: 0.12 } },
  ],
};

export default demographicsModule;
