import type { DomainModule } from '@/lib/domains/types';

const healthModule: DomainModule = {
  definition: {
    id: 'health',
    label: { fr: 'Santé', en: 'Health', es: 'Salud' },
    description: {
      fr: 'Mesure la performance des systèmes de santé nationaux via l\'espérance de vie, les dépenses, les infrastructures et la couverture universelle.',
      en: 'Measures national health system performance through life expectancy, spending, infrastructure and universal coverage.',
      es: 'Mide el rendimiento de los sistemas de salud nacionales a través de la esperanza de vida, el gasto, la infraestructura y la cobertura universal.',
    },
    icon: '🏥',
    group: 'society',
    active: true,
    seedSources: [
      'https://data.worldbank.org/indicator/SP.DYN.LE00.IN',
      'https://data.worldbank.org/indicator/SH.XPD.CHEX.GD.ZS',
      'https://data.worldbank.org/indicator/SH.MED.BEDS.ZS',
      'https://www.who.int/data/gho/data/themes/topics/universal-health-coverage',
    ],
    indicators: [
      {
        id: 'life_expectancy',
        label: { fr: 'Espérance de vie', en: 'Life expectancy', es: 'Esperanza de vida' },
        description: {
          fr: "Nombre moyen d'années qu'un nouveau-né peut espérer vivre si les taux de mortalité actuels restent constants",
          en: 'Average number of years a newborn can expect to live if current mortality rates remain constant',
        },
        unit: 'years',
        unitLabel: { fr: 'ans', en: 'years', es: 'años' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 82, good: 76, fair: 70, poor: 64 },
        minValue: 40,
        maxValue: 90,
      },
      {
        id: 'health_expenditure_gdp',
        label: { fr: 'Dépenses santé (% PIB)', en: 'Health spending (% GDP)', es: 'Gasto en salud (% PIB)' },
        description: {
          fr: "Part du PIB consacrée aux dépenses de santé courantes (hôpitaux, médecins, médicaments), publiques et privées confondues",
          en: 'Share of GDP spent on current health expenditure (hospitals, physicians, drugs), combining public and private spending',
        },
        unit: 'percent',
        unitLabel: { fr: '% PIB', en: '% GDP', es: '% PIB' },
        direction: 'higher_is_better',
        weight: 2,
        thresholds: { excellent: 9, good: 6, fair: 4, poor: 2.5 },
        minValue: 0,
        maxValue: 18,
      },
      {
        id: 'hospital_beds',
        label: { fr: 'Lits d\'hôpital (pour 1 000 hab.)', en: 'Hospital beds (per 1,000)', es: 'Camas de hospital (por 1.000 hab.)' },
        description: {
          fr: "Nombre de lits d'hôpitaux disponibles (soins aigus, réhabilitation et psychiatrie) pour 1 000 habitants",
          en: 'Number of hospital beds available (acute care, rehabilitation and psychiatry) per 1,000 inhabitants',
        },
        unit: 'ratio',
        unitLabel: { fr: 'pour 1 000', en: 'per 1,000', es: 'por 1.000' },
        direction: 'higher_is_better',
        weight: 1,
        thresholds: { excellent: 6, good: 4, fair: 2, poor: 1 },
        minValue: 0,
        maxValue: 15,
      },
      {
        id: 'uhc_index',
        label: { fr: 'Couverture santé universelle', en: 'UHC Index', es: 'Cobertura sanitaria universal' },
        description: {
          fr: "Score composite OMS mesurant l'accès effectif aux services de santé essentiels pour l'ensemble de la population (0-100)",
          en: 'WHO composite score measuring effective access to essential health services for the entire population (0-100)',
        },
        unit: 'index',
        unitLabel: { fr: 'indice /100', en: 'index /100', es: 'índice /100' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 85, good: 72, fair: 57, poor: 42 },
        minValue: 0,
        maxValue: 100,
      },
    ],
  },
  seedData: [
    // ── Europe de l'Ouest ──────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2022, values: { life_expectancy: 84.3, health_expenditure_gdp: 10.9, hospital_beds: 13.0, uhc_index: 80 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2022, values: { life_expectancy: 83.4, health_expenditure_gdp: 11.8, hospital_beds: 4.6,  uhc_index: 87 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2022, values: { life_expectancy: 83.2, health_expenditure_gdp: 9.4,  hospital_beds: 2.9,  uhc_index: 75 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2022, values: { life_expectancy: 83.0, health_expenditure_gdp: 8.7,  hospital_beds: 3.2,  uhc_index: 78 } },
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2022, values: { life_expectancy: 83.2, health_expenditure_gdp: 9.3,  hospital_beds: 3.8,  uhc_index: 88 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2022, values: { life_expectancy: 83.0, health_expenditure_gdp: 11.0, hospital_beds: 2.2,  uhc_index: 86 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2022, values: { life_expectancy: 83.2, health_expenditure_gdp: 11.4, hospital_beds: 3.6,  uhc_index: 91 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2022, values: { life_expectancy: 82.7, health_expenditure_gdp: 9.3,  hospital_beds: 2.9,  uhc_index: 90 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2022, values: { life_expectancy: 82.3, health_expenditure_gdp: 11.1, hospital_beds: 5.9,  uhc_index: 88 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2022, values: { life_expectancy: 81.1, health_expenditure_gdp: 12.8, hospital_beds: 8.0,  uhc_index: 87 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2022, values: { life_expectancy: 82.2, health_expenditure_gdp: 10.0, hospital_beds: 2.5,  uhc_index: 90 } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2022, values: { life_expectancy: 81.8, health_expenditure_gdp: 9.8,  hospital_beds: 2.6,  uhc_index: 88 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2022, values: { life_expectancy: 81.7, health_expenditure_gdp: 10.2, hospital_beds: 3.2,  uhc_index: 87 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2022, values: { life_expectancy: 81.7, health_expenditure_gdp: 9.6,  hospital_beds: 3.6,  uhc_index: 87 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2022, values: { life_expectancy: 81.3, health_expenditure_gdp: 10.5, hospital_beds: 2.5,  uhc_index: 87 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2022, values: { life_expectancy: 82.0, health_expenditure_gdp: 7.0,  hospital_beds: 3.0,  uhc_index: 84 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2022, values: { life_expectancy: 81.4, health_expenditure_gdp: 10.4, hospital_beds: 7.4,  uhc_index: 83 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2022, values: { life_expectancy: 81.4, health_expenditure_gdp: 10.7, hospital_beds: 5.6,  uhc_index: 85 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2022, values: { life_expectancy: 81.3, health_expenditure_gdp: 9.5,  hospital_beds: 3.4,  uhc_index: 78 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2022, values: { life_expectancy: 80.9, health_expenditure_gdp: 10.2, hospital_beds: 2.5,  uhc_index: 84 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2022, values: { life_expectancy: 81.7, health_expenditure_gdp: 7.7,  hospital_beds: 4.2,  uhc_index: 76 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2022, values: { life_expectancy: 82.1, health_expenditure_gdp: 5.4,  hospital_beds: 4.6,  uhc_index: 87 } },
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2022, values: { life_expectancy: 82.6, health_expenditure_gdp: 7.5,  hospital_beds: 3.0,  uhc_index: 82 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2022, values: { life_expectancy: 82.4, health_expenditure_gdp: 8.8,  hospital_beds: 4.5,  uhc_index: 81 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2022, values: { life_expectancy: 81.2, health_expenditure_gdp: 7.0,  hospital_beds: 3.4,  uhc_index: 78 } },
    // ── Europe de l'Est ────────────────────────────────────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2022, values: { life_expectancy: 78.8, health_expenditure_gdp: 8.6,  hospital_beds: 6.6,  uhc_index: 80 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2022, values: { life_expectancy: 77.7, health_expenditure_gdp: 6.5,  hospital_beds: 6.6,  uhc_index: 77 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2022, values: { life_expectancy: 76.0, health_expenditure_gdp: 7.0,  hospital_beds: 7.0,  uhc_index: 75 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2022, values: { life_expectancy: 77.5, health_expenditure_gdp: 7.0,  hospital_beds: 5.8,  uhc_index: 78 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2022, values: { life_expectancy: 78.0, health_expenditure_gdp: 7.8,  hospital_beds: 5.5,  uhc_index: 74 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2022, values: { life_expectancy: 75.5, health_expenditure_gdp: 6.3,  hospital_beds: 6.9,  uhc_index: 70 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2022, values: { life_expectancy: 75.0, health_expenditure_gdp: 8.3,  hospital_beds: 7.4,  uhc_index: 68 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2022, values: { life_expectancy: 81.3, health_expenditure_gdp: 8.7,  hospital_beds: 4.4,  uhc_index: 82 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2022, values: { life_expectancy: 78.0, health_expenditure_gdp: 7.5,  hospital_beds: 4.7,  uhc_index: 79 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2022, values: { life_expectancy: 75.1, health_expenditure_gdp: 6.7,  hospital_beds: 5.5,  uhc_index: 74 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2022, values: { life_expectancy: 75.6, health_expenditure_gdp: 7.0,  hospital_beds: 6.4,  uhc_index: 76 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2022, values: { life_expectancy: 75.2, health_expenditure_gdp: 8.5,  hospital_beds: 5.6,  uhc_index: 69 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2022, values: { life_expectancy: 77.2, health_expenditure_gdp: 9.1, hospital_beds: 3.5, uhc_index: 65 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2022, values: { life_expectancy: 76.5, health_expenditure_gdp: 8.2,  hospital_beds: 3.9,  uhc_index: 67 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2022, values: { life_expectancy: 75.3, health_expenditure_gdp: 7.0, hospital_beds: 4.3,  uhc_index: 66 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2022, values: { life_expectancy: 78.5, health_expenditure_gdp: 5.2,  hospital_beds: 2.9,  uhc_index: 64 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2022, values: { life_expectancy: 72.1, health_expenditure_gdp: 6.3,  hospital_beds: 5.8,  uhc_index: 62 } },
    // ── Amérique du Nord ────────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',  dataYear: 2022, values: { life_expectancy: 77.5, health_expenditure_gdp: 16.9, hospital_beds: 2.8,  uhc_index: 83 } },
    // ── Scandinavie & Baltes (déjà inclus ci-dessus) ─────────────────────
    // ── Asie de l'Est ───────────────────────────────────────────────────────
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2022, values: { life_expectancy: 83.6, health_expenditure_gdp: 8.4,  hospital_beds: 12.8, uhc_index: 82 } },
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2022, values: { life_expectancy: 84.0, health_expenditure_gdp: 4.5,  hospital_beds: 2.5,  uhc_index: 84 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2022, values: { life_expectancy: 80.9, health_expenditure_gdp: 6.7,  hospital_beds: 7.3,  uhc_index: 83 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2022, values: { life_expectancy: 77.1, health_expenditure_gdp: 5.5,  hospital_beds: 6.6,  uhc_index: 82 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2022, values: { life_expectancy: 71.0, health_expenditure_gdp: 4.0,  hospital_beds: 7.0,  uhc_index: 62 } },
    // ── Asie du Sud-Est ─────────────────────────────────────────────────────
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2022, values: { life_expectancy: 77.4, health_expenditure_gdp: 5.0,  hospital_beds: 2.1,  uhc_index: 80 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2022, values: { life_expectancy: 75.3, health_expenditure_gdp: 5.9,  hospital_beds: 2.6,  uhc_index: 73 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2022, values: { life_expectancy: 76.2, health_expenditure_gdp: 4.1,  hospital_beds: 1.9,  uhc_index: 73 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2022, values: { life_expectancy: 66.7, health_expenditure_gdp: 4.7,  hospital_beds: 0.9,  uhc_index: 53 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2022, values: { life_expectancy: 69.6, health_expenditure_gdp: 7.2,  hospital_beds: 0.8,  uhc_index: 55 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2022, values: { life_expectancy: 68.0, health_expenditure_gdp: 2.5,  hospital_beds: 1.5,  uhc_index: 48 } },
    // ── Asie du Sud ─────────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2022, values: { life_expectancy: 70.8, health_expenditure_gdp: 3.3,  hospital_beds: 0.5,  uhc_index: 61 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2022, values: { life_expectancy: 71.3, health_expenditure_gdp: 2.9,  hospital_beds: 1.0,  uhc_index: 59 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2022, values: { life_expectancy: 71.3, health_expenditure_gdp: 5.8,  hospital_beds: 1.0,  uhc_index: 62 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2022, values: { life_expectancy: 72.3, health_expenditure_gdp: 2.3,  hospital_beds: 0.5,  uhc_index: 43 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2022, values: { life_expectancy: 67.9, health_expenditure_gdp: 3.4,  hospital_beds: 0.6,  uhc_index: 44 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2022, values: { life_expectancy: 76.4, health_expenditure_gdp: 3.8,  hospital_beds: 3.6,  uhc_index: 67 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2022, values: { life_expectancy: 70.8, health_expenditure_gdp: 3.2,  hospital_beds: 0.3,  uhc_index: 45 } },
    { geoCode: 'AF', geoName: 'Afghanistan',    dataYear: 2022, values: { life_expectancy: 62.0, health_expenditure_gdp: 13.2, hospital_beds: 0.4,  uhc_index: 32 } },
    // ── Moyen-Orient ───────────────────────────────────────────────────────
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2022, values: { life_expectancy: 75.8, health_expenditure_gdp: 5.3,  hospital_beds: 2.2,  uhc_index: 73 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2022, values: { life_expectancy: 76.2, health_expenditure_gdp: 8.7,  hospital_beds: 1.6,  uhc_index: 75 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2022, values: { life_expectancy: 76.3, health_expenditure_gdp: 4.3,  hospital_beds: 2.9,  uhc_index: 73 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2022, values: { life_expectancy: 78.5, health_expenditure_gdp: 4.4, hospital_beds: 1.4, uhc_index: 76 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2022, values: { life_expectancy: 80.2, health_expenditure_gdp: 3.2,  hospital_beds: 1.2,  uhc_index: 74 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2022, values: { life_expectancy: 78.6, health_expenditure_gdp: 5.3,  hospital_beds: 2.0,  uhc_index: 72 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2022, values: { life_expectancy: 79.0, health_expenditure_gdp: 4.1,  hospital_beds: 2.0,  uhc_index: 73 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2022, values: { life_expectancy: 77.8, health_expenditure_gdp: 4.0,  hospital_beds: 1.5,  uhc_index: 70 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2022, values: { life_expectancy: 74.5, health_expenditure_gdp: 7.5,  hospital_beds: 1.4,  uhc_index: 68 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2022, values: { life_expectancy: 75.0, health_expenditure_gdp: 8.0,  hospital_beds: 2.7,  uhc_index: 64 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2022, values: { life_expectancy: 71.4, health_expenditure_gdp: 4.1,  hospital_beds: 1.3,  uhc_index: 52 } },
    { geoCode: 'YE', geoName: 'Yemen',          dataYear: 2022, values: { life_expectancy: 63.8, health_expenditure_gdp: 4.2,  hospital_beds: 0.7,  uhc_index: 39 } },
    // ── Asie centrale & Ex-URSS ───────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2022, values: { life_expectancy: 70.1, health_expenditure_gdp: 5.3,  hospital_beds: 8.2,  uhc_index: 72 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2022, values: { life_expectancy: 69.6, health_expenditure_gdp: 7.0,  hospital_beds: 7.5,  uhc_index: 65 } },
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2022, values: { life_expectancy: 73.2, health_expenditure_gdp: 3.3,  hospital_beds: 6.7,  uhc_index: 74 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2022, values: { life_expectancy: 72.0, health_expenditure_gdp: 5.3,  hospital_beds: 4.0,  uhc_index: 68 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2022, values: { life_expectancy: 73.0, health_expenditure_gdp: 5.5,  hospital_beds: 10.8, uhc_index: 74 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2022, values: { life_expectancy: 74.0, health_expenditure_gdp: 7.2,  hospital_beds: 2.6,  uhc_index: 67 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2022, values: { life_expectancy: 75.1, health_expenditure_gdp: 9.1,  hospital_beds: 4.2,  uhc_index: 66 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2022, values: { life_expectancy: 73.5, health_expenditure_gdp: 3.5,  hospital_beds: 4.7,  uhc_index: 63 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2022, values: { life_expectancy: 71.8, health_expenditure_gdp: 4.5,  hospital_beds: 4.4,  uhc_index: 61 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2022, values: { life_expectancy: 71.5, health_expenditure_gdp: 6.7,  hospital_beds: 4.7,  uhc_index: 57 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2022, values: { life_expectancy: 69.5, health_expenditure_gdp: 5.7,  hospital_beds: 4.0,  uhc_index: 55 } },
    // ── Amérique Latine ────────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2022, values: { life_expectancy: 72.8, health_expenditure_gdp: 9.6,  hospital_beds: 2.0,  uhc_index: 71 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2022, values: { life_expectancy: 74.4, health_expenditure_gdp: 5.5,  hospital_beds: 1.0,  uhc_index: 64 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2022, values: { life_expectancy: 76.4, health_expenditure_gdp: 9.6,  hospital_beds: 5.0,  uhc_index: 75 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2022, values: { life_expectancy: 80.2, health_expenditure_gdp: 8.4,  hospital_beds: 2.1,  uhc_index: 77 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2022, values: { life_expectancy: 76.2, health_expenditure_gdp: 7.9,  hospital_beds: 1.7,  uhc_index: 67 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2022, values: { life_expectancy: 74.0, health_expenditure_gdp: 5.2,  hospital_beds: 1.6,  uhc_index: 66 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2022, values: { life_expectancy: 72.1, health_expenditure_gdp: 3.8,  hospital_beds: 0.8,  uhc_index: 58 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2022, values: { life_expectancy: 76.0, health_expenditure_gdp: 7.6,  hospital_beds: 1.5,  uhc_index: 66 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2022, values: { life_expectancy: 78.0, health_expenditure_gdp: 11.2, hospital_beds: 5.3,  uhc_index: 80 } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2022, values: { life_expectancy: 80.3, health_expenditure_gdp: 7.3,  hospital_beds: 1.1,  uhc_index: 78 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2022, values: { life_expectancy: 76.8, health_expenditure_gdp: 7.3,  hospital_beds: 2.3,  uhc_index: 69 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2022, values: { life_expectancy: 77.8, health_expenditure_gdp: 9.2,  hospital_beds: 2.4,  uhc_index: 76 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2022, values: { life_expectancy: 73.2, health_expenditure_gdp: 4.5, hospital_beds: 1.6, uhc_index: 62 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2022, values: { life_expectancy: 71.0, health_expenditure_gdp: 5.8,  hospital_beds: 0.6,  uhc_index: 53 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2022, values: { life_expectancy: 70.5, health_expenditure_gdp: 7.1,  hospital_beds: 0.7,  uhc_index: 51 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2022, values: { life_expectancy: 74.0, health_expenditure_gdp: 7.6,  hospital_beds: 1.3,  uhc_index: 61 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2022, values: { life_expectancy: 63.6, health_expenditure_gdp: 6.9,  hospital_beds: 1.3,  uhc_index: 53 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2022, values: { life_expectancy: 71.0, health_expenditure_gdp: 7.2,  hospital_beds: 1.2,  uhc_index: 60 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2022, values: { life_expectancy: 73.8, health_expenditure_gdp: 8.6,  hospital_beds: 0.9,  uhc_index: 59 } },
    { geoCode: 'HT', geoName: 'Haiti',          dataYear: 2022, values: { life_expectancy: 63.2, health_expenditure_gdp: 3.0,  hospital_beds: 0.7,  uhc_index: 37 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2022, values: { life_expectancy: 74.5, health_expenditure_gdp: 5.8,  hospital_beds: 1.7,  uhc_index: 64 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2022, values: { life_expectancy: 73.4, health_expenditure_gdp: 5.5, hospital_beds: 3.0, uhc_index: 65 } },
    // ── Afrique du Nord ───────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2022, values: { life_expectancy: 71.8, health_expenditure_gdp: 5.8,  hospital_beds: 1.6,  uhc_index: 65 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2022, values: { life_expectancy: 74.3, health_expenditure_gdp: 5.3,  hospital_beds: 1.0,  uhc_index: 67 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2022, values: { life_expectancy: 76.4, health_expenditure_gdp: 6.2,  hospital_beds: 1.9,  uhc_index: 66 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2022, values: { life_expectancy: 76.7, health_expenditure_gdp: 7.0,  hospital_beds: 2.3,  uhc_index: 70 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2022, values: { life_expectancy: 72.5, health_expenditure_gdp: 3.3,  hospital_beds: 3.2,  uhc_index: 56 } },
    // ── Afrique de l'Ouest ────────────────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2022, values: { life_expectancy: 52.7, health_expenditure_gdp: 3.4,  hospital_beds: 0.5,  uhc_index: 40 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2022, values: { life_expectancy: 64.1, health_expenditure_gdp: 3.5,  hospital_beds: 0.9,  uhc_index: 47 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2022, values: { life_expectancy: 68.2, health_expenditure_gdp: 3.8,  hospital_beds: 0.3,  uhc_index: 42 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2022, values: { life_expectancy: 58.4, health_expenditure_gdp: 3.3,  hospital_beds: 0.4,  uhc_index: 37 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2022, values: { life_expectancy: 59.3, health_expenditure_gdp: 3.6,  hospital_beds: 0.1,  uhc_index: 34 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2022, values: { life_expectancy: 59.3, health_expenditure_gdp: 5.6,  hospital_beds: 0.4,  uhc_index: 36 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2022, values: { life_expectancy: 62.0, health_expenditure_gdp: 5.2,  hospital_beds: 0.3,  uhc_index: 31 } },
    { geoCode: 'GN', geoName: 'Guinea',         dataYear: 2022, values: { life_expectancy: 58.9, health_expenditure_gdp: 3.7,  hospital_beds: 0.3,  uhc_index: 33 } },
    { geoCode: 'BJ', geoName: 'Benin',          dataYear: 2022, values: { life_expectancy: 60.0, health_expenditure_gdp: 2.5,  hospital_beds: 0.5,  uhc_index: 35 } },
    { geoCode: 'TG', geoName: 'Togo',           dataYear: 2022, values: { life_expectancy: 61.6, health_expenditure_gdp: 5.8,  hospital_beds: 0.7,  uhc_index: 36 } },
    { geoCode: 'SL', geoName: 'Sierra Leone',   dataYear: 2022, values: { life_expectancy: 55.0, health_expenditure_gdp: 8.7,  hospital_beds: 0.4,  uhc_index: 30 } },
    { geoCode: 'LR', geoName: 'Liberia',        dataYear: 2022, values: { life_expectancy: 60.7, health_expenditure_gdp: 8.2,  hospital_beds: 0.8,  uhc_index: 34 } },
    // ── Afrique de l'Est ──────────────────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2022, values: { life_expectancy: 63.8, health_expenditure_gdp: 4.3,  hospital_beds: 1.4,  uhc_index: 46 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2022, values: { life_expectancy: 65.5, health_expenditure_gdp: 3.5,  hospital_beds: 0.3,  uhc_index: 38 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2022, values: { life_expectancy: 66.2, health_expenditure_gdp: 3.8,  hospital_beds: 0.7,  uhc_index: 42 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2022, values: { life_expectancy: 63.4, health_expenditure_gdp: 3.5,  hospital_beds: 0.5,  uhc_index: 44 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2022, values: { life_expectancy: 66.1, health_expenditure_gdp: 6.5,  hospital_beds: 1.6,  uhc_index: 51 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2022, values: { life_expectancy: 65.5, health_expenditure_gdp: 3.1,  hospital_beds: 0.2,  uhc_index: 30 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2022, values: { life_expectancy: 59.3, health_expenditure_gdp: 7.2,  hospital_beds: 0.7,  uhc_index: 37 } },
    { geoCode: 'SD', geoName: 'Sudan',          dataYear: 2022, values: { life_expectancy: 65.1, health_expenditure_gdp: 4.5,  hospital_beds: 0.7,  uhc_index: 38 } },
    { geoCode: 'SO', geoName: 'Somalia',        dataYear: 2022, values: { life_expectancy: 55.4, health_expenditure_gdp: 2.9,  hospital_beds: 0.4,  uhc_index: 25 } },
    // ── Afrique centrale ──────────────────────────────────────────────────
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2022, values: { life_expectancy: 60.7, health_expenditure_gdp: 3.5,  hospital_beds: 0.8,  uhc_index: 33 } },
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2022, values: { life_expectancy: 60.3, health_expenditure_gdp: 3.5,  hospital_beds: 1.3,  uhc_index: 39 } },
    { geoCode: 'TD', geoName: 'Chad',           dataYear: 2022, values: { life_expectancy: 52.5, health_expenditure_gdp: 4.3,  hospital_beds: 0.4,  uhc_index: 28 } },
    { geoCode: 'CG', geoName: 'Congo',          dataYear: 2022, values: { life_expectancy: 63.0, health_expenditure_gdp: 2.9,  hospital_beds: 1.6,  uhc_index: 36 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2022, values: { life_expectancy: 66.5, health_expenditure_gdp: 2.8,  hospital_beds: 6.3,  uhc_index: 43 } },
    // ── Afrique australe ──────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2022, values: { life_expectancy: 63.7, health_expenditure_gdp: 8.1,  hospital_beds: 2.3,  uhc_index: 64 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2022, values: { life_expectancy: 61.0, health_expenditure_gdp: 2.6,  hospital_beds: 0.8,  uhc_index: 34 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2022, values: { life_expectancy: 60.7, health_expenditure_gdp: 3.4,  hospital_beds: 1.7,  uhc_index: 46 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2022, values: { life_expectancy: 61.2, health_expenditure_gdp: 4.9,  hospital_beds: 2.0,  uhc_index: 42 } },
    { geoCode: 'MW', geoName: 'Malawi',         dataYear: 2022, values: { life_expectancy: 62.9, health_expenditure_gdp: 5.6,  hospital_beds: 1.3,  uhc_index: 43 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2022, values: { life_expectancy: 61.1, health_expenditure_gdp: 5.8,  hospital_beds: 1.8,  uhc_index: 52 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2022, values: { life_expectancy: 59.3, health_expenditure_gdp: 7.9,  hospital_beds: 2.7,  uhc_index: 50 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2022, values: { life_expectancy: 74.4, health_expenditure_gdp: 5.7,  hospital_beds: 3.4,  uhc_index: 63 } },
    // ── Océanie ───────────────────────────────────────────────────────────
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2022, values: { life_expectancy: 64.5, health_expenditure_gdp: 2.5, hospital_beds: 0.5, uhc_index: 35 } },
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2022, values: { life_expectancy: 67.4, health_expenditure_gdp: 3.5,  hospital_beds: 2.3,  uhc_index: 52 } },
  ],
  seedDataPrev: [
    // ── Europe de l'Ouest ──────────────────────────────────────────────────
    // Sources: World Bank SP.DYN.LE00.IN, SH.XPD.CHEX.GD.ZS, SH.MED.BEDS.ZS (2021); World Bank SH_UHC_SCI (2021)
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2021, values: { life_expectancy: 84.4, health_expenditure_gdp: 12.08, hospital_beds: 12.6,  uhc_index: 85 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2021, values: { life_expectancy: 83.8, health_expenditure_gdp: 11.96, hospital_beds: 4.4,   uhc_index: 86 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2021, values: { life_expectancy: 83.2, health_expenditure_gdp: 10.34, hospital_beds: 2.9,   uhc_index: 84 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2021, values: { life_expectancy: 82.6, health_expenditure_gdp: 9.28,  hospital_beds: 3.1,   uhc_index: 82 } },
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2021, values: { life_expectancy: 83.3, health_expenditure_gdp: 10.52, hospital_beds: 3.8,   uhc_index: 89 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2021, values: { life_expectancy: 83.1, health_expenditure_gdp: 11.23, hospital_beds: 2.0,   uhc_index: 85 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2021, values: { life_expectancy: 83.2, health_expenditure_gdp: 9.81,  hospital_beds: 3.4,   uhc_index: 88 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2021, values: { life_expectancy: 83.2, health_expenditure_gdp: 9.72,  hospital_beds: 2.8,   uhc_index: 90 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2021, values: { life_expectancy: 82.3, health_expenditure_gdp: 12.25, hospital_beds: 5.8,   uhc_index: 82 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2021, values: { life_expectancy: 80.8, health_expenditure_gdp: 12.72, hospital_beds: 7.7,   uhc_index: 86 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2021, values: { life_expectancy: 81.5, health_expenditure_gdp: 12.38, hospital_beds: 2.6,   uhc_index: 92 } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2021, values: { life_expectancy: 82.2, health_expenditure_gdp: 9.55,  hospital_beds: 2.7,   uhc_index: 89 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2021, values: { life_expectancy: 81.3, health_expenditure_gdp: 11.13, hospital_beds: 2.9,   uhc_index: 85 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2021, values: { life_expectancy: 81.9, health_expenditure_gdp: 9.91,  hospital_beds: 2.8,   uhc_index: 86 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2021, values: { life_expectancy: 81.4, health_expenditure_gdp: 10.66, hospital_beds: 2.5,   uhc_index: 85 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2021, values: { life_expectancy: 82.3, health_expenditure_gdp: 6.44,  hospital_beds: 2.9,   uhc_index: 82 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2021, values: { life_expectancy: 81.2, health_expenditure_gdp: 12.19, hospital_beds: 6.9,   uhc_index: 84 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2021, values: { life_expectancy: 81.8, health_expenditure_gdp: 11.29, hospital_beds: 5.5,   uhc_index: 85 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2021, values: { life_expectancy: 81.4, health_expenditure_gdp: 11.22, hospital_beds: 3.5,   uhc_index: 83 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2021, values: { life_expectancy: 80.6, health_expenditure_gdp: 12.08, hospital_beds: 2.4,   uhc_index: 88 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2021, values: { life_expectancy: 80.1, health_expenditure_gdp: 9.03,  hospital_beds: 4.2,   uhc_index: 78 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2021, values: { life_expectancy: 82.6, health_expenditure_gdp: 5.61,  hospital_beds: 4.1,   uhc_index: 83 } },
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2021, values: { life_expectancy: 82.5, health_expenditure_gdp: 7.84,  hospital_beds: 3.1,   uhc_index: 85 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2021, values: { life_expectancy: 82.5, health_expenditure_gdp: 9.04,  hospital_beds: 4.4,   uhc_index: 80 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2021, values: { life_expectancy: 81.0, health_expenditure_gdp: 7.18,  hospital_beds: 3.3,   uhc_index: 77 } },
    // ── Europe de l'Est ────────────────────────────────────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2021, values: { life_expectancy: 77.2, health_expenditure_gdp: 9.15,  hospital_beds: 6.7,   uhc_index: 83 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2021, values: { life_expectancy: 75.4, health_expenditure_gdp: 6.37,  hospital_beds: 6.2,   uhc_index: 82 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2021, values: { life_expectancy: 74.1, health_expenditure_gdp: 7.34,  hospital_beds: 6.8,   uhc_index: 80 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2021, values: { life_expectancy: 74.6, health_expenditure_gdp: 7.63,  hospital_beds: 5.7,   uhc_index: 80 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2021, values: { life_expectancy: 76.4, health_expenditure_gdp: 8.08,  hospital_beds: 5.7,   uhc_index: 76 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2021, values: { life_expectancy: 72.8, health_expenditure_gdp: 6.45,  hospital_beds: 7.2,   uhc_index: 76 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2021, values: { life_expectancy: 71.2, health_expenditure_gdp: 8.58,  hospital_beds: 7.9,   uhc_index: 72 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2021, values: { life_expectancy: 80.5, health_expenditure_gdp: 9.00,  hospital_beds: 4.3,   uhc_index: 81 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2021, values: { life_expectancy: 77.1, health_expenditure_gdp: 7.80,  hospital_beds: 4.6,   uhc_index: 78 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2021, values: { life_expectancy: 73.1, health_expenditure_gdp: 6.95,  hospital_beds: 5.4,   uhc_index: 73 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2021, values: { life_expectancy: 73.7, health_expenditure_gdp: 7.24,  hospital_beds: 6.2,   uhc_index: 75 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2021, values: { life_expectancy: 73.5, health_expenditure_gdp: 8.72,  hospital_beds: 5.5,   uhc_index: 68 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2021, values: { life_expectancy: 75.8, health_expenditure_gdp: 9.31, hospital_beds: 3.4, uhc_index: 64 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2021, values: { life_expectancy: 74.8, health_expenditure_gdp: 8.42,  hospital_beds: 3.8,   uhc_index: 66 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2021, values: { life_expectancy: 73.5, health_expenditure_gdp: 7.15, hospital_beds: 4.2,   uhc_index: 65 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2021, values: { life_expectancy: 76.9, health_expenditure_gdp: 5.30,  hospital_beds: 2.9,   uhc_index: 63 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2021, values: { life_expectancy: 68.8, health_expenditure_gdp: 6.60,  hospital_beds: 5.7,   uhc_index: 61 } },
    // ── Amérique du Nord ────────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',  dataYear: 2021, values: { life_expectancy: 76.3, health_expenditure_gdp: 17.35, hospital_beds: 2.7,   uhc_index: 87 } },
    // ── Asie de l'Est ───────────────────────────────────────────────────────
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2021, values: { life_expectancy: 83.5, health_expenditure_gdp: 8.34,  hospital_beds: 12.8,  uhc_index: 87 } },
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2021, values: { life_expectancy: 83.1, health_expenditure_gdp: 5.15,  hospital_beds: 2.8,   uhc_index: 88 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2021, values: { life_expectancy: 80.9, health_expenditure_gdp: 6.6,   hospital_beds: 7.3,   uhc_index: 83 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2021, values: { life_expectancy: 78.1, health_expenditure_gdp: 5.26,  hospital_beds: 5.2,   uhc_index: 84 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2021, values: { life_expectancy: 70.5, health_expenditure_gdp: 4.16,  hospital_beds: 6.8,   uhc_index: 61 } },
    // ── Asie du Sud-Est ─────────────────────────────────────────────────────
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2021, values: { life_expectancy: 77.6, health_expenditure_gdp: 5.15,  hospital_beds: 2.3,   uhc_index: 82 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2021, values: { life_expectancy: 74.1, health_expenditure_gdp: 4.54,  hospital_beds: 2.5,   uhc_index: 71 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2021, values: { life_expectancy: 75.5, health_expenditure_gdp: 4.25,  hospital_beds: 1.9,   uhc_index: 72 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2021, values: { life_expectancy: 65.7, health_expenditure_gdp: 4.85,  hospital_beds: 0.9,   uhc_index: 52 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2021, values: { life_expectancy: 69.0, health_expenditure_gdp: 7.45,  hospital_beds: 0.8,   uhc_index: 54 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2021, values: { life_expectancy: 67.5, health_expenditure_gdp: 2.62,  hospital_beds: 1.5,   uhc_index: 47 } },
    // ── Asie du Sud ─────────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2021, values: { life_expectancy: 67.3, health_expenditure_gdp: 3.35,  hospital_beds: 1.6,   uhc_index: 67 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2021, values: { life_expectancy: 67.5, health_expenditure_gdp: 3.71,  hospital_beds: 1.3,   uhc_index: 66 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2021, values: { life_expectancy: 66.7, health_expenditure_gdp: 5.98,  hospital_beds: 1.0,   uhc_index: 68 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2021, values: { life_expectancy: 71.1, health_expenditure_gdp: 2.27,  hospital_beds: 0.9,   uhc_index: 52 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2021, values: { life_expectancy: 65.8, health_expenditure_gdp: 2.99,  hospital_beds: 0.6,   uhc_index: 55 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2021, values: { life_expectancy: 76.0, health_expenditure_gdp: 3.95,  hospital_beds: 3.6,   uhc_index: 66 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2021, values: { life_expectancy: 70.2, health_expenditure_gdp: 3.15,  hospital_beds: 0.3,   uhc_index: 44 } },
    { geoCode: 'AF', geoName: 'Afghanistan',    dataYear: 2021, values: { life_expectancy: 61.0, health_expenditure_gdp: 14.22, hospital_beds: 0.4,   uhc_index: 31 } },
    // ── Moyen-Orient ───────────────────────────────────────────────────────
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2021, values: { life_expectancy: 77.1, health_expenditure_gdp: 5.93,  hospital_beds: 2.5,   uhc_index: 82 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2021, values: { life_expectancy: 73.8, health_expenditure_gdp: 4.86,  hospital_beds: 1.9,   uhc_index: 81 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2021, values: { life_expectancy: 75.7, health_expenditure_gdp: 4.56,  hospital_beds: 2.9,   uhc_index: 77 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2021, values: { life_expectancy: 78.0, health_expenditure_gdp: 4.52, hospital_beds: 1.4, uhc_index: 75 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2021, values: { life_expectancy: 79.8, health_expenditure_gdp: 3.40,  hospital_beds: 1.2,   uhc_index: 73 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2021, values: { life_expectancy: 78.2, health_expenditure_gdp: 5.50,  hospital_beds: 2.0,   uhc_index: 71 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2021, values: { life_expectancy: 78.5, health_expenditure_gdp: 4.25,  hospital_beds: 2.0,   uhc_index: 72 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2021, values: { life_expectancy: 77.5, health_expenditure_gdp: 4.20,  hospital_beds: 1.5,   uhc_index: 69 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2021, values: { life_expectancy: 74.2, health_expenditure_gdp: 7.68,  hospital_beds: 1.4,   uhc_index: 67 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2021, values: { life_expectancy: 75.2, health_expenditure_gdp: 8.18,  hospital_beds: 2.7,   uhc_index: 65 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2021, values: { life_expectancy: 70.5, health_expenditure_gdp: 4.28,  hospital_beds: 1.3,   uhc_index: 51 } },
    { geoCode: 'YE', geoName: 'Yemen',          dataYear: 2021, values: { life_expectancy: 63.0, health_expenditure_gdp: 4.35,  hospital_beds: 0.7,   uhc_index: 38 } },
    // ── Asie centrale & Ex-URSS ───────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2021, values: { life_expectancy: 69.9, health_expenditure_gdp: 7.03,  hospital_beds: 7.0,   uhc_index: 80 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2021, values: { life_expectancy: 71.6, health_expenditure_gdp: 8.20,  hospital_beds: 5.5,   uhc_index: 79 } },
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2021, values: { life_expectancy: 70.1, health_expenditure_gdp: 3.99,  hospital_beds: 6.5,   uhc_index: 84 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2021, values: { life_expectancy: 71.5, health_expenditure_gdp: 5.50,  hospital_beds: 4.0,   uhc_index: 67 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2021, values: { life_expectancy: 72.3, health_expenditure_gdp: 5.70,  hospital_beds: 10.6,  uhc_index: 73 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2021, values: { life_expectancy: 72.8, health_expenditure_gdp: 7.40,  hospital_beds: 2.6,   uhc_index: 66 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2021, values: { life_expectancy: 73.5, health_expenditure_gdp: 9.36,  hospital_beds: 4.2,   uhc_index: 65 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2021, values: { life_expectancy: 72.0, health_expenditure_gdp: 3.58,  hospital_beds: 4.7,   uhc_index: 62 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2021, values: { life_expectancy: 70.3, health_expenditure_gdp: 4.60,  hospital_beds: 4.4,   uhc_index: 60 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2021, values: { life_expectancy: 70.8, health_expenditure_gdp: 6.80,  hospital_beds: 4.7,   uhc_index: 56 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2021, values: { life_expectancy: 69.0, health_expenditure_gdp: 5.80,  hospital_beds: 4.0,   uhc_index: 54 } },
    // ── Amérique Latine ────────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2021, values: { life_expectancy: 73.0, health_expenditure_gdp: 9.64,  hospital_beds: 2.5,   uhc_index: 84 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2021, values: { life_expectancy: 69.8, health_expenditure_gdp: 5.88,  hospital_beds: 1.0,   uhc_index: 79 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2021, values: { life_expectancy: 73.9, health_expenditure_gdp: 11.01, hospital_beds: 3.3,   uhc_index: 80 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2021, values: { life_expectancy: 78.9, health_expenditure_gdp: 9.72,  hospital_beds: 2.0,   uhc_index: 82 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2021, values: { life_expectancy: 72.7, health_expenditure_gdp: 9.14,  hospital_beds: 1.7,   uhc_index: 82 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2021, values: { life_expectancy: 72.3, health_expenditure_gdp: 5.40,  hospital_beds: 1.6,   uhc_index: 65 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2021, values: { life_expectancy: 71.5, health_expenditure_gdp: 3.90,  hospital_beds: 0.8,   uhc_index: 57 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2021, values: { life_expectancy: 74.5, health_expenditure_gdp: 7.80,  hospital_beds: 1.5,   uhc_index: 65 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2021, values: { life_expectancy: 77.5, health_expenditure_gdp: 11.50, hospital_beds: 5.3,   uhc_index: 79 } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2021, values: { life_expectancy: 79.5, health_expenditure_gdp: 7.50,  hospital_beds: 1.1,   uhc_index: 77 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2021, values: { life_expectancy: 75.8, health_expenditure_gdp: 7.50,  hospital_beds: 2.3,   uhc_index: 68 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2021, values: { life_expectancy: 77.0, health_expenditure_gdp: 9.40,  hospital_beds: 2.4,   uhc_index: 75 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2021, values: { life_expectancy: 72.5, health_expenditure_gdp: 4.60, hospital_beds: 1.6, uhc_index: 61 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2021, values: { life_expectancy: 70.2, health_expenditure_gdp: 5.90,  hospital_beds: 0.6,   uhc_index: 52 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2021, values: { life_expectancy: 69.5, health_expenditure_gdp: 7.25,  hospital_beds: 0.7,   uhc_index: 50 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2021, values: { life_expectancy: 73.0, health_expenditure_gdp: 7.80,  hospital_beds: 1.3,   uhc_index: 60 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2021, values: { life_expectancy: 62.3, health_expenditure_gdp: 7.10,  hospital_beds: 1.3,   uhc_index: 52 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2021, values: { life_expectancy: 69.5, health_expenditure_gdp: 7.35,  hospital_beds: 1.2,   uhc_index: 59 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2021, values: { life_expectancy: 73.0, health_expenditure_gdp: 8.80,  hospital_beds: 0.9,   uhc_index: 58 } },
    { geoCode: 'HT', geoName: 'Haiti',          dataYear: 2021, values: { life_expectancy: 62.5, health_expenditure_gdp: 3.10,  hospital_beds: 0.7,   uhc_index: 36 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2021, values: { life_expectancy: 73.8, health_expenditure_gdp: 5.90,  hospital_beds: 1.7,   uhc_index: 63 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2021, values: { life_expectancy: 72.5, health_expenditure_gdp: 5.60, hospital_beds: 3.0, uhc_index: 64 } },
    // ── Afrique du Nord ───────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2021, values: { life_expectancy: 69.0, health_expenditure_gdp: 4.61,  hospital_beds: 1.1,   uhc_index: 71 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2021, values: { life_expectancy: 73.4, health_expenditure_gdp: 5.45,  hospital_beds: 0.7,   uhc_index: 65 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2021, values: { life_expectancy: 75.8, health_expenditure_gdp: 6.30,  hospital_beds: 1.9,   uhc_index: 65 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2021, values: { life_expectancy: 75.2, health_expenditure_gdp: 7.15,  hospital_beds: 2.3,   uhc_index: 69 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2021, values: { life_expectancy: 72.0, health_expenditure_gdp: 3.40,  hospital_beds: 3.2,   uhc_index: 55 } },
    // ── Afrique de l'Ouest ────────────────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2021, values: { life_expectancy: 53.5, health_expenditure_gdp: 4.08,  hospital_beds: 0.5,   uhc_index: 47 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2021, values: { life_expectancy: 63.5, health_expenditure_gdp: 3.60,  hospital_beds: 0.9,   uhc_index: 46 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2021, values: { life_expectancy: 67.5, health_expenditure_gdp: 3.90,  hospital_beds: 0.3,   uhc_index: 41 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2021, values: { life_expectancy: 57.8, health_expenditure_gdp: 3.40,  hospital_beds: 0.4,   uhc_index: 36 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2021, values: { life_expectancy: 58.5, health_expenditure_gdp: 3.70,  hospital_beds: 0.1,   uhc_index: 33 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2021, values: { life_expectancy: 58.5, health_expenditure_gdp: 5.70,  hospital_beds: 0.4,   uhc_index: 35 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2021, values: { life_expectancy: 61.2, health_expenditure_gdp: 5.30,  hospital_beds: 0.3,   uhc_index: 30 } },
    { geoCode: 'GN', geoName: 'Guinea',         dataYear: 2021, values: { life_expectancy: 58.2, health_expenditure_gdp: 3.80,  hospital_beds: 0.3,   uhc_index: 32 } },
    { geoCode: 'BJ', geoName: 'Benin',          dataYear: 2021, values: { life_expectancy: 59.2, health_expenditure_gdp: 2.55,  hospital_beds: 0.5,   uhc_index: 34 } },
    { geoCode: 'TG', geoName: 'Togo',           dataYear: 2021, values: { life_expectancy: 60.8, health_expenditure_gdp: 5.90,  hospital_beds: 0.7,   uhc_index: 35 } },
    { geoCode: 'SL', geoName: 'Sierra Leone',   dataYear: 2021, values: { life_expectancy: 54.3, health_expenditure_gdp: 8.80,  hospital_beds: 0.4,   uhc_index: 29 } },
    { geoCode: 'LR', geoName: 'Liberia',        dataYear: 2021, values: { life_expectancy: 60.0, health_expenditure_gdp: 8.30,  hospital_beds: 0.8,   uhc_index: 33 } },
    // ── Afrique de l'Est ──────────────────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2021, values: { life_expectancy: 61.2, health_expenditure_gdp: 4.57,  hospital_beds: 1.3,   uhc_index: 53 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2021, values: { life_expectancy: 65.3, health_expenditure_gdp: 3.21,  hospital_beds: 0.3,   uhc_index: 29 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2021, values: { life_expectancy: 65.5, health_expenditure_gdp: 3.90,  hospital_beds: 0.7,   uhc_index: 41 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2021, values: { life_expectancy: 62.7, health_expenditure_gdp: 3.55,  hospital_beds: 0.5,   uhc_index: 43 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2021, values: { life_expectancy: 65.4, health_expenditure_gdp: 6.60,  hospital_beds: 1.6,   uhc_index: 50 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2021, values: { life_expectancy: 65.0, health_expenditure_gdp: 3.15,  hospital_beds: 0.2,   uhc_index: 29 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2021, values: { life_expectancy: 58.5, health_expenditure_gdp: 7.30,  hospital_beds: 0.7,   uhc_index: 36 } },
    { geoCode: 'SD', geoName: 'Sudan',          dataYear: 2021, values: { life_expectancy: 64.5, health_expenditure_gdp: 4.55,  hospital_beds: 0.7,   uhc_index: 37 } },
    { geoCode: 'SO', geoName: 'Somalia',        dataYear: 2021, values: { life_expectancy: 54.8, health_expenditure_gdp: 2.95,  hospital_beds: 0.4,   uhc_index: 24 } },
    // ── Afrique centrale ──────────────────────────────────────────────────
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2021, values: { life_expectancy: 60.0, health_expenditure_gdp: 3.55,  hospital_beds: 0.8,   uhc_index: 32 } },
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2021, values: { life_expectancy: 59.5, health_expenditure_gdp: 3.55,  hospital_beds: 1.3,   uhc_index: 38 } },
    { geoCode: 'TD', geoName: 'Chad',           dataYear: 2021, values: { life_expectancy: 52.0, health_expenditure_gdp: 4.35,  hospital_beds: 0.4,   uhc_index: 27 } },
    { geoCode: 'CG', geoName: 'Congo',          dataYear: 2021, values: { life_expectancy: 62.5, health_expenditure_gdp: 2.95,  hospital_beds: 1.6,   uhc_index: 35 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2021, values: { life_expectancy: 66.0, health_expenditure_gdp: 2.85,  hospital_beds: 6.3,   uhc_index: 42 } },
    // ── Afrique australe ──────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2021, values: { life_expectancy: 62.0, health_expenditure_gdp: 8.66,  hospital_beds: 2.3,   uhc_index: 72 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2021, values: { life_expectancy: 60.2, health_expenditure_gdp: 2.65,  hospital_beds: 0.8,   uhc_index: 33 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2021, values: { life_expectancy: 59.5, health_expenditure_gdp: 3.45,  hospital_beds: 1.7,   uhc_index: 45 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2021, values: { life_expectancy: 60.5, health_expenditure_gdp: 5.00,  hospital_beds: 2.0,   uhc_index: 41 } },
    { geoCode: 'MW', geoName: 'Malawi',         dataYear: 2021, values: { life_expectancy: 62.2, health_expenditure_gdp: 5.70,  hospital_beds: 1.3,   uhc_index: 42 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2021, values: { life_expectancy: 60.5, health_expenditure_gdp: 5.90,  hospital_beds: 1.8,   uhc_index: 51 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2021, values: { life_expectancy: 58.5, health_expenditure_gdp: 8.00,  hospital_beds: 2.7,   uhc_index: 49 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2021, values: { life_expectancy: 73.5, health_expenditure_gdp: 5.80,  hospital_beds: 3.4,   uhc_index: 62 } },
    // ── Océanie ───────────────────────────────────────────────────────────
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2021, values: { life_expectancy: 64.0, health_expenditure_gdp: 2.55, hospital_beds: 0.5, uhc_index: 34 } },
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2021, values: { life_expectancy: 66.5, health_expenditure_gdp: 3.55,  hospital_beds: 2.3,   uhc_index: 51 } },
  ],
};

export default healthModule;
