import type { DomainModule } from '@/lib/domains/types';

const securityModule: DomainModule = {
  definition: {
    id: 'security',
    label: { fr: 'Sécurité publique', en: 'Public Safety' },
    description: {
      fr: 'Sécurité intérieure : homicides, état de droit, stabilité politique et indice de paix.',
      en: 'Internal security: homicides, rule of law, political stability and peace index.',
    },
    icon: '🛡️',
    group: 'security',
    active: true,
    seedSources: [
      'https://www.visionofhumanity.org/maps/',
      'https://info.worldbank.org/governance/wgi/',
      'https://www.unodc.org/unodc/en/data-and-analysis/homicide.html',
    ],
    indicators: [
      {
        id: 'homicide_rate',
        label: { fr: 'Taux d\'homicides (pour 100k)', en: 'Homicide rate (per 100k)' },
        unit: 'ratio',
        unitLabel: { fr: '/100 000', en: '/100,000' },
        direction: 'lower_is_better',
        weight: 3,
        thresholds: { excellent: 1.0, good: 2.5, fair: 5.0, poor: 10.0 },
        minValue: 0,
        maxValue: 60,
      },
      {
        id: 'rule_of_law',
        label: { fr: 'État de droit', en: 'Rule of law' },
        unit: 'index',
        unitLabel: { fr: 'indice /100', en: 'index /100' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 80, good: 65, fair: 45, poor: 28 },
        minValue: 0,
        maxValue: 100,
      },
      {
        id: 'political_stability',
        label: { fr: 'Stabilité politique', en: 'Political stability' },
        unit: 'index',
        unitLabel: { fr: 'indice /100', en: 'index /100' },
        direction: 'higher_is_better',
        weight: 2,
        thresholds: { excellent: 80, good: 62, fair: 42, poor: 25 },
        minValue: 0,
        maxValue: 100,
      },
      {
        id: 'global_peace_index',
        label: { fr: 'Indice de paix mondial', en: 'Global peace index' },
        unit: 'index',
        unitLabel: { fr: 'indice /100', en: 'index /100' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 80, good: 68, fair: 52, poor: 35 },
        minValue: 0,
        maxValue: 100,
      },
    ],
  },
  seedData: [
    // ── Europe nordique ────────────────────────────────────────────────────
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2023, values: { homicide_rate: 0.5,  rule_of_law: 97, political_stability: 92, global_peace_index: 97 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2023, values: { homicide_rate: 0.6,  rule_of_law: 95, political_stability: 90, global_peace_index: 94 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2023, values: { homicide_rate: 0.9,  rule_of_law: 96, political_stability: 88, global_peace_index: 93 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2023, values: { homicide_rate: 1.3,  rule_of_law: 95, political_stability: 89, global_peace_index: 92 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2023, values: { homicide_rate: 1.8,  rule_of_law: 91, political_stability: 80, global_peace_index: 88 } },
    // ── Océanie & Asie-Pacifique (hauts revenus) ─────────────────────────
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2023, values: { homicide_rate: 1.2,  rule_of_law: 93, political_stability: 88, global_peace_index: 91 } },
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2023, values: { homicide_rate: 0.2,  rule_of_law: 90, political_stability: 90, global_peace_index: 90 } },
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2023, values: { homicide_rate: 1.0,  rule_of_law: 88, political_stability: 82, global_peace_index: 86 } },
    // ── Europe de l'Ouest ──────────────────────────────────────────────────
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2023, values: { homicide_rate: 0.6,  rule_of_law: 94, political_stability: 87, global_peace_index: 91 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2023, values: { homicide_rate: 0.9,  rule_of_law: 90, political_stability: 82, global_peace_index: 89 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2023, values: { homicide_rate: 0.9,  rule_of_law: 90, political_stability: 80, global_peace_index: 87 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2023, values: { homicide_rate: 1.0,  rule_of_law: 88, political_stability: 83, global_peace_index: 88 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2023, values: { homicide_rate: 0.9,  rule_of_law: 87, political_stability: 80, global_peace_index: 86 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2023, values: { homicide_rate: 1.7,  rule_of_law: 82, political_stability: 72, global_peace_index: 83 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2023, values: { homicide_rate: 1.4,  rule_of_law: 82, political_stability: 68, global_peace_index: 80 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2023, values: { homicide_rate: 1.1,  rule_of_law: 85, political_stability: 70, global_peace_index: 81 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2023, values: { homicide_rate: 0.7,  rule_of_law: 88, political_stability: 82, global_peace_index: 88 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2023, values: { homicide_rate: 0.9,  rule_of_law: 82, political_stability: 78, global_peace_index: 88 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2023, values: { homicide_rate: 0.7,  rule_of_law: 75, political_stability: 62, global_peace_index: 82 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2023, values: { homicide_rate: 0.7,  rule_of_law: 65, political_stability: 60, global_peace_index: 79 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2023, values: { homicide_rate: 1.0,  rule_of_law: 68, political_stability: 58, global_peace_index: 75 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2023, values: { homicide_rate: 0.8,  rule_of_law: 72, political_stability: 78, global_peace_index: 82 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2023, values: { homicide_rate: 1.1,  rule_of_law: 70, political_stability: 62, global_peace_index: 76 } },
    // ── Europe de l'Est ────────────────────────────────────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2023, values: { homicide_rate: 1.0,  rule_of_law: 80, political_stability: 75, global_peace_index: 84 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2023, values: { homicide_rate: 0.8,  rule_of_law: 64, political_stability: 65, global_peace_index: 77 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2023, values: { homicide_rate: 1.0,  rule_of_law: 65, political_stability: 70, global_peace_index: 78 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2023, values: { homicide_rate: 1.3,  rule_of_law: 52, political_stability: 62, global_peace_index: 74 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2023, values: { homicide_rate: 1.1,  rule_of_law: 65, political_stability: 68, global_peace_index: 80 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2023, values: { homicide_rate: 1.5,  rule_of_law: 60, political_stability: 62, global_peace_index: 73 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2023, values: { homicide_rate: 1.2,  rule_of_law: 48, political_stability: 60, global_peace_index: 70 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2023, values: { homicide_rate: 0.5,  rule_of_law: 78, political_stability: 75, global_peace_index: 84 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2023, values: { homicide_rate: 1.6,  rule_of_law: 82, political_stability: 72, global_peace_index: 80 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2023, values: { homicide_rate: 2.4,  rule_of_law: 76, political_stability: 68, global_peace_index: 76 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2023, values: { homicide_rate: 2.2,  rule_of_law: 78, political_stability: 70, global_peace_index: 78 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2023, values: { homicide_rate: 1.4,  rule_of_law: 42, political_stability: 45, global_peace_index: 62 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2023, values: { homicide_rate: 1.2, rule_of_law: 38, political_stability: 40, global_peace_index: 60 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2023, values: { homicide_rate: 2.5,  rule_of_law: 44, political_stability: 50, global_peace_index: 65 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2023, values: { homicide_rate: 1.3, rule_of_law: 42, political_stability: 48, global_peace_index: 64 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2023, values: { homicide_rate: 2.3,  rule_of_law: 35, political_stability: 48, global_peace_index: 62 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2023, values: { homicide_rate: 2.6,  rule_of_law: 38, political_stability: 42, global_peace_index: 58 } },
    // ── Asie de l'Est ───────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2023, values: { homicide_rate: 0.3,  rule_of_law: 88, political_stability: 82, global_peace_index: 91 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2023, values: { homicide_rate: 0.6,  rule_of_law: 82, political_stability: 72, global_peace_index: 82 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2023, values: { homicide_rate: 0.9,  rule_of_law: 80, political_stability: 68, global_peace_index: 80 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2023, values: { homicide_rate: 0.7,  rule_of_law: 40, political_stability: 62, global_peace_index: 55 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2023, values: { homicide_rate: 5.8,  rule_of_law: 42, political_stability: 60, global_peace_index: 62 } },
    // ── Asie du Sud-Est ─────────────────────────────────────────────────────
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2023, values: { homicide_rate: 2.8,  rule_of_law: 50, political_stability: 42, global_peace_index: 55 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2023, values: { homicide_rate: 1.5,  rule_of_law: 42, political_stability: 68, global_peace_index: 62 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2023, values: { homicide_rate: 0.6,  rule_of_law: 45, political_stability: 48, global_peace_index: 60 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2023, values: { homicide_rate: 2.0,  rule_of_law: 62, political_stability: 55, global_peace_index: 68 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2023, values: { homicide_rate: 6.4,  rule_of_law: 38, political_stability: 35, global_peace_index: 42 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2023, values: { homicide_rate: 5.2,  rule_of_law: 15, political_stability: 8,  global_peace_index: 18 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2023, values: { homicide_rate: 2.4,  rule_of_law: 28, political_stability: 52, global_peace_index: 55 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2023, values: { homicide_rate: 3.8,  rule_of_law: 25, political_stability: 62, global_peace_index: 58 } },
    // ── Asie du Sud ─────────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2023, values: { homicide_rate: 2.8,  rule_of_law: 48, political_stability: 38, global_peace_index: 48 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2023, values: { homicide_rate: 2.5,  rule_of_law: 42, political_stability: 32, global_peace_index: 52 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2023, values: { homicide_rate: 2.3,  rule_of_law: 30, political_stability: 30, global_peace_index: 45 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2023, values: { homicide_rate: 3.9,  rule_of_law: 28, political_stability: 15, global_peace_index: 28 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2023, values: { homicide_rate: 2.0,  rule_of_law: 35, political_stability: 38, global_peace_index: 52 } },
    { geoCode: 'AF', geoName: 'Afghanistan',    dataYear: 2023, values: { homicide_rate: 7.0,  rule_of_law: 8,  political_stability: 5,  global_peace_index: 8  } },
    // ── Asie centrale ───────────────────────────────────────────────────────
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2023, values: { homicide_rate: 2.8,  rule_of_law: 25, political_stability: 55, global_peace_index: 55 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2023, values: { homicide_rate: 3.5,  rule_of_law: 28, political_stability: 38, global_peace_index: 50 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2023, values: { homicide_rate: 2.2,  rule_of_law: 18, political_stability: 42, global_peace_index: 48 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2023, values: { homicide_rate: 4.2,  rule_of_law: 12, political_stability: 58, global_peace_index: 50 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2023, values: { homicide_rate: 1.8,  rule_of_law: 52, political_stability: 42, global_peace_index: 58 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2023, values: { homicide_rate: 1.5,  rule_of_law: 42, political_stability: 32, global_peace_index: 50 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2023, values: { homicide_rate: 2.0,  rule_of_law: 28, political_stability: 45, global_peace_index: 48 } },
    // ── Moyen-Orient ──────────────────────────────────────────────────────
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2023, values: { homicide_rate: 2.8,  rule_of_law: 70, political_stability: 35, global_peace_index: 42 } },
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2023, values: { homicide_rate: 1.3,  rule_of_law: 45, political_stability: 48, global_peace_index: 48 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2023, values: { homicide_rate: 3.4,  rule_of_law: 40, political_stability: 38, global_peace_index: 45 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2023, values: { homicide_rate: 3.0,  rule_of_law: 22, political_stability: 32, global_peace_index: 38 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2023, values: { homicide_rate: 0.5, rule_of_law: 72, political_stability: 72, global_peace_index: 72 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2023, values: { homicide_rate: 0.4,  rule_of_law: 68, political_stability: 78, global_peace_index: 74 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2023, values: { homicide_rate: 1.8,  rule_of_law: 55, political_stability: 58, global_peace_index: 62 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2023, values: { homicide_rate: 0.5,  rule_of_law: 58, political_stability: 72, global_peace_index: 70 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2023, values: { homicide_rate: 0.8,  rule_of_law: 52, political_stability: 48, global_peace_index: 58 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2023, values: { homicide_rate: 1.2,  rule_of_law: 55, political_stability: 48, global_peace_index: 58 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2023, values: { homicide_rate: 3.2,  rule_of_law: 25, political_stability: 18, global_peace_index: 32 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2023, values: { homicide_rate: 8.5,  rule_of_law: 18, political_stability: 12, global_peace_index: 20 } },
    { geoCode: 'SY', geoName: 'Syria',          dataYear: 2023, values: { homicide_rate: 5.5,  rule_of_law: 8,  political_stability: 5,  global_peace_index: 10 } },
    { geoCode: 'YE', geoName: 'Yemen',          dataYear: 2023, values: { homicide_rate: 6.8,  rule_of_law: 8,  political_stability: 5,  global_peace_index: 10 } },
    // ── Ex-URSS ────────────────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2023, values: { homicide_rate: 6.5,  rule_of_law: 22, political_stability: 20, global_peace_index: 22 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2023, values: { homicide_rate: 4.0,  rule_of_law: 35, political_stability: 10, global_peace_index: 15 } },
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2023, values: { homicide_rate: 4.5,  rule_of_law: 32, political_stability: 52, global_peace_index: 55 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2023, values: { homicide_rate: 2.5,  rule_of_law: 18, political_stability: 42, global_peace_index: 42 } },
    // ── Amérique du Nord ──────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',  dataYear: 2023, values: { homicide_rate: 6.3,  rule_of_law: 78, political_stability: 58, global_peace_index: 68 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2023, values: { homicide_rate: 2.0,  rule_of_law: 87, political_stability: 82, global_peace_index: 85 } },
    // ── Amérique centrale & Caraïbes ──────────────────────────────────────
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2023, values: { homicide_rate: 11.5, rule_of_law: 62, political_stability: 62, global_peace_index: 62 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2023, values: { homicide_rate: 9.5,  rule_of_law: 48, political_stability: 52, global_peace_index: 55 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2023, values: { homicide_rate: 17.0, rule_of_law: 22, political_stability: 28, global_peace_index: 35 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2023, values: { homicide_rate: 35.0, rule_of_law: 18, political_stability: 25, global_peace_index: 28 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2023, values: { homicide_rate: 7.8,  rule_of_law: 28, political_stability: 42, global_peace_index: 48 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2023, values: { homicide_rate: 6.5,  rule_of_law: 18, political_stability: 38, global_peace_index: 45 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2023, values: { homicide_rate: 11.0, rule_of_law: 35, political_stability: 48, global_peace_index: 50 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2023, values: { homicide_rate: 44.0, rule_of_law: 42, political_stability: 42, global_peace_index: 35 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2023, values: { homicide_rate: 32.0, rule_of_law: 45, political_stability: 45, global_peace_index: 42 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2023, values: { homicide_rate: 5.0,  rule_of_law: 22, political_stability: 55, global_peace_index: 55 } },
    { geoCode: 'HT', geoName: 'Haiti',          dataYear: 2023, values: { homicide_rate: 18.0, rule_of_law: 8,  political_stability: 8,  global_peace_index: 15 } },
    // ── Amérique du Sud ──────────────────────────────────────────────────
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2023, values: { homicide_rate: 4.5,  rule_of_law: 70, political_stability: 58, global_peace_index: 68 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2023, values: { homicide_rate: 8.6,  rule_of_law: 72, political_stability: 72, global_peace_index: 68 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2023, values: { homicide_rate: 4.8,  rule_of_law: 48, political_stability: 38, global_peace_index: 52 } },
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2023, values: { homicide_rate: 22.0, rule_of_law: 42, political_stability: 32, global_peace_index: 40 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2023, values: { homicide_rate: 25.0, rule_of_law: 32, political_stability: 22, global_peace_index: 32 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2023, values: { homicide_rate: 26.0, rule_of_law: 40, political_stability: 25, global_peace_index: 35 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2023, values: { homicide_rate: 7.8,  rule_of_law: 35, political_stability: 28, global_peace_index: 48 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2023, values: { homicide_rate: 25.5, rule_of_law: 28, political_stability: 20, global_peace_index: 30 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2023, values: { homicide_rate: 36.0, rule_of_law: 12, political_stability: 15, global_peace_index: 22 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2023, values: { homicide_rate: 6.2,  rule_of_law: 22, political_stability: 28, global_peace_index: 45 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2023, values: { homicide_rate: 7.5,  rule_of_law: 28, political_stability: 38, global_peace_index: 48 } },
    { geoCode: 'GY', geoName: 'Guyana',         dataYear: 2023, values: { homicide_rate: 14.0, rule_of_law: 35, political_stability: 38, global_peace_index: 48 } },
    // ── Afrique du Nord ──────────────────────────────────────────────────
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2023, values: { homicide_rate: 1.0,  rule_of_law: 40, political_stability: 55, global_peace_index: 58 } },
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2023, values: { homicide_rate: 1.6,  rule_of_law: 35, political_stability: 38, global_peace_index: 45 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2023, values: { homicide_rate: 2.5,  rule_of_law: 42, political_stability: 35, global_peace_index: 52 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2023, values: { homicide_rate: 1.2,  rule_of_law: 30, political_stability: 35, global_peace_index: 50 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2023, values: { homicide_rate: 5.5,  rule_of_law: 10, political_stability: 8,  global_peace_index: 18 } },
    // ── Afrique de l'Ouest ───────────────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2023, values: { homicide_rate: 10.0, rule_of_law: 22, political_stability: 18, global_peace_index: 25 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2023, values: { homicide_rate: 2.2,  rule_of_law: 48, political_stability: 48, global_peace_index: 58 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2023, values: { homicide_rate: 3.5,  rule_of_law: 42, political_stability: 42, global_peace_index: 55 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2023, values: { homicide_rate: 6.5,  rule_of_law: 32, political_stability: 35, global_peace_index: 45 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2023, values: { homicide_rate: 8.0,  rule_of_law: 18, political_stability: 10, global_peace_index: 20 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2023, values: { homicide_rate: 6.2,  rule_of_law: 20, political_stability: 8,  global_peace_index: 18 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2023, values: { homicide_rate: 4.5,  rule_of_law: 22, political_stability: 15, global_peace_index: 28 } },
    { geoCode: 'GN', geoName: 'Guinea',         dataYear: 2023, values: { homicide_rate: 7.8,  rule_of_law: 18, political_stability: 22, global_peace_index: 32 } },
    { geoCode: 'SL', geoName: 'Sierra Leone',   dataYear: 2023, values: { homicide_rate: 4.8,  rule_of_law: 22, political_stability: 38, global_peace_index: 42 } },
    { geoCode: 'BJ', geoName: 'Benin',          dataYear: 2023, values: { homicide_rate: 2.0,  rule_of_law: 35, political_stability: 42, global_peace_index: 52 } },
    { geoCode: 'TG', geoName: 'Togo',           dataYear: 2023, values: { homicide_rate: 6.5,  rule_of_law: 28, political_stability: 38, global_peace_index: 45 } },
    { geoCode: 'GM', geoName: 'Gambia',         dataYear: 2023, values: { homicide_rate: 5.5,  rule_of_law: 30, political_stability: 42, global_peace_index: 50 } },
    // ── Afrique de l'Est ─────────────────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2023, values: { homicide_rate: 4.5,  rule_of_law: 35, political_stability: 28, global_peace_index: 38 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2023, values: { homicide_rate: 7.5,  rule_of_law: 25, political_stability: 15, global_peace_index: 28 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2023, values: { homicide_rate: 5.2,  rule_of_law: 32, political_stability: 40, global_peace_index: 48 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2023, values: { homicide_rate: 9.5,  rule_of_law: 28, political_stability: 25, global_peace_index: 35 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2023, values: { homicide_rate: 2.5,  rule_of_law: 52, political_stability: 55, global_peace_index: 58 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2023, values: { homicide_rate: 7.0,  rule_of_law: 22, political_stability: 32, global_peace_index: 42 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2023, values: { homicide_rate: 5.5,  rule_of_law: 22, political_stability: 20, global_peace_index: 30 } },
    { geoCode: 'SO', geoName: 'Somalia',        dataYear: 2023, values: { homicide_rate: 8.5,  rule_of_law: 5,  political_stability: 5,  global_peace_index: 10 } },
    { geoCode: 'SD', geoName: 'Sudan',          dataYear: 2023, values: { homicide_rate: 6.5,  rule_of_law: 8,  political_stability: 5,  global_peace_index: 12 } },
    { geoCode: 'SS', geoName: 'South Sudan',    dataYear: 2023, values: { homicide_rate: 11.5, rule_of_law: 5,  political_stability: 5,  global_peace_index: 10 } },
    // ── Afrique centrale ─────────────────────────────────────────────────
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2023, values: { homicide_rate: 12.0, rule_of_law: 10, political_stability: 8,  global_peace_index: 15 } },
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2023, values: { homicide_rate: 5.0,  rule_of_law: 22, political_stability: 22, global_peace_index: 30 } },
    { geoCode: 'TD', geoName: 'Chad',           dataYear: 2023, values: { homicide_rate: 8.5,  rule_of_law: 10, political_stability: 12, global_peace_index: 18 } },
    { geoCode: 'CG', geoName: 'Republic of the Congo', dataYear: 2023, values: { homicide_rate: 6.0, rule_of_law: 15, political_stability: 22, global_peace_index: 30 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2023, values: { homicide_rate: 5.2,  rule_of_law: 28, political_stability: 38, global_peace_index: 45 } },
    // ── Afrique australe ─────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2023, values: { homicide_rate: 41.0, rule_of_law: 50, political_stability: 38, global_peace_index: 38 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2023, values: { homicide_rate: 8.0,  rule_of_law: 58, political_stability: 68, global_peace_index: 62 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2023, values: { homicide_rate: 9.0,  rule_of_law: 52, political_stability: 62, global_peace_index: 58 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2023, values: { homicide_rate: 2.0,  rule_of_law: 65, political_stability: 72, global_peace_index: 70 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2023, values: { homicide_rate: 6.5,  rule_of_law: 18, political_stability: 28, global_peace_index: 35 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2023, values: { homicide_rate: 5.0,  rule_of_law: 32, political_stability: 48, global_peace_index: 52 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2023, values: { homicide_rate: 7.5,  rule_of_law: 18, political_stability: 35, global_peace_index: 38 } },
    { geoCode: 'MW', geoName: 'Malawi',         dataYear: 2023, values: { homicide_rate: 1.8,  rule_of_law: 38, political_stability: 48, global_peace_index: 55 } },
  ],
  seedDataPrev: [
    // ── Europe nordique ──────────────────────────────────────────────────── (Sources: UNODC/Wikipedia homicide; World Bank WGI RL.EST & PV.EST 2022 converted 0-100; GPI 2022 converted 0-100)
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2022, values: { homicide_rate: 1.29, rule_of_law: 84, political_stability: 75, global_peace_index: 96 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2022, values: { homicide_rate: 0.73, rule_of_law: 85, political_stability: 67, global_peace_index: 93 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2022, values: { homicide_rate: 0.84, rule_of_law: 88, political_stability: 67, global_peace_index: 93 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2022, values: { homicide_rate: 0.98, rule_of_law: 89, political_stability: 68, global_peace_index: 92 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2022, values: { homicide_rate: 1.15, rule_of_law: 84, political_stability: 68, global_peace_index: 87 } },
    // ── Océanie & Asie-Pacifique (hauts revenus) ─────────────────────────
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2022, values: { homicide_rate: 1.46, rule_of_law: 85, political_stability: 76, global_peace_index: 95 } },
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2022, values: { homicide_rate: 0.07, rule_of_law: 86, political_stability: 79, global_peace_index: 92 } },
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2022, values: { homicide_rate: 0.85, rule_of_law: 80, political_stability: 70, global_peace_index: 87 } },
    // ── Europe de l'Ouest ──────────────────────────────────────────────────
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2022, values: { homicide_rate: 0.60, rule_of_law: 85, political_stability: 73, global_peace_index: 93 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2022, values: { homicide_rate: 0.88, rule_of_law: 84, political_stability: 63, global_peace_index: 93 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2022, values: { homicide_rate: 0.69, rule_of_law: 83, political_stability: 65, global_peace_index: 88 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2022, values: { homicide_rate: 0.65, rule_of_law: 81, political_stability: 68, global_peace_index: 94 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2022, values: { homicide_rate: 0.91, rule_of_law: 81, political_stability: 63, global_peace_index: 86 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2022, values: { homicide_rate: 1.08, rule_of_law: 77, political_stability: 62, global_peace_index: 83 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2022, values: { homicide_rate: 1.34, rule_of_law: 74, political_stability: 58, global_peace_index: 79 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2022, values: { homicide_rate: 1.15, rule_of_law: 78, political_stability: 61, global_peace_index: 82 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2022, values: { homicide_rate: 1.53, rule_of_law: 85, political_stability: 71, global_peace_index: 90 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2022, values: { homicide_rate: 0.72, rule_of_law: 72, political_stability: 66, global_peace_index: 92 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2022, values: { homicide_rate: 0.69, rule_of_law: 66, political_stability: 56, global_peace_index: 82 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2022, values: { homicide_rate: 0.57, rule_of_law: 56, political_stability: 59, global_peace_index: 79 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2022, values: { homicide_rate: 0.84, rule_of_law: 57, political_stability: 52, global_peace_index: 76 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2022, values: { homicide_rate: 0.9,  rule_of_law: 68, political_stability: 76, global_peace_index: 80 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2022, values: { homicide_rate: 1.3,  rule_of_law: 67, political_stability: 60, global_peace_index: 75 } },
    // ── Europe de l'Est ────────────────────────────────────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2022, values: { homicide_rate: 0.77, rule_of_law: 72, political_stability: 66, global_peace_index: 90 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2022, values: { homicide_rate: 0.80, rule_of_law: 59, political_stability: 60, global_peace_index: 77 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2022, values: { homicide_rate: 1.12, rule_of_law: 62, political_stability: 59, global_peace_index: 78 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2022, values: { homicide_rate: 0.72, rule_of_law: 58, political_stability: 64, global_peace_index: 78 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2022, values: { homicide_rate: 0.67, rule_of_law: 57, political_stability: 63, global_peace_index: 82 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2022, values: { homicide_rate: 1.11, rule_of_law: 58, political_stability: 59, global_peace_index: 74 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2022, values: { homicide_rate: 1.09, rule_of_law: 48, political_stability: 56, global_peace_index: 72 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2022, values: { homicide_rate: 0.6,  rule_of_law: 75, political_stability: 72, global_peace_index: 83 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2022, values: { homicide_rate: 1.8,  rule_of_law: 80, political_stability: 68, global_peace_index: 78 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2022, values: { homicide_rate: 2.8,  rule_of_law: 73, political_stability: 64, global_peace_index: 74 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2022, values: { homicide_rate: 2.5,  rule_of_law: 75, political_stability: 66, global_peace_index: 76 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2022, values: { homicide_rate: 1.5,  rule_of_law: 40, political_stability: 42, global_peace_index: 60 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2022, values: { homicide_rate: 1.3, rule_of_law: 36, political_stability: 38, global_peace_index: 58 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2022, values: { homicide_rate: 2.8,  rule_of_law: 42, political_stability: 48, global_peace_index: 63 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2022, values: { homicide_rate: 1.5, rule_of_law: 40, political_stability: 45, global_peace_index: 62 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2022, values: { homicide_rate: 2.5,  rule_of_law: 33, political_stability: 45, global_peace_index: 60 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2022, values: { homicide_rate: 3.0,  rule_of_law: 35, political_stability: 38, global_peace_index: 55 } },
    // ── Asie de l'Est ───────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2022, values: { homicide_rate: 0.23, rule_of_law: 81, political_stability: 71, global_peace_index: 91 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2022, values: { homicide_rate: 0.48, rule_of_law: 73, political_stability: 62, global_peace_index: 82 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2022, values: { homicide_rate: 0.90, rule_of_law: 80, political_stability: 58, global_peace_index: 80 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2022, values: { homicide_rate: 0.50, rule_of_law: 49, political_stability: 41, global_peace_index: 55 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2022, values: { homicide_rate: 6.2,  rule_of_law: 40, political_stability: 58, global_peace_index: 60 } },
    // ── Asie du Sud-Est ─────────────────────────────────────────────────────
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2022, values: { homicide_rate: 4.79, rule_of_law: 51, political_stability: 42, global_peace_index: 55 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2022, values: { homicide_rate: 1.54, rule_of_law: 47, political_stability: 49, global_peace_index: 62 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2022, values: { homicide_rate: 0.30, rule_of_law: 46, political_stability: 39, global_peace_index: 60 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2022, values: { homicide_rate: 2.1,  rule_of_law: 60, political_stability: 52, global_peace_index: 66 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2022, values: { homicide_rate: 7.2,  rule_of_law: 36, political_stability: 32, global_peace_index: 40 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2022, values: { homicide_rate: 4.8,  rule_of_law: 14, political_stability: 6,  global_peace_index: 16 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2022, values: { homicide_rate: 2.6,  rule_of_law: 26, political_stability: 50, global_peace_index: 53 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2022, values: { homicide_rate: 4.0,  rule_of_law: 23, political_stability: 60, global_peace_index: 56 } },
    // ── Asie du Sud ─────────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2022, values: { homicide_rate: 2.82, rule_of_law: 52, political_stability: 38, global_peace_index: 47 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2022, values: { homicide_rate: 2.7,  rule_of_law: 40, political_stability: 28, global_peace_index: 50 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2022, values: { homicide_rate: 2.5,  rule_of_law: 28, political_stability: 28, global_peace_index: 43 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2022, values: { homicide_rate: 4.2,  rule_of_law: 26, political_stability: 12, global_peace_index: 26 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2022, values: { homicide_rate: 2.2,  rule_of_law: 33, political_stability: 35, global_peace_index: 50 } },
    { geoCode: 'AF', geoName: 'Afghanistan',    dataYear: 2022, values: { homicide_rate: 7.5,  rule_of_law: 6,  political_stability: 3,  global_peace_index: 6  } },
    // ── Asie centrale ───────────────────────────────────────────────────────
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2022, values: { homicide_rate: 3.0,  rule_of_law: 23, political_stability: 52, global_peace_index: 53 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2022, values: { homicide_rate: 3.8,  rule_of_law: 26, political_stability: 35, global_peace_index: 48 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2022, values: { homicide_rate: 2.5,  rule_of_law: 16, political_stability: 40, global_peace_index: 46 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2022, values: { homicide_rate: 4.5,  rule_of_law: 10, political_stability: 55, global_peace_index: 48 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2022, values: { homicide_rate: 2.0,  rule_of_law: 50, political_stability: 38, global_peace_index: 56 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2022, values: { homicide_rate: 1.7,  rule_of_law: 40, political_stability: 28, global_peace_index: 48 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2022, values: { homicide_rate: 2.2,  rule_of_law: 26, political_stability: 42, global_peace_index: 46 } },
    // ── Moyen-Orient ──────────────────────────────────────────────────────
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2022, values: { homicide_rate: 1.63, rule_of_law: 69, political_stability: 25, global_peace_index: 44 } },
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2022, values: { homicide_rate: 0.94, rule_of_law: 56, political_stability: 43, global_peace_index: 48 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2022, values: { homicide_rate: 3.23, rule_of_law: 41, political_stability: 29, global_peace_index: 43 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2022, values: { homicide_rate: 2.38, rule_of_law: 30, political_stability: 17, global_peace_index: 37 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2022, values: { homicide_rate: 0.6, rule_of_law: 70, political_stability: 70, global_peace_index: 70 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2022, values: { homicide_rate: 0.5,  rule_of_law: 66, political_stability: 76, global_peace_index: 72 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2022, values: { homicide_rate: 2.0,  rule_of_law: 53, political_stability: 56, global_peace_index: 60 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2022, values: { homicide_rate: 0.6,  rule_of_law: 56, political_stability: 70, global_peace_index: 68 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2022, values: { homicide_rate: 0.9,  rule_of_law: 50, political_stability: 45, global_peace_index: 56 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2022, values: { homicide_rate: 1.4,  rule_of_law: 53, political_stability: 45, global_peace_index: 56 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2022, values: { homicide_rate: 3.5,  rule_of_law: 23, political_stability: 15, global_peace_index: 30 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2022, values: { homicide_rate: 9.0,  rule_of_law: 16, political_stability: 10, global_peace_index: 18 } },
    { geoCode: 'SY', geoName: 'Syria',          dataYear: 2022, values: { homicide_rate: 6.0,  rule_of_law: 6,  political_stability: 3,  global_peace_index: 8  } },
    { geoCode: 'YE', geoName: 'Yemen',          dataYear: 2022, values: { homicide_rate: 7.2,  rule_of_law: 6,  political_stability: 3,  global_peace_index: 8  } },
    // ── Ex-URSS ────────────────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2022, values: { homicide_rate: 6.77, rule_of_law: 26, political_stability: 30, global_peace_index: 18 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2022, values: { homicide_rate: 3.78, rule_of_law: 32, political_stability: 11, global_peace_index: 8  } },
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2022, values: { homicide_rate: 2.55, rule_of_law: 41, political_stability: 41, global_peace_index: 55 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2022, values: { homicide_rate: 2.8,  rule_of_law: 16, political_stability: 38, global_peace_index: 40 } },
    // ── Amérique du Nord ──────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',  dataYear: 2022, values: { homicide_rate: 5.76, rule_of_law: 77, political_stability: 50, global_peace_index: 68 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2022, values: { homicide_rate: 1.98, rule_of_law: 81, political_stability: 66, global_peace_index: 85 } },
    // ── Amérique centrale & Caraïbes ──────────────────────────────────────
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2022, values: { homicide_rate: 12.0, rule_of_law: 60, political_stability: 60, global_peace_index: 60 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2022, values: { homicide_rate: 10.0, rule_of_law: 46, political_stability: 50, global_peace_index: 53 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2022, values: { homicide_rate: 18.0, rule_of_law: 20, political_stability: 26, global_peace_index: 33 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2022, values: { homicide_rate: 38.0, rule_of_law: 16, political_stability: 22, global_peace_index: 26 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2022, values: { homicide_rate: 18.0, rule_of_law: 25, political_stability: 38, global_peace_index: 38 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2022, values: { homicide_rate: 7.0,  rule_of_law: 16, political_stability: 35, global_peace_index: 43 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2022, values: { homicide_rate: 12.0, rule_of_law: 33, political_stability: 45, global_peace_index: 48 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2022, values: { homicide_rate: 47.0, rule_of_law: 40, political_stability: 40, global_peace_index: 33 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2022, values: { homicide_rate: 35.0, rule_of_law: 43, political_stability: 43, global_peace_index: 40 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2022, values: { homicide_rate: 5.2,  rule_of_law: 20, political_stability: 52, global_peace_index: 53 } },
    { geoCode: 'HT', geoName: 'Haiti',          dataYear: 2022, values: { homicide_rate: 15.0, rule_of_law: 6,  political_stability: 6,  global_peace_index: 13 } },
    // ── Amérique du Sud ──────────────────────────────────────────────────
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2022, values: { homicide_rate: 6.35, rule_of_law: 64, political_stability: 53, global_peace_index: 69 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2022, values: { homicide_rate: 9.2,  rule_of_law: 70, political_stability: 70, global_peace_index: 66 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2022, values: { homicide_rate: 4.49, rule_of_law: 40, political_stability: 48, global_peace_index: 53 } },
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2022, values: { homicide_rate: 19.3, rule_of_law: 45, political_stability: 42, global_peace_index: 40 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2022, values: { homicide_rate: 24.9, rule_of_law: 33, political_stability: 36, global_peace_index: 32 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2022, values: { homicide_rate: 24.9, rule_of_law: 41, political_stability: 37, global_peace_index: 35 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2022, values: { homicide_rate: 8.2,  rule_of_law: 33, political_stability: 25, global_peace_index: 46 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2022, values: { homicide_rate: 18.0, rule_of_law: 26, political_stability: 18, global_peace_index: 32 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2022, values: { homicide_rate: 40.0, rule_of_law: 10, political_stability: 12, global_peace_index: 20 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2022, values: { homicide_rate: 6.5,  rule_of_law: 20, political_stability: 25, global_peace_index: 43 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2022, values: { homicide_rate: 8.0,  rule_of_law: 26, political_stability: 35, global_peace_index: 46 } },
    { geoCode: 'GY', geoName: 'Guyana',         dataYear: 2022, values: { homicide_rate: 15.0, rule_of_law: 33, political_stability: 35, global_peace_index: 46 } },
    // ── Afrique du Nord ──────────────────────────────────────────────────
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2022, values: { homicide_rate: 1.71, rule_of_law: 46, political_stability: 43, global_peace_index: 58 } },
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2022, values: { homicide_rate: 1.31, rule_of_law: 45, political_stability: 30, global_peace_index: 45 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2022, values: { homicide_rate: 2.8,  rule_of_law: 40, political_stability: 32, global_peace_index: 50 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2022, values: { homicide_rate: 1.4,  rule_of_law: 28, political_stability: 32, global_peace_index: 48 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2022, values: { homicide_rate: 6.0,  rule_of_law: 8,  political_stability: 6,  global_peace_index: 16 } },
    // ── Afrique de l'Ouest ───────────────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2022, values: { homicide_rate: 15.7, rule_of_law: 32, political_stability: 14, global_peace_index: 21 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2022, values: { homicide_rate: 2.4,  rule_of_law: 46, political_stability: 45, global_peace_index: 56 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2022, values: { homicide_rate: 3.8,  rule_of_law: 40, political_stability: 38, global_peace_index: 53 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2022, values: { homicide_rate: 7.0,  rule_of_law: 30, political_stability: 32, global_peace_index: 43 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2022, values: { homicide_rate: 8.5,  rule_of_law: 16, political_stability: 8,  global_peace_index: 18 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2022, values: { homicide_rate: 5.8,  rule_of_law: 22, political_stability: 10, global_peace_index: 20 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2022, values: { homicide_rate: 4.8,  rule_of_law: 20, political_stability: 12, global_peace_index: 26 } },
    { geoCode: 'GN', geoName: 'Guinea',         dataYear: 2022, values: { homicide_rate: 8.2,  rule_of_law: 16, political_stability: 20, global_peace_index: 30 } },
    { geoCode: 'SL', geoName: 'Sierra Leone',   dataYear: 2022, values: { homicide_rate: 5.0,  rule_of_law: 20, political_stability: 35, global_peace_index: 40 } },
    { geoCode: 'BJ', geoName: 'Benin',          dataYear: 2022, values: { homicide_rate: 2.2,  rule_of_law: 33, political_stability: 40, global_peace_index: 50 } },
    { geoCode: 'TG', geoName: 'Togo',           dataYear: 2022, values: { homicide_rate: 7.0,  rule_of_law: 26, political_stability: 35, global_peace_index: 43 } },
    { geoCode: 'GM', geoName: 'Gambia',         dataYear: 2022, values: { homicide_rate: 6.0,  rule_of_law: 28, political_stability: 40, global_peace_index: 48 } },
    // ── Afrique de l'Est ─────────────────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2022, values: { homicide_rate: 4.87, rule_of_law: 44, political_stability: 31, global_peace_index: 39 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2022, values: { homicide_rate: 8.51, rule_of_law: 37, political_stability: 9,  global_peace_index: 22 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2022, values: { homicide_rate: 5.5,  rule_of_law: 30, political_stability: 38, global_peace_index: 46 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2022, values: { homicide_rate: 10.0, rule_of_law: 26, political_stability: 22, global_peace_index: 33 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2022, values: { homicide_rate: 2.7,  rule_of_law: 50, political_stability: 52, global_peace_index: 56 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2022, values: { homicide_rate: 7.5,  rule_of_law: 20, political_stability: 30, global_peace_index: 40 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2022, values: { homicide_rate: 6.0,  rule_of_law: 20, political_stability: 18, global_peace_index: 28 } },
    { geoCode: 'SO', geoName: 'Somalia',        dataYear: 2022, values: { homicide_rate: 9.0,  rule_of_law: 3,  political_stability: 3,  global_peace_index: 8  } },
    { geoCode: 'SD', geoName: 'Sudan',          dataYear: 2022, values: { homicide_rate: 6.0,  rule_of_law: 10, political_stability: 8,  global_peace_index: 14 } },
    { geoCode: 'SS', geoName: 'South Sudan',    dataYear: 2022, values: { homicide_rate: 12.0, rule_of_law: 3,  political_stability: 3,  global_peace_index: 8  } },
    // ── Afrique centrale ─────────────────────────────────────────────────
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2022, values: { homicide_rate: 13.0, rule_of_law: 8,  political_stability: 6,  global_peace_index: 13 } },
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2022, values: { homicide_rate: 5.5,  rule_of_law: 20, political_stability: 20, global_peace_index: 28 } },
    { geoCode: 'TD', geoName: 'Chad',           dataYear: 2022, values: { homicide_rate: 9.0,  rule_of_law: 8,  political_stability: 10, global_peace_index: 16 } },
    { geoCode: 'CG', geoName: 'Republic of the Congo', dataYear: 2022, values: { homicide_rate: 6.5, rule_of_law: 13, political_stability: 20, global_peace_index: 28 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2022, values: { homicide_rate: 5.5,  rule_of_law: 26, political_stability: 36, global_peace_index: 43 } },
    // ── Afrique australe ─────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2022, values: { homicide_rate: 43.7, rule_of_law: 51, political_stability: 36, global_peace_index: 38 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2022, values: { homicide_rate: 8.5,  rule_of_law: 56, political_stability: 66, global_peace_index: 60 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2022, values: { homicide_rate: 9.5,  rule_of_law: 50, political_stability: 60, global_peace_index: 56 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2022, values: { homicide_rate: 2.2,  rule_of_law: 63, political_stability: 70, global_peace_index: 68 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2022, values: { homicide_rate: 7.0,  rule_of_law: 16, political_stability: 25, global_peace_index: 33 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2022, values: { homicide_rate: 5.5,  rule_of_law: 30, political_stability: 45, global_peace_index: 50 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2022, values: { homicide_rate: 8.0,  rule_of_law: 16, political_stability: 32, global_peace_index: 36 } },
    { geoCode: 'MW', geoName: 'Malawi',         dataYear: 2022, values: { homicide_rate: 2.0,  rule_of_law: 36, political_stability: 45, global_peace_index: 53 } },
  ],
};

export default securityModule;
