import type { DomainModule } from '@/lib/domains/types';

const consumerConfidenceModule: DomainModule = {
  definition: {
    id: 'consumer-confidence',
    label: { fr: 'Confiance des ménages', en: 'Consumer Confidence', es: 'Confianza de los hogares' },
    description: {
      fr: 'Moral des consommateurs et perspectives économiques perçues par les ménages.',
      en: 'Consumer morale and economic outlook as perceived by households.',
      es: 'Moral de los consumidores y perspectivas económicas percibidas por los hogares.',
    },
    icon: '🏠',
    group: 'society',
    active: true,
    seedSources: [
      'https://stats.oecd.org/index.aspx?queryid=6680',
      'https://data.worldbank.org/indicator/NE.CON.PRVT.KD.ZG',
      'https://tradingeconomics.com/country-list/consumer-confidence',
    ],
    indicators: [
      {
        id: 'cci_index',
        label: { fr: 'Indice de confiance consommateurs', en: 'Consumer Confidence Index', es: 'Índice de confianza del consumidor' },
        description: {
          fr: 'Enquête OCDE mesurant l\'optimisme des ménages sur leur situation financière et l\'économie. Base 100 = moyenne historique.',
          en: 'OECD survey measuring household optimism about their financial situation and the economy. Base 100 = historical average.',
        },
        unit: 'index',
        unitLabel: { fr: 'indice', en: 'index', es: 'índice' },
        direction: 'higher_is_better',
        weight: 2,
        thresholds: { excellent: 102, good: 100, fair: 98, poor: 95 },
        minValue: 80,
        maxValue: 120,
      },
      {
        id: 'consumer_spending_growth',
        label: { fr: 'Croissance consommation privée', en: 'Private Consumption Growth', es: 'Crecimiento consumo privado' },
        description: {
          fr: 'Variation annuelle des dépenses de consommation des ménages en termes réels. Moteur principal de la croissance dans la plupart des économies.',
          en: 'Annual change in household consumer spending in real terms. The primary driver of growth in most economies.',
        },
        unit: 'percent',
        unitLabel: { fr: '%', en: '%', es: '%' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 3, good: 1.5, fair: 0, poor: -2 },
        minValue: -5,
        maxValue: 10,
      },
    ],
  },
  seedData: [
    // ── Europe nordique ─────────────────────────────────────────────────── (données 2026)
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2026, values: { cci_index: 101.2, consumer_spending_growth: 2.8 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2026, values: { cci_index: 97.0, consumer_spending_growth: 1.2 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2026, values: { cci_index: 100.5, consumer_spending_growth: 2.5 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2026, values: { cci_index: 98.8, consumer_spending_growth: 1.8 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2026, values: { cci_index: 99.5, consumer_spending_growth: 2.0 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2026, values: { cci_index: 97.5, consumer_spending_growth: 1.5 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2026, values: { cci_index: 98.5, consumer_spending_growth: 2.2 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2026, values: { cci_index: 97.8, consumer_spending_growth: 1.8 } },
    // ── Europe de l'Ouest ────────────────────────────────────────────────
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2026, values: { cci_index: 99.5, consumer_spending_growth: 2.0 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2026, values: { cci_index: 100.2, consumer_spending_growth: 2.2 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2026, values: { cci_index: 97.2, consumer_spending_growth: 0.5 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2026, values: { cci_index: 101.5, consumer_spending_growth: 3.2 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2026, values: { cci_index: 100.8, consumer_spending_growth: 2.0 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2026, values: { cci_index: 98.0, consumer_spending_growth: 1.0 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2026, values: { cci_index: 98.5, consumer_spending_growth: 1.5 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2026, values: { cci_index: 97.8, consumer_spending_growth: 1.2 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2026, values: { cci_index: 98.0, consumer_spending_growth: 1.5 } },
    // ── Europe du Sud ────────────────────────────────────────────────────
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2026, values: { cci_index: 99.5, consumer_spending_growth: 2.5 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2026, values: { cci_index: 100.2, consumer_spending_growth: 2.8 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2026, values: { cci_index: 97.5, consumer_spending_growth: 0.8 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2026, values: { cci_index: 99.0, consumer_spending_growth: 2.5 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2026, values: { cci_index: 99.5, consumer_spending_growth: 2.8 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2026, values: { cci_index: 98.8, consumer_spending_growth: 2.0 } },
    // ── Europe centrale & orientale ──────────────────────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2026, values: { cci_index: 99.2, consumer_spending_growth: 2.5 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2026, values: { cci_index: 99.5, consumer_spending_growth: 3.2 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2026, values: { cci_index: 98.5, consumer_spending_growth: 2.0 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2026, values: { cci_index: 99.0, consumer_spending_growth: 2.5 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2026, values: { cci_index: 97.0, consumer_spending_growth: 1.5 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2026, values: { cci_index: 98.5, consumer_spending_growth: 3.5 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2026, values: { cci_index: 98.0, consumer_spending_growth: 2.8 } },
    // ── Amérique du Nord & Océanie ────────────────────────────────────────
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2026, values: { cci_index: 98.5, consumer_spending_growth: 1.8 } },
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2026, values: { cci_index: 99.0, consumer_spending_growth: 2.1 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2026, values: { cci_index: 97.5, consumer_spending_growth: 2.2 } },
    { geoCode: 'US', geoName: 'United States',  dataYear: 2026, values: { cci_index: 98.5, consumer_spending_growth: 2.8 } },
    // ── Asie de l'Est ────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2026, values: { cci_index: 96.5, consumer_spending_growth: 0.8 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2026, values: { cci_index: 101.5, consumer_spending_growth: 4.5 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2026, values: { cci_index: 98.8, consumer_spending_growth: 2.5 } },
    // ── Asie du Sud-Est ──────────────────────────────────────────────────
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2026, values: { cci_index: 102.0, consumer_spending_growth: 3.5 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2026, values: { cci_index: 101.5, consumer_spending_growth: 4.0 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2026, values: { cci_index: 100.0, consumer_spending_growth: 3.2 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2026, values: { cci_index: 102.5, consumer_spending_growth: 4.8 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2026, values: { cci_index: 103.0, consumer_spending_growth: 5.5 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2026, values: { cci_index: 101.5, consumer_spending_growth: 5.0 } },
    // ── Asie du Sud ──────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2026, values: { cci_index: 103.5, consumer_spending_growth: 6.2 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2026, values: { cci_index: 98.0, consumer_spending_growth: 2.5 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2026, values: { cci_index: 99.0, consumer_spending_growth: 4.0 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2026, values: { cci_index: 93.5, consumer_spending_growth: 0.5 } },
    // ── Moyen-Orient & Afrique du Nord ───────────────────────────────────
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2026, values: { cci_index: 95.5, consumer_spending_growth: 1.2 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2026, values: { cci_index: 104.0, consumer_spending_growth: 5.5 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2026, values: { cci_index: 103.0, consumer_spending_growth: 4.5 } },
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2026, values: { cci_index: 102.5, consumer_spending_growth: 4.0 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2026, values: { cci_index: 96.5, consumer_spending_growth: 1.5 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2026, values: { cci_index: 88.0, consumer_spending_growth: -3.5 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2026, values: { cci_index: 85.0, consumer_spending_growth: -4.0 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2026, values: { cci_index: 94.0, consumer_spending_growth: 2.0 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2026, values: { cci_index: 93.5, consumer_spending_growth: -2.5 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2026, values: { cci_index: 98.0, consumer_spending_growth: 2.8 } },
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2026, values: { cci_index: 91.0, consumer_spending_growth: 1.0 } },
    // ── Ex-URSS ──────────────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2026, values: { cci_index: 92.0, consumer_spending_growth: -3.5 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2026, values: { cci_index: 87.0, consumer_spending_growth: -5.0 } },
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2026, values: { cci_index: 97.5, consumer_spending_growth: 3.5 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2026, values: { cci_index: 99.0, consumer_spending_growth: 4.0 } },
    // ── Amérique Latine ──────────────────────────────────────────────────
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2026, values: { cci_index: 99.5, consumer_spending_growth: 2.5 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2026, values: { cci_index: 99.0, consumer_spending_growth: 2.0 } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2026, values: { cci_index: 100.0, consumer_spending_growth: 3.0 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2026, values: { cci_index: 91.0, consumer_spending_growth: -1.5 } },
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2026, values: { cci_index: 97.8, consumer_spending_growth: 3.5 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2026, values: { cci_index: 98.5, consumer_spending_growth: 3.0 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2026, values: { cci_index: 98.0, consumer_spending_growth: 2.5 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2026, values: { cci_index: 98.5, consumer_spending_growth: 2.8 } },
    // ── Afrique subsaharienne ────────────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2026, values: { cci_index: 93.0, consumer_spending_growth: 0.5 } },
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2026, values: { cci_index: 96.5, consumer_spending_growth: 2.5 } },
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2026, values: { cci_index: 95.0, consumer_spending_growth: 0.8 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2026, values: { cci_index: 94.5, consumer_spending_growth: 1.5 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2026, values: { cci_index: 98.5, consumer_spending_growth: 4.2 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2026, values: { cci_index: 95.5, consumer_spending_growth: 3.5 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2026, values: { cci_index: 100.5, consumer_spending_growth: 5.0 } },
  ],
  seedDataPrev: [
    // ── Europe (données 2025) ────────────────────────────────────────────
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2025, values: { cci_index: 100.0, consumer_spending_growth: 2.2 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2025, values: { cci_index: 96.5, consumer_spending_growth: 0.8 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2025, values: { cci_index: 100.0, consumer_spending_growth: 2.0 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2025, values: { cci_index: 98.0, consumer_spending_growth: 1.5 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2025, values: { cci_index: 96.5, consumer_spending_growth: -0.2 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2025, values: { cci_index: 97.5, consumer_spending_growth: 1.0 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2025, values: { cci_index: 97.5, consumer_spending_growth: 1.2 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2025, values: { cci_index: 97.0, consumer_spending_growth: 0.5 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2025, values: { cci_index: 99.5, consumer_spending_growth: 2.5 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2025, values: { cci_index: 98.5, consumer_spending_growth: 3.5 } },
    // ── Amérique du Nord ─────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',  dataYear: 2025, values: { cci_index: 99.5, consumer_spending_growth: 3.0 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2025, values: { cci_index: 97.0, consumer_spending_growth: 2.0 } },
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2025, values: { cci_index: 98.5, consumer_spending_growth: 1.8 } },
    // ── Asie ─────────────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2025, values: { cci_index: 96.0, consumer_spending_growth: 0.5 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2025, values: { cci_index: 100.5, consumer_spending_growth: 4.0 } },
    { geoCode: 'IN', geoName: 'India',          dataYear: 2025, values: { cci_index: 102.5, consumer_spending_growth: 6.5 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2025, values: { cci_index: 98.5, consumer_spending_growth: 2.0 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2025, values: { cci_index: 101.5, consumer_spending_growth: 5.0 } },
    // ── Moyen-Orient ─────────────────────────────────────────────────────
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2025, values: { cci_index: 92.0, consumer_spending_growth: -3.5 } },
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2025, values: { cci_index: 93.5, consumer_spending_growth: -2.5 } },
    // ── Amérique Latine ──────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2025, values: { cci_index: 96.5, consumer_spending_growth: 3.0 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2025, values: { cci_index: 89.5, consumer_spending_growth: -2.0 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2025, values: { cci_index: 98.0, consumer_spending_growth: 2.5 } },
    // ── Afrique ──────────────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2025, values: { cci_index: 94.5, consumer_spending_growth: 0.5 } },
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2025, values: { cci_index: 92.5, consumer_spending_growth: 0.2 } },
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2025, values: { cci_index: 96.0, consumer_spending_growth: 2.0 } },
  ],
};

export default consumerConfidenceModule;
