import type { DomainModule } from '@/lib/domains/types';

const equalityModule: DomainModule = {
  definition: {
    id: 'equality',
    label: { fr: 'Égalité & Inclusion', en: 'Equality & Inclusion' },
    description: {
      fr: 'Égalité des genres et inclusion sociale : écart de genre, représentation politique des femmes, écart salarial et inégalités de genre.',
      en: 'Gender equality and social inclusion: gender gap, women\'s political representation, wage gap and gender inequality.',
    },
    icon: '⚖️',
    group: 'society',
    active: true,
    seedSources: [
      'https://www.weforum.org/reports/global-gender-gap-report/',
      'https://www.ipu.org/women-in-parliament',
      'https://hdr.undp.org/data-center/thematic-composite-indices/gender-inequality-index',
    ],
    indicators: [
      {
        id: 'gender_gap_index',
        label: { fr: "Indice d'écart de genre", en: 'Gender Gap Index' },
        unit: 'index',
        unitLabel: { fr: 'score', en: 'score' },
        direction: 'higher_is_better',
        weight: 4,
        thresholds: { excellent: 0.80, good: 0.74, fair: 0.68, poor: 0.62 },
        minValue: 0,
        maxValue: 1,
      },
      {
        id: 'women_parliament',
        label: { fr: 'Femmes au parlement', en: 'Women in parliament' },
        unit: 'percent',
        unitLabel: { fr: '% sièges', en: '% seats' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 40, good: 30, fair: 20, poor: 12 },
        minValue: 0,
        maxValue: 100,
      },
      {
        id: 'gender_wage_gap',
        label: { fr: 'Écart salarial H/F', en: 'Gender wage gap' },
        unit: 'percent',
        unitLabel: { fr: '%', en: '%' },
        direction: 'lower_is_better',
        weight: 2,
        thresholds: { excellent: 8, good: 14, fair: 20, poor: 28 },
        minValue: 0,
        maxValue: 50,
      },
      {
        id: 'gii_index',
        label: { fr: "Indice d'inégalité de genre", en: 'Gender Inequality Index' },
        unit: 'index',
        unitLabel: { fr: 'score', en: 'score' },
        direction: 'lower_is_better',
        weight: 3,
        thresholds: { excellent: 0.05, good: 0.10, fair: 0.25, poor: 0.45 },
        minValue: 0,
        maxValue: 1,
      },
    ],
  },

  seedData: [
    // ── Europe ──────────────────────────────────────────────────────────────
    { geoCode: 'IS', geoName: 'Iceland',          dataYear: 2023, values: { gender_gap_index: 0.91, women_parliament: 48, gender_wage_gap: 5, gii_index: 0.02 } },
    { geoCode: 'NO', geoName: 'Norway',           dataYear: 2023, values: { gender_gap_index: 0.88, women_parliament: 45, gender_wage_gap: 5, gii_index: 0.02 } },
    { geoCode: 'SE', geoName: 'Sweden',           dataYear: 2023, values: { gender_gap_index: 0.82, women_parliament: 46, gender_wage_gap: 7, gii_index: 0.04 } },
    { geoCode: 'FI', geoName: 'Finland',          dataYear: 2023, values: { gender_gap_index: 0.86, women_parliament: 46, gender_wage_gap: 6, gii_index: 0.03 } },
    { geoCode: 'AT', geoName: 'Austria',          dataYear: 2023, values: { gender_gap_index: 0.78, women_parliament: 40, gender_wage_gap: 13, gii_index: 0.06 } },
    { geoCode: 'DK', geoName: 'Denmark',          dataYear: 2023, values: { gender_gap_index: 0.82, women_parliament: 44, gender_wage_gap: 5, gii_index: 0.01 } },
    { geoCode: 'CH', geoName: 'Switzerland',      dataYear: 2023, values: { gender_gap_index: 0.80, women_parliament: 42, gender_wage_gap: 8, gii_index: 0.02 } },
    { geoCode: 'PT', geoName: 'Portugal',         dataYear: 2023, values: { gender_gap_index: 0.76, women_parliament: 37, gender_wage_gap: 11, gii_index: 0.08 } },
    { geoCode: 'HR', geoName: 'Croatia',          dataYear: 2023, values: { gender_gap_index: 0.72, women_parliament: 30, gender_wage_gap: 12, gii_index: 0.12 } },
    { geoCode: 'RO', geoName: 'Romania',          dataYear: 2023, values: { gender_gap_index: 0.69, women_parliament: 19, gender_wage_gap: 4, gii_index: 0.28 } },
    { geoCode: 'FR', geoName: 'France',           dataYear: 2023, values: { gender_gap_index: 0.76, women_parliament: 37, gender_wage_gap: 12, gii_index: 0.05 } },
    { geoCode: 'IE', geoName: 'Ireland',          dataYear: 2023, values: { gender_gap_index: 0.80, women_parliament: 28, gender_wage_gap: 10, gii_index: 0.06 } },
    { geoCode: 'ES', geoName: 'Spain',            dataYear: 2023, values: { gender_gap_index: 0.79, women_parliament: 44, gender_wage_gap: 10, gii_index: 0.05 } },
    { geoCode: 'DE', geoName: 'Germany',          dataYear: 2023, values: { gender_gap_index: 0.79, women_parliament: 35, gender_wage_gap: 14, gii_index: 0.04 } },
    { geoCode: 'IT', geoName: 'Italy',            dataYear: 2023, values: { gender_gap_index: 0.72, women_parliament: 32, gender_wage_gap: 15, gii_index: 0.06 } },
    { geoCode: 'NL', geoName: 'Netherlands',      dataYear: 2023, values: { gender_gap_index: 0.77, women_parliament: 39, gender_wage_gap: 9, gii_index: 0.03 } },
    { geoCode: 'BE', geoName: 'Belgium',          dataYear: 2023, values: { gender_gap_index: 0.78, women_parliament: 42, gender_wage_gap: 4, gii_index: 0.04 } },
    { geoCode: 'GB', geoName: 'United Kingdom',   dataYear: 2023, values: { gender_gap_index: 0.78, women_parliament: 35, gender_wage_gap: 13, gii_index: 0.06 } },
    { geoCode: 'GR', geoName: 'Greece',           dataYear: 2023, values: { gender_gap_index: 0.70, women_parliament: 21, gender_wage_gap: 10, gii_index: 0.12 } },
    { geoCode: 'SK', geoName: 'Slovakia',         dataYear: 2023, values: { gender_gap_index: 0.69, women_parliament: 22, gender_wage_gap: 11, gii_index: 0.15 } },
    { geoCode: 'CZ', geoName: 'Czechia',          dataYear: 2023, values: { gender_gap_index: 0.71, women_parliament: 25, gender_wage_gap: 15, gii_index: 0.13 } },
    { geoCode: 'PL', geoName: 'Poland',           dataYear: 2023, values: { gender_gap_index: 0.71, women_parliament: 28, gender_wage_gap: 9, gii_index: 0.11 } },
    { geoCode: 'HU', geoName: 'Hungary',          dataYear: 2023, values: { gender_gap_index: 0.68, women_parliament: 14, gender_wage_gap: 14, gii_index: 0.22 } },
    { geoCode: 'BG', geoName: 'Bulgaria',         dataYear: 2023, values: { gender_gap_index: 0.71, women_parliament: 26, gender_wage_gap: 11, gii_index: 0.21 } },
    { geoCode: 'LU', geoName: 'Luxembourg',       dataYear: 2023, values: { gender_gap_index: 0.75, women_parliament: 35, gender_wage_gap: 1, gii_index: 0.04 } },
    { geoCode: 'EE', geoName: 'Estonia',          dataYear: 2023, values: { gender_gap_index: 0.74, women_parliament: 29, gender_wage_gap: 18, gii_index: 0.09 } },
    { geoCode: 'LT', geoName: 'Lithuania',        dataYear: 2023, values: { gender_gap_index: 0.75, women_parliament: 28, gender_wage_gap: 10, gii_index: 0.10 } },
    { geoCode: 'LV', geoName: 'Latvia',           dataYear: 2023, values: { gender_gap_index: 0.76, women_parliament: 31, gender_wage_gap: 14, gii_index: 0.17 } },
    { geoCode: 'SI', geoName: 'Slovenia',         dataYear: 2023, values: { gender_gap_index: 0.74, women_parliament: 36, gender_wage_gap: 7, gii_index: 0.07 } },
    { geoCode: 'RS', geoName: 'Serbia',           dataYear: 2023, values: { gender_gap_index: 0.71, women_parliament: 35, gender_wage_gap: 13, gii_index: 0.14 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2023, values: { gender_gap_index: 0.68, women_parliament: 21, gender_wage_gap: 16, gii_index: 0.16 } },
    { geoCode: 'AL', geoName: 'Albania',          dataYear: 2023, values: { gender_gap_index: 0.70, women_parliament: 36, gender_wage_gap: 12, gii_index: 0.18 } },
    { geoCode: 'MK', geoName: 'North Macedonia',  dataYear: 2023, values: { gender_gap_index: 0.69, women_parliament: 40, gender_wage_gap: 14, gii_index: 0.15 } },
    { geoCode: 'ME', geoName: 'Montenegro',       dataYear: 2023, values: { gender_gap_index: 0.71, women_parliament: 27, gender_wage_gap: 14, gii_index: 0.13 } },
    { geoCode: 'MT', geoName: 'Malta',            dataYear: 2023, values: { gender_gap_index: 0.70, women_parliament: 28, gender_wage_gap: 10, gii_index: 0.17 } },
    { geoCode: 'CY', geoName: 'Cyprus',           dataYear: 2023, values: { gender_gap_index: 0.69, women_parliament: 18, gender_wage_gap: 15, gii_index: 0.11 } },
    { geoCode: 'MD', geoName: 'Moldova',          dataYear: 2023, values: { gender_gap_index: 0.74, women_parliament: 27, gender_wage_gap: 12, gii_index: 0.23 } },

    // ── North America ───────────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',    dataYear: 2023, values: { gender_gap_index: 0.75, women_parliament: 28, gender_wage_gap: 17, gii_index: 0.16 } },
    { geoCode: 'CA', geoName: 'Canada',           dataYear: 2023, values: { gender_gap_index: 0.77, women_parliament: 30, gender_wage_gap: 11, gii_index: 0.07 } },
    { geoCode: 'MX', geoName: 'Mexico',           dataYear: 2023, values: { gender_gap_index: 0.76, women_parliament: 50, gender_wage_gap: 16, gii_index: 0.31 } },

    // ── Central America & Caribbean ─────────────────────────────────────────
    { geoCode: 'GT', geoName: 'Guatemala',        dataYear: 2023, values: { gender_gap_index: 0.66, women_parliament: 19, gender_wage_gap: 20, gii_index: 0.44 } },
    { geoCode: 'HN', geoName: 'Honduras',         dataYear: 2023, values: { gender_gap_index: 0.69, women_parliament: 28, gender_wage_gap: 18, gii_index: 0.42 } },
    { geoCode: 'SV', geoName: 'El Salvador',      dataYear: 2023, values: { gender_gap_index: 0.69, women_parliament: 27, gender_wage_gap: 17, gii_index: 0.38 } },
    { geoCode: 'CR', geoName: 'Costa Rica',       dataYear: 2023, values: { gender_gap_index: 0.78, women_parliament: 46, gender_wage_gap: 13, gii_index: 0.22 } },
    { geoCode: 'PA', geoName: 'Panama',           dataYear: 2023, values: { gender_gap_index: 0.74, women_parliament: 23, gender_wage_gap: 16, gii_index: 0.41 } },
    { geoCode: 'JM', geoName: 'Jamaica',          dataYear: 2023, values: { gender_gap_index: 0.73, women_parliament: 18, gender_wage_gap: 15, gii_index: 0.37 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2023, values: { gender_gap_index: 0.72, women_parliament: 31, gender_wage_gap: 14, gii_index: 0.32 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2023, values: { gender_gap_index: 0.71, women_parliament: 27, gender_wage_gap: 18, gii_index: 0.42 } },
    { geoCode: 'NI', geoName: 'Nicaragua',        dataYear: 2023, values: { gender_gap_index: 0.81, women_parliament: 51, gender_wage_gap: 16, gii_index: 0.43 } },
    { geoCode: 'CU', geoName: 'Cuba',             dataYear: 2023, values: { gender_gap_index: 0.75, women_parliament: 53, gender_wage_gap: 14, gii_index: 0.30 } },
    { geoCode: 'HT', geoName: 'Haiti',            dataYear: 2023, values: { gender_gap_index: 0.60, women_parliament: 3, gender_wage_gap: 32, gii_index: 0.64 } },
    { geoCode: 'BZ', geoName: 'Belize',           dataYear: 2023, values: { gender_gap_index: 0.70, women_parliament: 12, gender_wage_gap: 18, gii_index: 0.39 } },

    // ── South America ───────────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',           dataYear: 2023, values: { gender_gap_index: 0.73, women_parliament: 18, gender_wage_gap: 19, gii_index: 0.39 } },
    { geoCode: 'AR', geoName: 'Argentina',        dataYear: 2023, values: { gender_gap_index: 0.76, women_parliament: 44, gender_wage_gap: 16, gii_index: 0.29 } },
    { geoCode: 'CL', geoName: 'Chile',            dataYear: 2023, values: { gender_gap_index: 0.74, women_parliament: 35, gender_wage_gap: 15, gii_index: 0.25 } },
    { geoCode: 'CO', geoName: 'Colombia',         dataYear: 2023, values: { gender_gap_index: 0.74, women_parliament: 29, gender_wage_gap: 16, gii_index: 0.35 } },
    { geoCode: 'PE', geoName: 'Peru',             dataYear: 2023, values: { gender_gap_index: 0.73, women_parliament: 28, gender_wage_gap: 18, gii_index: 0.39 } },
    { geoCode: 'VE', geoName: 'Venezuela',        dataYear: 2023, values: { gender_gap_index: 0.73, women_parliament: 22, gender_wage_gap: 20, gii_index: 0.46 } },
    { geoCode: 'EC', geoName: 'Ecuador',          dataYear: 2023, values: { gender_gap_index: 0.74, women_parliament: 38, gender_wage_gap: 17, gii_index: 0.37 } },
    { geoCode: 'UY', geoName: 'Uruguay',          dataYear: 2023, values: { gender_gap_index: 0.75, women_parliament: 25, gender_wage_gap: 10, gii_index: 0.26 } },
    { geoCode: 'PY', geoName: 'Paraguay',         dataYear: 2023, values: { gender_gap_index: 0.68, women_parliament: 16, gender_wage_gap: 22, gii_index: 0.45 } },
    { geoCode: 'BO', geoName: 'Bolivia',          dataYear: 2023, values: { gender_gap_index: 0.76, women_parliament: 46, gender_wage_gap: 19, gii_index: 0.42 } },
    { geoCode: 'GY', geoName: 'Guyana',           dataYear: 2023, values: { gender_gap_index: 0.72, women_parliament: 36, gender_wage_gap: 18, gii_index: 0.44 } },
    { geoCode: 'SR', geoName: 'Suriname',         dataYear: 2023, values: { gender_gap_index: 0.70, women_parliament: 31, gender_wage_gap: 19, gii_index: 0.46 } },

    // ── East Asia ───────────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',            dataYear: 2023, values: { gender_gap_index: 0.65, women_parliament: 10, gender_wage_gap: 22, gii_index: 0.08 } },
    { geoCode: 'KR', geoName: 'South Korea',      dataYear: 2023, values: { gender_gap_index: 0.68, women_parliament: 19, gender_wage_gap: 31, gii_index: 0.07 } },
    { geoCode: 'CN', geoName: 'China',            dataYear: 2023, values: { gender_gap_index: 0.68, women_parliament: 25, gender_wage_gap: 19, gii_index: 0.16 } },
    { geoCode: 'TW', geoName: 'Taiwan',           dataYear: 2023, values: { gender_gap_index: 0.71, women_parliament: 42, gender_wage_gap: 14, gii_index: 0.05 } },
    { geoCode: 'MN', geoName: 'Mongolia',         dataYear: 2023, values: { gender_gap_index: 0.73, women_parliament: 17, gender_wage_gap: 15, gii_index: 0.32 } },

    // ── Southeast Asia ──────────────────────────────────────────────────────
    { geoCode: 'SG', geoName: 'Singapore',        dataYear: 2023, values: { gender_gap_index: 0.73, women_parliament: 29, gender_wage_gap: 14, gii_index: 0.04 } },
    { geoCode: 'TH', geoName: 'Thailand',         dataYear: 2023, values: { gender_gap_index: 0.71, women_parliament: 16, gender_wage_gap: 12, gii_index: 0.33 } },
    { geoCode: 'VN', geoName: 'Vietnam',          dataYear: 2023, values: { gender_gap_index: 0.71, women_parliament: 31, gender_wage_gap: 13, gii_index: 0.30 } },
    { geoCode: 'ID', geoName: 'Indonesia',        dataYear: 2023, values: { gender_gap_index: 0.70, women_parliament: 22, gender_wage_gap: 19, gii_index: 0.45 } },
    { geoCode: 'PH', geoName: 'Philippines',      dataYear: 2023, values: { gender_gap_index: 0.79, women_parliament: 28, gender_wage_gap: 10, gii_index: 0.42 } },
    { geoCode: 'MY', geoName: 'Malaysia',         dataYear: 2023, values: { gender_gap_index: 0.68, women_parliament: 14, gender_wage_gap: 16, gii_index: 0.25 } },
    { geoCode: 'MM', geoName: 'Myanmar',          dataYear: 2023, values: { gender_gap_index: 0.67, women_parliament: 15, gender_wage_gap: 18, gii_index: 0.48 } },
    { geoCode: 'KH', geoName: 'Cambodia',         dataYear: 2023, values: { gender_gap_index: 0.68, women_parliament: 21, gender_wage_gap: 20, gii_index: 0.47 } },
    { geoCode: 'LA', geoName: 'Laos',             dataYear: 2023, values: { gender_gap_index: 0.69, women_parliament: 22, gender_wage_gap: 17, gii_index: 0.46 } },
    { geoCode: 'BN', geoName: 'Brunei',           dataYear: 2023, values: { gender_gap_index: 0.66, women_parliament: 9, gender_wage_gap: 14, gii_index: 0.22 } },
    { geoCode: 'TL', geoName: 'Timor-Leste',     dataYear: 2023, values: { gender_gap_index: 0.69, women_parliament: 38, gender_wage_gap: 20, gii_index: 0.43 } },

    // ── South Asia ──────────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',            dataYear: 2023, values: { gender_gap_index: 0.64, women_parliament: 15, gender_wage_gap: 25, gii_index: 0.49 } },
    { geoCode: 'PK', geoName: 'Pakistan',         dataYear: 2023, values: { gender_gap_index: 0.56, women_parliament: 20, gender_wage_gap: 35, gii_index: 0.54 } },
    { geoCode: 'BD', geoName: 'Bangladesh',       dataYear: 2023, values: { gender_gap_index: 0.71, women_parliament: 21, gender_wage_gap: 23, gii_index: 0.53 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',        dataYear: 2023, values: { gender_gap_index: 0.68, women_parliament: 5, gender_wage_gap: 20, gii_index: 0.40 } },
    { geoCode: 'NP', geoName: 'Nepal',            dataYear: 2023, values: { gender_gap_index: 0.69, women_parliament: 34, gender_wage_gap: 22, gii_index: 0.45 } },
    { geoCode: 'AF', geoName: 'Afghanistan',      dataYear: 2023, values: { gender_gap_index: 0.41, women_parliament: 0, gender_wage_gap: 45, gii_index: 0.66 } },
    { geoCode: 'BT', geoName: 'Bhutan',           dataYear: 2023, values: { gender_gap_index: 0.67, women_parliament: 15, gender_wage_gap: 18, gii_index: 0.42 } },
    { geoCode: 'MV', geoName: 'Maldives',         dataYear: 2023, values: { gender_gap_index: 0.64, women_parliament: 5, gender_wage_gap: 20, gii_index: 0.35 } },

    // ── Central Asia ────────────────────────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',       dataYear: 2023, values: { gender_gap_index: 0.71, women_parliament: 27, gender_wage_gap: 20, gii_index: 0.19 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',       dataYear: 2023, values: { gender_gap_index: 0.69, women_parliament: 32, gender_wage_gap: 22, gii_index: 0.28 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',     dataYear: 2023, values: { gender_gap_index: 0.67, women_parliament: 25, gender_wage_gap: 24, gii_index: 0.35 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',       dataYear: 2023, values: { gender_gap_index: 0.70, women_parliament: 19, gender_wage_gap: 23, gii_index: 0.37 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',       dataYear: 2023, values: { gender_gap_index: 0.66, women_parliament: 24, gender_wage_gap: 26, gii_index: 0.42 } },

    // ── Middle East ─────────────────────────────────────────────────────────
    { geoCode: 'SA', geoName: 'Saudi Arabia',     dataYear: 2023, values: { gender_gap_index: 0.60, women_parliament: 20, gender_wage_gap: 28, gii_index: 0.25 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2023, values: { gender_gap_index: 0.68, women_parliament: 50, gender_wage_gap: 18, gii_index: 0.08 } },
    { geoCode: 'IL', geoName: 'Israel',           dataYear: 2023, values: { gender_gap_index: 0.73, women_parliament: 29, gender_wage_gap: 22, gii_index: 0.08 } },
    { geoCode: 'TR', geoName: 'Turkey',           dataYear: 2023, values: { gender_gap_index: 0.64, women_parliament: 17, gender_wage_gap: 20, gii_index: 0.27 } },
    { geoCode: 'IR', geoName: 'Iran',             dataYear: 2023, values: { gender_gap_index: 0.57, women_parliament: 6, gender_wage_gap: 32, gii_index: 0.46 } },
    { geoCode: 'IQ', geoName: 'Iraq',             dataYear: 2023, values: { gender_gap_index: 0.55, women_parliament: 26, gender_wage_gap: 34, gii_index: 0.58 } },
    { geoCode: 'JO', geoName: 'Jordan',           dataYear: 2023, values: { gender_gap_index: 0.61, women_parliament: 16, gender_wage_gap: 27, gii_index: 0.44 } },
    { geoCode: 'LB', geoName: 'Lebanon',          dataYear: 2023, values: { gender_gap_index: 0.61, women_parliament: 6, gender_wage_gap: 26, gii_index: 0.36 } },
    { geoCode: 'KW', geoName: 'Kuwait',           dataYear: 2023, values: { gender_gap_index: 0.63, women_parliament: 5, gender_wage_gap: 22, gii_index: 0.24 } },
    { geoCode: 'QA', geoName: 'Qatar',            dataYear: 2023, values: { gender_gap_index: 0.63, women_parliament: 5, gender_wage_gap: 20, gii_index: 0.19 } },
    { geoCode: 'BH', geoName: 'Bahrain',          dataYear: 2023, values: { gender_gap_index: 0.63, women_parliament: 15, gender_wage_gap: 22, gii_index: 0.21 } },
    { geoCode: 'OM', geoName: 'Oman',             dataYear: 2023, values: { gender_gap_index: 0.60, women_parliament: 2, gender_wage_gap: 24, gii_index: 0.28 } },
    { geoCode: 'YE', geoName: 'Yemen',            dataYear: 2023, values: { gender_gap_index: 0.49, women_parliament: 1, gender_wage_gap: 38, gii_index: 0.82 } },
    { geoCode: 'SY', geoName: 'Syria',            dataYear: 2023, values: { gender_gap_index: 0.55, women_parliament: 12, gender_wage_gap: 35, gii_index: 0.55 } },
    { geoCode: 'PS', geoName: 'Palestine',        dataYear: 2023, values: { gender_gap_index: 0.56, women_parliament: 7, gender_wage_gap: 30, gii_index: 0.52 } },

    // ── North Africa ────────────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',            dataYear: 2023, values: { gender_gap_index: 0.63, women_parliament: 28, gender_wage_gap: 28, gii_index: 0.44 } },
    { geoCode: 'MA', geoName: 'Morocco',          dataYear: 2023, values: { gender_gap_index: 0.61, women_parliament: 24, gender_wage_gap: 25, gii_index: 0.41 } },
    { geoCode: 'DZ', geoName: 'Algeria',          dataYear: 2023, values: { gender_gap_index: 0.60, women_parliament: 8, gender_wage_gap: 30, gii_index: 0.43 } },
    { geoCode: 'TN', geoName: 'Tunisia',          dataYear: 2023, values: { gender_gap_index: 0.63, women_parliament: 26, gender_wage_gap: 22, gii_index: 0.30 } },
    { geoCode: 'LY', geoName: 'Libya',            dataYear: 2023, values: { gender_gap_index: 0.56, women_parliament: 16, gender_wage_gap: 30, gii_index: 0.52 } },

    // ── Sub-Saharan Africa ──────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',     dataYear: 2023, values: { gender_gap_index: 0.78, women_parliament: 45, gender_wage_gap: 22, gii_index: 0.41 } },
    { geoCode: 'NG', geoName: 'Nigeria',          dataYear: 2023, values: { gender_gap_index: 0.63, women_parliament: 4, gender_wage_gap: 28, gii_index: 0.68 } },
    { geoCode: 'KE', geoName: 'Kenya',            dataYear: 2023, values: { gender_gap_index: 0.73, women_parliament: 23, gender_wage_gap: 22, gii_index: 0.53 } },
    { geoCode: 'ET', geoName: 'Ethiopia',         dataYear: 2023, values: { gender_gap_index: 0.69, women_parliament: 42, gender_wage_gap: 25, gii_index: 0.52 } },
    { geoCode: 'GH', geoName: 'Ghana',            dataYear: 2023, values: { gender_gap_index: 0.67, women_parliament: 15, gender_wage_gap: 23, gii_index: 0.55 } },
    { geoCode: 'TZ', geoName: 'Tanzania',         dataYear: 2023, values: { gender_gap_index: 0.72, women_parliament: 37, gender_wage_gap: 22, gii_index: 0.56 } },
    { geoCode: 'UG', geoName: 'Uganda',           dataYear: 2023, values: { gender_gap_index: 0.72, women_parliament: 34, gender_wage_gap: 24, gii_index: 0.53 } },
    { geoCode: 'RW', geoName: 'Rwanda',           dataYear: 2023, values: { gender_gap_index: 0.80, women_parliament: 61, gender_wage_gap: 15, gii_index: 0.40 } },
    { geoCode: 'SN', geoName: 'Senegal',          dataYear: 2023, values: { gender_gap_index: 0.68, women_parliament: 44, gender_wage_gap: 25, gii_index: 0.52 } },
    { geoCode: 'CI', geoName: "Cote d'Ivoire",    dataYear: 2023, values: { gender_gap_index: 0.64, women_parliament: 14, gender_wage_gap: 27, gii_index: 0.63 } },
    { geoCode: 'CM', geoName: 'Cameroon',         dataYear: 2023, values: { gender_gap_index: 0.66, women_parliament: 34, gender_wage_gap: 26, gii_index: 0.56 } },
    { geoCode: 'AO', geoName: 'Angola',           dataYear: 2023, values: { gender_gap_index: 0.66, women_parliament: 30, gender_wage_gap: 28, gii_index: 0.58 } },
    { geoCode: 'MZ', geoName: 'Mozambique',       dataYear: 2023, values: { gender_gap_index: 0.72, women_parliament: 43, gender_wage_gap: 24, gii_index: 0.54 } },
    { geoCode: 'MG', geoName: 'Madagascar',       dataYear: 2023, values: { gender_gap_index: 0.69, women_parliament: 18, gender_wage_gap: 22, gii_index: 0.55 } },
    { geoCode: 'CD', geoName: 'DR Congo',         dataYear: 2023, values: { gender_gap_index: 0.64, women_parliament: 14, gender_wage_gap: 30, gii_index: 0.62 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',         dataYear: 2023, values: { gender_gap_index: 0.73, women_parliament: 35, gender_wage_gap: 20, gii_index: 0.53 } },
    { geoCode: 'BW', geoName: 'Botswana',         dataYear: 2023, values: { gender_gap_index: 0.72, women_parliament: 11, gender_wage_gap: 16, gii_index: 0.46 } },
    { geoCode: 'NA', geoName: 'Namibia',          dataYear: 2023, values: { gender_gap_index: 0.80, women_parliament: 44, gender_wage_gap: 17, gii_index: 0.44 } },
    { geoCode: 'MU', geoName: 'Mauritius',        dataYear: 2023, values: { gender_gap_index: 0.69, women_parliament: 20, gender_wage_gap: 15, gii_index: 0.36 } },
    { geoCode: 'GA', geoName: 'Gabon',            dataYear: 2023, values: { gender_gap_index: 0.67, women_parliament: 17, gender_wage_gap: 22, gii_index: 0.53 } },
    { geoCode: 'ML', geoName: 'Mali',             dataYear: 2023, values: { gender_gap_index: 0.62, women_parliament: 28, gender_wage_gap: 28, gii_index: 0.67 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',     dataYear: 2023, values: { gender_gap_index: 0.63, women_parliament: 6, gender_wage_gap: 30, gii_index: 0.65 } },
    { geoCode: 'NE', geoName: 'Niger',            dataYear: 2023, values: { gender_gap_index: 0.60, women_parliament: 26, gender_wage_gap: 32, gii_index: 0.64 } },
    { geoCode: 'TD', geoName: 'Chad',             dataYear: 2023, values: { gender_gap_index: 0.58, women_parliament: 15, gender_wage_gap: 34, gii_index: 0.71 } },
    { geoCode: 'MW', geoName: 'Malawi',           dataYear: 2023, values: { gender_gap_index: 0.71, women_parliament: 23, gender_wage_gap: 22, gii_index: 0.57 } },
    { geoCode: 'ZM', geoName: 'Zambia',           dataYear: 2023, values: { gender_gap_index: 0.71, women_parliament: 15, gender_wage_gap: 24, gii_index: 0.54 } },
    { geoCode: 'SL', geoName: 'Sierra Leone',     dataYear: 2023, values: { gender_gap_index: 0.65, women_parliament: 12, gender_wage_gap: 28, gii_index: 0.65 } },
    { geoCode: 'LR', geoName: 'Liberia',          dataYear: 2023, values: { gender_gap_index: 0.66, women_parliament: 11, gender_wage_gap: 26, gii_index: 0.66 } },
    { geoCode: 'TG', geoName: 'Togo',             dataYear: 2023, values: { gender_gap_index: 0.64, women_parliament: 17, gender_wage_gap: 25, gii_index: 0.57 } },
    { geoCode: 'BI', geoName: 'Burundi',          dataYear: 2023, values: { gender_gap_index: 0.72, women_parliament: 39, gender_wage_gap: 23, gii_index: 0.50 } },
    { geoCode: 'SS', geoName: 'South Sudan',      dataYear: 2023, values: { gender_gap_index: 0.57, women_parliament: 28, gender_wage_gap: 35, gii_index: 0.84 } },
    { geoCode: 'SD', geoName: 'Sudan',            dataYear: 2023, values: { gender_gap_index: 0.54, women_parliament: 0, gender_wage_gap: 36, gii_index: 0.56 } },

    // ── Oceania ─────────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',        dataYear: 2023, values: { gender_gap_index: 0.78, women_parliament: 38, gender_wage_gap: 12, gii_index: 0.07 } },
    { geoCode: 'NZ', geoName: 'New Zealand',      dataYear: 2023, values: { gender_gap_index: 0.84, women_parliament: 48, gender_wage_gap: 8, gii_index: 0.03 } },
    { geoCode: 'FJ', geoName: 'Fiji',             dataYear: 2023, values: { gender_gap_index: 0.66, women_parliament: 20, gender_wage_gap: 18, gii_index: 0.37 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2023, values: { gender_gap_index: 0.60, women_parliament: 2, gender_wage_gap: 28, gii_index: 0.72 } },

    // ── Ex-USSR ─────────────────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',           dataYear: 2023, values: { gender_gap_index: 0.69, women_parliament: 16, gender_wage_gap: 28, gii_index: 0.20 } },
    { geoCode: 'UA', geoName: 'Ukraine',          dataYear: 2023, values: { gender_gap_index: 0.71, women_parliament: 21, gender_wage_gap: 22, gii_index: 0.23 } },
    { geoCode: 'BY', geoName: 'Belarus',          dataYear: 2023, values: { gender_gap_index: 0.73, women_parliament: 33, gender_wage_gap: 25, gii_index: 0.12 } },
    { geoCode: 'GE', geoName: 'Georgia',          dataYear: 2023, values: { gender_gap_index: 0.69, women_parliament: 19, gender_wage_gap: 21, gii_index: 0.33 } },
    { geoCode: 'AM', geoName: 'Armenia',          dataYear: 2023, values: { gender_gap_index: 0.67, women_parliament: 36, gender_wage_gap: 23, gii_index: 0.26 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',       dataYear: 2023, values: { gender_gap_index: 0.68, women_parliament: 18, gender_wage_gap: 24, gii_index: 0.30 } },
  ],

  seedDataPrev: [
    // ── Europe ──────────────────────────────────────────────────────────────
    { geoCode: 'IS', geoName: 'Iceland',          dataYear: 2022, values: { gender_gap_index: 0.91, women_parliament: 48, gender_wage_gap: 6, gii_index: 0.02 } },
    { geoCode: 'NO', geoName: 'Norway',           dataYear: 2022, values: { gender_gap_index: 0.87, women_parliament: 45, gender_wage_gap: 5, gii_index: 0.02 } },
    { geoCode: 'SE', geoName: 'Sweden',           dataYear: 2022, values: { gender_gap_index: 0.82, women_parliament: 47, gender_wage_gap: 7, gii_index: 0.04 } },
    { geoCode: 'FI', geoName: 'Finland',          dataYear: 2022, values: { gender_gap_index: 0.86, women_parliament: 46, gender_wage_gap: 7, gii_index: 0.03 } },
    { geoCode: 'AT', geoName: 'Austria',          dataYear: 2022, values: { gender_gap_index: 0.77, women_parliament: 40, gender_wage_gap: 14, gii_index: 0.06 } },
    { geoCode: 'DK', geoName: 'Denmark',          dataYear: 2022, values: { gender_gap_index: 0.81, women_parliament: 43, gender_wage_gap: 5, gii_index: 0.01 } },
    { geoCode: 'CH', geoName: 'Switzerland',      dataYear: 2022, values: { gender_gap_index: 0.80, women_parliament: 42, gender_wage_gap: 9, gii_index: 0.02 } },
    { geoCode: 'PT', geoName: 'Portugal',         dataYear: 2022, values: { gender_gap_index: 0.75, women_parliament: 36, gender_wage_gap: 12, gii_index: 0.08 } },
    { geoCode: 'HR', geoName: 'Croatia',          dataYear: 2022, values: { gender_gap_index: 0.72, women_parliament: 29, gender_wage_gap: 13, gii_index: 0.12 } },
    { geoCode: 'RO', geoName: 'Romania',          dataYear: 2022, values: { gender_gap_index: 0.69, women_parliament: 19, gender_wage_gap: 5, gii_index: 0.29 } },
    { geoCode: 'FR', geoName: 'France',           dataYear: 2022, values: { gender_gap_index: 0.76, women_parliament: 37, gender_wage_gap: 12, gii_index: 0.05 } },
    { geoCode: 'IE', geoName: 'Ireland',          dataYear: 2022, values: { gender_gap_index: 0.80, women_parliament: 27, gender_wage_gap: 11, gii_index: 0.06 } },
    { geoCode: 'ES', geoName: 'Spain',            dataYear: 2022, values: { gender_gap_index: 0.79, women_parliament: 43, gender_wage_gap: 11, gii_index: 0.05 } },
    { geoCode: 'DE', geoName: 'Germany',          dataYear: 2022, values: { gender_gap_index: 0.80, women_parliament: 35, gender_wage_gap: 14, gii_index: 0.04 } },
    { geoCode: 'IT', geoName: 'Italy',            dataYear: 2022, values: { gender_gap_index: 0.72, women_parliament: 31, gender_wage_gap: 16, gii_index: 0.06 } },
    { geoCode: 'NL', geoName: 'Netherlands',      dataYear: 2022, values: { gender_gap_index: 0.77, women_parliament: 38, gender_wage_gap: 10, gii_index: 0.03 } },
    { geoCode: 'BE', geoName: 'Belgium',          dataYear: 2022, values: { gender_gap_index: 0.78, women_parliament: 41, gender_wage_gap: 5, gii_index: 0.04 } },
    { geoCode: 'GB', geoName: 'United Kingdom',   dataYear: 2022, values: { gender_gap_index: 0.78, women_parliament: 34, gender_wage_gap: 14, gii_index: 0.06 } },
    { geoCode: 'GR', geoName: 'Greece',           dataYear: 2022, values: { gender_gap_index: 0.69, women_parliament: 21, gender_wage_gap: 11, gii_index: 0.12 } },
    { geoCode: 'SK', geoName: 'Slovakia',         dataYear: 2022, values: { gender_gap_index: 0.69, women_parliament: 21, gender_wage_gap: 12, gii_index: 0.15 } },
    { geoCode: 'CZ', geoName: 'Czechia',          dataYear: 2022, values: { gender_gap_index: 0.70, women_parliament: 25, gender_wage_gap: 16, gii_index: 0.14 } },
    { geoCode: 'PL', geoName: 'Poland',           dataYear: 2022, values: { gender_gap_index: 0.71, women_parliament: 28, gender_wage_gap: 9, gii_index: 0.11 } },
    { geoCode: 'HU', geoName: 'Hungary',          dataYear: 2022, values: { gender_gap_index: 0.68, women_parliament: 13, gender_wage_gap: 15, gii_index: 0.23 } },
    { geoCode: 'BG', geoName: 'Bulgaria',         dataYear: 2022, values: { gender_gap_index: 0.71, women_parliament: 25, gender_wage_gap: 12, gii_index: 0.22 } },
    { geoCode: 'LU', geoName: 'Luxembourg',       dataYear: 2022, values: { gender_gap_index: 0.75, women_parliament: 35, gender_wage_gap: 1, gii_index: 0.04 } },
    { geoCode: 'EE', geoName: 'Estonia',          dataYear: 2022, values: { gender_gap_index: 0.74, women_parliament: 28, gender_wage_gap: 19, gii_index: 0.10 } },
    { geoCode: 'LT', geoName: 'Lithuania',        dataYear: 2022, values: { gender_gap_index: 0.74, women_parliament: 27, gender_wage_gap: 11, gii_index: 0.10 } },
    { geoCode: 'LV', geoName: 'Latvia',           dataYear: 2022, values: { gender_gap_index: 0.76, women_parliament: 30, gender_wage_gap: 15, gii_index: 0.18 } },
    { geoCode: 'SI', geoName: 'Slovenia',         dataYear: 2022, values: { gender_gap_index: 0.74, women_parliament: 35, gender_wage_gap: 7, gii_index: 0.07 } },
    { geoCode: 'RS', geoName: 'Serbia',           dataYear: 2022, values: { gender_gap_index: 0.71, women_parliament: 34, gender_wage_gap: 14, gii_index: 0.14 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2022, values: { gender_gap_index: 0.67, women_parliament: 20, gender_wage_gap: 17, gii_index: 0.16 } },
    { geoCode: 'AL', geoName: 'Albania',          dataYear: 2022, values: { gender_gap_index: 0.70, women_parliament: 35, gender_wage_gap: 13, gii_index: 0.19 } },
    { geoCode: 'MK', geoName: 'North Macedonia',  dataYear: 2022, values: { gender_gap_index: 0.69, women_parliament: 39, gender_wage_gap: 15, gii_index: 0.16 } },
    { geoCode: 'ME', geoName: 'Montenegro',       dataYear: 2022, values: { gender_gap_index: 0.70, women_parliament: 26, gender_wage_gap: 14, gii_index: 0.14 } },
    { geoCode: 'MT', geoName: 'Malta',            dataYear: 2022, values: { gender_gap_index: 0.70, women_parliament: 27, gender_wage_gap: 11, gii_index: 0.18 } },
    { geoCode: 'CY', geoName: 'Cyprus',           dataYear: 2022, values: { gender_gap_index: 0.68, women_parliament: 18, gender_wage_gap: 16, gii_index: 0.12 } },
    { geoCode: 'MD', geoName: 'Moldova',          dataYear: 2022, values: { gender_gap_index: 0.73, women_parliament: 26, gender_wage_gap: 13, gii_index: 0.24 } },

    // ── North America ───────────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',    dataYear: 2022, values: { gender_gap_index: 0.74, women_parliament: 28, gender_wage_gap: 17, gii_index: 0.16 } },
    { geoCode: 'CA', geoName: 'Canada',           dataYear: 2022, values: { gender_gap_index: 0.77, women_parliament: 30, gender_wage_gap: 12, gii_index: 0.07 } },
    { geoCode: 'MX', geoName: 'Mexico',           dataYear: 2022, values: { gender_gap_index: 0.76, women_parliament: 49, gender_wage_gap: 17, gii_index: 0.31 } },

    // ── Central America & Caribbean ─────────────────────────────────────────
    { geoCode: 'GT', geoName: 'Guatemala',        dataYear: 2022, values: { gender_gap_index: 0.66, women_parliament: 19, gender_wage_gap: 21, gii_index: 0.44 } },
    { geoCode: 'HN', geoName: 'Honduras',         dataYear: 2022, values: { gender_gap_index: 0.69, women_parliament: 27, gender_wage_gap: 19, gii_index: 0.43 } },
    { geoCode: 'SV', geoName: 'El Salvador',      dataYear: 2022, values: { gender_gap_index: 0.69, women_parliament: 26, gender_wage_gap: 18, gii_index: 0.38 } },
    { geoCode: 'CR', geoName: 'Costa Rica',       dataYear: 2022, values: { gender_gap_index: 0.78, women_parliament: 45, gender_wage_gap: 14, gii_index: 0.22 } },
    { geoCode: 'PA', geoName: 'Panama',           dataYear: 2022, values: { gender_gap_index: 0.74, women_parliament: 22, gender_wage_gap: 17, gii_index: 0.41 } },
    { geoCode: 'JM', geoName: 'Jamaica',          dataYear: 2022, values: { gender_gap_index: 0.73, women_parliament: 18, gender_wage_gap: 16, gii_index: 0.38 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2022, values: { gender_gap_index: 0.72, women_parliament: 30, gender_wage_gap: 15, gii_index: 0.33 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2022, values: { gender_gap_index: 0.71, women_parliament: 26, gender_wage_gap: 19, gii_index: 0.43 } },
    { geoCode: 'NI', geoName: 'Nicaragua',        dataYear: 2022, values: { gender_gap_index: 0.81, women_parliament: 50, gender_wage_gap: 17, gii_index: 0.44 } },
    { geoCode: 'CU', geoName: 'Cuba',             dataYear: 2022, values: { gender_gap_index: 0.75, women_parliament: 53, gender_wage_gap: 15, gii_index: 0.31 } },
    { geoCode: 'HT', geoName: 'Haiti',            dataYear: 2022, values: { gender_gap_index: 0.60, women_parliament: 3, gender_wage_gap: 33, gii_index: 0.65 } },
    { geoCode: 'BZ', geoName: 'Belize',           dataYear: 2022, values: { gender_gap_index: 0.69, women_parliament: 11, gender_wage_gap: 19, gii_index: 0.40 } },

    // ── South America ───────────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',           dataYear: 2022, values: { gender_gap_index: 0.73, women_parliament: 17, gender_wage_gap: 20, gii_index: 0.39 } },
    { geoCode: 'AR', geoName: 'Argentina',        dataYear: 2022, values: { gender_gap_index: 0.76, women_parliament: 43, gender_wage_gap: 17, gii_index: 0.30 } },
    { geoCode: 'CL', geoName: 'Chile',            dataYear: 2022, values: { gender_gap_index: 0.74, women_parliament: 34, gender_wage_gap: 16, gii_index: 0.26 } },
    { geoCode: 'CO', geoName: 'Colombia',         dataYear: 2022, values: { gender_gap_index: 0.74, women_parliament: 28, gender_wage_gap: 17, gii_index: 0.36 } },
    { geoCode: 'PE', geoName: 'Peru',             dataYear: 2022, values: { gender_gap_index: 0.72, women_parliament: 28, gender_wage_gap: 19, gii_index: 0.40 } },
    { geoCode: 'VE', geoName: 'Venezuela',        dataYear: 2022, values: { gender_gap_index: 0.72, women_parliament: 22, gender_wage_gap: 21, gii_index: 0.47 } },
    { geoCode: 'EC', geoName: 'Ecuador',          dataYear: 2022, values: { gender_gap_index: 0.74, women_parliament: 37, gender_wage_gap: 18, gii_index: 0.38 } },
    { geoCode: 'UY', geoName: 'Uruguay',          dataYear: 2022, values: { gender_gap_index: 0.74, women_parliament: 24, gender_wage_gap: 11, gii_index: 0.27 } },
    { geoCode: 'PY', geoName: 'Paraguay',         dataYear: 2022, values: { gender_gap_index: 0.68, women_parliament: 16, gender_wage_gap: 23, gii_index: 0.46 } },
    { geoCode: 'BO', geoName: 'Bolivia',          dataYear: 2022, values: { gender_gap_index: 0.76, women_parliament: 46, gender_wage_gap: 20, gii_index: 0.43 } },
    { geoCode: 'GY', geoName: 'Guyana',           dataYear: 2022, values: { gender_gap_index: 0.72, women_parliament: 35, gender_wage_gap: 19, gii_index: 0.45 } },
    { geoCode: 'SR', geoName: 'Suriname',         dataYear: 2022, values: { gender_gap_index: 0.70, women_parliament: 30, gender_wage_gap: 20, gii_index: 0.47 } },

    // ── East Asia ───────────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',            dataYear: 2022, values: { gender_gap_index: 0.65, women_parliament: 10, gender_wage_gap: 22, gii_index: 0.08 } },
    { geoCode: 'KR', geoName: 'South Korea',      dataYear: 2022, values: { gender_gap_index: 0.68, women_parliament: 19, gender_wage_gap: 31, gii_index: 0.07 } },
    { geoCode: 'CN', geoName: 'China',            dataYear: 2022, values: { gender_gap_index: 0.68, women_parliament: 25, gender_wage_gap: 19, gii_index: 0.17 } },
    { geoCode: 'TW', geoName: 'Taiwan',           dataYear: 2022, values: { gender_gap_index: 0.71, women_parliament: 42, gender_wage_gap: 14, gii_index: 0.05 } },
    { geoCode: 'MN', geoName: 'Mongolia',         dataYear: 2022, values: { gender_gap_index: 0.72, women_parliament: 17, gender_wage_gap: 16, gii_index: 0.33 } },

    // ── Southeast Asia ──────────────────────────────────────────────────────
    { geoCode: 'SG', geoName: 'Singapore',        dataYear: 2022, values: { gender_gap_index: 0.73, women_parliament: 29, gender_wage_gap: 15, gii_index: 0.04 } },
    { geoCode: 'TH', geoName: 'Thailand',         dataYear: 2022, values: { gender_gap_index: 0.71, women_parliament: 16, gender_wage_gap: 13, gii_index: 0.33 } },
    { geoCode: 'VN', geoName: 'Vietnam',          dataYear: 2022, values: { gender_gap_index: 0.71, women_parliament: 30, gender_wage_gap: 14, gii_index: 0.30 } },
    { geoCode: 'ID', geoName: 'Indonesia',        dataYear: 2022, values: { gender_gap_index: 0.69, women_parliament: 21, gender_wage_gap: 20, gii_index: 0.45 } },
    { geoCode: 'PH', geoName: 'Philippines',      dataYear: 2022, values: { gender_gap_index: 0.78, women_parliament: 28, gender_wage_gap: 11, gii_index: 0.43 } },
    { geoCode: 'MY', geoName: 'Malaysia',         dataYear: 2022, values: { gender_gap_index: 0.68, women_parliament: 13, gender_wage_gap: 17, gii_index: 0.25 } },
    { geoCode: 'MM', geoName: 'Myanmar',          dataYear: 2022, values: { gender_gap_index: 0.67, women_parliament: 15, gender_wage_gap: 19, gii_index: 0.49 } },
    { geoCode: 'KH', geoName: 'Cambodia',         dataYear: 2022, values: { gender_gap_index: 0.68, women_parliament: 20, gender_wage_gap: 21, gii_index: 0.47 } },
    { geoCode: 'LA', geoName: 'Laos',             dataYear: 2022, values: { gender_gap_index: 0.69, women_parliament: 22, gender_wage_gap: 18, gii_index: 0.46 } },
    { geoCode: 'BN', geoName: 'Brunei',           dataYear: 2022, values: { gender_gap_index: 0.66, women_parliament: 9, gender_wage_gap: 15, gii_index: 0.23 } },
    { geoCode: 'TL', geoName: 'Timor-Leste',     dataYear: 2022, values: { gender_gap_index: 0.69, women_parliament: 38, gender_wage_gap: 21, gii_index: 0.44 } },

    // ── South Asia ──────────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',            dataYear: 2022, values: { gender_gap_index: 0.63, women_parliament: 14, gender_wage_gap: 26, gii_index: 0.49 } },
    { geoCode: 'PK', geoName: 'Pakistan',         dataYear: 2022, values: { gender_gap_index: 0.56, women_parliament: 20, gender_wage_gap: 36, gii_index: 0.55 } },
    { geoCode: 'BD', geoName: 'Bangladesh',       dataYear: 2022, values: { gender_gap_index: 0.71, women_parliament: 21, gender_wage_gap: 24, gii_index: 0.54 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',        dataYear: 2022, values: { gender_gap_index: 0.67, women_parliament: 5, gender_wage_gap: 21, gii_index: 0.40 } },
    { geoCode: 'NP', geoName: 'Nepal',            dataYear: 2022, values: { gender_gap_index: 0.69, women_parliament: 33, gender_wage_gap: 23, gii_index: 0.46 } },
    { geoCode: 'AF', geoName: 'Afghanistan',      dataYear: 2022, values: { gender_gap_index: 0.44, women_parliament: 0, gender_wage_gap: 44, gii_index: 0.66 } },
    { geoCode: 'BT', geoName: 'Bhutan',           dataYear: 2022, values: { gender_gap_index: 0.67, women_parliament: 15, gender_wage_gap: 19, gii_index: 0.43 } },
    { geoCode: 'MV', geoName: 'Maldives',         dataYear: 2022, values: { gender_gap_index: 0.64, women_parliament: 5, gender_wage_gap: 21, gii_index: 0.36 } },

    // ── Central Asia ────────────────────────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',       dataYear: 2022, values: { gender_gap_index: 0.71, women_parliament: 26, gender_wage_gap: 21, gii_index: 0.20 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',       dataYear: 2022, values: { gender_gap_index: 0.69, women_parliament: 32, gender_wage_gap: 23, gii_index: 0.29 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',     dataYear: 2022, values: { gender_gap_index: 0.67, women_parliament: 25, gender_wage_gap: 25, gii_index: 0.36 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',       dataYear: 2022, values: { gender_gap_index: 0.70, women_parliament: 19, gender_wage_gap: 24, gii_index: 0.38 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',       dataYear: 2022, values: { gender_gap_index: 0.66, women_parliament: 23, gender_wage_gap: 27, gii_index: 0.43 } },

    // ── Middle East ─────────────────────────────────────────────────────────
    { geoCode: 'SA', geoName: 'Saudi Arabia',     dataYear: 2022, values: { gender_gap_index: 0.60, women_parliament: 19, gender_wage_gap: 29, gii_index: 0.26 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2022, values: { gender_gap_index: 0.68, women_parliament: 50, gender_wage_gap: 19, gii_index: 0.08 } },
    { geoCode: 'IL', geoName: 'Israel',           dataYear: 2022, values: { gender_gap_index: 0.73, women_parliament: 28, gender_wage_gap: 23, gii_index: 0.08 } },
    { geoCode: 'TR', geoName: 'Turkey',           dataYear: 2022, values: { gender_gap_index: 0.64, women_parliament: 17, gender_wage_gap: 21, gii_index: 0.27 } },
    { geoCode: 'IR', geoName: 'Iran',             dataYear: 2022, values: { gender_gap_index: 0.57, women_parliament: 6, gender_wage_gap: 33, gii_index: 0.47 } },
    { geoCode: 'IQ', geoName: 'Iraq',             dataYear: 2022, values: { gender_gap_index: 0.55, women_parliament: 25, gender_wage_gap: 35, gii_index: 0.58 } },
    { geoCode: 'JO', geoName: 'Jordan',           dataYear: 2022, values: { gender_gap_index: 0.61, women_parliament: 15, gender_wage_gap: 28, gii_index: 0.45 } },
    { geoCode: 'LB', geoName: 'Lebanon',          dataYear: 2022, values: { gender_gap_index: 0.60, women_parliament: 5, gender_wage_gap: 27, gii_index: 0.36 } },
    { geoCode: 'KW', geoName: 'Kuwait',           dataYear: 2022, values: { gender_gap_index: 0.63, women_parliament: 4, gender_wage_gap: 23, gii_index: 0.25 } },
    { geoCode: 'QA', geoName: 'Qatar',            dataYear: 2022, values: { gender_gap_index: 0.62, women_parliament: 4, gender_wage_gap: 21, gii_index: 0.20 } },
    { geoCode: 'BH', geoName: 'Bahrain',          dataYear: 2022, values: { gender_gap_index: 0.63, women_parliament: 15, gender_wage_gap: 23, gii_index: 0.22 } },
    { geoCode: 'OM', geoName: 'Oman',             dataYear: 2022, values: { gender_gap_index: 0.60, women_parliament: 2, gender_wage_gap: 25, gii_index: 0.29 } },
    { geoCode: 'YE', geoName: 'Yemen',            dataYear: 2022, values: { gender_gap_index: 0.49, women_parliament: 1, gender_wage_gap: 39, gii_index: 0.83 } },
    { geoCode: 'SY', geoName: 'Syria',            dataYear: 2022, values: { gender_gap_index: 0.55, women_parliament: 12, gender_wage_gap: 36, gii_index: 0.56 } },
    { geoCode: 'PS', geoName: 'Palestine',        dataYear: 2022, values: { gender_gap_index: 0.56, women_parliament: 7, gender_wage_gap: 31, gii_index: 0.53 } },

    // ── North Africa ────────────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',            dataYear: 2022, values: { gender_gap_index: 0.63, women_parliament: 27, gender_wage_gap: 29, gii_index: 0.45 } },
    { geoCode: 'MA', geoName: 'Morocco',          dataYear: 2022, values: { gender_gap_index: 0.61, women_parliament: 23, gender_wage_gap: 26, gii_index: 0.42 } },
    { geoCode: 'DZ', geoName: 'Algeria',          dataYear: 2022, values: { gender_gap_index: 0.60, women_parliament: 8, gender_wage_gap: 31, gii_index: 0.44 } },
    { geoCode: 'TN', geoName: 'Tunisia',          dataYear: 2022, values: { gender_gap_index: 0.63, women_parliament: 26, gender_wage_gap: 23, gii_index: 0.30 } },
    { geoCode: 'LY', geoName: 'Libya',            dataYear: 2022, values: { gender_gap_index: 0.56, women_parliament: 16, gender_wage_gap: 31, gii_index: 0.53 } },

    // ── Sub-Saharan Africa ──────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',     dataYear: 2022, values: { gender_gap_index: 0.78, women_parliament: 44, gender_wage_gap: 23, gii_index: 0.42 } },
    { geoCode: 'NG', geoName: 'Nigeria',          dataYear: 2022, values: { gender_gap_index: 0.63, women_parliament: 4, gender_wage_gap: 29, gii_index: 0.69 } },
    { geoCode: 'KE', geoName: 'Kenya',            dataYear: 2022, values: { gender_gap_index: 0.73, women_parliament: 23, gender_wage_gap: 23, gii_index: 0.54 } },
    { geoCode: 'ET', geoName: 'Ethiopia',         dataYear: 2022, values: { gender_gap_index: 0.69, women_parliament: 41, gender_wage_gap: 26, gii_index: 0.52 } },
    { geoCode: 'GH', geoName: 'Ghana',            dataYear: 2022, values: { gender_gap_index: 0.67, women_parliament: 15, gender_wage_gap: 24, gii_index: 0.56 } },
    { geoCode: 'TZ', geoName: 'Tanzania',         dataYear: 2022, values: { gender_gap_index: 0.72, women_parliament: 36, gender_wage_gap: 23, gii_index: 0.56 } },
    { geoCode: 'UG', geoName: 'Uganda',           dataYear: 2022, values: { gender_gap_index: 0.72, women_parliament: 33, gender_wage_gap: 25, gii_index: 0.54 } },
    { geoCode: 'RW', geoName: 'Rwanda',           dataYear: 2022, values: { gender_gap_index: 0.80, women_parliament: 61, gender_wage_gap: 16, gii_index: 0.40 } },
    { geoCode: 'SN', geoName: 'Senegal',          dataYear: 2022, values: { gender_gap_index: 0.68, women_parliament: 43, gender_wage_gap: 26, gii_index: 0.53 } },
    { geoCode: 'CI', geoName: "Cote d'Ivoire",    dataYear: 2022, values: { gender_gap_index: 0.64, women_parliament: 13, gender_wage_gap: 28, gii_index: 0.64 } },
    { geoCode: 'CM', geoName: 'Cameroon',         dataYear: 2022, values: { gender_gap_index: 0.66, women_parliament: 33, gender_wage_gap: 27, gii_index: 0.57 } },
    { geoCode: 'AO', geoName: 'Angola',           dataYear: 2022, values: { gender_gap_index: 0.66, women_parliament: 30, gender_wage_gap: 29, gii_index: 0.59 } },
    { geoCode: 'MZ', geoName: 'Mozambique',       dataYear: 2022, values: { gender_gap_index: 0.72, women_parliament: 42, gender_wage_gap: 25, gii_index: 0.54 } },
    { geoCode: 'MG', geoName: 'Madagascar',       dataYear: 2022, values: { gender_gap_index: 0.69, women_parliament: 17, gender_wage_gap: 23, gii_index: 0.56 } },
    { geoCode: 'CD', geoName: 'DR Congo',         dataYear: 2022, values: { gender_gap_index: 0.64, women_parliament: 13, gender_wage_gap: 31, gii_index: 0.63 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',         dataYear: 2022, values: { gender_gap_index: 0.73, women_parliament: 34, gender_wage_gap: 21, gii_index: 0.54 } },
    { geoCode: 'BW', geoName: 'Botswana',         dataYear: 2022, values: { gender_gap_index: 0.71, women_parliament: 11, gender_wage_gap: 17, gii_index: 0.47 } },
    { geoCode: 'NA', geoName: 'Namibia',          dataYear: 2022, values: { gender_gap_index: 0.80, women_parliament: 43, gender_wage_gap: 18, gii_index: 0.45 } },
    { geoCode: 'MU', geoName: 'Mauritius',        dataYear: 2022, values: { gender_gap_index: 0.68, women_parliament: 20, gender_wage_gap: 16, gii_index: 0.37 } },
    { geoCode: 'GA', geoName: 'Gabon',            dataYear: 2022, values: { gender_gap_index: 0.67, women_parliament: 16, gender_wage_gap: 23, gii_index: 0.54 } },
    { geoCode: 'ML', geoName: 'Mali',             dataYear: 2022, values: { gender_gap_index: 0.62, women_parliament: 27, gender_wage_gap: 29, gii_index: 0.68 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',     dataYear: 2022, values: { gender_gap_index: 0.62, women_parliament: 6, gender_wage_gap: 31, gii_index: 0.66 } },
    { geoCode: 'NE', geoName: 'Niger',            dataYear: 2022, values: { gender_gap_index: 0.60, women_parliament: 25, gender_wage_gap: 33, gii_index: 0.65 } },
    { geoCode: 'TD', geoName: 'Chad',             dataYear: 2022, values: { gender_gap_index: 0.58, women_parliament: 15, gender_wage_gap: 35, gii_index: 0.72 } },
    { geoCode: 'MW', geoName: 'Malawi',           dataYear: 2022, values: { gender_gap_index: 0.71, women_parliament: 23, gender_wage_gap: 23, gii_index: 0.58 } },
    { geoCode: 'ZM', geoName: 'Zambia',           dataYear: 2022, values: { gender_gap_index: 0.71, women_parliament: 15, gender_wage_gap: 25, gii_index: 0.55 } },
    { geoCode: 'SL', geoName: 'Sierra Leone',     dataYear: 2022, values: { gender_gap_index: 0.65, women_parliament: 12, gender_wage_gap: 29, gii_index: 0.66 } },
    { geoCode: 'LR', geoName: 'Liberia',          dataYear: 2022, values: { gender_gap_index: 0.66, women_parliament: 11, gender_wage_gap: 27, gii_index: 0.67 } },
    { geoCode: 'TG', geoName: 'Togo',             dataYear: 2022, values: { gender_gap_index: 0.64, women_parliament: 16, gender_wage_gap: 26, gii_index: 0.58 } },
    { geoCode: 'BI', geoName: 'Burundi',          dataYear: 2022, values: { gender_gap_index: 0.71, women_parliament: 38, gender_wage_gap: 24, gii_index: 0.51 } },
    { geoCode: 'SS', geoName: 'South Sudan',      dataYear: 2022, values: { gender_gap_index: 0.57, women_parliament: 28, gender_wage_gap: 36, gii_index: 0.84 } },
    { geoCode: 'SD', geoName: 'Sudan',            dataYear: 2022, values: { gender_gap_index: 0.54, women_parliament: 0, gender_wage_gap: 37, gii_index: 0.57 } },

    // ── Oceania ─────────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',        dataYear: 2022, values: { gender_gap_index: 0.77, women_parliament: 37, gender_wage_gap: 13, gii_index: 0.07 } },
    { geoCode: 'NZ', geoName: 'New Zealand',      dataYear: 2022, values: { gender_gap_index: 0.84, women_parliament: 48, gender_wage_gap: 9, gii_index: 0.03 } },
    { geoCode: 'FJ', geoName: 'Fiji',             dataYear: 2022, values: { gender_gap_index: 0.65, women_parliament: 19, gender_wage_gap: 19, gii_index: 0.38 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2022, values: { gender_gap_index: 0.60, women_parliament: 2, gender_wage_gap: 29, gii_index: 0.73 } },

    // ── Ex-USSR ─────────────────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',           dataYear: 2022, values: { gender_gap_index: 0.69, women_parliament: 16, gender_wage_gap: 29, gii_index: 0.20 } },
    { geoCode: 'UA', geoName: 'Ukraine',          dataYear: 2022, values: { gender_gap_index: 0.71, women_parliament: 21, gender_wage_gap: 23, gii_index: 0.24 } },
    { geoCode: 'BY', geoName: 'Belarus',          dataYear: 2022, values: { gender_gap_index: 0.73, women_parliament: 33, gender_wage_gap: 26, gii_index: 0.13 } },
    { geoCode: 'GE', geoName: 'Georgia',          dataYear: 2022, values: { gender_gap_index: 0.69, women_parliament: 18, gender_wage_gap: 22, gii_index: 0.34 } },
    { geoCode: 'AM', geoName: 'Armenia',          dataYear: 2022, values: { gender_gap_index: 0.67, women_parliament: 35, gender_wage_gap: 24, gii_index: 0.27 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',       dataYear: 2022, values: { gender_gap_index: 0.68, women_parliament: 18, gender_wage_gap: 25, gii_index: 0.31 } },
  ],
};

export default equalityModule;
