import type { DomainModule } from '@/lib/domains/types';

const infrastructureModule: DomainModule = {
  definition: {
    id: 'infrastructure',
    label: { fr: 'Infrastructure', en: 'Infrastructure', es: 'Infraestructura' },
    description: {
      fr: 'Qualité des infrastructures nationales : accès à internet, réseau routier, énergie électrique et performance logistique.',
      en: 'Quality of national infrastructure: internet access, road networks, electricity and logistics performance.',
      es: 'Calidad de las infraestructuras nacionales: acceso a internet, red vial, energía eléctrica y rendimiento logístico.',
    },
    icon: '🏗️',
    group: 'society',
    active: true,
    seedSources: [
      'https://data.worldbank.org/indicator/IT.NET.USER.ZS',
      'https://lpi.worldbank.org/',
      'https://data.worldbank.org/indicator/EG.ELC.ACCS.ZS',
      'https://www.weforum.org/reports/the-global-competitiveness-report-2019/',
    ],
    indicators: [
      {
        id: 'internet_access',
        label: { fr: 'Accès à internet', en: 'Internet access', es: 'Acceso a internet' },
        description: {
          fr: "Part de la population ayant utilisé internet (depuis n'importe quel appareil) au cours des 3 derniers mois",
          en: 'Share of the population that used the internet (from any device) in the last 3 months',
        },
        unit: 'percent',
        unitLabel: { fr: '% population', en: '% population', es: '% población' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 92, good: 80, fair: 60, poor: 35 },
        minValue: 0,
        maxValue: 100,
      },
      {
        id: 'logistics_performance',
        label: { fr: 'Performance logistique (LPI)', en: 'Logistics performance (LPI)', es: 'Rendimiento logístico (LPI)' },
        description: {
          fr: "Score de compétence logistique nationale : douanes, infrastructures, expéditions, qualité des services et suivi des cargaisons (Banque Mondiale, /5)",
          en: 'National logistics competence score: customs, infrastructure, shipments, service quality and cargo tracking (World Bank, /5)',
        },
        unit: 'index',
        unitLabel: { fr: 'indice /5', en: 'index /5', es: 'índice /5' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 4.0, good: 3.5, fair: 3.0, poor: 2.5 },
        minValue: 1,
        maxValue: 5,
      },
      {
        id: 'electricity_access',
        label: { fr: 'Accès à l\'électricité', en: 'Electricity access', es: 'Acceso a la electricidad' },
        description: {
          fr: "Part de la population disposant d'un accès à l'électricité au domicile, tant en zone urbaine que rurale",
          en: 'Share of the population with access to electricity at home, in both urban and rural areas',
        },
        unit: 'percent',
        unitLabel: { fr: '% population', en: '% population', es: '% población' },
        direction: 'higher_is_better',
        weight: 2,
        thresholds: { excellent: 99, good: 95, fair: 85, poor: 70 },
        minValue: 0,
        maxValue: 100,
      },
      {
        id: 'road_quality',
        label: { fr: 'Qualité des routes', en: 'Road quality', es: 'Calidad de carreteras' },
        description: {
          fr: "Score de qualité du réseau routier basé sur des enquêtes auprès des décideurs économiques (Forum économique mondial, /7)",
          en: 'Road network quality score based on surveys of business executives (World Economic Forum, /7)',
        },
        unit: 'index',
        unitLabel: { fr: 'indice /7', en: 'index /7', es: 'índice /7' },
        direction: 'higher_is_better',
        weight: 2,
        thresholds: { excellent: 5.8, good: 5.0, fair: 4.0, poor: 3.0 },
        minValue: 1,
        maxValue: 7,
      },
    ],
  },
  seedData: [
    // ── Europe de l'Ouest ──────────────────────────────────────────────────
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2023, values: { internet_access: 98.0, logistics_performance: 4.23, electricity_access: 100, road_quality: 5.7 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2023, values: { internet_access: 94.0, logistics_performance: 4.20, electricity_access: 100, road_quality: 5.4 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2023, values: { internet_access: 97.0, logistics_performance: 4.05, electricity_access: 100, road_quality: 5.5 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2023, values: { internet_access: 97.0, logistics_performance: 4.18, electricity_access: 100, road_quality: 5.5 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2023, values: { internet_access: 97.0, logistics_performance: 3.99, electricity_access: 100, road_quality: 5.2 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2023, values: { internet_access: 95.0, logistics_performance: 3.97, electricity_access: 100, road_quality: 5.3 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2023, values: { internet_access: 96.0, logistics_performance: 4.10, electricity_access: 100, road_quality: 5.9 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2023, values: { internet_access: 94.0, logistics_performance: 4.10, electricity_access: 100, road_quality: 5.4 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2023, values: { internet_access: 93.0, logistics_performance: 4.08, electricity_access: 100, road_quality: 4.8 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2023, values: { internet_access: 97.0, logistics_performance: 3.90, electricity_access: 100, road_quality: 5.5 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2023, values: { internet_access: 92.0, logistics_performance: 3.84, electricity_access: 100, road_quality: 5.1 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2023, values: { internet_access: 95.0, logistics_performance: 3.72, electricity_access: 100, road_quality: 4.8 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2023, values: { internet_access: 97.0, logistics_performance: 4.01, electricity_access: 100, road_quality: 5.0 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2023, values: { internet_access: 94.0, logistics_performance: 3.76, electricity_access: 100, road_quality: 5.2 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2023, values: { internet_access: 90.0, logistics_performance: 3.70, electricity_access: 100, road_quality: 4.4 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2023, values: { internet_access: 91.0, logistics_performance: 3.55, electricity_access: 100, road_quality: 4.9 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2023, values: { internet_access: 99.0, logistics_performance: 3.60, electricity_access: 100, road_quality: 5.0 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2023, values: { internet_access: 84.0, logistics_performance: 3.40, electricity_access: 100, road_quality: 4.0 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2023, values: { internet_access: 92.0, logistics_performance: 3.20, electricity_access: 100, road_quality: 4.5 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2023, values: { internet_access: 91.0, logistics_performance: 3.15, electricity_access: 100, road_quality: 4.8 } },
    // ── Europe du Nord / Baltes ───────────────────────────────────────────
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2023, values: { internet_access: 96.0, logistics_performance: 3.55, electricity_access: 100, road_quality: 4.5 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2023, values: { internet_access: 92.0, logistics_performance: 3.33, electricity_access: 100, road_quality: 3.8 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2023, values: { internet_access: 90.0, logistics_performance: 3.40, electricity_access: 100, road_quality: 4.1 } },
    // ── Europe Centrale & de l'Est ────────────────────────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2023, values: { internet_access: 93.0, logistics_performance: 3.60, electricity_access: 100, road_quality: 4.5 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2023, values: { internet_access: 90.0, logistics_performance: 3.71, electricity_access: 100, road_quality: 4.2 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2023, values: { internet_access: 90.0, logistics_performance: 3.40, electricity_access: 100, road_quality: 4.0 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2023, values: { internet_access: 88.0, logistics_performance: 3.42, electricity_access: 100, road_quality: 3.8 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2023, values: { internet_access: 85.0, logistics_performance: 3.15, electricity_access: 100, road_quality: 4.0 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2023, values: { internet_access: 89.0, logistics_performance: 3.35, electricity_access: 100, road_quality: 4.6 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2023, values: { internet_access: 86.0, logistics_performance: 3.08, electricity_access: 100, road_quality: 3.5 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2023, values: { internet_access: 82.0, logistics_performance: 3.02, electricity_access: 100, road_quality: 3.4 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2023, values: { internet_access: 81.0, logistics_performance: 2.90, electricity_access: 100, road_quality: 3.3 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2023, values: { internet_access: 78.0, logistics_performance: 2.75, electricity_access: 100, road_quality: 3.1 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2023, values: { internet_access: 80.0, logistics_performance: 2.70, electricity_access: 100, road_quality: 3.4 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2023, values: { internet_access: 83.0, logistics_performance: 2.72, electricity_access: 100, road_quality: 3.3 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2023, values: { internet_access: 79.0, logistics_performance: 2.60, electricity_access: 100, road_quality: 3.2 } },
    // ── Amérique du Nord ──────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',  dataYear: 2023, values: { internet_access: 92.0, logistics_performance: 3.99, electricity_access: 100, road_quality: 4.8 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2023, values: { internet_access: 93.0, logistics_performance: 3.97, electricity_access: 100, road_quality: 4.8 } },
    // ── Océanie ───────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2023, values: { internet_access: 91.0, logistics_performance: 3.75, electricity_access: 100, road_quality: 5.0 } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2023, values: { internet_access: 93.0, logistics_performance: 3.70, electricity_access: 100, road_quality: 4.8 } },
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2023, values: { internet_access: 68.0, logistics_performance: 2.55, electricity_access: 92,  road_quality: 3.0 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2023, values: { internet_access: 15.0, logistics_performance: 2.20, electricity_access: 22, road_quality: 2.2 } },
    // ── Asie de l'Est ───────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2023, values: { internet_access: 94.0, logistics_performance: 4.03, electricity_access: 100, road_quality: 6.0 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2023, values: { internet_access: 97.0, logistics_performance: 3.60, electricity_access: 100, road_quality: 5.5 } },
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2023, values: { internet_access: 96.0, logistics_performance: 4.00, electricity_access: 100, road_quality: 6.5 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2023, values: { internet_access: 92.0, logistics_performance: 3.55, electricity_access: 100, road_quality: 5.5 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2023, values: { internet_access: 77.0, logistics_performance: 3.65, electricity_access: 100, road_quality: 4.5 } },
    { geoCode: 'HK', geoName: 'Hong Kong',      dataYear: 2023, values: { internet_access: 93.0, logistics_performance: 3.92, electricity_access: 100, road_quality: 6.2 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2023, values: { internet_access: 64.0, logistics_performance: 2.50, electricity_access: 98,  road_quality: 2.8 } },
    // ── Asie du Sud-Est ──────────────────────────────────────────────────
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2023, values: { internet_access: 67.0, logistics_performance: 3.41, electricity_access: 100, road_quality: 4.2 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2023, values: { internet_access: 73.0, logistics_performance: 3.27, electricity_access: 99,  road_quality: 3.9 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2023, values: { internet_access: 62.0, logistics_performance: 3.15, electricity_access: 98,  road_quality: 3.8 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2023, values: { internet_access: 68.0, logistics_performance: 2.90, electricity_access: 97,  road_quality: 3.3 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2023, values: { internet_access: 90.0, logistics_performance: 3.43, electricity_access: 100, road_quality: 5.0 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2023, values: { internet_access: 44.0, logistics_performance: 2.30, electricity_access: 73,  road_quality: 2.5 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2023, values: { internet_access: 60.0, logistics_performance: 2.58, electricity_access: 82,  road_quality: 3.0 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2023, values: { internet_access: 52.0, logistics_performance: 2.44, electricity_access: 98,  road_quality: 2.8 } },
    // ── Asie du Sud ──────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2023, values: { internet_access: 50.0, logistics_performance: 3.18, electricity_access: 99,  road_quality: 3.8 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2023, values: { internet_access: 36.0, logistics_performance: 2.82, electricity_access: 96,  road_quality: 3.2 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2023, values: { internet_access: 44.0, logistics_performance: 2.52, electricity_access: 99,  road_quality: 3.0 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2023, values: { internet_access: 52.0, logistics_performance: 2.75, electricity_access: 100, road_quality: 3.6 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2023, values: { internet_access: 48.0, logistics_performance: 2.30, electricity_access: 90,  road_quality: 2.5 } },
    // ── Asie Centrale ────────────────────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2023, values: { internet_access: 83.0, logistics_performance: 2.81, electricity_access: 100, road_quality: 3.6 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2023, values: { internet_access: 72.0, logistics_performance: 2.58, electricity_access: 100, road_quality: 3.2 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2023, values: { internet_access: 76.0, logistics_performance: 2.62, electricity_access: 100, road_quality: 3.5 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2023, values: { internet_access: 79.0, logistics_performance: 2.71, electricity_access: 100, road_quality: 3.8 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2023, values: { internet_access: 78.0, logistics_performance: 2.50, electricity_access: 100, road_quality: 3.3 } },
    // ── Moyen-Orient ──────────────────────────────────────────────────────
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2023, values: { internet_access: 99.0, logistics_performance: 3.96, electricity_access: 100, road_quality: 6.4 } },
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2023, values: { internet_access: 98.0, logistics_performance: 3.54, electricity_access: 100, road_quality: 5.0 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2023, values: { internet_access: 99.0, logistics_performance: 3.47, electricity_access: 100, road_quality: 5.7 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2023, values: { internet_access: 98.0, logistics_performance: 3.25, electricity_access: 100, road_quality: 5.0 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2023, values: { internet_access: 98.0, logistics_performance: 3.10, electricity_access: 100, road_quality: 4.5 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2023, values: { internet_access: 95.0, logistics_performance: 3.20, electricity_access: 100, road_quality: 5.2 } },
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2023, values: { internet_access: 88.0, logistics_performance: 3.38, electricity_access: 100, road_quality: 4.8 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2023, values: { internet_access: 83.0, logistics_performance: 2.89, electricity_access: 100, road_quality: 4.0 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2023, values: { internet_access: 78.0, logistics_performance: 2.72, electricity_access: 100, road_quality: 3.5 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2023, values: { internet_access: 75.0, logistics_performance: 2.35, electricity_access: 100, road_quality: 2.8 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2023, values: { internet_access: 78.0, logistics_performance: 2.85, electricity_access: 100, road_quality: 3.8 } },
    // ── Turquie ───────────────────────────────────────────────────────────
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2023, values: { internet_access: 85.0, logistics_performance: 3.39, electricity_access: 100, road_quality: 4.4 } },
    // ── Ex-URSS ────────────────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2023, values: { internet_access: 88.0, logistics_performance: 2.76, electricity_access: 100, road_quality: 3.5 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2023, values: { internet_access: 82.0, logistics_performance: 2.60, electricity_access: 100, road_quality: 3.0 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2023, values: { internet_access: 85.0, logistics_performance: 2.65, electricity_access: 100, road_quality: 3.4 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2023, values: { internet_access: 76.0, logistics_performance: 2.48, electricity_access: 100, road_quality: 2.8 } },
    // ── Amérique Latine ────────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2023, values: { internet_access: 81.0, logistics_performance: 3.15, electricity_access: 100, road_quality: 3.4 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2023, values: { internet_access: 76.0, logistics_performance: 3.00, electricity_access: 100, road_quality: 3.8 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2023, values: { internet_access: 88.0, logistics_performance: 2.88, electricity_access: 100, road_quality: 3.0 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2023, values: { internet_access: 90.0, logistics_performance: 3.32, electricity_access: 100, road_quality: 4.2 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2023, values: { internet_access: 73.0, logistics_performance: 2.94, electricity_access: 100, road_quality: 3.5 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2023, values: { internet_access: 71.0, logistics_performance: 2.78, electricity_access: 97,  road_quality: 3.2 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2023, values: { internet_access: 70.0, logistics_performance: 2.74, electricity_access: 99,  road_quality: 3.6 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2023, values: { internet_access: 87.0, logistics_performance: 2.82, electricity_access: 100, road_quality: 3.8 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2023, values: { internet_access: 74.0, logistics_performance: 2.55, electricity_access: 100, road_quality: 2.7 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2023, values: { internet_access: 66.0, logistics_performance: 2.48, electricity_access: 97,  road_quality: 2.6 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2023, values: { internet_access: 72.0, logistics_performance: 2.38, electricity_access: 99,  road_quality: 2.4 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2023, values: { internet_access: 75.0, logistics_performance: 3.28, electricity_access: 95,  road_quality: 4.2 } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2023, values: { internet_access: 81.0, logistics_performance: 2.85, electricity_access: 100, road_quality: 3.5 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2023, values: { internet_access: 75.0, logistics_performance: 2.66, electricity_access: 98, road_quality: 3.3 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2023, values: { internet_access: 51.0, logistics_performance: 2.50, electricity_access: 96,  road_quality: 3.0 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2023, values: { internet_access: 68.0, logistics_performance: 2.20, electricity_access: 100, road_quality: 2.8 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2023, values: { internet_access: 48.0, logistics_performance: 2.46, electricity_access: 93,  road_quality: 2.8 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2023, values: { internet_access: 72.0, logistics_performance: 2.52, electricity_access: 98,  road_quality: 3.0 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2023, values: { internet_access: 77.0, logistics_performance: 2.62, electricity_access: 100, road_quality: 3.4 } },
    // ── Afrique du Nord ──────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2023, values: { internet_access: 72.0, logistics_performance: 2.82, electricity_access: 100, road_quality: 3.5 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2023, values: { internet_access: 88.0, logistics_performance: 2.94, electricity_access: 100, road_quality: 4.0 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2023, values: { internet_access: 71.0, logistics_performance: 2.80, electricity_access: 100, road_quality: 3.6 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2023, values: { internet_access: 64.0, logistics_performance: 2.45, electricity_access: 100, road_quality: 3.4 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2023, values: { internet_access: 50.0, logistics_performance: 2.10, electricity_access: 70,  road_quality: 2.5 } },
    // ── Afrique de l'Ouest ───────────────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2023, values: { internet_access: 55.0, logistics_performance: 2.53, electricity_access: 60,  road_quality: 2.5 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2023, values: { internet_access: 68.0, logistics_performance: 2.62, electricity_access: 85,  road_quality: 3.2 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2023, values: { internet_access: 58.0, logistics_performance: 2.65, electricity_access: 70,  road_quality: 3.0 } },
    { geoCode: 'CI', geoName: "Cote d'Ivoire",  dataYear: 2023, values: { internet_access: 45.0, logistics_performance: 2.60, electricity_access: 70,  road_quality: 3.1 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2023, values: { internet_access: 34.0, logistics_performance: 2.20, electricity_access: 50,  road_quality: 2.3 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2023, values: { internet_access: 25.0, logistics_performance: 2.18, electricity_access: 22,  road_quality: 2.4 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2023, values: { internet_access: 18.0, logistics_performance: 2.10, electricity_access: 19,  road_quality: 2.2 } },
    { geoCode: 'GN', geoName: 'Guinea',         dataYear: 2023, values: { internet_access: 28.0, logistics_performance: 2.15, electricity_access: 44,  road_quality: 2.3 } },
    { geoCode: 'BJ', geoName: 'Benin',          dataYear: 2023, values: { internet_access: 37.0, logistics_performance: 2.35, electricity_access: 42,  road_quality: 2.5 } },
    { geoCode: 'TG', geoName: 'Togo',           dataYear: 2023, values: { internet_access: 35.0, logistics_performance: 2.30, electricity_access: 54,  road_quality: 2.5 } },
    // ── Afrique de l'Est ─────────────────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2023, values: { internet_access: 40.0, logistics_performance: 2.81, electricity_access: 75,  road_quality: 3.0 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2023, values: { internet_access: 22.0, logistics_performance: 2.31, electricity_access: 52,  road_quality: 2.5 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2023, values: { internet_access: 32.0, logistics_performance: 2.56, electricity_access: 42,  road_quality: 2.8 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2023, values: { internet_access: 26.0, logistics_performance: 2.48, electricity_access: 43,  road_quality: 2.6 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2023, values: { internet_access: 33.0, logistics_performance: 2.62, electricity_access: 48,  road_quality: 3.5 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2023, values: { internet_access: 22.0, logistics_performance: 2.15, electricity_access: 34,  road_quality: 2.2 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2023, values: { internet_access: 72.0, logistics_performance: 2.85, electricity_access: 100, road_quality: 4.0 } },
    // ── Afrique Australe ─────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2023, values: { internet_access: 72.0, logistics_performance: 3.38, electricity_access: 84,  road_quality: 4.0 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2023, values: { internet_access: 65.0, logistics_performance: 2.75, electricity_access: 72,  road_quality: 3.5 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2023, values: { internet_access: 56.0, logistics_performance: 2.60, electricity_access: 55,  road_quality: 3.4 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2023, values: { internet_access: 30.0, logistics_performance: 2.42, electricity_access: 44,  road_quality: 2.7 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2023, values: { internet_access: 35.0, logistics_performance: 2.30, electricity_access: 46,  road_quality: 2.5 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2023, values: { internet_access: 22.0, logistics_performance: 2.18, electricity_access: 35,  road_quality: 2.3 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2023, values: { internet_access: 36.0, logistics_performance: 2.25, electricity_access: 47,  road_quality: 2.4 } },
    // ── Afrique Centrale ─────────────────────────────────────────────────
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2023, values: { internet_access: 38.0, logistics_performance: 2.38, electricity_access: 65,  road_quality: 2.5 } },
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2023, values: { internet_access: 23.0, logistics_performance: 2.05, electricity_access: 21,  road_quality: 2.0 } },
    { geoCode: 'CG', geoName: 'Congo',          dataYear: 2023, values: { internet_access: 30.0, logistics_performance: 2.15, electricity_access: 50,  road_quality: 2.2 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2023, values: { internet_access: 72.0, logistics_performance: 2.35, electricity_access: 92,  road_quality: 2.8 } },
  ],
  seedDataPrev: [
    // ── Europe de l'Ouest ──────────────────────────────── (WB internet/elec 2022, LPI 2023, road WEF 2019)
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2022, values: { internet_access: 92.5, logistics_performance: 4.10, electricity_access: 100, road_quality: 5.7 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2022, values: { internet_access: 91.6, logistics_performance: 4.10, electricity_access: 100, road_quality: 5.4 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2022, values: { internet_access: 95.0, logistics_performance: 4.00, electricity_access: 100, road_quality: 5.5 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2022, values: { internet_access: 97.9, logistics_performance: 4.10, electricity_access: 100, road_quality: 5.5 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2022, values: { internet_access: 99.0, logistics_performance: 3.70, electricity_access: 100, road_quality: 5.2 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2022, values: { internet_access: 93.0, logistics_performance: 4.20, electricity_access: 100, road_quality: 5.3 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2022, values: { internet_access: 96.5, logistics_performance: 4.10, electricity_access: 100, road_quality: 5.9 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2022, values: { internet_access: 93.6, logistics_performance: 4.00, electricity_access: 100, road_quality: 5.4 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2022, values: { internet_access: 94.0, logistics_performance: 4.00, electricity_access: 100, road_quality: 4.8 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2022, values: { internet_access: 98.2, logistics_performance: 3.60, electricity_access: 100, road_quality: 5.5 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2022, values: { internet_access: 85.3, logistics_performance: 3.90, electricity_access: 100, road_quality: 5.1 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2022, values: { internet_access: 96.6, logistics_performance: 3.60, electricity_access: 100, road_quality: 4.8 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2022, values: { internet_access: 96.3, logistics_performance: 3.70, electricity_access: 100, road_quality: 5.0 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2022, values: { internet_access: 94.5, logistics_performance: 3.90, electricity_access: 100, road_quality: 5.2 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2022, values: { internet_access: 85.1, logistics_performance: 3.70, electricity_access: 100, road_quality: 4.4 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2022, values: { internet_access: 84.5, logistics_performance: 3.40, electricity_access: 100, road_quality: 4.9 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2022, values: { internet_access: 99.8, logistics_performance: 3.60, electricity_access: 100, road_quality: 5.0 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2022, values: { internet_access: 83.2, logistics_performance: 3.70, electricity_access: 100, road_quality: 4.0 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2022, values: { internet_access: 91.0, logistics_performance: 3.10, electricity_access: 100, road_quality: 4.5 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2022, values: { internet_access: 90.0, logistics_performance: 3.10, electricity_access: 100, road_quality: 4.8 } },
    // ── Europe du Nord / Baltes ───────────────────────────
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2022, values: { internet_access: 91.5, logistics_performance: 3.60, electricity_access: 100, road_quality: 4.5 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2022, values: { internet_access: 90.0, logistics_performance: 3.25, electricity_access: 100, road_quality: 3.8 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2022, values: { internet_access: 88.0, logistics_performance: 3.30, electricity_access: 100, road_quality: 4.1 } },
    // ── Europe Centrale & de l'Est ───────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2022, values: { internet_access: 84.5, logistics_performance: 3.30, electricity_access: 100, road_quality: 4.5 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2022, values: { internet_access: 86.9, logistics_performance: 3.60, electricity_access: 100, road_quality: 4.2 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2022, values: { internet_access: 89.1, logistics_performance: 3.30, electricity_access: 100, road_quality: 4.0 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2022, values: { internet_access: 89.1, logistics_performance: 3.20, electricity_access: 100, road_quality: 3.8 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2022, values: { internet_access: 82.1, logistics_performance: 3.30, electricity_access: 100, road_quality: 4.0 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2022, values: { internet_access: 87.0, logistics_performance: 3.25, electricity_access: 100, road_quality: 4.6 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2022, values: { internet_access: 85.5, logistics_performance: 3.20, electricity_access: 100, road_quality: 3.5 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2022, values: { internet_access: 79.1, logistics_performance: 3.20, electricity_access: 100, road_quality: 3.4 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2022, values: { internet_access: 79.0, logistics_performance: 2.85, electricity_access: 100, road_quality: 3.3 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2022, values: { internet_access: 76.0, logistics_performance: 2.70, electricity_access: 100, road_quality: 3.1 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2022, values: { internet_access: 78.0, logistics_performance: 2.65, electricity_access: 100, road_quality: 3.4 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2022, values: { internet_access: 81.0, logistics_performance: 2.68, electricity_access: 100, road_quality: 3.3 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2022, values: { internet_access: 77.0, logistics_performance: 2.55, electricity_access: 100, road_quality: 3.2 } },
    // ── Amérique du Nord ──────────────────────────────────
    { geoCode: 'US', geoName: 'United States',  dataYear: 2022, values: { internet_access: 92.2, logistics_performance: 3.80, electricity_access: 100, road_quality: 4.8 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2022, values: { internet_access: 94.0, logistics_performance: 4.00, electricity_access: 100, road_quality: 4.8 } },
    // ── Océanie ───────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2022, values: { internet_access: 97.0, logistics_performance: 3.70, electricity_access: 100, road_quality: 5.0 } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2022, values: { internet_access: 96.2, logistics_performance: 3.60, electricity_access: 100, road_quality: 4.8 } },
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2022, values: { internet_access: 65.0, logistics_performance: 2.50, electricity_access: 91,  road_quality: 3.0 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2022, values: { internet_access: 14.0, logistics_performance: 2.15, electricity_access: 21, road_quality: 2.2 } },
    // ── Asie de l'Est ────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2022, values: { internet_access: 84.9, logistics_performance: 3.90, electricity_access: 100, road_quality: 6.0 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2022, values: { internet_access: 97.2, logistics_performance: 3.80, electricity_access: 100, road_quality: 5.5 } },
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2022, values: { internet_access: 96.0, logistics_performance: 4.30, electricity_access: 100, road_quality: 6.5 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2022, values: { internet_access: 90.5, logistics_performance: 3.90, electricity_access: 100, road_quality: 5.5 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2022, values: { internet_access: 75.6, logistics_performance: 3.70, electricity_access: 100, road_quality: 4.5 } },
    { geoCode: 'HK', geoName: 'Hong Kong',      dataYear: 2022, values: { internet_access: 92.0, logistics_performance: 3.85, electricity_access: 100, road_quality: 6.2 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2022, values: { internet_access: 62.0, logistics_performance: 2.45, electricity_access: 97,  road_quality: 2.8 } },
    // ── Asie du Sud-Est ──────────────────────────────────
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2022, values: { internet_access: 88.0, logistics_performance: 3.50, electricity_access: 100, road_quality: 4.2 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2022, values: { internet_access: 78.6, logistics_performance: 3.30, electricity_access: 100, road_quality: 3.9 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2022, values: { internet_access: 66.5, logistics_performance: 3.00, electricity_access: 100, road_quality: 3.8 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2022, values: { internet_access: 75.2, logistics_performance: 3.30, electricity_access: 94.8, road_quality: 3.3 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2022, values: { internet_access: 89.0, logistics_performance: 3.40, electricity_access: 100, road_quality: 5.0 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2022, values: { internet_access: 42.0, logistics_performance: 2.25, electricity_access: 70,  road_quality: 2.5 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2022, values: { internet_access: 57.0, logistics_performance: 2.52, electricity_access: 80,  road_quality: 3.0 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2022, values: { internet_access: 50.0, logistics_performance: 2.40, electricity_access: 97,  road_quality: 2.8 } },
    // ── Asie du Sud ──────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2022, values: { internet_access: 55.9, logistics_performance: 3.40, electricity_access: 99.2, road_quality: 3.8 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2022, values: { internet_access: 24.2, logistics_performance: 2.80, electricity_access: 95.0, road_quality: 3.2 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2022, values: { internet_access: 41.6, logistics_performance: 2.60, electricity_access: 99.4, road_quality: 3.0 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2022, values: { internet_access: 50.0, logistics_performance: 2.70, electricity_access: 100, road_quality: 3.6 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2022, values: { internet_access: 45.0, logistics_performance: 2.25, electricity_access: 88,  road_quality: 2.5 } },
    // ── Asie Centrale ────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2022, values: { internet_access: 92.3, logistics_performance: 2.70, electricity_access: 100, road_quality: 3.6 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2022, values: { internet_access: 70.0, logistics_performance: 2.52, electricity_access: 100, road_quality: 3.2 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2022, values: { internet_access: 74.0, logistics_performance: 2.55, electricity_access: 100, road_quality: 3.5 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2022, values: { internet_access: 77.0, logistics_performance: 2.65, electricity_access: 100, road_quality: 3.8 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2022, values: { internet_access: 76.0, logistics_performance: 2.45, electricity_access: 100, road_quality: 3.3 } },
    // ── Moyen-Orient ─────────────────────────────────────
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2022, values: { internet_access: 98.0, logistics_performance: 3.90, electricity_access: 100, road_quality: 6.4 } },
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2022, values: { internet_access: 100,  logistics_performance: 3.40, electricity_access: 100, road_quality: 5.0 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2022, values: { internet_access: 98.0, logistics_performance: 3.40, electricity_access: 100, road_quality: 5.7 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2022, values: { internet_access: 97.0, logistics_performance: 3.20, electricity_access: 100, road_quality: 5.0 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2022, values: { internet_access: 97.0, logistics_performance: 3.00, electricity_access: 100, road_quality: 4.5 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2022, values: { internet_access: 93.0, logistics_performance: 3.15, electricity_access: 100, road_quality: 5.2 } },
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2022, values: { internet_access: 91.9, logistics_performance: 3.60, electricity_access: 100, road_quality: 4.8 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2022, values: { internet_access: 81.0, logistics_performance: 2.85, electricity_access: 100, road_quality: 4.0 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2022, values: { internet_access: 76.0, logistics_performance: 2.68, electricity_access: 100, road_quality: 3.5 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2022, values: { internet_access: 73.0, logistics_performance: 2.30, electricity_access: 100, road_quality: 2.8 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2022, values: { internet_access: 76.0, logistics_performance: 2.80, electricity_access: 100, road_quality: 3.8 } },
    // ── Turquie ──────────────────────────────────────────
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2022, values: { internet_access: 83.4, logistics_performance: 3.40, electricity_access: 100, road_quality: 4.4 } },
    // ── Ex-URSS ──────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2022, values: { internet_access: 90.4, logistics_performance: 2.60, electricity_access: 100, road_quality: 3.5 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2022, values: { internet_access: 82.7, logistics_performance: 2.70, electricity_access: 100, road_quality: 3.0 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2022, values: { internet_access: 83.0, logistics_performance: 2.60, electricity_access: 100, road_quality: 3.4 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2022, values: { internet_access: 74.0, logistics_performance: 2.42, electricity_access: 100, road_quality: 2.8 } },
    // ── Amérique Latine ──────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2022, values: { internet_access: 80.5, logistics_performance: 3.20, electricity_access: 100, road_quality: 3.4 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2022, values: { internet_access: 78.6, logistics_performance: 2.90, electricity_access: 100, road_quality: 3.8 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2022, values: { internet_access: 88.4, logistics_performance: 2.80, electricity_access: 100, road_quality: 3.0 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2022, values: { internet_access: 93.5, logistics_performance: 3.00, electricity_access: 100, road_quality: 4.2 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2022, values: { internet_access: 72.8, logistics_performance: 2.90, electricity_access: 100, road_quality: 3.5 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2022, values: { internet_access: 69.0, logistics_performance: 2.72, electricity_access: 96,  road_quality: 3.2 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2022, values: { internet_access: 68.0, logistics_performance: 2.70, electricity_access: 99,  road_quality: 3.6 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2022, values: { internet_access: 86.0, logistics_performance: 2.78, electricity_access: 100, road_quality: 3.8 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2022, values: { internet_access: 72.0, logistics_performance: 2.50, electricity_access: 100, road_quality: 2.7 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2022, values: { internet_access: 64.0, logistics_performance: 2.44, electricity_access: 96,  road_quality: 2.6 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2022, values: { internet_access: 70.0, logistics_performance: 2.35, electricity_access: 99,  road_quality: 2.4 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2022, values: { internet_access: 73.0, logistics_performance: 3.22, electricity_access: 94,  road_quality: 4.2 } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2022, values: { internet_access: 79.0, logistics_performance: 2.80, electricity_access: 100, road_quality: 3.5 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2022, values: { internet_access: 73.0, logistics_performance: 2.60, electricity_access: 97, road_quality: 3.3 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2022, values: { internet_access: 49.0, logistics_performance: 2.45, electricity_access: 95,  road_quality: 3.0 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2022, values: { internet_access: 65.0, logistics_performance: 2.15, electricity_access: 100, road_quality: 2.8 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2022, values: { internet_access: 46.0, logistics_performance: 2.40, electricity_access: 92,  road_quality: 2.8 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2022, values: { internet_access: 70.0, logistics_performance: 2.48, electricity_access: 98,  road_quality: 3.0 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2022, values: { internet_access: 75.0, logistics_performance: 2.58, electricity_access: 100, road_quality: 3.4 } },
    // ── Afrique du Nord ──────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2022, values: { internet_access: 72.2, logistics_performance: 3.10, electricity_access: 100, road_quality: 3.5 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2022, values: { internet_access: 89.9, logistics_performance: 2.90, electricity_access: 100, road_quality: 4.0 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2022, values: { internet_access: 69.0, logistics_performance: 2.75, electricity_access: 100, road_quality: 3.6 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2022, values: { internet_access: 62.0, logistics_performance: 2.40, electricity_access: 100, road_quality: 3.4 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2022, values: { internet_access: 48.0, logistics_performance: 2.05, electricity_access: 69,  road_quality: 2.5 } },
    // ── Afrique de l'Ouest ───────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2022, values: { internet_access: 37.7, logistics_performance: 2.60, electricity_access: 60.5, road_quality: 2.5 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2022, values: { internet_access: 66.0, logistics_performance: 2.58, electricity_access: 84,  road_quality: 3.2 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2022, values: { internet_access: 55.0, logistics_performance: 2.60, electricity_access: 68,  road_quality: 3.0 } },
    { geoCode: 'CI', geoName: "Cote d'Ivoire",  dataYear: 2022, values: { internet_access: 43.0, logistics_performance: 2.55, electricity_access: 68,  road_quality: 3.1 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2022, values: { internet_access: 32.0, logistics_performance: 2.15, electricity_access: 48,  road_quality: 2.3 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2022, values: { internet_access: 23.0, logistics_performance: 2.14, electricity_access: 20,  road_quality: 2.4 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2022, values: { internet_access: 16.0, logistics_performance: 2.05, electricity_access: 17,  road_quality: 2.2 } },
    { geoCode: 'GN', geoName: 'Guinea',         dataYear: 2022, values: { internet_access: 26.0, logistics_performance: 2.10, electricity_access: 42,  road_quality: 2.3 } },
    { geoCode: 'BJ', geoName: 'Benin',          dataYear: 2022, values: { internet_access: 35.0, logistics_performance: 2.30, electricity_access: 40,  road_quality: 2.5 } },
    { geoCode: 'TG', geoName: 'Togo',           dataYear: 2022, values: { internet_access: 33.0, logistics_performance: 2.25, electricity_access: 52,  road_quality: 2.5 } },
    // ── Afrique de l'Est ─────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2022, values: { internet_access: 40.0, logistics_performance: 2.80, electricity_access: 76.0, road_quality: 3.0 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2022, values: { internet_access: 22.0, logistics_performance: 2.30, electricity_access: 55.4, road_quality: 2.5 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2022, values: { internet_access: 30.0, logistics_performance: 2.50, electricity_access: 40,  road_quality: 2.8 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2022, values: { internet_access: 24.0, logistics_performance: 2.44, electricity_access: 41,  road_quality: 2.6 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2022, values: { internet_access: 30.0, logistics_performance: 2.58, electricity_access: 46,  road_quality: 3.5 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2022, values: { internet_access: 20.0, logistics_performance: 2.10, electricity_access: 32,  road_quality: 2.2 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2022, values: { internet_access: 70.0, logistics_performance: 2.80, electricity_access: 100, road_quality: 4.0 } },
    // ── Afrique Australe ─────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2022, values: { internet_access: 75.5, logistics_performance: 3.70, electricity_access: 86.5, road_quality: 4.0 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2022, values: { internet_access: 63.0, logistics_performance: 2.70, electricity_access: 70,  road_quality: 3.5 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2022, values: { internet_access: 54.0, logistics_performance: 2.55, electricity_access: 53,  road_quality: 3.4 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2022, values: { internet_access: 28.0, logistics_performance: 2.38, electricity_access: 42,  road_quality: 2.7 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2022, values: { internet_access: 33.0, logistics_performance: 2.25, electricity_access: 44,  road_quality: 2.5 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2022, values: { internet_access: 20.0, logistics_performance: 2.14, electricity_access: 33,  road_quality: 2.3 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2022, values: { internet_access: 34.0, logistics_performance: 2.20, electricity_access: 45,  road_quality: 2.4 } },
    // ── Afrique Centrale ─────────────────────────────────
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2022, values: { internet_access: 36.0, logistics_performance: 2.34, electricity_access: 63,  road_quality: 2.5 } },
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2022, values: { internet_access: 21.0, logistics_performance: 2.00, electricity_access: 20,  road_quality: 2.0 } },
    { geoCode: 'CG', geoName: 'Congo',          dataYear: 2022, values: { internet_access: 28.0, logistics_performance: 2.10, electricity_access: 48,  road_quality: 2.2 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2022, values: { internet_access: 70.0, logistics_performance: 2.30, electricity_access: 91,  road_quality: 2.8 } },
  ],
};

export default infrastructureModule;
