import type { DomainModule } from '@/lib/domains/types';

const inflationModule: DomainModule = {
  definition: {
    id: 'inflation',
    label: { fr: 'Inflation', en: 'Inflation', es: 'Inflación' },
    description: {
      fr: 'Évolution des prix à la consommation. Mesure la hausse du coût de la vie et le pouvoir d\'achat des ménages.',
      en: 'Consumer price evolution. Measures the rise in cost of living and household purchasing power.',
      es: 'Evolución de los precios al consumo. Mide el alza del coste de vida y el poder adquisitivo de los hogares.',
    },
    icon: '📈',
    group: 'economy',
    active: true,
    seedSources: [
      'https://www.oecd.org/en/data/indicators/inflation-cpi.html',
      'https://data.worldbank.org/indicator/FP.CPI.TOTL.ZG',
      'https://tradingeconomics.com/country-list/inflation-rate',
    ],
    indicators: [
      {
        id: 'cpi_annual',
        label: { fr: 'Inflation annuelle', en: 'Annual Inflation', es: 'Inflación anual' },
        description: {
          fr: 'Variation annuelle de l\'indice des prix à la consommation (IPC). Mesure la hausse générale des prix sur 12 mois.',
          en: 'Annual change in the consumer price index (CPI). Measures the general rise in prices over 12 months.',
        },
        unit: 'percent',
        unitLabel: { fr: '%', en: '%', es: '%' },
        direction: 'lower_is_better',
        weight: 3,
        thresholds: { excellent: 2, good: 4, fair: 8, poor: 15 },
        minValue: 0,
        maxValue: 50,
      },
      {
        id: 'food_inflation',
        label: { fr: 'Inflation alimentaire', en: 'Food Inflation', es: 'Inflación alimentaria' },
        description: {
          fr: 'Variation annuelle des prix des produits alimentaires. Impact direct sur le budget des ménages les plus modestes.',
          en: 'Annual change in food prices. Direct impact on the budgets of lower-income households.',
        },
        unit: 'percent',
        unitLabel: { fr: '%', en: '%', es: '%' },
        direction: 'lower_is_better',
        weight: 2,
        thresholds: { excellent: 3, good: 6, fair: 12, poor: 20 },
        minValue: 0,
        maxValue: 60,
      },
    ],
  },
  seedData: [
    // ── Europe nordique ─────────────────────────────────────────────────── (données février 2026)
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2026, values: { cpi_annual: 1.8, food_inflation: 2.5 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2026, values: { cpi_annual: 1.5, food_inflation: 2.2 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2026, values: { cpi_annual: 2.0, food_inflation: 2.8 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2026, values: { cpi_annual: 1.2, food_inflation: 1.8 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2026, values: { cpi_annual: 3.5, food_inflation: 4.5 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2026, values: { cpi_annual: 3.2, food_inflation: 4.0 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2026, values: { cpi_annual: 3.8, food_inflation: 4.8 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2026, values: { cpi_annual: 3.5, food_inflation: 4.5 } },
    // ── Europe de l'Ouest ────────────────────────────────────────────────
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2026, values: { cpi_annual: 2.2, food_inflation: 3.0 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2026, values: { cpi_annual: 1.9, food_inflation: 2.6 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2026, values: { cpi_annual: 2.0, food_inflation: 2.5 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2026, values: { cpi_annual: 1.9, food_inflation: 2.5 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2026, values: { cpi_annual: 0.8, food_inflation: 1.2 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2026, values: { cpi_annual: 2.3, food_inflation: 3.0 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2026, values: { cpi_annual: 1.8, food_inflation: 2.5 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2026, values: { cpi_annual: 1.1, food_inflation: 1.8 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2026, values: { cpi_annual: 2.2, food_inflation: 2.8 } },
    // ── Europe du Sud ────────────────────────────────────────────────────
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2026, values: { cpi_annual: 2.1, food_inflation: 2.8 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2026, values: { cpi_annual: 2.5, food_inflation: 3.2 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2026, values: { cpi_annual: 1.5, food_inflation: 2.0 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2026, values: { cpi_annual: 2.3, food_inflation: 3.0 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2026, values: { cpi_annual: 2.8, food_inflation: 3.5 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2026, values: { cpi_annual: 2.2, food_inflation: 3.0 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2026, values: { cpi_annual: 2.5, food_inflation: 3.2 } },
    // ── Europe centrale & orientale ──────────────────────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2026, values: { cpi_annual: 2.8, food_inflation: 3.5 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2026, values: { cpi_annual: 4.5, food_inflation: 5.5 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2026, values: { cpi_annual: 3.5, food_inflation: 4.5 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2026, values: { cpi_annual: 3.2, food_inflation: 4.0 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2026, values: { cpi_annual: 5.2, food_inflation: 6.5 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2026, values: { cpi_annual: 4.8, food_inflation: 6.0 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2026, values: { cpi_annual: 3.8, food_inflation: 5.0 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2026, values: { cpi_annual: 4.5, food_inflation: 5.5 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2026, values: { cpi_annual: 3.5, food_inflation: 4.5 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2026, values: { cpi_annual: 3.2, food_inflation: 4.0 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2026, values: { cpi_annual: 4.0, food_inflation: 5.0 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2026, values: { cpi_annual: 3.5, food_inflation: 4.5 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2026, values: { cpi_annual: 6.5, food_inflation: 8.0 } },
    // ── Amérique du Nord & Océanie ────────────────────────────────────────
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2026, values: { cpi_annual: 2.3, food_inflation: 3.0 } },
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2026, values: { cpi_annual: 2.5, food_inflation: 3.2 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2026, values: { cpi_annual: 2.1, food_inflation: 3.0 } },
    { geoCode: 'US', geoName: 'United States',  dataYear: 2026, values: { cpi_annual: 2.4, food_inflation: 2.8 } },
    // ── Asie de l'Est ────────────────────────────────────────────────────
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2026, values: { cpi_annual: 2.0, food_inflation: 2.8 } },
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2026, values: { cpi_annual: 2.5, food_inflation: 3.5 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2026, values: { cpi_annual: 2.0, food_inflation: 2.5 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2026, values: { cpi_annual: 2.1, food_inflation: 2.5 } },
    { geoCode: 'HK', geoName: 'Hong Kong',      dataYear: 2026, values: { cpi_annual: 2.2, food_inflation: 3.0 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2026, values: { cpi_annual: 8.5, food_inflation: 11.0 } },
    // ── Asie du Sud-Est ──────────────────────────────────────────────────
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2026, values: { cpi_annual: 1.8, food_inflation: 2.5 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2026, values: { cpi_annual: 2.5, food_inflation: 3.5 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2026, values: { cpi_annual: 3.2, food_inflation: 4.5 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2026, values: { cpi_annual: 3.8, food_inflation: 5.0 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2026, values: { cpi_annual: 3.5, food_inflation: 5.0 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2026, values: { cpi_annual: 3.0, food_inflation: 4.5 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2026, values: { cpi_annual: 12.0, food_inflation: 16.0 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2026, values: { cpi_annual: 18.0, food_inflation: 22.0 } },
    // ── Asie du Sud ──────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2026, values: { cpi_annual: 4.5, food_inflation: 6.0 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2026, values: { cpi_annual: 4.5, food_inflation: 5.5 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2026, values: { cpi_annual: 5.5, food_inflation: 7.0 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2026, values: { cpi_annual: 10.0, food_inflation: 12.0 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2026, values: { cpi_annual: 15.0, food_inflation: 18.0 } },
    { geoCode: 'AF', geoName: 'Afghanistan',    dataYear: 2026, values: { cpi_annual: 8.0, food_inflation: 12.0 } },
    // ── Asie centrale ────────────────────────────────────────────────────
    { geoCode: 'CN', geoName: 'China',          dataYear: 2026, values: { cpi_annual: 0.2, food_inflation: 0.5 } },
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2026, values: { cpi_annual: 9.0, food_inflation: 11.5 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2026, values: { cpi_annual: 10.5, food_inflation: 13.0 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2026, values: { cpi_annual: 8.5, food_inflation: 11.0 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2026, values: { cpi_annual: 7.0, food_inflation: 9.5 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2026, values: { cpi_annual: 12.0, food_inflation: 15.0 } },
    // ── Moyen-Orient & Afrique du Nord ───────────────────────────────────
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2026, values: { cpi_annual: 3.5, food_inflation: 5.0 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2026, values: { cpi_annual: 2.2, food_inflation: 3.0 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2026, values: { cpi_annual: 1.5, food_inflation: 2.2 } },
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2026, values: { cpi_annual: 1.8, food_inflation: 2.5 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2026, values: { cpi_annual: 2.5, food_inflation: 3.2 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2026, values: { cpi_annual: 2.0, food_inflation: 2.8 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2026, values: { cpi_annual: 2.2, food_inflation: 3.0 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2026, values: { cpi_annual: 4.5, food_inflation: 6.5 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2026, values: { cpi_annual: 28.0, food_inflation: 35.0 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2026, values: { cpi_annual: 35.0, food_inflation: 42.0 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2026, values: { cpi_annual: 5.0, food_inflation: 7.0 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2026, values: { cpi_annual: 38.0, food_inflation: 46.0 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2026, values: { cpi_annual: 7.5, food_inflation: 10.0 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2026, values: { cpi_annual: 5.5, food_inflation: 7.5 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2026, values: { cpi_annual: 8.0, food_inflation: 12.0 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2026, values: { cpi_annual: 3.5, food_inflation: 5.0 } },
    // ── Ex-URSS (Europe) ─────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2026, values: { cpi_annual: 9.5, food_inflation: 11.0 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2026, values: { cpi_annual: 12.0, food_inflation: 15.0 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2026, values: { cpi_annual: 7.5, food_inflation: 9.0 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2026, values: { cpi_annual: 5.0, food_inflation: 6.5 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2026, values: { cpi_annual: 4.5, food_inflation: 6.0 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2026, values: { cpi_annual: 4.5, food_inflation: 6.0 } },
    // ── Amérique Latine ──────────────────────────────────────────────────
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2026, values: { cpi_annual: 3.5, food_inflation: 4.5 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2026, values: { cpi_annual: 6.5, food_inflation: 7.5 } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2026, values: { cpi_annual: 3.0, food_inflation: 4.0 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2026, values: { cpi_annual: 95.0, food_inflation: 105.0 } },
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2026, values: { cpi_annual: 5.1, food_inflation: 6.5 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2026, values: { cpi_annual: 5.0, food_inflation: 6.0 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2026, values: { cpi_annual: 3.8, food_inflation: 5.0 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2026, values: { cpi_annual: 3.0, food_inflation: 4.0 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2026, values: { cpi_annual: 2.5, food_inflation: 3.5 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2026, values: { cpi_annual: 4.5, food_inflation: 6.0 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2026, values: { cpi_annual: 4.2, food_inflation: 5.5 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2026, values: { cpi_annual: 4.0, food_inflation: 5.5 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2026, values: { cpi_annual: 4.5, food_inflation: 6.0 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2026, values: { cpi_annual: 5.5, food_inflation: 7.0 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2026, values: { cpi_annual: 5.8, food_inflation: 7.5 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2026, values: { cpi_annual: 180.0, food_inflation: 210.0 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2026, values: { cpi_annual: 6.5, food_inflation: 8.5 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2026, values: { cpi_annual: 25.0, food_inflation: 32.0 } },
    { geoCode: 'HT', geoName: 'Haiti',          dataYear: 2026, values: { cpi_annual: 22.0, food_inflation: 28.0 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2026, values: { cpi_annual: 3.5, food_inflation: 5.0 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2026, values: { cpi_annual: 5.5, food_inflation: 7.0 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2026, values: { cpi_annual: 3.2, food_inflation: 4.5 } },
    // ── Afrique subsaharienne (Est) ──────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2026, values: { cpi_annual: 5.2, food_inflation: 7.0 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2026, values: { cpi_annual: 22.0, food_inflation: 28.0 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2026, values: { cpi_annual: 4.5, food_inflation: 6.0 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2026, values: { cpi_annual: 4.8, food_inflation: 6.5 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2026, values: { cpi_annual: 5.5, food_inflation: 7.5 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2026, values: { cpi_annual: 6.0, food_inflation: 8.5 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2026, values: { cpi_annual: 7.5, food_inflation: 10.0 } },
    { geoCode: 'SD', geoName: 'Sudan',          dataYear: 2026, values: { cpi_annual: 48.0, food_inflation: 55.0 } },
    { geoCode: 'SO', geoName: 'Somalia',        dataYear: 2026, values: { cpi_annual: 5.5, food_inflation: 8.0 } },
    // ── Afrique subsaharienne (Ouest) ────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2026, values: { cpi_annual: 28.0, food_inflation: 35.0 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2026, values: { cpi_annual: 18.0, food_inflation: 22.0 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2026, values: { cpi_annual: 3.5, food_inflation: 5.0 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2026, values: { cpi_annual: 3.8, food_inflation: 5.5 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2026, values: { cpi_annual: 4.5, food_inflation: 6.5 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2026, values: { cpi_annual: 4.0, food_inflation: 6.0 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2026, values: { cpi_annual: 4.5, food_inflation: 7.0 } },
    { geoCode: 'GN', geoName: 'Guinea',         dataYear: 2026, values: { cpi_annual: 8.5, food_inflation: 12.0 } },
    { geoCode: 'GM', geoName: 'Gambia',         dataYear: 2026, values: { cpi_annual: 10.0, food_inflation: 14.0 } },
    { geoCode: 'BJ', geoName: 'Benin',          dataYear: 2026, values: { cpi_annual: 3.5, food_inflation: 5.0 } },
    { geoCode: 'TG', geoName: 'Togo',           dataYear: 2026, values: { cpi_annual: 4.0, food_inflation: 5.5 } },
    { geoCode: 'SL', geoName: 'Sierra Leone',   dataYear: 2026, values: { cpi_annual: 12.0, food_inflation: 16.0 } },
    { geoCode: 'LR', geoName: 'Liberia',        dataYear: 2026, values: { cpi_annual: 7.5, food_inflation: 10.0 } },
    // ── Afrique subsaharienne (Centre) ───────────────────────────────────
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2026, values: { cpi_annual: 4.5, food_inflation: 6.5 } },
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2026, values: { cpi_annual: 15.0, food_inflation: 20.0 } },
    { geoCode: 'CG', geoName: 'Congo',          dataYear: 2026, values: { cpi_annual: 5.0, food_inflation: 7.0 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2026, values: { cpi_annual: 3.5, food_inflation: 5.0 } },
    { geoCode: 'TD', geoName: 'Chad',           dataYear: 2026, values: { cpi_annual: 5.5, food_inflation: 8.5 } },
    // ── Afrique australe ─────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2026, values: { cpi_annual: 4.0, food_inflation: 5.5 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2026, values: { cpi_annual: 4.5, food_inflation: 6.0 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2026, values: { cpi_annual: 4.0, food_inflation: 5.5 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2026, values: { cpi_annual: 4.5, food_inflation: 6.0 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2026, values: { cpi_annual: 12.0, food_inflation: 16.0 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2026, values: { cpi_annual: 20.0, food_inflation: 26.0 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2026, values: { cpi_annual: 22.0, food_inflation: 28.0 } },
    // ── Afrique du Nord (EG déjà dans MENA) ─────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2026, values: { cpi_annual: 25.0, food_inflation: 30.0 } },
    // ── Pacifique ────────────────────────────────────────────────────────
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2026, values: { cpi_annual: 3.5, food_inflation: 5.0 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2026, values: { cpi_annual: 5.5, food_inflation: 8.0 } },
  ],
  seedDataPrev: [
    // ── Europe (données 2024) ────────────────────────────────────────────
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2025, values: { cpi_annual: 2.5, food_inflation: 3.2 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2025, values: { cpi_annual: 1.8, food_inflation: 2.5 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2025, values: { cpi_annual: 3.0, food_inflation: 4.0 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2025, values: { cpi_annual: 2.2, food_inflation: 3.0 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2025, values: { cpi_annual: 5.5, food_inflation: 7.0 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2025, values: { cpi_annual: 2.2, food_inflation: 2.8 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2025, values: { cpi_annual: 1.3, food_inflation: 2.0 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2025, values: { cpi_annual: 2.5, food_inflation: 3.2 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2025, values: { cpi_annual: 3.5, food_inflation: 4.5 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2025, values: { cpi_annual: 1.0, food_inflation: 1.5 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2025, values: { cpi_annual: 2.2, food_inflation: 3.0 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2025, values: { cpi_annual: 4.8, food_inflation: 6.0 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2025, values: { cpi_annual: 6.5, food_inflation: 8.0 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2025, values: { cpi_annual: 5.2, food_inflation: 6.5 } },
    // ── Amérique du Nord & Océanie ────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',  dataYear: 2025, values: { cpi_annual: 2.9, food_inflation: 3.5 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2025, values: { cpi_annual: 2.3, food_inflation: 3.2 } },
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2025, values: { cpi_annual: 2.8, food_inflation: 3.5 } },
    // ── Asie ─────────────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2025, values: { cpi_annual: 2.5, food_inflation: 3.8 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2025, values: { cpi_annual: 0.4, food_inflation: 0.8 } },
    { geoCode: 'IN', geoName: 'India',          dataYear: 2025, values: { cpi_annual: 4.8, food_inflation: 6.5 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2025, values: { cpi_annual: 1.8, food_inflation: 2.3 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2025, values: { cpi_annual: 2.8, food_inflation: 4.0 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2025, values: { cpi_annual: 52.0, food_inflation: 62.0 } },
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2025, values: { cpi_annual: 7.5, food_inflation: 9.0 } },
    // ── Moyen-Orient ─────────────────────────────────────────────────────
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2025, values: { cpi_annual: 30.0, food_inflation: 38.0 } },
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2025, values: { cpi_annual: 28.0, food_inflation: 35.0 } },
    // ── Amérique Latine ──────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2025, values: { cpi_annual: 4.8, food_inflation: 6.2 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2025, values: { cpi_annual: 120.0, food_inflation: 135.0 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2025, values: { cpi_annual: 4.5, food_inflation: 5.8 } },
    // ── Afrique ──────────────────────────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2025, values: { cpi_annual: 32.0, food_inflation: 40.0 } },
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2025, values: { cpi_annual: 3.5, food_inflation: 5.0 } },
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2025, values: { cpi_annual: 5.5, food_inflation: 7.5 } },
  ],
};

export default inflationModule;
