import type { DomainModule } from '@/lib/domains/types';

const educationModule: DomainModule = {
  definition: {
    id: 'education',
    label: { fr: 'Éducation & Capital humain', en: 'Education & Human Capital', es: 'Educación y capital humano' },
    description: {
      fr: 'Performance éducative et investissement dans le capital humain : scores PISA, taux d\'enseignement supérieur, R&D et alphabétisation.',
      en: 'Educational performance and human capital investment: PISA scores, higher education rates, R&D and literacy.',
      es: 'Rendimiento educativo e inversión en capital humano: puntuaciones PISA, tasas de educación superior, I+D y alfabetización.',
    },
    icon: '🎓',
    group: 'society',
    active: true,
    seedSources: [
      'https://www.oecd.org/pisa/',
      'https://data.worldbank.org/indicator/SE.TER.ENRR',
      'https://data.worldbank.org/indicator/GB.XPD.RSDV.GD.ZS',
    ],
    indicators: [
      {
        id: 'pisa_score',
        label: { fr: 'Score PISA', en: 'PISA score', es: 'Puntuación PISA' },
        description: {
          fr: "Score moyen des élèves de 15 ans en mathématiques, lecture et sciences (enquête OCDE, tous les 3 ans)",
          en: 'Average score of 15-year-old students in mathematics, reading and science (OECD survey, every 3 years)',
        },
        unit: 'index',
        unitLabel: { fr: 'points', en: 'points', es: 'puntos' },
        direction: 'higher_is_better',
        weight: 4,
        thresholds: { excellent: 520, good: 490, fair: 460, poor: 420 },
        minValue: 300,
        maxValue: 600,
      },
      {
        id: 'higher_education_rate',
        label: { fr: 'Taux d\'enseignement supérieur', en: 'Higher education rate', es: 'Tasa de educación superior' },
        description: {
          fr: "Part de la population adulte (25-64 ans) titulaire d'un diplôme de l'enseignement supérieur (licence ou équivalent)",
          en: 'Share of the adult population (25-64) holding a higher education qualification (bachelor degree or equivalent)',
        },
        unit: 'percent',
        unitLabel: { fr: '% 25-64 ans', en: '% 25-64 yrs', es: '% 25-64 años' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 55, good: 42, fair: 30, poor: 18 },
        minValue: 0,
        maxValue: 80,
      },
      {
        id: 'r_and_d_gdp_share',
        label: { fr: 'Dépenses R&D (% PIB)', en: 'R&D spending (% GDP)', es: 'Gasto en I+D (% PIB)' },
        description: {
          fr: "Part du PIB consacrée aux dépenses de recherche fondamentale, appliquée et développement expérimental",
          en: 'Share of GDP devoted to expenditure on basic research, applied research and experimental development',
        },
        unit: 'percent',
        unitLabel: { fr: '% PIB', en: '% GDP', es: '% PIB' },
        direction: 'higher_is_better',
        weight: 2,
        thresholds: { excellent: 3.0, good: 2.0, fair: 1.2, poor: 0.5 },
        minValue: 0,
        maxValue: 6,
      },
      {
        id: 'literacy_rate',
        label: { fr: 'Taux d\'alphabétisation', en: 'Literacy rate', es: 'Tasa de alfabetización' },
        description: {
          fr: "Part de la population adulte capable de lire et d'écrire un texte simple dans sa vie quotidienne",
          en: 'Share of the adult population able to read and write a simple text in their everyday life',
        },
        unit: 'percent',
        unitLabel: { fr: '%', en: '%', es: '%' },
        direction: 'higher_is_better',
        weight: 2,
        thresholds: { excellent: 99, good: 96, fair: 90, poor: 78 },
        minValue: 0,
        maxValue: 100,
      },
    ],
  },
  seedData: [
    // ── Asie de l'Est & Pacifique (haute performance) ─────────────────────
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2023, values: { pisa_score: 575, higher_education_rate: 55, r_and_d_gdp_share: 2.18, literacy_rate: 98 } },
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2023, values: { pisa_score: 521, higher_education_rate: 62, r_and_d_gdp_share: 3.26, literacy_rate: 99 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2023, values: { pisa_score: 527, higher_education_rate: 70, r_and_d_gdp_share: 4.93, literacy_rate: 99 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2023, values: { pisa_score: 561, higher_education_rate: 30, r_and_d_gdp_share: 2.55, literacy_rate: 97 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2023, values: { pisa_score: 547, higher_education_rate: 72, r_and_d_gdp_share: 3.77, literacy_rate: 99 } },
    { geoCode: 'HK', geoName: 'Hong Kong',      dataYear: 2023, values: { pisa_score: 540, higher_education_rate: 48, r_and_d_gdp_share: 0.97, literacy_rate: 99 } },
    { geoCode: 'MO', geoName: 'Macao',          dataYear: 2023, values: { pisa_score: 535, higher_education_rate: 40, r_and_d_gdp_share: 0.21, literacy_rate: 97 } },

    // ── Asie du Sud-Est ──────────────────────────────────────────────────
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2023, values: { pisa_score: 469, higher_education_rate: 28, r_and_d_gdp_share: 0.53, literacy_rate: 96 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2023, values: { pisa_score: 394, higher_education_rate: 25, r_and_d_gdp_share: 1.14, literacy_rate: 95 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2023, values: { pisa_score: 366, higher_education_rate: 18, r_and_d_gdp_share: 0.28, literacy_rate: 96 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2023, values: { pisa_score: 438, higher_education_rate: 30, r_and_d_gdp_share: 1.04, literacy_rate: 96 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2023, values: { pisa_score: 353, higher_education_rate: 28, r_and_d_gdp_share: 0.16, literacy_rate: 96 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2023, values: { pisa_score: 340, higher_education_rate: 12, r_and_d_gdp_share: 0.12, literacy_rate: 82 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2023, values: { pisa_score: 335, higher_education_rate: 14, r_and_d_gdp_share: 0.06, literacy_rate: 76 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2023, values: { pisa_score: 338, higher_education_rate: 14, r_and_d_gdp_share: 0.04, literacy_rate: 85 } },
    { geoCode: 'BN', geoName: 'Brunei',         dataYear: 2023, values: { pisa_score: 442, higher_education_rate: 25, r_and_d_gdp_share: 0.28, literacy_rate: 98 } },

    // ── Asie du Sud ──────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2023, values: { pisa_score: 415, higher_education_rate: 30, r_and_d_gdp_share: 0.65, literacy_rate: 77 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2023, values: { pisa_score: 350, higher_education_rate: 10, r_and_d_gdp_share: 0.25, literacy_rate: 58 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2023, values: { pisa_score: 355, higher_education_rate: 18, r_and_d_gdp_share: 0.30, literacy_rate: 75 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2023, values: { pisa_score: 400, higher_education_rate: 22, r_and_d_gdp_share: 0.12, literacy_rate: 92 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2023, values: { pisa_score: 348, higher_education_rate: 12, r_and_d_gdp_share: 0.30, literacy_rate: 68 } },

    // ── Asie centrale ────────────────────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2023, values: { pisa_score: 481, higher_education_rate: 58, r_and_d_gdp_share: 0.12, literacy_rate: 99 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2023, values: { pisa_score: 370, higher_education_rate: 15, r_and_d_gdp_share: 0.14, literacy_rate: 100 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2023, values: { pisa_score: 380, higher_education_rate: 42, r_and_d_gdp_share: 0.30, literacy_rate: 99 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2023, values: { pisa_score: 378, higher_education_rate: 38, r_and_d_gdp_share: 0.23, literacy_rate: 99 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2023, values: { pisa_score: 375, higher_education_rate: 20, r_and_d_gdp_share: 0.18, literacy_rate: 100 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2023, values: { pisa_score: 355, higher_education_rate: 18, r_and_d_gdp_share: 0.12, literacy_rate: 100 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2023, values: { pisa_score: 340, higher_education_rate: 14, r_and_d_gdp_share: 0.09, literacy_rate: 100 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2023, values: { pisa_score: 400, higher_education_rate: 42, r_and_d_gdp_share: 0.25, literacy_rate: 99 } },

    // ── Europe du Nord & de l'Ouest ──────────────────────────────────────
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2023, values: { pisa_score: 526, higher_education_rate: 44, r_and_d_gdp_share: 1.75, literacy_rate: 99 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2023, values: { pisa_score: 516, higher_education_rate: 58, r_and_d_gdp_share: 1.17, literacy_rate: 99 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2023, values: { pisa_score: 508, higher_education_rate: 52, r_and_d_gdp_share: 3.37, literacy_rate: 99 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2023, values: { pisa_score: 493, higher_education_rate: 50, r_and_d_gdp_share: 2.28, literacy_rate: 99 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2023, values: { pisa_score: 491, higher_education_rate: 52, r_and_d_gdp_share: 3.40, literacy_rate: 99 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2023, values: { pisa_score: 489, higher_education_rate: 50, r_and_d_gdp_share: 2.97, literacy_rate: 99 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2023, values: { pisa_score: 494, higher_education_rate: 52, r_and_d_gdp_share: 1.71, literacy_rate: 99 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2023, values: { pisa_score: 484, higher_education_rate: 52, r_and_d_gdp_share: 3.22, literacy_rate: 99 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2023, values: { pisa_score: 481, higher_education_rate: 48, r_and_d_gdp_share: 3.43, literacy_rate: 99 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2023, values: { pisa_score: 476, higher_education_rate: 50, r_and_d_gdp_share: 2.41, literacy_rate: 99 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2023, values: { pisa_score: 475, higher_education_rate: 35, r_and_d_gdp_share: 3.13, literacy_rate: 99 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2023, values: { pisa_score: 474, higher_education_rate: 45, r_and_d_gdp_share: 2.20, literacy_rate: 99 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2023, values: { pisa_score: 487, higher_education_rate: 40, r_and_d_gdp_share: 3.22, literacy_rate: 99 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2023, values: { pisa_score: 472, higher_education_rate: 48, r_and_d_gdp_share: 1.05, literacy_rate: 99 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2023, values: { pisa_score: 470, higher_education_rate: 48, r_and_d_gdp_share: 2.47, literacy_rate: 99 } },

    // ── Europe du Sud ────────────────────────────────────────────────────
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2023, values: { pisa_score: 473, higher_education_rate: 46, r_and_d_gdp_share: 1.44, literacy_rate: 99 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2023, values: { pisa_score: 471, higher_education_rate: 28, r_and_d_gdp_share: 1.45, literacy_rate: 99 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2023, values: { pisa_score: 472, higher_education_rate: 40, r_and_d_gdp_share: 1.65, literacy_rate: 96 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2023, values: { pisa_score: 447, higher_education_rate: 42, r_and_d_gdp_share: 1.50, literacy_rate: 98 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2023, values: { pisa_score: 457, higher_education_rate: 38, r_and_d_gdp_share: 0.68, literacy_rate: 95 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2023, values: { pisa_score: 441, higher_education_rate: 55, r_and_d_gdp_share: 0.72, literacy_rate: 99 } },

    // ── Europe centrale & de l'Est ───────────────────────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2023, values: { pisa_score: 487, higher_education_rate: 35, r_and_d_gdp_share: 2.01, literacy_rate: 99 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2023, values: { pisa_score: 489, higher_education_rate: 45, r_and_d_gdp_share: 1.45, literacy_rate: 99 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2023, values: { pisa_score: 485, higher_education_rate: 46, r_and_d_gdp_share: 2.13, literacy_rate: 99 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2023, values: { pisa_score: 473, higher_education_rate: 33, r_and_d_gdp_share: 1.61, literacy_rate: 99 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2023, values: { pisa_score: 472, higher_education_rate: 34, r_and_d_gdp_share: 1.11, literacy_rate: 99 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2023, values: { pisa_score: 464, higher_education_rate: 38, r_and_d_gdp_share: 0.92, literacy_rate: 99 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2023, values: { pisa_score: 475, higher_education_rate: 55, r_and_d_gdp_share: 1.11, literacy_rate: 99 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2023, values: { pisa_score: 475, higher_education_rate: 44, r_and_d_gdp_share: 0.74, literacy_rate: 99 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2023, values: { pisa_score: 428, higher_education_rate: 26, r_and_d_gdp_share: 0.48, literacy_rate: 99 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2023, values: { pisa_score: 420, higher_education_rate: 33, r_and_d_gdp_share: 0.85, literacy_rate: 98 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2023, values: { pisa_score: 440, higher_education_rate: 32, r_and_d_gdp_share: 0.90, literacy_rate: 99 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2023, values: { pisa_score: 410, higher_education_rate: 30, r_and_d_gdp_share: 0.50, literacy_rate: 99 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2023, values: { pisa_score: 389, higher_education_rate: 24, r_and_d_gdp_share: 0.37, literacy_rate: 98 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2023, values: { pisa_score: 395, higher_education_rate: 22, r_and_d_gdp_share: 0.20, literacy_rate: 98 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2023, values: { pisa_score: 392, higher_education_rate: 20, r_and_d_gdp_share: 0.15, literacy_rate: 98 } },
    { geoCode: 'XK', geoName: 'Kosovo',         dataYear: 2023, values: { pisa_score: 365, higher_education_rate: 18, r_and_d_gdp_share: 0.10, literacy_rate: 95 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2023, values: { pisa_score: 458, higher_education_rate: 58, r_and_d_gdp_share: 0.45, literacy_rate: 100 } },
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2023, values: { pisa_score: 472, higher_education_rate: 62, r_and_d_gdp_share: 1.10, literacy_rate: 99 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2023, values: { pisa_score: 465, higher_education_rate: 56, r_and_d_gdp_share: 0.52, literacy_rate: 100 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2023, values: { pisa_score: 400, higher_education_rate: 28, r_and_d_gdp_share: 0.25, literacy_rate: 99 } },

    // ── Amérique du Nord ─────────────────────────────────────────────────
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2023, values: { pisa_score: 507, higher_education_rate: 65, r_and_d_gdp_share: 1.71, literacy_rate: 99 } },
    { geoCode: 'US', geoName: 'United States',  dataYear: 2023, values: { pisa_score: 496, higher_education_rate: 55, r_and_d_gdp_share: 3.46, literacy_rate: 99 } },

    // ── Océanie ──────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2023, values: { pisa_score: 496, higher_education_rate: 58, r_and_d_gdp_share: 1.79, literacy_rate: 99 } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2023, values: { pisa_score: 494, higher_education_rate: 55, r_and_d_gdp_share: 1.28, literacy_rate: 99 } },

    // ── Amérique latine & Caraïbes ───────────────────────────────────────
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2023, values: { pisa_score: 448, higher_education_rate: 35, r_and_d_gdp_share: 0.34, literacy_rate: 97 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2023, values: { pisa_score: 430, higher_education_rate: 28, r_and_d_gdp_share: 0.48, literacy_rate: 99 } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2023, values: { pisa_score: 415, higher_education_rate: 28, r_and_d_gdp_share: 0.39, literacy_rate: 98 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2023, values: { pisa_score: 410, higher_education_rate: 24, r_and_d_gdp_share: 0.31, literacy_rate: 95 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2023, values: { pisa_score: 394, higher_education_rate: 25, r_and_d_gdp_share: 0.24, literacy_rate: 96 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2023, values: { pisa_score: 398, higher_education_rate: 28, r_and_d_gdp_share: 0.13, literacy_rate: 95 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2023, values: { pisa_score: 388, higher_education_rate: 30, r_and_d_gdp_share: 0.52, literacy_rate: 99 } },
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2023, values: { pisa_score: 379, higher_education_rate: 22, r_and_d_gdp_share: 1.21, literacy_rate: 94 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2023, values: { pisa_score: 383, higher_education_rate: 22, r_and_d_gdp_share: 0.26, literacy_rate: 94 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2023, values: { pisa_score: 377, higher_education_rate: 25, r_and_d_gdp_share: 0.15, literacy_rate: 96 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2023, values: { pisa_score: 370, higher_education_rate: 18, r_and_d_gdp_share: 0.15, literacy_rate: 95 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2023, values: { pisa_score: 368, higher_education_rate: 20, r_and_d_gdp_share: 0.16, literacy_rate: 94 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2023, values: { pisa_score: 350, higher_education_rate: 12, r_and_d_gdp_share: 0.03, literacy_rate: 82 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2023, values: { pisa_score: 345, higher_education_rate: 14, r_and_d_gdp_share: 0.04, literacy_rate: 88 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2023, values: { pisa_score: 365, higher_education_rate: 16, r_and_d_gdp_share: 0.17, literacy_rate: 89 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2023, values: { pisa_score: 342, higher_education_rate: 14, r_and_d_gdp_share: 0.11, literacy_rate: 83 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2023, values: { pisa_score: 351, higher_education_rate: 22, r_and_d_gdp_share: 0.10, literacy_rate: 95 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2023, values: { pisa_score: 370, higher_education_rate: 28, r_and_d_gdp_share: 0.10, literacy_rate: 97 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2023, values: { pisa_score: 420, higher_education_rate: 38, r_and_d_gdp_share: 0.42, literacy_rate: 100 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2023, values: { pisa_score: 362, higher_education_rate: 18, r_and_d_gdp_share: 0.08, literacy_rate: 88 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2023, values: { pisa_score: 380, higher_education_rate: 15, r_and_d_gdp_share: 0.08, literacy_rate: 99 } },

    // ── Moyen-Orient ─────────────────────────────────────────────────────
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2023, values: { pisa_score: 474, higher_education_rate: 55, r_and_d_gdp_share: 5.56, literacy_rate: 97 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2023, values: { pisa_score: 456, higher_education_rate: 40, r_and_d_gdp_share: 1.09, literacy_rate: 97 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2023, values: { pisa_score: 440, higher_education_rate: 35, r_and_d_gdp_share: 1.32, literacy_rate: 98 } },
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2023, values: { pisa_score: 395, higher_education_rate: 35, r_and_d_gdp_share: 0.82, literacy_rate: 97 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2023, values: { pisa_score: 414, higher_education_rate: 18, r_and_d_gdp_share: 0.80, literacy_rate: 98 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2023, values: { pisa_score: 410, higher_education_rate: 32, r_and_d_gdp_share: 0.20, literacy_rate: 98 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2023, values: { pisa_score: 388, higher_education_rate: 28, r_and_d_gdp_share: 0.10, literacy_rate: 96 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2023, values: { pisa_score: 398, higher_education_rate: 22, r_and_d_gdp_share: 0.33, literacy_rate: 96 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2023, values: { pisa_score: 399, higher_education_rate: 28, r_and_d_gdp_share: 0.72, literacy_rate: 98 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2023, values: { pisa_score: 390, higher_education_rate: 38, r_and_d_gdp_share: 0.30, literacy_rate: 95 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2023, values: { pisa_score: 350, higher_education_rate: 18, r_and_d_gdp_share: 0.04, literacy_rate: 86 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2023, values: { pisa_score: 405, higher_education_rate: 42, r_and_d_gdp_share: 0.83, literacy_rate: 88 } },
    { geoCode: 'YE', geoName: 'Yemen',          dataYear: 2023, values: { pisa_score: 315, higher_education_rate: 8,  r_and_d_gdp_share: 0.02, literacy_rate: 54 } },
    { geoCode: 'PS', geoName: 'Palestine',      dataYear: 2023, values: { pisa_score: 360, higher_education_rate: 22, r_and_d_gdp_share: 0.08, literacy_rate: 97 } },

    // ── Afrique du Nord ──────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2023, values: { pisa_score: 390, higher_education_rate: 35, r_and_d_gdp_share: 0.72, literacy_rate: 73 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2023, values: { pisa_score: 375, higher_education_rate: 18, r_and_d_gdp_share: 0.70, literacy_rate: 75 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2023, values: { pisa_score: 380, higher_education_rate: 28, r_and_d_gdp_share: 0.60, literacy_rate: 82 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2023, values: { pisa_score: 370, higher_education_rate: 25, r_and_d_gdp_share: 0.13, literacy_rate: 81 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2023, values: { pisa_score: 360, higher_education_rate: 22, r_and_d_gdp_share: 0.08, literacy_rate: 91 } },

    // ── Afrique de l'Ouest ───────────────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2023, values: { pisa_score: 320, higher_education_rate: 10, r_and_d_gdp_share: 0.22, literacy_rate: 62 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2023, values: { pisa_score: 340, higher_education_rate: 12, r_and_d_gdp_share: 0.38, literacy_rate: 80 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2023, values: { pisa_score: 335, higher_education_rate: 8,  r_and_d_gdp_share: 0.65, literacy_rate: 52 } },
    { geoCode: 'CI', geoName: "Cote d'Ivoire",  dataYear: 2023, values: { pisa_score: 330, higher_education_rate: 9,  r_and_d_gdp_share: 0.12, literacy_rate: 48 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2023, values: { pisa_score: 310, higher_education_rate: 5,  r_and_d_gdp_share: 0.30, literacy_rate: 35 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2023, values: { pisa_score: 308, higher_education_rate: 5,  r_and_d_gdp_share: 0.22, literacy_rate: 41 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2023, values: { pisa_score: 305, higher_education_rate: 3,  r_and_d_gdp_share: 0.04, literacy_rate: 35 } },
    { geoCode: 'GN', geoName: 'Guinea',         dataYear: 2023, values: { pisa_score: 312, higher_education_rate: 6,  r_and_d_gdp_share: 0.06, literacy_rate: 45 } },
    { geoCode: 'BJ', geoName: 'Benin',          dataYear: 2023, values: { pisa_score: 318, higher_education_rate: 7,  r_and_d_gdp_share: 0.12, literacy_rate: 42 } },
    { geoCode: 'TG', geoName: 'Togo',           dataYear: 2023, values: { pisa_score: 315, higher_education_rate: 7,  r_and_d_gdp_share: 0.18, literacy_rate: 65 } },
    { geoCode: 'SL', geoName: 'Sierra Leone',   dataYear: 2023, values: { pisa_score: 305, higher_education_rate: 4,  r_and_d_gdp_share: 0.04, literacy_rate: 43 } },

    // ── Afrique de l'Est ─────────────────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2023, values: { pisa_score: 345, higher_education_rate: 8,  r_and_d_gdp_share: 0.30, literacy_rate: 82 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2023, values: { pisa_score: 330, higher_education_rate: 5,  r_and_d_gdp_share: 0.50, literacy_rate: 78 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2023, values: { pisa_score: 325, higher_education_rate: 8,  r_and_d_gdp_share: 0.27, literacy_rate: 52 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2023, values: { pisa_score: 330, higher_education_rate: 5,  r_and_d_gdp_share: 0.17, literacy_rate: 77 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2023, values: { pisa_score: 335, higher_education_rate: 7,  r_and_d_gdp_share: 0.76, literacy_rate: 75 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2023, values: { pisa_score: 310, higher_education_rate: 5,  r_and_d_gdp_share: 0.01, literacy_rate: 77 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2023, values: { pisa_score: 308, higher_education_rate: 4,  r_and_d_gdp_share: 0.35, literacy_rate: 63 } },
    { geoCode: 'MW', geoName: 'Malawi',         dataYear: 2023, values: { pisa_score: 312, higher_education_rate: 4,  r_and_d_gdp_share: 0.01, literacy_rate: 62 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2023, values: { pisa_score: 318, higher_education_rate: 5,  r_and_d_gdp_share: 0.28, literacy_rate: 87 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2023, values: { pisa_score: 322, higher_education_rate: 6,  r_and_d_gdp_share: 0.22, literacy_rate: 89 } },

    // ── Afrique centrale ─────────────────────────────────────────────────
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2023, values: { pisa_score: 308, higher_education_rate: 5,  r_and_d_gdp_share: 0.02, literacy_rate: 77 } },
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2023, values: { pisa_score: 325, higher_education_rate: 10, r_and_d_gdp_share: 0.04, literacy_rate: 78 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2023, values: { pisa_score: 315, higher_education_rate: 7,  r_and_d_gdp_share: 0.04, literacy_rate: 72 } },
    { geoCode: 'TD', geoName: 'Chad',           dataYear: 2023, values: { pisa_score: 303, higher_education_rate: 3,  r_and_d_gdp_share: 0.06, literacy_rate: 26 } },

    // ── Afrique australe ─────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2023, values: { pisa_score: 360, higher_education_rate: 22, r_and_d_gdp_share: 0.65, literacy_rate: 95 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2023, values: { pisa_score: 345, higher_education_rate: 14, r_and_d_gdp_share: 0.54, literacy_rate: 88 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2023, values: { pisa_score: 335, higher_education_rate: 10, r_and_d_gdp_share: 0.08, literacy_rate: 92 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2023, values: { pisa_score: 378, higher_education_rate: 20, r_and_d_gdp_share: 0.35, literacy_rate: 92 } },
  ],
  seedDataPrev: [
    // ── Asie de l'Est & Pacifique (haute performance) ─────────────────────
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2022, values: { pisa_score: 560, higher_education_rate: 98,  r_and_d_gdp_share: 1.93, literacy_rate: 98 } },
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2022, values: { pisa_score: 533, higher_education_rate: 65,  r_and_d_gdp_share: 3.41, literacy_rate: 99 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2022, values: { pisa_score: 523, higher_education_rate: 103, r_and_d_gdp_share: 5.21, literacy_rate: 99 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2022, values: { pisa_score: 550, higher_education_rate: 72,  r_and_d_gdp_share: 2.56, literacy_rate: 97 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2022, values: { pisa_score: 543, higher_education_rate: 76,  r_and_d_gdp_share: 3.70, literacy_rate: 99 } },
    { geoCode: 'HK', geoName: 'Hong Kong',      dataYear: 2022, values: { pisa_score: 531, higher_education_rate: 55,  r_and_d_gdp_share: 0.92, literacy_rate: 99 } },
    { geoCode: 'MO', geoName: 'Macao',          dataYear: 2022, values: { pisa_score: 530, higher_education_rate: 44,  r_and_d_gdp_share: 0.19, literacy_rate: 97 } },

    // ── Asie du Sud-Est ──────────────────────────────────────────────────
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2022, values: { pisa_score: 468, higher_education_rate: 45,  r_and_d_gdp_share: 0.42, literacy_rate: 96 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2022, values: { pisa_score: 394, higher_education_rate: 43,  r_and_d_gdp_share: 1.16, literacy_rate: 91 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2022, values: { pisa_score: 369, higher_education_rate: 42,  r_and_d_gdp_share: 0.28, literacy_rate: 96 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2022, values: { pisa_score: 437, higher_education_rate: 39,  r_and_d_gdp_share: 1.01, literacy_rate: 95 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2022, values: { pisa_score: 347, higher_education_rate: 31,  r_and_d_gdp_share: 0.16, literacy_rate: 96 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2022, values: { pisa_score: 336, higher_education_rate: 13,  r_and_d_gdp_share: 0.12, literacy_rate: 81 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2022, values: { pisa_score: 332, higher_education_rate: 15,  r_and_d_gdp_share: 0.06, literacy_rate: 76 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2022, values: { pisa_score: 335, higher_education_rate: 15,  r_and_d_gdp_share: 0.04, literacy_rate: 84 } },
    { geoCode: 'BN', geoName: 'Brunei',         dataYear: 2022, values: { pisa_score: 440, higher_education_rate: 26,  r_and_d_gdp_share: 0.26, literacy_rate: 98 } },

    // ── Asie du Sud ──────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2022, values: { pisa_score: 410, higher_education_rate: 33,  r_and_d_gdp_share: 0.65, literacy_rate: 76 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2022, values: { pisa_score: 347, higher_education_rate: 11,  r_and_d_gdp_share: 0.24, literacy_rate: 57 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2022, values: { pisa_score: 352, higher_education_rate: 19,  r_and_d_gdp_share: 0.28, literacy_rate: 74 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2022, values: { pisa_score: 398, higher_education_rate: 23,  r_and_d_gdp_share: 0.11, literacy_rate: 92 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2022, values: { pisa_score: 345, higher_education_rate: 13,  r_and_d_gdp_share: 0.28, literacy_rate: 67 } },

    // ── Asie centrale ────────────────────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2022, values: { pisa_score: 411, higher_education_rate: 57,  r_and_d_gdp_share: 0.12, literacy_rate: 99 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2022, values: { pisa_score: 364, higher_education_rate: 16,  r_and_d_gdp_share: 0.13, literacy_rate: 100 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2022, values: { pisa_score: 374, higher_education_rate: 44,  r_and_d_gdp_share: 0.28, literacy_rate: 99 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2022, values: { pisa_score: 375, higher_education_rate: 39,  r_and_d_gdp_share: 0.21, literacy_rate: 99 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2022, values: { pisa_score: 371, higher_education_rate: 21,  r_and_d_gdp_share: 0.17, literacy_rate: 100 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2022, values: { pisa_score: 350, higher_education_rate: 19,  r_and_d_gdp_share: 0.11, literacy_rate: 100 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2022, values: { pisa_score: 336, higher_education_rate: 15,  r_and_d_gdp_share: 0.08, literacy_rate: 100 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2022, values: { pisa_score: 395, higher_education_rate: 43,  r_and_d_gdp_share: 0.23, literacy_rate: 99 } },

    // ── Europe du Nord & de l'Ouest ──────────────────────────────────────
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2022, values: { pisa_score: 516, higher_education_rate: 71,  r_and_d_gdp_share: 1.78, literacy_rate: 99 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2022, values: { pisa_score: 504, higher_education_rate: 77,  r_and_d_gdp_share: 0.96, literacy_rate: 99 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2022, values: { pisa_score: 498, higher_education_rate: 74,  r_and_d_gdp_share: 3.31, literacy_rate: 99 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2022, values: { pisa_score: 480, higher_education_rate: 90,  r_and_d_gdp_share: 2.26, literacy_rate: 99 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2022, values: { pisa_score: 488, higher_education_rate: 84,  r_and_d_gdp_share: 3.41, literacy_rate: 99 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2022, values: { pisa_score: 491, higher_education_rate: 85,  r_and_d_gdp_share: 2.89, literacy_rate: 99 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2022, values: { pisa_score: 486, higher_education_rate: 80,  r_and_d_gdp_share: 2.90, literacy_rate: 99 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2022, values: { pisa_score: 495, higher_education_rate: 105, r_and_d_gdp_share: 2.96, literacy_rate: 99 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2022, values: { pisa_score: 494, higher_education_rate: 84,  r_and_d_gdp_share: 3.41, literacy_rate: 99 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2022, values: { pisa_score: 474, higher_education_rate: 98,  r_and_d_gdp_share: 1.56, literacy_rate: 99 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2022, values: { pisa_score: 482, higher_education_rate: 77,  r_and_d_gdp_share: 3.13, literacy_rate: 99 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2022, values: { pisa_score: 478, higher_education_rate: 72,  r_and_d_gdp_share: 2.23, literacy_rate: 99 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2022, values: { pisa_score: 491, higher_education_rate: 95,  r_and_d_gdp_share: 3.20, literacy_rate: 99 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2022, values: { pisa_score: 468, higher_education_rate: 54,  r_and_d_gdp_share: 1.02, literacy_rate: 99 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2022, values: { pisa_score: 466, higher_education_rate: 55,  r_and_d_gdp_share: 2.42, literacy_rate: 99 } },

    // ── Europe du Sud ────────────────────────────────────────────────────
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2022, values: { pisa_score: 477, higher_education_rate: 95,  r_and_d_gdp_share: 1.44, literacy_rate: 99 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2022, values: { pisa_score: 477, higher_education_rate: 74,  r_and_d_gdp_share: 1.39, literacy_rate: 99 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2022, values: { pisa_score: 478, higher_education_rate: 75,  r_and_d_gdp_share: 1.70, literacy_rate: 96 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2022, values: { pisa_score: 436, higher_education_rate: 167, r_and_d_gdp_share: 1.49, literacy_rate: 98 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2022, values: { pisa_score: 453, higher_education_rate: 41,  r_and_d_gdp_share: 0.65, literacy_rate: 95 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2022, values: { pisa_score: 437, higher_education_rate: 60,  r_and_d_gdp_share: 0.70, literacy_rate: 99 } },

    // ── Europe centrale & de l'Est ───────────────────────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2022, values: { pisa_score: 486, higher_education_rate: 71,  r_and_d_gdp_share: 1.96, literacy_rate: 99 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2022, values: { pisa_score: 495, higher_education_rate: 75,  r_and_d_gdp_share: 1.45, literacy_rate: 99 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2022, values: { pisa_score: 485, higher_education_rate: 82,  r_and_d_gdp_share: 2.10, literacy_rate: 99 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2022, values: { pisa_score: 477, higher_education_rate: 58,  r_and_d_gdp_share: 1.39, literacy_rate: 99 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2022, values: { pisa_score: 474, higher_education_rate: 81,  r_and_d_gdp_share: 1.40, literacy_rate: 99 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2022, values: { pisa_score: 458, higher_education_rate: 53,  r_and_d_gdp_share: 0.98, literacy_rate: 99 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2022, values: { pisa_score: 477, higher_education_rate: 77,  r_and_d_gdp_share: 1.05, literacy_rate: 99 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2022, values: { pisa_score: 473, higher_education_rate: 64,  r_and_d_gdp_share: 0.71, literacy_rate: 99 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2022, values: { pisa_score: 428, higher_education_rate: 58,  r_and_d_gdp_share: 0.46, literacy_rate: 99 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2022, values: { pisa_score: 414, higher_education_rate: 84,  r_and_d_gdp_share: 0.75, literacy_rate: 98 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2022, values: { pisa_score: 436, higher_education_rate: 34,  r_and_d_gdp_share: 0.87, literacy_rate: 99 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2022, values: { pisa_score: 405, higher_education_rate: 32,  r_and_d_gdp_share: 0.48, literacy_rate: 99 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2022, values: { pisa_score: 385, higher_education_rate: 25, r_and_d_gdp_share: 0.36, literacy_rate: 98 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2022, values: { pisa_score: 390, higher_education_rate: 23, r_and_d_gdp_share: 0.19, literacy_rate: 98 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2022, values: { pisa_score: 388, higher_education_rate: 21,  r_and_d_gdp_share: 0.14, literacy_rate: 98 } },
    { geoCode: 'XK', geoName: 'Kosovo',         dataYear: 2022, values: { pisa_score: 362, higher_education_rate: 19,  r_and_d_gdp_share: 0.09, literacy_rate: 95 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2022, values: { pisa_score: 440, higher_education_rate: 80,  r_and_d_gdp_share: 0.33, literacy_rate: 100 } },
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2022, values: { pisa_score: 472, higher_education_rate: 54,  r_and_d_gdp_share: 0.93, literacy_rate: 99 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2022, values: { pisa_score: 462, higher_education_rate: 57,  r_and_d_gdp_share: 0.50, literacy_rate: 100 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2022, values: { pisa_score: 396, higher_education_rate: 29,  r_and_d_gdp_share: 0.23, literacy_rate: 99 } },

    // ── Amérique du Nord ─────────────────────────────────────────────────
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2022, values: { pisa_score: 506, higher_education_rate: 79,  r_and_d_gdp_share: 1.71, literacy_rate: 99 } },
    { geoCode: 'US', geoName: 'United States',  dataYear: 2022, values: { pisa_score: 489, higher_education_rate: 79,  r_and_d_gdp_share: 3.59, literacy_rate: 99 } },

    // ── Océanie ──────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2022, values: { pisa_score: 497, higher_education_rate: 106, r_and_d_gdp_share: 1.86, literacy_rate: 99 } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2022, values: { pisa_score: 495, higher_education_rate: 77,  r_and_d_gdp_share: 1.47, literacy_rate: 99 } },

    // ── Amérique latine & Caraïbes ───────────────────────────────────────
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2022, values: { pisa_score: 435, higher_education_rate: 99,  r_and_d_gdp_share: 0.36, literacy_rate: 97 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2022, values: { pisa_score: 427, higher_education_rate: 29,  r_and_d_gdp_share: 0.46, literacy_rate: 99 } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2022, values: { pisa_score: 411, higher_education_rate: 29,  r_and_d_gdp_share: 0.37, literacy_rate: 98 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2022, values: { pisa_score: 407, higher_education_rate: 46,  r_and_d_gdp_share: 0.26, literacy_rate: 96 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2022, values: { pisa_score: 402, higher_education_rate: 59,  r_and_d_gdp_share: 0.23, literacy_rate: 95 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2022, values: { pisa_score: 391, higher_education_rate: 30,  r_and_d_gdp_share: 0.12, literacy_rate: 95 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2022, values: { pisa_score: 395, higher_education_rate: 107, r_and_d_gdp_share: 0.55, literacy_rate: 99 } },
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2022, values: { pisa_score: 397, higher_education_rate: 60,  r_and_d_gdp_share: 1.16, literacy_rate: 94 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2022, values: { pisa_score: 380, higher_education_rate: 24,  r_and_d_gdp_share: 0.24, literacy_rate: 94 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2022, values: { pisa_score: 374, higher_education_rate: 26,  r_and_d_gdp_share: 0.14, literacy_rate: 96 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2022, values: { pisa_score: 366, higher_education_rate: 19,  r_and_d_gdp_share: 0.14, literacy_rate: 95 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2022, values: { pisa_score: 365, higher_education_rate: 21,  r_and_d_gdp_share: 0.15, literacy_rate: 94 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2022, values: { pisa_score: 347, higher_education_rate: 13,  r_and_d_gdp_share: 0.03, literacy_rate: 81 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2022, values: { pisa_score: 342, higher_education_rate: 15,  r_and_d_gdp_share: 0.04, literacy_rate: 87 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2022, values: { pisa_score: 362, higher_education_rate: 17,  r_and_d_gdp_share: 0.16, literacy_rate: 89 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2022, values: { pisa_score: 339, higher_education_rate: 15,  r_and_d_gdp_share: 0.10, literacy_rate: 83 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2022, values: { pisa_score: 348, higher_education_rate: 23, r_and_d_gdp_share: 0.09, literacy_rate: 95 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2022, values: { pisa_score: 367, higher_education_rate: 29,  r_and_d_gdp_share: 0.09, literacy_rate: 97 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2022, values: { pisa_score: 418, higher_education_rate: 39,  r_and_d_gdp_share: 0.41, literacy_rate: 100 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2022, values: { pisa_score: 358, higher_education_rate: 19,  r_and_d_gdp_share: 0.07, literacy_rate: 88 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2022, values: { pisa_score: 376, higher_education_rate: 16, r_and_d_gdp_share: 0.07, literacy_rate: 99 } },

    // ── Moyen-Orient ─────────────────────────────────────────────────────
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2022, values: { pisa_score: 466, higher_education_rate: 58,  r_and_d_gdp_share: 6.02, literacy_rate: 97 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2022, values: { pisa_score: 462, higher_education_rate: 128, r_and_d_gdp_share: 1.32, literacy_rate: 97 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2022, values: { pisa_score: 432, higher_education_rate: 37, r_and_d_gdp_share: 1.28, literacy_rate: 98 } },
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2022, values: { pisa_score: 387, higher_education_rate: 69,  r_and_d_gdp_share: 0.46, literacy_rate: 97 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2022, values: { pisa_score: 407, higher_education_rate: 20,  r_and_d_gdp_share: 0.78, literacy_rate: 98 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2022, values: { pisa_score: 406, higher_education_rate: 33,  r_and_d_gdp_share: 0.18, literacy_rate: 98 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2022, values: { pisa_score: 384, higher_education_rate: 29,  r_and_d_gdp_share: 0.09, literacy_rate: 96 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2022, values: { pisa_score: 394, higher_education_rate: 23,  r_and_d_gdp_share: 0.31, literacy_rate: 96 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2022, values: { pisa_score: 395, higher_education_rate: 29,  r_and_d_gdp_share: 0.70, literacy_rate: 98 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2022, values: { pisa_score: 388, higher_education_rate: 39,  r_and_d_gdp_share: 0.28, literacy_rate: 95 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2022, values: { pisa_score: 346, higher_education_rate: 19,  r_and_d_gdp_share: 0.04, literacy_rate: 85 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2022, values: { pisa_score: 402, higher_education_rate: 43,  r_and_d_gdp_share: 0.80, literacy_rate: 88 } },
    { geoCode: 'YE', geoName: 'Yemen',          dataYear: 2022, values: { pisa_score: 312, higher_education_rate: 9,   r_and_d_gdp_share: 0.02, literacy_rate: 53 } },
    { geoCode: 'PS', geoName: 'Palestine',      dataYear: 2022, values: { pisa_score: 357, higher_education_rate: 23,  r_and_d_gdp_share: 0.07, literacy_rate: 97 } },

    // ── Afrique du Nord ──────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2022, values: { pisa_score: 380, higher_education_rate: 37,  r_and_d_gdp_share: 1.02, literacy_rate: 80 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2022, values: { pisa_score: 356, higher_education_rate: 46,  r_and_d_gdp_share: 0.70, literacy_rate: 75 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2022, values: { pisa_score: 376, higher_education_rate: 30,  r_and_d_gdp_share: 0.58, literacy_rate: 81 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2022, values: { pisa_score: 366, higher_education_rate: 26,  r_and_d_gdp_share: 0.12, literacy_rate: 80 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2022, values: { pisa_score: 356, higher_education_rate: 23,  r_and_d_gdp_share: 0.07, literacy_rate: 91 } },

    // ── Afrique de l'Ouest ───────────────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2022, values: { pisa_score: 325, higher_education_rate: 11,  r_and_d_gdp_share: 0.13, literacy_rate: 62 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2022, values: { pisa_score: 337, higher_education_rate: 13,  r_and_d_gdp_share: 0.37, literacy_rate: 79 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2022, values: { pisa_score: 332, higher_education_rate: 9,   r_and_d_gdp_share: 0.63, literacy_rate: 52 } },
    { geoCode: 'CI', geoName: "Cote d'Ivoire",  dataYear: 2022, values: { pisa_score: 327, higher_education_rate: 10,  r_and_d_gdp_share: 0.11, literacy_rate: 47 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2022, values: { pisa_score: 307, higher_education_rate: 6,   r_and_d_gdp_share: 0.29, literacy_rate: 35 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2022, values: { pisa_score: 305, higher_education_rate: 6,   r_and_d_gdp_share: 0.21, literacy_rate: 41 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2022, values: { pisa_score: 302, higher_education_rate: 4,   r_and_d_gdp_share: 0.03, literacy_rate: 35 } },
    { geoCode: 'GN', geoName: 'Guinea',         dataYear: 2022, values: { pisa_score: 309, higher_education_rate: 7,   r_and_d_gdp_share: 0.05, literacy_rate: 44 } },
    { geoCode: 'BJ', geoName: 'Benin',          dataYear: 2022, values: { pisa_score: 315, higher_education_rate: 8,   r_and_d_gdp_share: 0.11, literacy_rate: 42 } },
    { geoCode: 'TG', geoName: 'Togo',           dataYear: 2022, values: { pisa_score: 312, higher_education_rate: 8,   r_and_d_gdp_share: 0.17, literacy_rate: 64 } },
    { geoCode: 'SL', geoName: 'Sierra Leone',   dataYear: 2022, values: { pisa_score: 302, higher_education_rate: 5,   r_and_d_gdp_share: 0.03, literacy_rate: 43 } },

    // ── Afrique de l'Est ─────────────────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2022, values: { pisa_score: 347, higher_education_rate: 12,  r_and_d_gdp_share: 0.41, literacy_rate: 82 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2022, values: { pisa_score: 327, higher_education_rate: 6,   r_and_d_gdp_share: 0.48, literacy_rate: 78 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2022, values: { pisa_score: 322, higher_education_rate: 9,   r_and_d_gdp_share: 0.26, literacy_rate: 51 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2022, values: { pisa_score: 327, higher_education_rate: 6,   r_and_d_gdp_share: 0.16, literacy_rate: 76 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2022, values: { pisa_score: 332, higher_education_rate: 8,   r_and_d_gdp_share: 0.74, literacy_rate: 74 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2022, values: { pisa_score: 307, higher_education_rate: 6,   r_and_d_gdp_share: 0.01, literacy_rate: 77 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2022, values: { pisa_score: 305, higher_education_rate: 5,   r_and_d_gdp_share: 0.34, literacy_rate: 62 } },
    { geoCode: 'MW', geoName: 'Malawi',         dataYear: 2022, values: { pisa_score: 309, higher_education_rate: 5,   r_and_d_gdp_share: 0.01, literacy_rate: 62 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2022, values: { pisa_score: 315, higher_education_rate: 6,   r_and_d_gdp_share: 0.27, literacy_rate: 87 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2022, values: { pisa_score: 319, higher_education_rate: 7,   r_and_d_gdp_share: 0.21, literacy_rate: 89 } },

    // ── Afrique centrale ─────────────────────────────────────────────────
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2022, values: { pisa_score: 305, higher_education_rate: 6,   r_and_d_gdp_share: 0.02, literacy_rate: 77 } },
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2022, values: { pisa_score: 322, higher_education_rate: 11,  r_and_d_gdp_share: 0.04, literacy_rate: 78 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2022, values: { pisa_score: 312, higher_education_rate: 8,   r_and_d_gdp_share: 0.04, literacy_rate: 71 } },
    { geoCode: 'TD', geoName: 'Chad',           dataYear: 2022, values: { pisa_score: 300, higher_education_rate: 4,   r_and_d_gdp_share: 0.05, literacy_rate: 26 } },

    // ── Afrique australe ─────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2022, values: { pisa_score: 358, higher_education_rate: 24,  r_and_d_gdp_share: 0.62, literacy_rate: 95 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2022, values: { pisa_score: 342, higher_education_rate: 15,  r_and_d_gdp_share: 0.52, literacy_rate: 88 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2022, values: { pisa_score: 332, higher_education_rate: 11,  r_and_d_gdp_share: 0.07, literacy_rate: 92 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2022, values: { pisa_score: 374, higher_education_rate: 21,  r_and_d_gdp_share: 0.33, literacy_rate: 92 } },
  ],
};

export default educationModule;
