import type { DomainModule } from '@/lib/domains/types';

const costOfLivingModule: DomainModule = {
  definition: {
    id: 'cost-of-living',
    label: { fr: 'Coût de la vie', en: 'Cost of Living', es: 'Coste de vida' },
    description: {
      fr: 'Pouvoir d\'achat et conditions économiques des ménages — logement, inégalités, revenu disponible et précarité énergétique.',
      en: 'Purchasing power and household economic conditions — housing, inequality, disposable income and energy poverty.',
      es: 'Poder adquisitivo y condiciones económicas de los hogares — vivienda, desigualdad, renta disponible y pobreza energética.',
    },
    icon: '🛒',
    group: 'economy',
    active: true,
    seedSources: [
      'https://ec.europa.eu/eurostat/statistics-explained/index.php/Housing_statistics',
      'https://ec.europa.eu/eurostat/statistics-explained/index.php/Income_distribution_statistics',
      'https://www.oecd.org/social/income-distribution-database.htm',
    ],
    indicators: [
      {
        id: 'housing_cost_ratio',
        label: { fr: 'Coût du logement / revenus', en: 'Housing cost / income ratio', es: 'Coste de vivienda / ingresos' },
        unit: 'percent',
        unitLabel: { fr: '% revenus', en: '% income', es: '% ingresos' },
        direction: 'lower_is_better',
        weight: 3,
        thresholds: { excellent: 20, good: 28, fair: 35, poor: 45 },
        minValue: 0,
        maxValue: 70,
      },
      {
        id: 'gini_coefficient',
        label: { fr: 'Coefficient de Gini', en: 'Gini coefficient', es: 'Coeficiente de Gini' },
        unit: 'index',
        unitLabel: { fr: 'Gini', en: 'Gini', es: 'Gini' },
        direction: 'lower_is_better',
        weight: 3,
        thresholds: { excellent: 25, good: 30, fair: 36, poor: 42 },
        minValue: 0,
        maxValue: 65,
      },
      {
        id: 'purchasing_power_index',
        label: { fr: 'Pouvoir d\'achat (PPA)', en: 'Purchasing power (PPP)', es: 'Poder adquisitivo (PPA)' },
        unit: 'index',
        unitLabel: { fr: 'base 100', en: 'index 100', es: 'base 100' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 120, good: 100, fair: 75, poor: 50 },
        minValue: 0,
        maxValue: 250,
      },
      {
        id: 'energy_poverty_rate',
        label: { fr: 'Précarité énergétique', en: 'Energy poverty rate', es: 'Pobreza energética' },
        unit: 'percent',
        unitLabel: { fr: '%', en: '%', es: '%' },
        direction: 'lower_is_better',
        weight: 2,
        thresholds: { excellent: 5, good: 10, fair: 18, poor: 28 },
        minValue: 0,
        maxValue: 50,
      },
    ],
  },
  seedData: [
    // ── Europe de l'Ouest & du Nord ──────────────────────────────────────
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2023, values: { housing_cost_ratio: 22, gini_coefficient: 25.0, purchasing_power_index: 155, energy_poverty_rate: 2.1 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2023, values: { housing_cost_ratio: 25, gini_coefficient: 28.3, purchasing_power_index: 133, energy_poverty_rate: 3.5 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2023, values: { housing_cost_ratio: 27, gini_coefficient: 32.0, purchasing_power_index: 168, energy_poverty_rate: 3.2 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2023, values: { housing_cost_ratio: 26, gini_coefficient: 28.8, purchasing_power_index: 127, energy_poverty_rate: 2.9 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2023, values: { housing_cost_ratio: 24, gini_coefficient: 27.7, purchasing_power_index: 120, energy_poverty_rate: 2.8 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 27.5, purchasing_power_index: 124, energy_poverty_rate: 3.7 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2023, values: { housing_cost_ratio: 32, gini_coefficient: 32.0, purchasing_power_index: 245, energy_poverty_rate: 3.0 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2023, values: { housing_cost_ratio: 34, gini_coefficient: 28.2, purchasing_power_index: 122, energy_poverty_rate: 3.8 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 25.3, purchasing_power_index: 119, energy_poverty_rate: 5.2 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 31.7, purchasing_power_index: 118, energy_poverty_rate: 4.8 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2023, values: { housing_cost_ratio: 32, gini_coefficient: 29.8, purchasing_power_index: 112, energy_poverty_rate: 6.5 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2023, values: { housing_cost_ratio: 36, gini_coefficient: 30.0, purchasing_power_index: 128, energy_poverty_rate: 5.5 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2023, values: { housing_cost_ratio: 35, gini_coefficient: 34.0, purchasing_power_index: 105, energy_poverty_rate: 8.5 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2023, values: { housing_cost_ratio: 24, gini_coefficient: 26.1, purchasing_power_index: 138, energy_poverty_rate: 2.5 } },
    // ── Europe du Sud ────────────────────────────────────────────────────
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2023, values: { housing_cost_ratio: 36, gini_coefficient: 33.0, purchasing_power_index: 95,  energy_poverty_rate: 10.9 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2023, values: { housing_cost_ratio: 38, gini_coefficient: 33.4, purchasing_power_index: 98,  energy_poverty_rate: 14.3 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2023, values: { housing_cost_ratio: 38, gini_coefficient: 33.8, purchasing_power_index: 80,  energy_poverty_rate: 24.7 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2023, values: { housing_cost_ratio: 42, gini_coefficient: 31.4, purchasing_power_index: 65,  energy_poverty_rate: 22.0 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 28.7, purchasing_power_index: 100, energy_poverty_rate: 7.5 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 30.5, purchasing_power_index: 92,  energy_poverty_rate: 14.2 } },
    // ── Europe de l'Est ──────────────────────────────────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2023, values: { housing_cost_ratio: 26, gini_coefficient: 26.4, purchasing_power_index: 88,  energy_poverty_rate: 7.2 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2023, values: { housing_cost_ratio: 24, gini_coefficient: 22.5, purchasing_power_index: 78,  energy_poverty_rate: 8.5 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2023, values: { housing_cost_ratio: 22, gini_coefficient: 28.5, purchasing_power_index: 72,  energy_poverty_rate: 9.8 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2023, values: { housing_cost_ratio: 26, gini_coefficient: 29.0, purchasing_power_index: 68,  energy_poverty_rate: 12.5 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 28.4, purchasing_power_index: 65,  energy_poverty_rate: 14.0 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2023, values: { housing_cost_ratio: 20, gini_coefficient: 33.5, purchasing_power_index: 55,  energy_poverty_rate: 28.0 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2023, values: { housing_cost_ratio: 18, gini_coefficient: 37.0, purchasing_power_index: 48,  energy_poverty_rate: 30.0 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2023, values: { housing_cost_ratio: 22, gini_coefficient: 31.8, purchasing_power_index: 82,  energy_poverty_rate: 5.8 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2023, values: { housing_cost_ratio: 20, gini_coefficient: 35.4, purchasing_power_index: 78,  energy_poverty_rate: 9.5 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2023, values: { housing_cost_ratio: 22, gini_coefficient: 34.3, purchasing_power_index: 70,  energy_poverty_rate: 11.2 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2023, values: { housing_cost_ratio: 22, gini_coefficient: 24.4, purchasing_power_index: 85,  energy_poverty_rate: 5.0 } },
    // ── Balkans ──────────────────────────────────────────────────────────
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2023, values: { housing_cost_ratio: 24, gini_coefficient: 33.3, purchasing_power_index: 42,  energy_poverty_rate: 18.0 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2023, values: { housing_cost_ratio: 26, gini_coefficient: 32.7, purchasing_power_index: 38,  energy_poverty_rate: 20.0 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 30.4, purchasing_power_index: 32,  energy_poverty_rate: 22.5 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2023, values: { housing_cost_ratio: 26, gini_coefficient: 33.0, purchasing_power_index: 36,  energy_poverty_rate: 21.0 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 32.5, purchasing_power_index: 40,  energy_poverty_rate: 19.5 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 32.1, purchasing_power_index: 22,  energy_poverty_rate: 35.0 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2023, values: { housing_cost_ratio: 18, gini_coefficient: 25.2, purchasing_power_index: 32,  energy_poverty_rate: 8.5 } },
    // ── Amérique du Nord ─────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',  dataYear: 2023, values: { housing_cost_ratio: 40, gini_coefficient: 39.8, purchasing_power_index: 180, energy_poverty_rate: 12.0 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2023, values: { housing_cost_ratio: 38, gini_coefficient: 33.0, purchasing_power_index: 140, energy_poverty_rate: 6.0 } },
    // ── Amérique centrale & Caraïbes ─────────────────────────────────────
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2023, values: { housing_cost_ratio: 35, gini_coefficient: 48.3, purchasing_power_index: 16,  energy_poverty_rate: 42.0 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2023, values: { housing_cost_ratio: 34, gini_coefficient: 48.2, purchasing_power_index: 13,  energy_poverty_rate: 44.0 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2023, values: { housing_cost_ratio: 32, gini_coefficient: 38.8, purchasing_power_index: 16,  energy_poverty_rate: 32.0 } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 48.2, purchasing_power_index: 30,  energy_poverty_rate: 14.0 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 49.2, purchasing_power_index: 35,  energy_poverty_rate: 18.0 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2023, values: { housing_cost_ratio: 36, gini_coefficient: 46.2, purchasing_power_index: 10,  energy_poverty_rate: 48.0 } },
    { geoCode: 'HT', geoName: 'Haiti',          dataYear: 2023, values: { housing_cost_ratio: 42, gini_coefficient: 41.1, purchasing_power_index: 5,   energy_poverty_rate: 75.0 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2023, values: { housing_cost_ratio: 35, gini_coefficient: 40.2, purchasing_power_index: 18,  energy_poverty_rate: 28.0 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 39.0, purchasing_power_index: 38,  energy_poverty_rate: 12.0 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 39.6, purchasing_power_index: 22,  energy_poverty_rate: 22.0 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2023, values: { housing_cost_ratio: 15, gini_coefficient: 38.0, purchasing_power_index: 12,  energy_poverty_rate: 35.0 } },
    // ── Amérique du Sud ──────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2023, values: { housing_cost_ratio: 32, gini_coefficient: 52.0, purchasing_power_index: 28,  energy_poverty_rate: 12.0 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 45.4, purchasing_power_index: 25,  energy_poverty_rate: 10.5 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2023, values: { housing_cost_ratio: 35, gini_coefficient: 42.0, purchasing_power_index: 18,  energy_poverty_rate: 15.0 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 44.4, purchasing_power_index: 32,  energy_poverty_rate: 8.0 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2023, values: { housing_cost_ratio: 32, gini_coefficient: 51.3, purchasing_power_index: 18,  energy_poverty_rate: 18.0 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 43.8, purchasing_power_index: 17,  energy_poverty_rate: 20.0 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2023, values: { housing_cost_ratio: 45, gini_coefficient: 44.8, purchasing_power_index: 6,   energy_poverty_rate: 42.0 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 45.5, purchasing_power_index: 16,  energy_poverty_rate: 22.0 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 40.2, purchasing_power_index: 28,  energy_poverty_rate: 8.5 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2023, values: { housing_cost_ratio: 26, gini_coefficient: 43.5, purchasing_power_index: 15,  energy_poverty_rate: 30.0 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 42.2, purchasing_power_index: 12,  energy_poverty_rate: 38.0 } },
    // ── Asie de l'Est ────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2023, values: { housing_cost_ratio: 26, gini_coefficient: 32.9, purchasing_power_index: 110, energy_poverty_rate: 4.5 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 31.4, purchasing_power_index: 105, energy_poverty_rate: 5.2 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2023, values: { housing_cost_ratio: 38, gini_coefficient: 38.5, purchasing_power_index: 55,  energy_poverty_rate: 5.5 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2023, values: { housing_cost_ratio: 34, gini_coefficient: 33.6, purchasing_power_index: 108, energy_poverty_rate: 4.0 } },
    { geoCode: 'HK', geoName: 'Hong Kong',      dataYear: 2023, values: { housing_cost_ratio: 50, gini_coefficient: 53.9, purchasing_power_index: 130, energy_poverty_rate: 3.5 } },
    // ── Asie du Sud-Est ──────────────────────────────────────────────────
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 37.5, purchasing_power_index: 150, energy_poverty_rate: 2.0 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 34.9, purchasing_power_index: 30,  energy_poverty_rate: 8.5 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 41.1, purchasing_power_index: 42,  energy_poverty_rate: 5.0 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2023, values: { housing_cost_ratio: 26, gini_coefficient: 35.7, purchasing_power_index: 18,  energy_poverty_rate: 12.0 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2023, values: { housing_cost_ratio: 32, gini_coefficient: 42.3, purchasing_power_index: 14,  energy_poverty_rate: 25.0 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 37.9, purchasing_power_index: 16,  energy_poverty_rate: 18.0 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 30.7, purchasing_power_index: 8,   energy_poverty_rate: 52.0 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 36.0, purchasing_power_index: 10,  energy_poverty_rate: 48.0 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2023, values: { housing_cost_ratio: 26, gini_coefficient: 38.8, purchasing_power_index: 10,  energy_poverty_rate: 50.0 } },
    { geoCode: 'BN', geoName: 'Brunei',         dataYear: 2023, values: { housing_cost_ratio: 18, gini_coefficient: 32.0, purchasing_power_index: 78,  energy_poverty_rate: 2.5 } },
    // ── Asie du Sud ──────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2023, values: { housing_cost_ratio: 25, gini_coefficient: 35.7, purchasing_power_index: 22,  energy_poverty_rate: 18.0 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 32.4, purchasing_power_index: 10,  energy_poverty_rate: 42.0 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 29.6, purchasing_power_index: 10,  energy_poverty_rate: 45.0 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 39.3, purchasing_power_index: 16,  energy_poverty_rate: 28.0 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 32.8, purchasing_power_index: 8,   energy_poverty_rate: 55.0 } },
    { geoCode: 'AF', geoName: 'Afghanistan',    dataYear: 2023, values: { housing_cost_ratio: 40, gini_coefficient: 29.4, purchasing_power_index: 4,   energy_poverty_rate: 78.0 } },
    // ── Asie centrale ────────────────────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2023, values: { housing_cost_ratio: 22, gini_coefficient: 29.0, purchasing_power_index: 38,  energy_poverty_rate: 8.0 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2023, values: { housing_cost_ratio: 24, gini_coefficient: 35.3, purchasing_power_index: 14,  energy_poverty_rate: 22.0 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2023, values: { housing_cost_ratio: 16, gini_coefficient: 40.8, purchasing_power_index: 20,  energy_poverty_rate: 15.0 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 29.0, purchasing_power_index: 8,   energy_poverty_rate: 35.0 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 34.0, purchasing_power_index: 6,   energy_poverty_rate: 55.0 } },
    // ── Caucase ──────────────────────────────────────────────────────────
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 34.5, purchasing_power_index: 22,  energy_poverty_rate: 18.0 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2023, values: { housing_cost_ratio: 26, gini_coefficient: 29.9, purchasing_power_index: 18,  energy_poverty_rate: 20.0 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2023, values: { housing_cost_ratio: 22, gini_coefficient: 26.6, purchasing_power_index: 22,  energy_poverty_rate: 14.0 } },
    // ── Ex-URSS (Russie, Turquie) ────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2023, values: { housing_cost_ratio: 20, gini_coefficient: 36.0, purchasing_power_index: 40,  energy_poverty_rate: 6.0 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2023, values: { housing_cost_ratio: 38, gini_coefficient: 41.9, purchasing_power_index: 35,  energy_poverty_rate: 18.5 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2023, values: { housing_cost_ratio: 24, gini_coefficient: 26.1, purchasing_power_index: 18,  energy_poverty_rate: 32.0 } },
    // ── Moyen-Orient ─────────────────────────────────────────────────────
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 32.5, purchasing_power_index: 125, energy_poverty_rate: 1.5 } },
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2023, values: { housing_cost_ratio: 26, gini_coefficient: 45.9, purchasing_power_index: 75,  energy_poverty_rate: 2.0 } },
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2023, values: { housing_cost_ratio: 38, gini_coefficient: 38.6, purchasing_power_index: 105, energy_poverty_rate: 8.0 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 29.5, purchasing_power_index: 15,  energy_poverty_rate: 28.0 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2023, values: { housing_cost_ratio: 32, gini_coefficient: 33.7, purchasing_power_index: 16,  energy_poverty_rate: 20.0 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2023, values: { housing_cost_ratio: 48, gini_coefficient: 31.8, purchasing_power_index: 10,  energy_poverty_rate: 40.0 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2023, values: { housing_cost_ratio: 22, gini_coefficient: 30.0, purchasing_power_index: 88,  energy_poverty_rate: 1.8 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2023, values: { housing_cost_ratio: 20, gini_coefficient: 41.1, purchasing_power_index: 140, energy_poverty_rate: 1.2 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2023, values: { housing_cost_ratio: 24, gini_coefficient: 32.0, purchasing_power_index: 68,  energy_poverty_rate: 2.0 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2023, values: { housing_cost_ratio: 24, gini_coefficient: 31.2, purchasing_power_index: 52,  energy_poverty_rate: 3.0 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2023, values: { housing_cost_ratio: 38, gini_coefficient: 40.9, purchasing_power_index: 20,  energy_poverty_rate: 12.0 } },
    // ── Afrique du Nord ──────────────────────────────────────────────────
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2023, values: { housing_cost_ratio: 35, gini_coefficient: 40.5, purchasing_power_index: 12,  energy_poverty_rate: 25.0 } },
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2023, values: { housing_cost_ratio: 32, gini_coefficient: 31.5, purchasing_power_index: 10,  energy_poverty_rate: 15.0 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 27.6, purchasing_power_index: 14,  energy_poverty_rate: 18.0 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2023, values: { housing_cost_ratio: 32, gini_coefficient: 32.8, purchasing_power_index: 12,  energy_poverty_rate: 22.0 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 36.0, purchasing_power_index: 14,  energy_poverty_rate: 25.0 } },
    // ── Afrique de l'Ouest ───────────────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2023, values: { housing_cost_ratio: 40, gini_coefficient: 35.1, purchasing_power_index: 8,   energy_poverty_rate: 58.0 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2023, values: { housing_cost_ratio: 35, gini_coefficient: 43.5, purchasing_power_index: 10,  energy_poverty_rate: 42.0 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2023, values: { housing_cost_ratio: 32, gini_coefficient: 40.3, purchasing_power_index: 8,   energy_poverty_rate: 52.0 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2023, values: { housing_cost_ratio: 34, gini_coefficient: 41.5, purchasing_power_index: 8,   energy_poverty_rate: 55.0 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 33.0, purchasing_power_index: 5,   energy_poverty_rate: 72.0 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 37.3, purchasing_power_index: 3,   energy_poverty_rate: 85.0 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 35.3, purchasing_power_index: 4,   energy_poverty_rate: 80.0 } },
    // ── Afrique centrale ─────────────────────────────────────────────────
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2023, values: { housing_cost_ratio: 32, gini_coefficient: 46.6, purchasing_power_index: 7,   energy_poverty_rate: 55.0 } },
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2023, values: { housing_cost_ratio: 35, gini_coefficient: 42.1, purchasing_power_index: 3,   energy_poverty_rate: 90.0 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 38.0, purchasing_power_index: 18,  energy_poverty_rate: 35.0 } },
    { geoCode: 'TD', geoName: 'Chad',           dataYear: 2023, values: { housing_cost_ratio: 32, gini_coefficient: 43.3, purchasing_power_index: 3,   energy_poverty_rate: 92.0 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2023, values: { housing_cost_ratio: 38, gini_coefficient: 51.3, purchasing_power_index: 8,   energy_poverty_rate: 60.0 } },
    // ── Afrique de l'Est ─────────────────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2023, values: { housing_cost_ratio: 35, gini_coefficient: 40.8, purchasing_power_index: 8,   energy_poverty_rate: 50.0 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 35.0, purchasing_power_index: 5,   energy_poverty_rate: 75.0 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 40.5, purchasing_power_index: 5,   energy_poverty_rate: 68.0 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 42.8, purchasing_power_index: 4,   energy_poverty_rate: 72.0 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2023, values: { housing_cost_ratio: 26, gini_coefficient: 43.7, purchasing_power_index: 4,   energy_poverty_rate: 70.0 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2023, values: { housing_cost_ratio: 32, gini_coefficient: 54.0, purchasing_power_index: 3,   energy_poverty_rate: 78.0 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 42.6, purchasing_power_index: 3,   energy_poverty_rate: 82.0 } },
    // ── Afrique australe ─────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2023, values: { housing_cost_ratio: 40, gini_coefficient: 63.0, purchasing_power_index: 18,  energy_poverty_rate: 32.0 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2023, values: { housing_cost_ratio: 38, gini_coefficient: 50.3, purchasing_power_index: 4,   energy_poverty_rate: 65.0 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2023, values: { housing_cost_ratio: 28, gini_coefficient: 53.3, purchasing_power_index: 18,  energy_poverty_rate: 30.0 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 59.1, purchasing_power_index: 14,  energy_poverty_rate: 42.0 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2023, values: { housing_cost_ratio: 26, gini_coefficient: 36.8, purchasing_power_index: 28,  energy_poverty_rate: 10.0 } },
    // ── Océanie ──────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2023, values: { housing_cost_ratio: 38, gini_coefficient: 34.0, purchasing_power_index: 135, energy_poverty_rate: 5.5 } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2023, values: { housing_cost_ratio: 36, gini_coefficient: 33.9, purchasing_power_index: 118, energy_poverty_rate: 6.0 } },
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2023, values: { housing_cost_ratio: 30, gini_coefficient: 36.7, purchasing_power_index: 14,  energy_poverty_rate: 35.0 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2023, values: { housing_cost_ratio: 32, gini_coefficient: 41.9, purchasing_power_index: 6,   energy_poverty_rate: 78.0 } },
  ],
  seedDataPrev: [
    // ── Europe de l'Ouest & du Nord ──────────────────────────────────────
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2022, values: { housing_cost_ratio: 21, gini_coefficient: 25.3, purchasing_power_index: 152, energy_poverty_rate: 1.8 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2022, values: { housing_cost_ratio: 24, gini_coefficient: 29.3, purchasing_power_index: 130, energy_poverty_rate: 4.0 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 32.3, purchasing_power_index: 165, energy_poverty_rate: 3.4 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2022, values: { housing_cost_ratio: 25, gini_coefficient: 28.8, purchasing_power_index: 125, energy_poverty_rate: 3.3 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2022, values: { housing_cost_ratio: 24, gini_coefficient: 27.9, purchasing_power_index: 118, energy_poverty_rate: 1.4 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2022, values: { housing_cost_ratio: 30, gini_coefficient: 30.9, purchasing_power_index: 122, energy_poverty_rate: 2.7 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2022, values: { housing_cost_ratio: 31, gini_coefficient: 34.1, purchasing_power_index: 242, energy_poverty_rate: 2.1 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2022, values: { housing_cost_ratio: 33, gini_coefficient: 28.4, purchasing_power_index: 120, energy_poverty_rate: 4.0 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2022, values: { housing_cost_ratio: 29, gini_coefficient: 26.4, purchasing_power_index: 117, energy_poverty_rate: 5.5 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2022, values: { housing_cost_ratio: 28, gini_coefficient: 32.4, purchasing_power_index: 116, energy_poverty_rate: 5.5 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2022, values: { housing_cost_ratio: 32, gini_coefficient: 31.2, purchasing_power_index: 110, energy_poverty_rate: 8.5 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2022, values: { housing_cost_ratio: 35, gini_coefficient: 29.9, purchasing_power_index: 125, energy_poverty_rate: 5.8 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2022, values: { housing_cost_ratio: 34, gini_coefficient: 34.4, purchasing_power_index: 103, energy_poverty_rate: 9.2 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2022, values: { housing_cost_ratio: 23, gini_coefficient: 26.5, purchasing_power_index: 135, energy_poverty_rate: 2.8 } },
    // ── Europe du Sud ────────────────────────────────────────────────────
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2022, values: { housing_cost_ratio: 35, gini_coefficient: 33.0, purchasing_power_index: 93,  energy_poverty_rate: 17.1 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2022, values: { housing_cost_ratio: 37, gini_coefficient: 33.7, purchasing_power_index: 96,  energy_poverty_rate: 10.1 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2022, values: { housing_cost_ratio: 37, gini_coefficient: 34.0, purchasing_power_index: 78,  energy_poverty_rate: 17.5 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2022, values: { housing_cost_ratio: 41, gini_coefficient: 33.4, purchasing_power_index: 62,  energy_poverty_rate: 18.7 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 29.2, purchasing_power_index: 97,  energy_poverty_rate: 7.8 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2022, values: { housing_cost_ratio: 29, gini_coefficient: 31.0, purchasing_power_index: 90,  energy_poverty_rate: 14.8 } },
    // ── Europe de l'Est ──────────────────────────────────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2022, values: { housing_cost_ratio: 26, gini_coefficient: 25.9, purchasing_power_index: 85,  energy_poverty_rate: 2.9 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2022, values: { housing_cost_ratio: 24, gini_coefficient: 22.7, purchasing_power_index: 76,  energy_poverty_rate: 8.8 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2022, values: { housing_cost_ratio: 22, gini_coefficient: 28.7, purchasing_power_index: 70,  energy_poverty_rate: 10.2 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2022, values: { housing_cost_ratio: 26, gini_coefficient: 29.2, purchasing_power_index: 66,  energy_poverty_rate: 13.0 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2022, values: { housing_cost_ratio: 28, gini_coefficient: 30.0, purchasing_power_index: 63,  energy_poverty_rate: 14.5 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2022, values: { housing_cost_ratio: 20, gini_coefficient: 33.7, purchasing_power_index: 52,  energy_poverty_rate: 15.2 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2022, values: { housing_cost_ratio: 18, gini_coefficient: 38.2, purchasing_power_index: 45,  energy_poverty_rate: 22.5 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2022, values: { housing_cost_ratio: 21, gini_coefficient: 31.2, purchasing_power_index: 80,  energy_poverty_rate: 5.5 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2022, values: { housing_cost_ratio: 19, gini_coefficient: 36.2, purchasing_power_index: 76,  energy_poverty_rate: 10.0 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2022, values: { housing_cost_ratio: 21, gini_coefficient: 34.5, purchasing_power_index: 68,  energy_poverty_rate: 11.8 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2022, values: { housing_cost_ratio: 21, gini_coefficient: 24.0, purchasing_power_index: 83,  energy_poverty_rate: 5.2 } },
    // ── Balkans ──────────────────────────────────────────────────────────
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2022, values: { housing_cost_ratio: 23, gini_coefficient: 33.8, purchasing_power_index: 40,  energy_poverty_rate: 18.5 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2022, values: { housing_cost_ratio: 25, gini_coefficient: 33.0, purchasing_power_index: 36,  energy_poverty_rate: 20.5 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 30.8, purchasing_power_index: 30,  energy_poverty_rate: 23.0 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2022, values: { housing_cost_ratio: 25, gini_coefficient: 33.5, purchasing_power_index: 34,  energy_poverty_rate: 21.5 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 33.0, purchasing_power_index: 38,  energy_poverty_rate: 20.0 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2022, values: { housing_cost_ratio: 29, gini_coefficient: 32.5, purchasing_power_index: 20,  energy_poverty_rate: 36.0 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2022, values: { housing_cost_ratio: 17, gini_coefficient: 25.0, purchasing_power_index: 30,  energy_poverty_rate: 9.0 } },
    // ── Amérique du Nord ─────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',  dataYear: 2022, values: { housing_cost_ratio: 39, gini_coefficient: 39.8, purchasing_power_index: 176, energy_poverty_rate: 12.5 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2022, values: { housing_cost_ratio: 37, gini_coefficient: 31.1, purchasing_power_index: 137, energy_poverty_rate: 6.3 } },
    // ── Amérique centrale & Caraïbes ─────────────────────────────────────
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2022, values: { housing_cost_ratio: 34, gini_coefficient: 48.5, purchasing_power_index: 15,  energy_poverty_rate: 43.0 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2022, values: { housing_cost_ratio: 33, gini_coefficient: 48.5, purchasing_power_index: 12,  energy_poverty_rate: 45.0 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2022, values: { housing_cost_ratio: 31, gini_coefficient: 39.0, purchasing_power_index: 15,  energy_poverty_rate: 33.0 } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2022, values: { housing_cost_ratio: 29, gini_coefficient: 48.5, purchasing_power_index: 29,  energy_poverty_rate: 14.5 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 49.5, purchasing_power_index: 34,  energy_poverty_rate: 18.5 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2022, values: { housing_cost_ratio: 35, gini_coefficient: 46.5, purchasing_power_index: 9,   energy_poverty_rate: 49.0 } },
    { geoCode: 'HT', geoName: 'Haiti',          dataYear: 2022, values: { housing_cost_ratio: 41, gini_coefficient: 41.1, purchasing_power_index: 5,   energy_poverty_rate: 76.0 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2022, values: { housing_cost_ratio: 34, gini_coefficient: 40.5, purchasing_power_index: 17,  energy_poverty_rate: 29.0 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 39.2, purchasing_power_index: 37,  energy_poverty_rate: 12.5 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2022, values: { housing_cost_ratio: 29, gini_coefficient: 39.8, purchasing_power_index: 21,  energy_poverty_rate: 22.5 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2022, values: { housing_cost_ratio: 14, gini_coefficient: 38.0, purchasing_power_index: 13,  energy_poverty_rate: 34.0 } },
    // ── Amérique du Sud ──────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2022, values: { housing_cost_ratio: 32, gini_coefficient: 52.0, purchasing_power_index: 27,  energy_poverty_rate: 12.3 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2022, values: { housing_cost_ratio: 28, gini_coefficient: 45.4, purchasing_power_index: 24,  energy_poverty_rate: 10.8 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2022, values: { housing_cost_ratio: 34, gini_coefficient: 40.7, purchasing_power_index: 20,  energy_poverty_rate: 15.5 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2022, values: { housing_cost_ratio: 30, gini_coefficient: 43.0, purchasing_power_index: 31,  energy_poverty_rate: 8.3 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2022, values: { housing_cost_ratio: 31, gini_coefficient: 51.5, purchasing_power_index: 17,  energy_poverty_rate: 18.5 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2022, values: { housing_cost_ratio: 29, gini_coefficient: 44.0, purchasing_power_index: 16,  energy_poverty_rate: 20.5 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2022, values: { housing_cost_ratio: 46, gini_coefficient: 44.8, purchasing_power_index: 5,   energy_poverty_rate: 44.0 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 45.8, purchasing_power_index: 15,  energy_poverty_rate: 22.5 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 40.5, purchasing_power_index: 27,  energy_poverty_rate: 9.0 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2022, values: { housing_cost_ratio: 25, gini_coefficient: 43.8, purchasing_power_index: 14,  energy_poverty_rate: 31.0 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 42.5, purchasing_power_index: 11,  energy_poverty_rate: 39.0 } },
    // ── Asie de l'Est ────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2022, values: { housing_cost_ratio: 26, gini_coefficient: 32.3, purchasing_power_index: 108, energy_poverty_rate: 4.7 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2022, values: { housing_cost_ratio: 30, gini_coefficient: 32.9, purchasing_power_index: 103, energy_poverty_rate: 5.4 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2022, values: { housing_cost_ratio: 38, gini_coefficient: 36.0, purchasing_power_index: 52,  energy_poverty_rate: 5.8 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2022, values: { housing_cost_ratio: 33, gini_coefficient: 33.8, purchasing_power_index: 106, energy_poverty_rate: 4.2 } },
    { geoCode: 'HK', geoName: 'Hong Kong',      dataYear: 2022, values: { housing_cost_ratio: 49, gini_coefficient: 53.9, purchasing_power_index: 128, energy_poverty_rate: 3.8 } },
    // ── Asie du Sud-Est ──────────────────────────────────────────────────
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 37.6, purchasing_power_index: 147, energy_poverty_rate: 2.1 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2022, values: { housing_cost_ratio: 30, gini_coefficient: 35.0, purchasing_power_index: 28,  energy_poverty_rate: 8.8 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 41.2, purchasing_power_index: 40,  energy_poverty_rate: 5.3 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2022, values: { housing_cost_ratio: 25, gini_coefficient: 35.8, purchasing_power_index: 17,  energy_poverty_rate: 12.5 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2022, values: { housing_cost_ratio: 31, gini_coefficient: 42.5, purchasing_power_index: 13,  energy_poverty_rate: 25.5 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 38.0, purchasing_power_index: 15,  energy_poverty_rate: 18.5 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2022, values: { housing_cost_ratio: 29, gini_coefficient: 30.8, purchasing_power_index: 8,   energy_poverty_rate: 53.0 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 36.2, purchasing_power_index: 9,   energy_poverty_rate: 49.0 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2022, values: { housing_cost_ratio: 25, gini_coefficient: 39.0, purchasing_power_index: 9,   energy_poverty_rate: 51.0 } },
    { geoCode: 'BN', geoName: 'Brunei',         dataYear: 2022, values: { housing_cost_ratio: 17, gini_coefficient: 32.2, purchasing_power_index: 76,  energy_poverty_rate: 2.8 } },
    // ── Asie du Sud ──────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2022, values: { housing_cost_ratio: 25, gini_coefficient: 35.7, purchasing_power_index: 20,  energy_poverty_rate: 18.8 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 32.6, purchasing_power_index: 9,   energy_poverty_rate: 43.0 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2022, values: { housing_cost_ratio: 29, gini_coefficient: 29.8, purchasing_power_index: 9,   energy_poverty_rate: 46.0 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2022, values: { housing_cost_ratio: 28, gini_coefficient: 39.5, purchasing_power_index: 16,  energy_poverty_rate: 26.0 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 33.0, purchasing_power_index: 7,   energy_poverty_rate: 56.0 } },
    { geoCode: 'AF', geoName: 'Afghanistan',    dataYear: 2022, values: { housing_cost_ratio: 38, gini_coefficient: 29.4, purchasing_power_index: 4,   energy_poverty_rate: 77.0 } },
    // ── Asie centrale ────────────────────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2022, values: { housing_cost_ratio: 21, gini_coefficient: 29.2, purchasing_power_index: 36,  energy_poverty_rate: 8.5 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2022, values: { housing_cost_ratio: 23, gini_coefficient: 35.5, purchasing_power_index: 13,  energy_poverty_rate: 23.0 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2022, values: { housing_cost_ratio: 15, gini_coefficient: 41.0, purchasing_power_index: 19,  energy_poverty_rate: 16.0 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 29.2, purchasing_power_index: 7,   energy_poverty_rate: 36.0 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2022, values: { housing_cost_ratio: 29, gini_coefficient: 34.2, purchasing_power_index: 5,   energy_poverty_rate: 56.0 } },
    // ── Caucase ──────────────────────────────────────────────────────────
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 34.8, purchasing_power_index: 20,  energy_poverty_rate: 18.5 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2022, values: { housing_cost_ratio: 25, gini_coefficient: 30.2, purchasing_power_index: 17,  energy_poverty_rate: 20.5 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2022, values: { housing_cost_ratio: 21, gini_coefficient: 26.8, purchasing_power_index: 21,  energy_poverty_rate: 14.5 } },
    // ── Ex-URSS (Russie, Turquie, Ukraine) ───────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2022, values: { housing_cost_ratio: 20, gini_coefficient: 36.0, purchasing_power_index: 38,  energy_poverty_rate: 6.3 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2022, values: { housing_cost_ratio: 36, gini_coefficient: 41.8, purchasing_power_index: 28,  energy_poverty_rate: 19.5 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2022, values: { housing_cost_ratio: 25, gini_coefficient: 26.3, purchasing_power_index: 16,  energy_poverty_rate: 35.0 } },
    // ── Moyen-Orient ─────────────────────────────────────────────────────
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2022, values: { housing_cost_ratio: 29, gini_coefficient: 32.8, purchasing_power_index: 122, energy_poverty_rate: 1.6 } },
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2022, values: { housing_cost_ratio: 25, gini_coefficient: 46.0, purchasing_power_index: 72,  energy_poverty_rate: 2.2 } },
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2022, values: { housing_cost_ratio: 37, gini_coefficient: 38.8, purchasing_power_index: 103, energy_poverty_rate: 8.3 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2022, values: { housing_cost_ratio: 29, gini_coefficient: 29.7, purchasing_power_index: 14,  energy_poverty_rate: 29.0 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2022, values: { housing_cost_ratio: 31, gini_coefficient: 33.9, purchasing_power_index: 15,  energy_poverty_rate: 20.5 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2022, values: { housing_cost_ratio: 50, gini_coefficient: 31.5, purchasing_power_index: 8,   energy_poverty_rate: 42.0 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2022, values: { housing_cost_ratio: 21, gini_coefficient: 30.2, purchasing_power_index: 86,  energy_poverty_rate: 2.0 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2022, values: { housing_cost_ratio: 19, gini_coefficient: 41.3, purchasing_power_index: 138, energy_poverty_rate: 1.3 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2022, values: { housing_cost_ratio: 23, gini_coefficient: 32.2, purchasing_power_index: 66,  energy_poverty_rate: 2.2 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2022, values: { housing_cost_ratio: 23, gini_coefficient: 31.5, purchasing_power_index: 50,  energy_poverty_rate: 3.2 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2022, values: { housing_cost_ratio: 37, gini_coefficient: 41.0, purchasing_power_index: 19,  energy_poverty_rate: 12.5 } },
    // ── Afrique du Nord ──────────────────────────────────────────────────
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2022, values: { housing_cost_ratio: 35, gini_coefficient: 40.5, purchasing_power_index: 11,  energy_poverty_rate: 25.8 } },
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2022, values: { housing_cost_ratio: 31, gini_coefficient: 28.5, purchasing_power_index: 11,  energy_poverty_rate: 15.5 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2022, values: { housing_cost_ratio: 29, gini_coefficient: 27.8, purchasing_power_index: 13,  energy_poverty_rate: 18.5 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2022, values: { housing_cost_ratio: 31, gini_coefficient: 33.0, purchasing_power_index: 11,  energy_poverty_rate: 22.5 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 36.2, purchasing_power_index: 13,  energy_poverty_rate: 26.0 } },
    // ── Afrique de l'Ouest ───────────────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2022, values: { housing_cost_ratio: 39, gini_coefficient: 35.3, purchasing_power_index: 7,   energy_poverty_rate: 59.0 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2022, values: { housing_cost_ratio: 34, gini_coefficient: 43.7, purchasing_power_index: 9,   energy_poverty_rate: 43.0 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2022, values: { housing_cost_ratio: 31, gini_coefficient: 40.5, purchasing_power_index: 7,   energy_poverty_rate: 53.0 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2022, values: { housing_cost_ratio: 33, gini_coefficient: 41.7, purchasing_power_index: 7,   energy_poverty_rate: 56.0 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2022, values: { housing_cost_ratio: 29, gini_coefficient: 33.2, purchasing_power_index: 5,   energy_poverty_rate: 73.0 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 37.5, purchasing_power_index: 3,   energy_poverty_rate: 86.0 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2022, values: { housing_cost_ratio: 29, gini_coefficient: 35.5, purchasing_power_index: 4,   energy_poverty_rate: 81.0 } },
    // ── Afrique centrale ─────────────────────────────────────────────────
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2022, values: { housing_cost_ratio: 31, gini_coefficient: 46.8, purchasing_power_index: 6,   energy_poverty_rate: 56.0 } },
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2022, values: { housing_cost_ratio: 34, gini_coefficient: 42.3, purchasing_power_index: 3,   energy_poverty_rate: 91.0 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 38.2, purchasing_power_index: 17,  energy_poverty_rate: 36.0 } },
    { geoCode: 'TD', geoName: 'Chad',           dataYear: 2022, values: { housing_cost_ratio: 31, gini_coefficient: 43.5, purchasing_power_index: 3,   energy_poverty_rate: 93.0 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2022, values: { housing_cost_ratio: 37, gini_coefficient: 51.5, purchasing_power_index: 7,   energy_poverty_rate: 61.0 } },
    // ── Afrique de l'Est ─────────────────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2022, values: { housing_cost_ratio: 34, gini_coefficient: 41.0, purchasing_power_index: 7,   energy_poverty_rate: 51.0 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2022, values: { housing_cost_ratio: 29, gini_coefficient: 35.2, purchasing_power_index: 5,   energy_poverty_rate: 76.0 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2022, values: { housing_cost_ratio: 29, gini_coefficient: 40.7, purchasing_power_index: 5,   energy_poverty_rate: 69.0 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 43.0, purchasing_power_index: 4,   energy_poverty_rate: 73.0 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2022, values: { housing_cost_ratio: 25, gini_coefficient: 43.9, purchasing_power_index: 4,   energy_poverty_rate: 71.0 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2022, values: { housing_cost_ratio: 31, gini_coefficient: 54.2, purchasing_power_index: 3,   energy_poverty_rate: 79.0 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2022, values: { housing_cost_ratio: 29, gini_coefficient: 42.8, purchasing_power_index: 3,   energy_poverty_rate: 83.0 } },
    // ── Afrique australe ─────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2022, values: { housing_cost_ratio: 40, gini_coefficient: 63.0, purchasing_power_index: 17,  energy_poverty_rate: 33.0 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2022, values: { housing_cost_ratio: 37, gini_coefficient: 50.5, purchasing_power_index: 4,   energy_poverty_rate: 66.0 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2022, values: { housing_cost_ratio: 27, gini_coefficient: 53.5, purchasing_power_index: 17,  energy_poverty_rate: 31.0 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2022, values: { housing_cost_ratio: 29, gini_coefficient: 59.3, purchasing_power_index: 13,  energy_poverty_rate: 43.0 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2022, values: { housing_cost_ratio: 25, gini_coefficient: 37.0, purchasing_power_index: 27,  energy_poverty_rate: 10.5 } },
    // ── Océanie ──────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2022, values: { housing_cost_ratio: 37, gini_coefficient: 33.8, purchasing_power_index: 133, energy_poverty_rate: 5.8 } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2022, values: { housing_cost_ratio: 35, gini_coefficient: 34.0, purchasing_power_index: 116, energy_poverty_rate: 6.3 } },
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2022, values: { housing_cost_ratio: 29, gini_coefficient: 37.0, purchasing_power_index: 13,  energy_poverty_rate: 36.0 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2022, values: { housing_cost_ratio: 31, gini_coefficient: 42.1, purchasing_power_index: 6,   energy_poverty_rate: 79.0 } },
  ],
};

export default costOfLivingModule;
