import type { DomainModule } from '@/lib/domains/types';

const corruptionModule: DomainModule = {
  definition: {
    id: 'corruption',
    label: { fr: 'Transparence', en: 'Transparency', es: 'Transparencia' },
    description: {
      fr: 'Mesure la corruption perçue, la liberté de la presse et la transparence budgétaire des États.',
      en: 'Measures perceived corruption, press freedom and budget transparency.',
      es: 'Mide la corrupción percibida, la libertad de prensa y la transparencia presupuestaria de los Estados.',
    },
    icon: '⚖️',
    group: 'security',
    active: true,
    seedSources: [
      'https://www.transparency.org/en/cpi',
      'https://rsf.org/en/index',
      'https://internationalbudget.org/open-budget-survey',
    ],
    indicators: [
      {
        id: 'cpi_score',
        label: { fr: 'Indice de perception corruption (IPC)', en: 'Corruption Perceptions Index (CPI)', es: 'Índice de Percepción de la Corrupción (IPC)' },
        unit: 'index',
        unitLabel: { fr: 'score /100', en: 'score /100', es: 'score /100' },
        direction: 'higher_is_better',
        weight: 4,
        thresholds: { excellent: 70, good: 55, fair: 40, poor: 25 },
        minValue: 0,
        maxValue: 100,
      },
      {
        id: 'press_freedom',
        label: { fr: 'Liberté de la presse (RSF)', en: 'Press freedom (RSF)', es: 'Libertad de prensa (RSF)' },
        unit: 'index',
        unitLabel: { fr: 'score /100', en: 'score /100', es: 'score /100' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 80, good: 65, fair: 45, poor: 25 },
        minValue: 0,
        maxValue: 100,
      },
      {
        id: 'budget_transparency',
        label: { fr: 'Transparence budgétaire', en: 'Budget transparency', es: 'Transparencia presupuestaria' },
        unit: 'index',
        unitLabel: { fr: 'score /100', en: 'score /100', es: 'score /100' },
        direction: 'higher_is_better',
        weight: 2,
        thresholds: { excellent: 80, good: 65, fair: 45, poor: 30 },
        minValue: 0,
        maxValue: 100,
      },
    ],
  },
  seedData: [
    // ── Europe nordique ─────────────────────────────────────────────────
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2023, values: { cpi_score: 90, press_freedom: 90, budget_transparency: 85 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2023, values: { cpi_score: 87, press_freedom: 94, budget_transparency: 82 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2023, values: { cpi_score: 84, press_freedom: 95, budget_transparency: 88 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2023, values: { cpi_score: 83, press_freedom: 92, budget_transparency: 85 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2023, values: { cpi_score: 74, press_freedom: 92, budget_transparency: 80 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2023, values: { cpi_score: 76, press_freedom: 85, budget_transparency: 72 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2023, values: { cpi_score: 61, press_freedom: 78, budget_transparency: 68 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2023, values: { cpi_score: 59, press_freedom: 77, budget_transparency: 65 } },
    // ── Europe de l'Ouest ────────────────────────────────────────────────
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2023, values: { cpi_score: 80, press_freedom: 88, budget_transparency: 80 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2023, values: { cpi_score: 77, press_freedom: 81, budget_transparency: 75 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2023, values: { cpi_score: 79, press_freedom: 78, budget_transparency: 80 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2023, values: { cpi_score: 77, press_freedom: 85, budget_transparency: 78 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2023, values: { cpi_score: 82, press_freedom: 82, budget_transparency: 72 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2023, values: { cpi_score: 74, press_freedom: 78, budget_transparency: 76 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2023, values: { cpi_score: 73, press_freedom: 82, budget_transparency: 73 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2023, values: { cpi_score: 72, press_freedom: 72, budget_transparency: 79 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2023, values: { cpi_score: 73, press_freedom: 69, budget_transparency: 82 } },
    // ── Europe du Sud ────────────────────────────────────────────────────
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2023, values: { cpi_score: 62, press_freedom: 87, budget_transparency: 72 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2023, values: { cpi_score: 60, press_freedom: 73, budget_transparency: 70 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2023, values: { cpi_score: 56, press_freedom: 67, budget_transparency: 68 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2023, values: { cpi_score: 52, press_freedom: 55, budget_transparency: 60 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2023, values: { cpi_score: 53, press_freedom: 65, budget_transparency: 50 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2023, values: { cpi_score: 51, press_freedom: 63, budget_transparency: 48 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2023, values: { cpi_score: 56, press_freedom: 72, budget_transparency: 62 } },
    // ── Europe centrale & orientale ──────────────────────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2023, values: { cpi_score: 56, press_freedom: 74, budget_transparency: 68 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2023, values: { cpi_score: 55, press_freedom: 62, budget_transparency: 65 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2023, values: { cpi_score: 53, press_freedom: 71, budget_transparency: 63 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2023, values: { cpi_score: 48, press_freedom: 62, budget_transparency: 60 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2023, values: { cpi_score: 42, press_freedom: 52, budget_transparency: 55 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2023, values: { cpi_score: 46, press_freedom: 56, budget_transparency: 55 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2023, values: { cpi_score: 43, press_freedom: 50, budget_transparency: 54 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2023, values: { cpi_score: 36, press_freedom: 45, budget_transparency: 48 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2023, values: { cpi_score: 34, press_freedom: 42, budget_transparency: 38 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2023, values: { cpi_score: 46, press_freedom: 48, budget_transparency: 42 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2023, values: { cpi_score: 42, press_freedom: 52, budget_transparency: 40 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2023, values: { cpi_score: 36, press_freedom: 52, budget_transparency: 38 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2023, values: { cpi_score: 36, press_freedom: 55, budget_transparency: 40 } },
    // ── Amérique du Nord & Océanie ────────────────────────────────────────
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2023, values: { cpi_score: 87, press_freedom: 80, budget_transparency: 90 } },
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2023, values: { cpi_score: 75, press_freedom: 71, budget_transparency: 87 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2023, values: { cpi_score: 74, press_freedom: 76, budget_transparency: 81 } },
    { geoCode: 'US', geoName: 'United States',  dataYear: 2023, values: { cpi_score: 69, press_freedom: 66, budget_transparency: 78 } },
    // ── Asie de l'Est ────────────────────────────────────────────────────
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2023, values: { cpi_score: 83, press_freedom: 58, budget_transparency: 68 } },
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2023, values: { cpi_score: 73, press_freedom: 68, budget_transparency: 76 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2023, values: { cpi_score: 68, press_freedom: 72, budget_transparency: 70 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2023, values: { cpi_score: 63, press_freedom: 65, budget_transparency: 78 } },
    { geoCode: 'HK', geoName: 'Hong Kong',      dataYear: 2023, values: { cpi_score: 75, press_freedom: 40, budget_transparency: 60 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2023, values: { cpi_score: 33, press_freedom: 60, budget_transparency: 38 } },
    // ── Asie du Sud-Est ──────────────────────────────────────────────────
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2023, values: { cpi_score: 50, press_freedom: 42, budget_transparency: 52 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2023, values: { cpi_score: 36, press_freedom: 35, budget_transparency: 48 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2023, values: { cpi_score: 34, press_freedom: 55, budget_transparency: 52 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2023, values: { cpi_score: 42, press_freedom: 22, budget_transparency: 38 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2023, values: { cpi_score: 33, press_freedom: 42, budget_transparency: 48 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2023, values: { cpi_score: 22, press_freedom: 20, budget_transparency: 18 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2023, values: { cpi_score: 20, press_freedom: 12, budget_transparency: 10 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2023, values: { cpi_score: 26, press_freedom: 18, budget_transparency: 15 } },
    // ── Asie du Sud ──────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2023, values: { cpi_score: 40, press_freedom: 41, budget_transparency: 48 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2023, values: { cpi_score: 34, press_freedom: 38, budget_transparency: 35 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2023, values: { cpi_score: 33, press_freedom: 52, budget_transparency: 30 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2023, values: { cpi_score: 25, press_freedom: 35, budget_transparency: 38 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2023, values: { cpi_score: 27, press_freedom: 30, budget_transparency: 40 } },
    { geoCode: 'AF', geoName: 'Afghanistan',    dataYear: 2023, values: { cpi_score: 20, press_freedom: 12, budget_transparency: 8 } },
    // ── Asie centrale ────────────────────────────────────────────────────
    { geoCode: 'CN', geoName: 'China',          dataYear: 2023, values: { cpi_score: 45, press_freedom: 22, budget_transparency: 40 } },
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2023, values: { cpi_score: 36, press_freedom: 28, budget_transparency: 42 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2023, values: { cpi_score: 33, press_freedom: 22, budget_transparency: 30 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2023, values: { cpi_score: 27, press_freedom: 38, budget_transparency: 28 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2023, values: { cpi_score: 22, press_freedom: 15, budget_transparency: 12 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2023, values: { cpi_score: 18, press_freedom: 8, budget_transparency: 5 } },
    // ── Moyen-Orient & Afrique du Nord ───────────────────────────────────
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2023, values: { cpi_score: 64, press_freedom: 54, budget_transparency: 72 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2023, values: { cpi_score: 68, press_freedom: 30, budget_transparency: 42 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2023, values: { cpi_score: 58, press_freedom: 32, budget_transparency: 35 } },
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2023, values: { cpi_score: 51, press_freedom: 25, budget_transparency: 35 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2023, values: { cpi_score: 42, press_freedom: 22, budget_transparency: 30 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2023, values: { cpi_score: 46, press_freedom: 28, budget_transparency: 25 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2023, values: { cpi_score: 42, press_freedom: 40, budget_transparency: 42 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2023, values: { cpi_score: 47, press_freedom: 38, budget_transparency: 52 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2023, values: { cpi_score: 24, press_freedom: 44, budget_transparency: 25 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2023, values: { cpi_score: 25, press_freedom: 15, budget_transparency: 28 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2023, values: { cpi_score: 23, press_freedom: 28, budget_transparency: 20 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2023, values: { cpi_score: 36, press_freedom: 35, budget_transparency: 50 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2023, values: { cpi_score: 40, press_freedom: 48, budget_transparency: 45 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2023, values: { cpi_score: 33, press_freedom: 28, budget_transparency: 18 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2023, values: { cpi_score: 18, press_freedom: 15, budget_transparency: 8 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2023, values: { cpi_score: 38, press_freedom: 42, budget_transparency: 50 } },
    // ── Ex-URSS (Europe) ─────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2023, values: { cpi_score: 28, press_freedom: 20, budget_transparency: 35 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2023, values: { cpi_score: 33, press_freedom: 58, budget_transparency: 52 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2023, values: { cpi_score: 32, press_freedom: 10, budget_transparency: 15 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2023, values: { cpi_score: 53, press_freedom: 55, budget_transparency: 62 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2023, values: { cpi_score: 46, press_freedom: 52, budget_transparency: 45 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2023, values: { cpi_score: 23, press_freedom: 15, budget_transparency: 20 } },
    // ── Amérique Latine ──────────────────────────────────────────────────
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2023, values: { cpi_score: 66, press_freedom: 78, budget_transparency: 70 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2023, values: { cpi_score: 73, press_freedom: 82, budget_transparency: 68 } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2023, values: { cpi_score: 55, press_freedom: 78, budget_transparency: 60 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2023, values: { cpi_score: 38, press_freedom: 56, budget_transparency: 55 } },
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2023, values: { cpi_score: 38, press_freedom: 55, budget_transparency: 60 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2023, values: { cpi_score: 39, press_freedom: 45, budget_transparency: 52 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2023, values: { cpi_score: 36, press_freedom: 52, budget_transparency: 48 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2023, values: { cpi_score: 34, press_freedom: 50, budget_transparency: 45 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2023, values: { cpi_score: 36, press_freedom: 48, budget_transparency: 42 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2023, values: { cpi_score: 32, press_freedom: 48, budget_transparency: 38 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2023, values: { cpi_score: 31, press_freedom: 35, budget_transparency: 55 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2023, values: { cpi_score: 28, press_freedom: 42, budget_transparency: 35 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2023, values: { cpi_score: 29, press_freedom: 45, budget_transparency: 32 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2023, values: { cpi_score: 24, press_freedom: 35, budget_transparency: 30 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2023, values: { cpi_score: 23, press_freedom: 30, budget_transparency: 28 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2023, values: { cpi_score: 14, press_freedom: 18, budget_transparency: 10 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2023, values: { cpi_score: 17, press_freedom: 15, budget_transparency: 12 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2023, values: { cpi_score: 42, press_freedom: 12, budget_transparency: 8 } },
    { geoCode: 'HT', geoName: 'Haiti',          dataYear: 2023, values: { cpi_score: 17, press_freedom: 28, budget_transparency: 10 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2023, values: { cpi_score: 42, press_freedom: 55, budget_transparency: 40 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2023, values: { cpi_score: 44, press_freedom: 65, budget_transparency: 42 } },
    // ── Afrique subsaharienne (Est) ──────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2023, values: { cpi_score: 32, press_freedom: 48, budget_transparency: 48 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2023, values: { cpi_score: 38, press_freedom: 25, budget_transparency: 35 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2023, values: { cpi_score: 40, press_freedom: 35, budget_transparency: 42 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2023, values: { cpi_score: 26, press_freedom: 32, budget_transparency: 35 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2023, values: { cpi_score: 53, press_freedom: 25, budget_transparency: 55 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2023, values: { cpi_score: 26, press_freedom: 38, budget_transparency: 32 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2023, values: { cpi_score: 26, press_freedom: 42, budget_transparency: 22 } },
    { geoCode: 'SD', geoName: 'Sudan',          dataYear: 2023, values: { cpi_score: 20, press_freedom: 15, budget_transparency: 8 } },
    { geoCode: 'SO', geoName: 'Somalia',        dataYear: 2023, values: { cpi_score: 12, press_freedom: 18, budget_transparency: 5 } },
    // ── Afrique subsaharienne (Ouest) ────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2023, values: { cpi_score: 24, press_freedom: 38, budget_transparency: 35 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2023, values: { cpi_score: 43, press_freedom: 62, budget_transparency: 48 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2023, values: { cpi_score: 43, press_freedom: 55, budget_transparency: 48 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2023, values: { cpi_score: 37, press_freedom: 42, budget_transparency: 35 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2023, values: { cpi_score: 37, press_freedom: 35, budget_transparency: 20 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2023, values: { cpi_score: 28, press_freedom: 30, budget_transparency: 15 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2023, values: { cpi_score: 32, press_freedom: 30, budget_transparency: 18 } },
    { geoCode: 'GN', geoName: 'Guinea',         dataYear: 2023, values: { cpi_score: 25, press_freedom: 30, budget_transparency: 12 } },
    { geoCode: 'GM', geoName: 'Gambia',         dataYear: 2023, values: { cpi_score: 34, press_freedom: 40, budget_transparency: 20 } },
    { geoCode: 'BJ', geoName: 'Benin',          dataYear: 2023, values: { cpi_score: 42, press_freedom: 48, budget_transparency: 38 } },
    { geoCode: 'TG', geoName: 'Togo',           dataYear: 2023, values: { cpi_score: 30, press_freedom: 35, budget_transparency: 18 } },
    { geoCode: 'SL', geoName: 'Sierra Leone',   dataYear: 2023, values: { cpi_score: 34, press_freedom: 45, budget_transparency: 28 } },
    { geoCode: 'LR', geoName: 'Liberia',        dataYear: 2023, values: { cpi_score: 26, press_freedom: 48, budget_transparency: 22 } },
    // ── Afrique subsaharienne (Centre) ───────────────────────────────────
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2023, values: { cpi_score: 26, press_freedom: 22, budget_transparency: 15 } },
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2023, values: { cpi_score: 20, press_freedom: 28, budget_transparency: 12 } },
    { geoCode: 'CG', geoName: 'Congo',          dataYear: 2023, values: { cpi_score: 21, press_freedom: 22, budget_transparency: 10 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2023, values: { cpi_score: 29, press_freedom: 28, budget_transparency: 15 } },
    { geoCode: 'TD', geoName: 'Chad',           dataYear: 2023, values: { cpi_score: 20, press_freedom: 18, budget_transparency: 8 } },
    // ── Afrique australe ─────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2023, values: { cpi_score: 43, press_freedom: 64, budget_transparency: 65 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2023, values: { cpi_score: 60, press_freedom: 62, budget_transparency: 50 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2023, values: { cpi_score: 50, press_freedom: 65, budget_transparency: 45 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2023, values: { cpi_score: 49, press_freedom: 68, budget_transparency: 42 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2023, values: { cpi_score: 33, press_freedom: 42, budget_transparency: 35 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2023, values: { cpi_score: 24, press_freedom: 28, budget_transparency: 20 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2023, values: { cpi_score: 33, press_freedom: 30, budget_transparency: 25 } },
    // ── Afrique du Nord (déjà incluse ci-dessus: MA, EG, TN, DZ, LY) ────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2023, values: { cpi_score: 30, press_freedom: 26, budget_transparency: 38 } },
    // ── Caraïbes & Amérique centrale (déjà inclus ci-dessus) ─────────────
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2023, values: { cpi_score: 31, press_freedom: 28, budget_transparency: 35 } },
    // ── Pacifique ────────────────────────────────────────────────────────
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2023, values: { cpi_score: 38, press_freedom: 45, budget_transparency: 25 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2023, values: { cpi_score: 28, press_freedom: 42, budget_transparency: 18 } },
  ],
  seedDataPrev: [
    // ── Europe nordique ───────────────────────────────────────────────── (CPI: TI 2022, Press Freedom: RSF 2022, Budget Transparency: OBS 2021)
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2022, values: { cpi_score: 90, press_freedom: 90.27, budget_transparency: 83 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2022, values: { cpi_score: 87, press_freedom: 88.42, budget_transparency: 82 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2022, values: { cpi_score: 84, press_freedom: 92.65, budget_transparency: 81 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2022, values: { cpi_score: 83, press_freedom: 88.84, budget_transparency: 85 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2022, values: { cpi_score: 74, press_freedom: 82.69, budget_transparency: 74 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2022, values: { cpi_score: 74, press_freedom: 84.20, budget_transparency: 70 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2022, values: { cpi_score: 60, press_freedom: 77.12, budget_transparency: 65 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2022, values: { cpi_score: 59, press_freedom: 76.80, budget_transparency: 62 } },
    // ── Europe de l'Ouest ────────────────────────────────────────────────
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2022, values: { cpi_score: 80, press_freedom: 77.93, budget_transparency: 76 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2022, values: { cpi_score: 77, press_freedom: 79.81, budget_transparency: 72 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2022, values: { cpi_score: 79, press_freedom: 82.04, budget_transparency: 73 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2022, values: { cpi_score: 77, press_freedom: 88.30, budget_transparency: 74 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2022, values: { cpi_score: 82, press_freedom: 82.72, budget_transparency: 70 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2022, values: { cpi_score: 71, press_freedom: 76.74, budget_transparency: 69 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2022, values: { cpi_score: 73, press_freedom: 78.86, budget_transparency: 72 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2022, values: { cpi_score: 72, press_freedom: 78.53, budget_transparency: 72 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2022, values: { cpi_score: 73, press_freedom: 78.71, budget_transparency: 74 } },
    // ── Europe du Sud ────────────────────────────────────────────────────
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2022, values: { cpi_score: 62, press_freedom: 87.07, budget_transparency: 60 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2022, values: { cpi_score: 60, press_freedom: 76.71, budget_transparency: 54 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2022, values: { cpi_score: 56, press_freedom: 68.16, budget_transparency: 75 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2022, values: { cpi_score: 52, press_freedom: 55.52, budget_transparency: 55 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2022, values: { cpi_score: 52, press_freedom: 64.30, budget_transparency: 45 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2022, values: { cpi_score: 51, press_freedom: 62.10, budget_transparency: 44 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2022, values: { cpi_score: 56, press_freedom: 68.50, budget_transparency: 60 } },
    // ── Europe centrale & orientale ──────────────────────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2022, values: { cpi_score: 56, press_freedom: 80.54, budget_transparency: 60 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2022, values: { cpi_score: 55, press_freedom: 65.64, budget_transparency: 60 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2022, values: { cpi_score: 53, press_freedom: 78.37, budget_transparency: 65 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2022, values: { cpi_score: 50, press_freedom: 70.42, budget_transparency: 64 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2022, values: { cpi_score: 42, press_freedom: 54.82, budget_transparency: 52 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2022, values: { cpi_score: 46, press_freedom: 68.46, budget_transparency: 63 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2022, values: { cpi_score: 43, press_freedom: 59.12, budget_transparency: 71 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2022, values: { cpi_score: 36, press_freedom: 49.20, budget_transparency: 45 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2022, values: { cpi_score: 34, press_freedom: 44.73, budget_transparency: 35 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2022, values: { cpi_score: 45, press_freedom: 50.60, budget_transparency: 40 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2022, values: { cpi_score: 40, press_freedom: 55.80, budget_transparency: 38 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2022, values: { cpi_score: 36, press_freedom: 54.40, budget_transparency: 35 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2022, values: { cpi_score: 34, press_freedom: 53.20, budget_transparency: 38 } },
    // ── Amérique du Nord & Océanie ────────────────────────────────────────
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2022, values: { cpi_score: 87, press_freedom: 83.54, budget_transparency: 85 } },
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2022, values: { cpi_score: 75, press_freedom: 73.77, budget_transparency: 79 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2022, values: { cpi_score: 74, press_freedom: 81.74, budget_transparency: 74 } },
    { geoCode: 'US', geoName: 'United States',  dataYear: 2022, values: { cpi_score: 69, press_freedom: 72.74, budget_transparency: 68 } },
    // ── Asie de l'Est ────────────────────────────────────────────────────
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2022, values: { cpi_score: 83, press_freedom: 44.23, budget_transparency: 48 } },
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2022, values: { cpi_score: 73, press_freedom: 64.37, budget_transparency: 61 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2022, values: { cpi_score: 68, press_freedom: 74.08, budget_transparency: 65 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2022, values: { cpi_score: 63, press_freedom: 72.11, budget_transparency: 74 } },
    { geoCode: 'HK', geoName: 'Hong Kong',      dataYear: 2022, values: { cpi_score: 76, press_freedom: 42.50, budget_transparency: 58 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2022, values: { cpi_score: 35, press_freedom: 62.40, budget_transparency: 36 } },
    // ── Asie du Sud-Est ──────────────────────────────────────────────────
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2022, values: { cpi_score: 47, press_freedom: 39.80, budget_transparency: 48 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2022, values: { cpi_score: 36, press_freedom: 50.15, budget_transparency: 58 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2022, values: { cpi_score: 34, press_freedom: 49.27, budget_transparency: 70 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2022, values: { cpi_score: 42, press_freedom: 26.11, budget_transparency: 44 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2022, values: { cpi_score: 33, press_freedom: 41.84, budget_transparency: 68 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2022, values: { cpi_score: 24, press_freedom: 22.10, budget_transparency: 16 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2022, values: { cpi_score: 23, press_freedom: 14.30, budget_transparency: 12 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2022, values: { cpi_score: 28, press_freedom: 19.50, budget_transparency: 14 } },
    // ── Asie du Sud ──────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2022, values: { cpi_score: 40, press_freedom: 41.00, budget_transparency: 37 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2022, values: { cpi_score: 36, press_freedom: 40.20, budget_transparency: 32 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2022, values: { cpi_score: 34, press_freedom: 54.80, budget_transparency: 28 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2022, values: { cpi_score: 25, press_freedom: 36.63, budget_transparency: 30 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2022, values: { cpi_score: 27, press_freedom: 37.99, budget_transparency: 46 } },
    { geoCode: 'AF', geoName: 'Afghanistan',    dataYear: 2022, values: { cpi_score: 24, press_freedom: 15.80, budget_transparency: 10 } },
    // ── Asie centrale ────────────────────────────────────────────────────
    { geoCode: 'CN', geoName: 'China',          dataYear: 2022, values: { cpi_score: 45, press_freedom: 25.17, budget_transparency: 20 } },
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2022, values: { cpi_score: 36, press_freedom: 48.28, budget_transparency: 63 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2022, values: { cpi_score: 31, press_freedom: 24.50, budget_transparency: 28 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2022, values: { cpi_score: 27, press_freedom: 42.10, budget_transparency: 25 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2022, values: { cpi_score: 20, press_freedom: 16.80, budget_transparency: 10 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2022, values: { cpi_score: 19, press_freedom: 9.20, budget_transparency: 4 } },
    // ── Moyen-Orient & Afrique du Nord ───────────────────────────────────
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2022, values: { cpi_score: 63, press_freedom: 59.62, budget_transparency: 62 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2022, values: { cpi_score: 67, press_freedom: 31.50, budget_transparency: 40 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2022, values: { cpi_score: 58, press_freedom: 34.20, budget_transparency: 33 } },
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2022, values: { cpi_score: 51, press_freedom: 33.71, budget_transparency: 23 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2022, values: { cpi_score: 42, press_freedom: 24.50, budget_transparency: 28 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2022, values: { cpi_score: 44, press_freedom: 30.10, budget_transparency: 22 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2022, values: { cpi_score: 40, press_freedom: 42.80, budget_transparency: 40 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2022, values: { cpi_score: 47, press_freedom: 40.60, budget_transparency: 50 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2022, values: { cpi_score: 24, press_freedom: 46.30, budget_transparency: 22 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2022, values: { cpi_score: 25, press_freedom: 23.22, budget_transparency: 18 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2022, values: { cpi_score: 23, press_freedom: 30.40, budget_transparency: 18 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2022, values: { cpi_score: 36, press_freedom: 41.25, budget_transparency: 55 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2022, values: { cpi_score: 40, press_freedom: 52.40, budget_transparency: 42 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2022, values: { cpi_score: 33, press_freedom: 30.20, budget_transparency: 15 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2022, values: { cpi_score: 17, press_freedom: 16.80, budget_transparency: 6 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2022, values: { cpi_score: 38, press_freedom: 45.42, budget_transparency: 48 } },
    // ── Ex-URSS (Europe) ─────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2022, values: { cpi_score: 28, press_freedom: 38.82, budget_transparency: 73 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2022, values: { cpi_score: 33, press_freedom: 55.76, budget_transparency: 65 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2022, values: { cpi_score: 33, press_freedom: 12.40, budget_transparency: 14 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2022, values: { cpi_score: 56, press_freedom: 58.30, budget_transparency: 60 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2022, values: { cpi_score: 46, press_freedom: 55.40, budget_transparency: 42 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2022, values: { cpi_score: 23, press_freedom: 17.60, budget_transparency: 18 } },
    // ── Amérique Latine ──────────────────────────────────────────────────
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2022, values: { cpi_score: 67, press_freedom: 60.61, budget_transparency: 60 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2022, values: { cpi_score: 74, press_freedom: 80.30, budget_transparency: 65 } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2022, values: { cpi_score: 54, press_freedom: 76.20, budget_transparency: 58 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2022, values: { cpi_score: 38, press_freedom: 77.28, budget_transparency: 50 } },
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2022, values: { cpi_score: 38, press_freedom: 55.36, budget_transparency: 80 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2022, values: { cpi_score: 39, press_freedom: 42.43, budget_transparency: 50 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2022, values: { cpi_score: 36, press_freedom: 54.20, budget_transparency: 45 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2022, values: { cpi_score: 36, press_freedom: 52.80, budget_transparency: 42 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2022, values: { cpi_score: 36, press_freedom: 50.30, budget_transparency: 40 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2022, values: { cpi_score: 32, press_freedom: 50.60, budget_transparency: 35 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2022, values: { cpi_score: 31, press_freedom: 47.57, budget_transparency: 82 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2022, values: { cpi_score: 28, press_freedom: 44.50, budget_transparency: 32 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2022, values: { cpi_score: 31, press_freedom: 48.20, budget_transparency: 30 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2022, values: { cpi_score: 24, press_freedom: 38.40, budget_transparency: 28 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2022, values: { cpi_score: 23, press_freedom: 32.50, budget_transparency: 25 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2022, values: { cpi_score: 14, press_freedom: 20.30, budget_transparency: 8 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2022, values: { cpi_score: 17, press_freedom: 17.80, budget_transparency: 10 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2022, values: { cpi_score: 42, press_freedom: 14.60, budget_transparency: 6 } },
    { geoCode: 'HT', geoName: 'Haiti',          dataYear: 2022, values: { cpi_score: 17, press_freedom: 30.20, budget_transparency: 8 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2022, values: { cpi_score: 40, press_freedom: 57.30, budget_transparency: 38 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2022, values: { cpi_score: 44, press_freedom: 67.80, budget_transparency: 40 } },
    // ── Afrique subsaharienne (Est) ──────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2022, values: { cpi_score: 32, press_freedom: 64.59, budget_transparency: 50 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2022, values: { cpi_score: 38, press_freedom: 50.53, budget_transparency: 8 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2022, values: { cpi_score: 38, press_freedom: 32.40, budget_transparency: 40 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2022, values: { cpi_score: 26, press_freedom: 34.50, budget_transparency: 32 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2022, values: { cpi_score: 53, press_freedom: 27.40, budget_transparency: 52 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2022, values: { cpi_score: 26, press_freedom: 40.30, budget_transparency: 30 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2022, values: { cpi_score: 26, press_freedom: 44.50, budget_transparency: 20 } },
    { geoCode: 'SD', geoName: 'Sudan',          dataYear: 2022, values: { cpi_score: 22, press_freedom: 18.30, budget_transparency: 6 } },
    { geoCode: 'SO', geoName: 'Somalia',        dataYear: 2022, values: { cpi_score: 12, press_freedom: 20.40, budget_transparency: 4 } },
    // ── Afrique subsaharienne (Ouest) ────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2022, values: { cpi_score: 24, press_freedom: 46.79, budget_transparency: 45 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2022, values: { cpi_score: 43, press_freedom: 64.80, budget_transparency: 46 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2022, values: { cpi_score: 43, press_freedom: 57.40, budget_transparency: 45 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2022, values: { cpi_score: 37, press_freedom: 44.20, budget_transparency: 32 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2022, values: { cpi_score: 37, press_freedom: 38.50, budget_transparency: 18 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2022, values: { cpi_score: 28, press_freedom: 34.20, budget_transparency: 12 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2022, values: { cpi_score: 32, press_freedom: 34.60, budget_transparency: 15 } },
    { geoCode: 'GN', geoName: 'Guinea',         dataYear: 2022, values: { cpi_score: 25, press_freedom: 32.80, budget_transparency: 10 } },
    { geoCode: 'GM', geoName: 'Gambia',         dataYear: 2022, values: { cpi_score: 34, press_freedom: 42.30, budget_transparency: 18 } },
    { geoCode: 'BJ', geoName: 'Benin',          dataYear: 2022, values: { cpi_score: 43, press_freedom: 50.20, budget_transparency: 35 } },
    { geoCode: 'TG', geoName: 'Togo',           dataYear: 2022, values: { cpi_score: 30, press_freedom: 37.40, budget_transparency: 15 } },
    { geoCode: 'SL', geoName: 'Sierra Leone',   dataYear: 2022, values: { cpi_score: 34, press_freedom: 47.60, budget_transparency: 25 } },
    { geoCode: 'LR', geoName: 'Liberia',        dataYear: 2022, values: { cpi_score: 26, press_freedom: 50.40, budget_transparency: 20 } },
    // ── Afrique subsaharienne (Centre) ───────────────────────────────────
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2022, values: { cpi_score: 26, press_freedom: 24.30, budget_transparency: 12 } },
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2022, values: { cpi_score: 20, press_freedom: 30.60, budget_transparency: 10 } },
    { geoCode: 'CG', geoName: 'Congo',          dataYear: 2022, values: { cpi_score: 21, press_freedom: 24.50, budget_transparency: 8 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2022, values: { cpi_score: 29, press_freedom: 30.40, budget_transparency: 12 } },
    { geoCode: 'TD', geoName: 'Chad',           dataYear: 2022, values: { cpi_score: 20, press_freedom: 20.80, budget_transparency: 6 } },
    // ── Afrique australe ─────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2022, values: { cpi_score: 43, press_freedom: 75.56, budget_transparency: 86 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2022, values: { cpi_score: 60, press_freedom: 64.30, budget_transparency: 48 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2022, values: { cpi_score: 50, press_freedom: 67.20, budget_transparency: 42 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2022, values: { cpi_score: 49, press_freedom: 70.40, budget_transparency: 40 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2022, values: { cpi_score: 33, press_freedom: 44.50, budget_transparency: 32 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2022, values: { cpi_score: 23, press_freedom: 30.20, budget_transparency: 18 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2022, values: { cpi_score: 33, press_freedom: 32.80, budget_transparency: 22 } },
    // ── Afrique du Nord ──────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2022, values: { cpi_score: 30, press_freedom: 30.23, budget_transparency: 43 } },
    // ── Caraïbes & Amérique centrale ─────────────────────────────────────
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2022, values: { cpi_score: 33, press_freedom: 32.40, budget_transparency: 32 } },
    // ── Pacifique ────────────────────────────────────────────────────────
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2022, values: { cpi_score: 37, press_freedom: 47.30, budget_transparency: 22 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2022, values: { cpi_score: 28, press_freedom: 44.60, budget_transparency: 15 } },
  ],
};

export default corruptionModule;
