import type { DomainModule } from '@/lib/domains/types';

const geopoliticalRiskModule: DomainModule = {
  definition: {
    id: 'geopolitical-risk',
    label: { fr: 'Risque géopolitique', en: 'Geopolitical Risk', es: 'Riesgo geopolítico' },
    description: {
      fr: 'Exposition aux risques géopolitiques : conflits régionaux, efficacité gouvernementale, relations internationales et stabilité institutionnelle.',
      en: 'Exposure to geopolitical risks: regional conflicts, government effectiveness, international relations and institutional stability.',
      es: 'Exposición a riesgos geopolíticos: conflictos regionales, eficacia gubernamental, relaciones internacionales y estabilidad institucional.',
    },
    icon: '🌐',
    group: 'security',
    active: true,
    seedSources: [
      'https://info.worldbank.org/governance/wgi/',
      'https://www.blackknightfinancialservices.com/geopolitical-risk-index',
      'https://rsf.org/en/index',
      'https://eiu.com/democracy-index',
    ],
    indicators: [
      {
        id: 'government_effectiveness',
        label: { fr: 'Efficacité gouvernementale', en: 'Government effectiveness', es: 'Eficacia gubernamental' },
        unit: 'index',
        unitLabel: { fr: 'indice /100', en: 'index /100', es: 'índice /100' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 85, good: 68, fair: 48, poor: 28 },
        minValue: 0,
        maxValue: 100,
      },
      {
        id: 'democracy_index',
        label: { fr: 'Indice de démocratie', en: 'Democracy index', es: 'Índice de democracia' },
        unit: 'index',
        unitLabel: { fr: 'score /10', en: 'score /10', es: 'score /10' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 8.0, good: 6.5, fair: 4.5, poor: 2.5 },
        minValue: 0,
        maxValue: 10,
      },
      {
        id: 'conflict_exposure',
        label: { fr: 'Exposition aux conflits', en: 'Conflict exposure', es: 'Exposición a conflictos' },
        unit: 'index',
        unitLabel: { fr: 'indice /100 (inv.)', en: 'index /100 (inv.)', es: 'índice /100 (inv.)' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 90, good: 75, fair: 55, poor: 35 },
        minValue: 0,
        maxValue: 100,
      },
      {
        id: 'international_relations',
        label: { fr: 'Relations internationales', en: 'International relations', es: 'Relaciones internacionales' },
        unit: 'index',
        unitLabel: { fr: 'indice /100', en: 'index /100', es: 'índice /100' },
        direction: 'higher_is_better',
        weight: 2,
        thresholds: { excellent: 82, good: 68, fair: 50, poor: 30 },
        minValue: 0,
        maxValue: 100,
      },
    ],
  },
  seedData: [
    // ── Europe nordique ────────────────────────────────────────────────────
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2023, values: { government_effectiveness: 96, democracy_index: 9.61, conflict_exposure: 96, international_relations: 95 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2023, values: { government_effectiveness: 95, democracy_index: 9.52, conflict_exposure: 98, international_relations: 94 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2023, values: { government_effectiveness: 95, democracy_index: 9.39, conflict_exposure: 94, international_relations: 92 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2023, values: { government_effectiveness: 95, democracy_index: 9.30, conflict_exposure: 90, international_relations: 90 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2023, values: { government_effectiveness: 94, democracy_index: 9.28, conflict_exposure: 94, international_relations: 92 } },
    // ── Océanie & autres démocraties avancées ─────────────────────────────
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2023, values: { government_effectiveness: 94, democracy_index: 9.61, conflict_exposure: 97, international_relations: 92 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2023, values: { government_effectiveness: 95, democracy_index: 9.14, conflict_exposure: 96, international_relations: 92 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2023, values: { government_effectiveness: 92, democracy_index: 9.00, conflict_exposure: 92, international_relations: 90 } },
    // ── Europe de l'Ouest ──────────────────────────────────────────────────
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2023, values: { government_effectiveness: 90, democracy_index: 8.30, conflict_exposure: 92, international_relations: 88 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2023, values: { government_effectiveness: 88, democracy_index: 9.06, conflict_exposure: 92, international_relations: 88 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2023, values: { government_effectiveness: 92, democracy_index: 8.88, conflict_exposure: 94, international_relations: 90 } },
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2023, values: { government_effectiveness: 90, democracy_index: 8.71, conflict_exposure: 90, international_relations: 88 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2023, values: { government_effectiveness: 92, democracy_index: 8.88, conflict_exposure: 90, international_relations: 90 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2023, values: { government_effectiveness: 90, democracy_index: 8.80, conflict_exposure: 86, international_relations: 88 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2023, values: { government_effectiveness: 85, democracy_index: 7.89, conflict_exposure: 88, international_relations: 85 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2023, values: { government_effectiveness: 85, democracy_index: 8.07, conflict_exposure: 82, international_relations: 85 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2023, values: { government_effectiveness: 85, democracy_index: 8.28, conflict_exposure: 82, international_relations: 85 } },
    { geoCode: 'US', geoName: 'United States',  dataYear: 2023, values: { government_effectiveness: 85, democracy_index: 7.85, conflict_exposure: 72, international_relations: 82 } },
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2023, values: { government_effectiveness: 90, democracy_index: 8.40, conflict_exposure: 78, international_relations: 82 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2023, values: { government_effectiveness: 80, democracy_index: 8.02, conflict_exposure: 90, international_relations: 82 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2023, values: { government_effectiveness: 78, democracy_index: 8.08, conflict_exposure: 82, international_relations: 80 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2023, values: { government_effectiveness: 72, democracy_index: 7.68, conflict_exposure: 80, international_relations: 78 } },
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2023, values: { government_effectiveness: 78, democracy_index: 7.93, conflict_exposure: 35, international_relations: 55 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2023, values: { government_effectiveness: 88, democracy_index: 8.09, conflict_exposure: 60, international_relations: 72 } },
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2023, values: { government_effectiveness: 98, democracy_index: 6.22, conflict_exposure: 90, international_relations: 85 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2023, values: { government_effectiveness: 88, democracy_index: 8.00, conflict_exposure: 50, international_relations: 68 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2023, values: { government_effectiveness: 68, democracy_index: 7.92, conflict_exposure: 72, international_relations: 72 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2023, values: { government_effectiveness: 78, democracy_index: 8.15, conflict_exposure: 92, international_relations: 78 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2023, values: { government_effectiveness: 75, democracy_index: 7.56, conflict_exposure: 70, international_relations: 72 } },
    // ── Europe de l'Est ────────────────────────────────────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2023, values: { government_effectiveness: 80, democracy_index: 7.85, conflict_exposure: 82, international_relations: 80 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2023, values: { government_effectiveness: 82, democracy_index: 8.27, conflict_exposure: 72, international_relations: 78 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2023, values: { government_effectiveness: 70, democracy_index: 6.80, conflict_exposure: 70, international_relations: 72 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2023, values: { government_effectiveness: 68, democracy_index: 6.98, conflict_exposure: 76, international_relations: 70 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2023, values: { government_effectiveness: 62, democracy_index: 6.64, conflict_exposure: 76, international_relations: 60 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2023, values: { government_effectiveness: 65, democracy_index: 6.94, conflict_exposure: 78, international_relations: 70 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2023, values: { government_effectiveness: 60, democracy_index: 6.49, conflict_exposure: 72, international_relations: 68 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2023, values: { government_effectiveness: 55, democracy_index: 6.64, conflict_exposure: 72, international_relations: 62 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2023, values: { government_effectiveness: 78, democracy_index: 7.50, conflict_exposure: 70, international_relations: 76 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2023, values: { government_effectiveness: 75, democracy_index: 7.37, conflict_exposure: 70, international_relations: 74 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2023, values: { government_effectiveness: 76, democracy_index: 7.60, conflict_exposure: 88, international_relations: 76 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2023, values: { government_effectiveness: 48, democracy_index: 6.22, conflict_exposure: 62, international_relations: 50 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2023, values: { government_effectiveness: 30, democracy_index: 5.04, conflict_exposure: 58, international_relations: 42 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2023, values: { government_effectiveness: 45, democracy_index: 5.74, conflict_exposure: 72, international_relations: 52 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2023, values: { government_effectiveness: 42, democracy_index: 5.90, conflict_exposure: 68, international_relations: 52 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2023, values: { government_effectiveness: 40, democracy_index: 5.52, conflict_exposure: 72, international_relations: 55 } },
    { geoCode: 'XK', geoName: 'Kosovo',         dataYear: 2023, values: { government_effectiveness: 35, democracy_index: 5.10, conflict_exposure: 55, international_relations: 40 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2023, values: { government_effectiveness: 35, democracy_index: 5.65, conflict_exposure: 55, international_relations: 48 } },
    // ── Ex-URSS & Asie centrale ───────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2023, values: { government_effectiveness: 40, democracy_index: 2.22, conflict_exposure: 15, international_relations: 15 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2023, values: { government_effectiveness: 42, democracy_index: 5.81, conflict_exposure: 8,  international_relations: 42 } },
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2023, values: { government_effectiveness: 48, democracy_index: 3.14, conflict_exposure: 62, international_relations: 55 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2023, values: { government_effectiveness: 38, democracy_index: 2.03, conflict_exposure: 50, international_relations: 18 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2023, values: { government_effectiveness: 55, democracy_index: 5.16, conflict_exposure: 52, international_relations: 52 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2023, values: { government_effectiveness: 42, democracy_index: 5.48, conflict_exposure: 35, international_relations: 40 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2023, values: { government_effectiveness: 45, democracy_index: 2.68, conflict_exposure: 38, international_relations: 45 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2023, values: { government_effectiveness: 42, democracy_index: 2.12, conflict_exposure: 60, international_relations: 50 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2023, values: { government_effectiveness: 28, democracy_index: 1.66, conflict_exposure: 65, international_relations: 30 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2023, values: { government_effectiveness: 30, democracy_index: 3.62, conflict_exposure: 52, international_relations: 42 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2023, values: { government_effectiveness: 25, democracy_index: 1.94, conflict_exposure: 48, international_relations: 35 } },
    // ── Asie de l'Est & du Sud-Est ────────────────────────────────────────
    { geoCode: 'CN', geoName: 'China',          dataYear: 2023, values: { government_effectiveness: 72, democracy_index: 2.12, conflict_exposure: 52, international_relations: 55 } },
    { geoCode: 'IN', geoName: 'India',          dataYear: 2023, values: { government_effectiveness: 50, democracy_index: 7.04, conflict_exposure: 42, international_relations: 60 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2023, values: { government_effectiveness: 58, democracy_index: 4.32, conflict_exposure: 58, international_relations: 62 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2023, values: { government_effectiveness: 55, democracy_index: 2.91, conflict_exposure: 65, international_relations: 60 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2023, values: { government_effectiveness: 52, democracy_index: 6.71, conflict_exposure: 60, international_relations: 65 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2023, values: { government_effectiveness: 42, democracy_index: 6.84, conflict_exposure: 48, international_relations: 58 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2023, values: { government_effectiveness: 28, democracy_index: 4.26, conflict_exposure: 28, international_relations: 35 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2023, values: { government_effectiveness: 32, democracy_index: 5.99, conflict_exposure: 50, international_relations: 48 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2023, values: { government_effectiveness: 72, democracy_index: 6.41, conflict_exposure: 72, international_relations: 70 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2023, values: { government_effectiveness: 15, democracy_index: 1.60, conflict_exposure: 12, international_relations: 20 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2023, values: { government_effectiveness: 32, democracy_index: 3.18, conflict_exposure: 62, international_relations: 48 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2023, values: { government_effectiveness: 30, democracy_index: 2.14, conflict_exposure: 68, international_relations: 48 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2023, values: { government_effectiveness: 38, democracy_index: 6.52, conflict_exposure: 78, international_relations: 55 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2023, values: { government_effectiveness: 38, democracy_index: 6.14, conflict_exposure: 52, international_relations: 50 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2023, values: { government_effectiveness: 28, democracy_index: 4.84, conflict_exposure: 55, international_relations: 45 } },
    { geoCode: 'KP', geoName: 'North Korea',    dataYear: 2023, values: { government_effectiveness: 22, democracy_index: 1.08, conflict_exposure: 30, international_relations: 5 } },
    // ── Moyen-Orient ──────────────────────────────────────────────────────
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2023, values: { government_effectiveness: 58, democracy_index: 1.85, conflict_exposure: 38, international_relations: 55 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2023, values: { government_effectiveness: 32, democracy_index: 2.20, conflict_exposure: 25, international_relations: 20 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2023, values: { government_effectiveness: 52, democracy_index: 4.35, conflict_exposure: 38, international_relations: 45 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2023, values: { government_effectiveness: 88, democracy_index: 2.76, conflict_exposure: 72, international_relations: 75 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2023, values: { government_effectiveness: 82, democracy_index: 3.24, conflict_exposure: 70, international_relations: 68 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2023, values: { government_effectiveness: 58, democracy_index: 3.85, conflict_exposure: 60, international_relations: 62 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2023, values: { government_effectiveness: 62, democracy_index: 3.12, conflict_exposure: 72, international_relations: 65 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2023, values: { government_effectiveness: 60, democracy_index: 2.55, conflict_exposure: 58, international_relations: 58 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2023, values: { government_effectiveness: 52, democracy_index: 3.42, conflict_exposure: 48, international_relations: 58 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2023, values: { government_effectiveness: 18, democracy_index: 4.36, conflict_exposure: 28, international_relations: 35 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2023, values: { government_effectiveness: 18, democracy_index: 3.52, conflict_exposure: 18, international_relations: 32 } },
    { geoCode: 'SY', geoName: 'Syria',          dataYear: 2023, values: { government_effectiveness: 8,  democracy_index: 1.43, conflict_exposure: 5,  international_relations: 10 } },
    { geoCode: 'YE', geoName: 'Yemen',          dataYear: 2023, values: { government_effectiveness: 5,  democracy_index: 1.95, conflict_exposure: 5,  international_relations: 12 } },
    { geoCode: 'PS', geoName: 'Palestine',      dataYear: 2023, values: { government_effectiveness: 12, democracy_index: 3.42, conflict_exposure: 8,  international_relations: 25 } },
    // ── Amérique du Nord & Caraïbes ───────────────────────────────────────
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2023, values: { government_effectiveness: 62, democracy_index: 8.29, conflict_exposure: 82, international_relations: 72 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2023, values: { government_effectiveness: 68, democracy_index: 8.61, conflict_exposure: 85, international_relations: 72 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2023, values: { government_effectiveness: 48, democracy_index: 7.18, conflict_exposure: 72, international_relations: 62 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2023, values: { government_effectiveness: 52, democracy_index: 7.31, conflict_exposure: 58, international_relations: 58 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2023, values: { government_effectiveness: 48, democracy_index: 7.16, conflict_exposure: 60, international_relations: 55 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2023, values: { government_effectiveness: 38, democracy_index: 6.50, conflict_exposure: 62, international_relations: 52 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2023, values: { government_effectiveness: 38, democracy_index: 2.84, conflict_exposure: 72, international_relations: 28 } },
    { geoCode: 'HT', geoName: 'Haiti',          dataYear: 2023, values: { government_effectiveness: 8,  democracy_index: 2.81, conflict_exposure: 15, international_relations: 22 } },
    // ── Amérique Latine ────────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2023, values: { government_effectiveness: 48, democracy_index: 6.97, conflict_exposure: 65, international_relations: 62 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2023, values: { government_effectiveness: 40, democracy_index: 5.66, conflict_exposure: 38, international_relations: 55 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2023, values: { government_effectiveness: 40, democracy_index: 7.02, conflict_exposure: 68, international_relations: 55 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2023, values: { government_effectiveness: 72, democracy_index: 8.21, conflict_exposure: 78, international_relations: 75 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2023, values: { government_effectiveness: 45, democracy_index: 6.73, conflict_exposure: 35, international_relations: 52 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2023, values: { government_effectiveness: 35, democracy_index: 5.85, conflict_exposure: 52, international_relations: 52 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2023, values: { government_effectiveness: 32, democracy_index: 5.78, conflict_exposure: 40, international_relations: 48 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2023, values: { government_effectiveness: 12, democracy_index: 2.38, conflict_exposure: 35, international_relations: 22 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2023, values: { government_effectiveness: 28, democracy_index: 5.60, conflict_exposure: 55, international_relations: 42 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2023, values: { government_effectiveness: 28, democracy_index: 6.32, conflict_exposure: 68, international_relations: 48 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2023, values: { government_effectiveness: 22, democracy_index: 4.93, conflict_exposure: 42, international_relations: 42 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2023, values: { government_effectiveness: 18, democracy_index: 5.12, conflict_exposure: 38, international_relations: 40 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2023, values: { government_effectiveness: 32, democracy_index: 4.56, conflict_exposure: 48, international_relations: 45 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2023, values: { government_effectiveness: 18, democracy_index: 2.64, conflict_exposure: 52, international_relations: 25 } },
    // ── Afrique du Nord ───────────────────────────────────────────────────
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2023, values: { government_effectiveness: 52, democracy_index: 4.07, conflict_exposure: 55, international_relations: 58 } },
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2023, values: { government_effectiveness: 40, democracy_index: 3.18, conflict_exposure: 35, international_relations: 45 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2023, values: { government_effectiveness: 42, democracy_index: 5.51, conflict_exposure: 62, international_relations: 55 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2023, values: { government_effectiveness: 32, democracy_index: 3.56, conflict_exposure: 48, international_relations: 42 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2023, values: { government_effectiveness: 8,  democracy_index: 2.06, conflict_exposure: 15, international_relations: 22 } },
    // ── Afrique de l'Ouest ────────────────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2023, values: { government_effectiveness: 22, democracy_index: 4.23, conflict_exposure: 22, international_relations: 38 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2023, values: { government_effectiveness: 42, democracy_index: 6.32, conflict_exposure: 62, international_relations: 58 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2023, values: { government_effectiveness: 40, democracy_index: 5.98, conflict_exposure: 55, international_relations: 55 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2023, values: { government_effectiveness: 28, democracy_index: 4.01, conflict_exposure: 48, international_relations: 48 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2023, values: { government_effectiveness: 15, democracy_index: 3.08, conflict_exposure: 18, international_relations: 28 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2023, values: { government_effectiveness: 12, democracy_index: 3.32, conflict_exposure: 15, international_relations: 22 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2023, values: { government_effectiveness: 15, democracy_index: 3.28, conflict_exposure: 20, international_relations: 25 } },
    { geoCode: 'GN', geoName: 'Guinea',         dataYear: 2023, values: { government_effectiveness: 15, democracy_index: 2.82, conflict_exposure: 38, international_relations: 30 } },
    { geoCode: 'BJ', geoName: 'Benin',          dataYear: 2023, values: { government_effectiveness: 32, democracy_index: 5.09, conflict_exposure: 60, international_relations: 50 } },
    { geoCode: 'TG', geoName: 'Togo',           dataYear: 2023, values: { government_effectiveness: 20, democracy_index: 3.22, conflict_exposure: 55, international_relations: 40 } },
    // ── Afrique de l'Est ──────────────────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2023, values: { government_effectiveness: 38, democracy_index: 5.35, conflict_exposure: 35, international_relations: 45 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2023, values: { government_effectiveness: 25, democracy_index: 3.44, conflict_exposure: 18, international_relations: 30 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2023, values: { government_effectiveness: 28, democracy_index: 4.46, conflict_exposure: 55, international_relations: 48 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2023, values: { government_effectiveness: 28, democracy_index: 4.50, conflict_exposure: 38, international_relations: 38 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2023, values: { government_effectiveness: 52, democracy_index: 3.10, conflict_exposure: 48, international_relations: 48 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2023, values: { government_effectiveness: 18, democracy_index: 3.51, conflict_exposure: 28, international_relations: 35 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2023, values: { government_effectiveness: 15, democracy_index: 4.98, conflict_exposure: 52, international_relations: 38 } },
    { geoCode: 'SO', geoName: 'Somalia',        dataYear: 2023, values: { government_effectiveness: 5,  democracy_index: 1.32, conflict_exposure: 8,  international_relations: 15 } },
    { geoCode: 'SD', geoName: 'Sudan',          dataYear: 2023, values: { government_effectiveness: 5,  democracy_index: 2.47, conflict_exposure: 8,  international_relations: 15 } },
    { geoCode: 'SS', geoName: 'South Sudan',    dataYear: 2023, values: { government_effectiveness: 3,  democracy_index: 1.20, conflict_exposure: 8,  international_relations: 12 } },
    { geoCode: 'ER', geoName: 'Eritrea',        dataYear: 2023, values: { government_effectiveness: 12, democracy_index: 1.82, conflict_exposure: 32, international_relations: 15 } },
    { geoCode: 'DJ', geoName: 'Djibouti',       dataYear: 2023, values: { government_effectiveness: 22, democracy_index: 2.54, conflict_exposure: 52, international_relations: 42 } },
    // ── Afrique australe & centrale ───────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2023, values: { government_effectiveness: 52, democracy_index: 7.05, conflict_exposure: 55, international_relations: 62 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2023, values: { government_effectiveness: 62, democracy_index: 7.62, conflict_exposure: 82, international_relations: 65 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2023, values: { government_effectiveness: 48, democracy_index: 6.52, conflict_exposure: 78, international_relations: 60 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2023, values: { government_effectiveness: 65, democracy_index: 8.14, conflict_exposure: 90, international_relations: 65 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2023, values: { government_effectiveness: 28, democracy_index: 5.68, conflict_exposure: 68, international_relations: 52 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2023, values: { government_effectiveness: 12, democracy_index: 3.07, conflict_exposure: 48, international_relations: 28 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2023, values: { government_effectiveness: 15, democracy_index: 2.97, conflict_exposure: 48, international_relations: 38 } },
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2023, values: { government_effectiveness: 5,  democracy_index: 2.29, conflict_exposure: 10, international_relations: 22 } },
    { geoCode: 'CG', geoName: 'Congo',          dataYear: 2023, values: { government_effectiveness: 12, democracy_index: 2.94, conflict_exposure: 42, international_relations: 32 } },
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2023, values: { government_effectiveness: 18, democracy_index: 3.40, conflict_exposure: 28, international_relations: 35 } },
    { geoCode: 'TD', geoName: 'Chad',           dataYear: 2023, values: { government_effectiveness: 8,  democracy_index: 1.67, conflict_exposure: 18, international_relations: 22 } },
    { geoCode: 'CF', geoName: 'Central African Republic', dataYear: 2023, values: { government_effectiveness: 3, democracy_index: 1.35, conflict_exposure: 10, international_relations: 15 } },
    // ── Pacifique ─────────────────────────────────────────────────────────
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2023, values: { government_effectiveness: 42, democracy_index: 5.61, conflict_exposure: 82, international_relations: 55 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2023, values: { government_effectiveness: 22, democracy_index: 5.84, conflict_exposure: 48, international_relations: 42 } },
  ],
  seedDataPrev: [
    // ── Europe nordique ──────────────────────────── (WB WGI 2022 -> 0-100, EIU Democracy Index 2022)
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2022, values: { government_effectiveness: 89, democracy_index: 9.81, conflict_exposure: 95, international_relations: 94 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2022, values: { government_effectiveness: 81, democracy_index: 9.52, conflict_exposure: 98, international_relations: 93 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2022, values: { government_effectiveness: 81, democracy_index: 9.39, conflict_exposure: 94, international_relations: 91 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2022, values: { government_effectiveness: 85, democracy_index: 9.29, conflict_exposure: 89, international_relations: 89 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2022, values: { government_effectiveness: 90, democracy_index: 9.28, conflict_exposure: 94, international_relations: 91 } },
    // ── Océanie & autres démocraties avancées ─────────────────────────────
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2022, values: { government_effectiveness: 77, democracy_index: 9.61, conflict_exposure: 97, international_relations: 91 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2022, values: { government_effectiveness: 91, democracy_index: 9.14, conflict_exposure: 96, international_relations: 91 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2022, values: { government_effectiveness: 82, democracy_index: 8.88, conflict_exposure: 92, international_relations: 89 } },
    // ── Europe de l'Ouest ──────────────────────────────────────────────────
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2022, values: { government_effectiveness: 79, democracy_index: 8.20, conflict_exposure: 92, international_relations: 87 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2022, values: { government_effectiveness: 81, democracy_index: 9.00, conflict_exposure: 92, international_relations: 87 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2022, values: { government_effectiveness: 85, democracy_index: 8.68, conflict_exposure: 94, international_relations: 89 } },
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2022, values: { government_effectiveness: 81, democracy_index: 8.71, conflict_exposure: 90, international_relations: 87 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2022, values: { government_effectiveness: 81, democracy_index: 8.88, conflict_exposure: 90, international_relations: 89 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2022, values: { government_effectiveness: 76, democracy_index: 8.80, conflict_exposure: 86, international_relations: 87 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2022, values: { government_effectiveness: 75, democracy_index: 7.64, conflict_exposure: 88, international_relations: 84 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2022, values: { government_effectiveness: 73, democracy_index: 8.07, conflict_exposure: 82, international_relations: 84 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2022, values: { government_effectiveness: 75, democracy_index: 8.28, conflict_exposure: 82, international_relations: 84 } },
    { geoCode: 'US', geoName: 'United States',  dataYear: 2022, values: { government_effectiveness: 75, democracy_index: 7.85, conflict_exposure: 72, international_relations: 81 } },
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2022, values: { government_effectiveness: 82, democracy_index: 8.33, conflict_exposure: 78, international_relations: 81 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2022, values: { government_effectiveness: 70, democracy_index: 8.03, conflict_exposure: 90, international_relations: 81 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2022, values: { government_effectiveness: 68, democracy_index: 7.94, conflict_exposure: 82, international_relations: 79 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2022, values: { government_effectiveness: 59, democracy_index: 7.69, conflict_exposure: 80, international_relations: 77 } },
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2022, values: { government_effectiveness: 75, democracy_index: 7.93, conflict_exposure: 40, international_relations: 57 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2022, values: { government_effectiveness: 77, democracy_index: 8.03, conflict_exposure: 60, international_relations: 71 } },
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2022, values: { government_effectiveness: 93, democracy_index: 6.22, conflict_exposure: 90, international_relations: 84 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2022, values: { government_effectiveness: 85, democracy_index: 8.99, conflict_exposure: 50, international_relations: 67 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2022, values: { government_effectiveness: 59, democracy_index: 7.56, conflict_exposure: 72, international_relations: 71 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2022, values: { government_effectiveness: 75, democracy_index: 8.10, conflict_exposure: 92, international_relations: 77 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2022, values: { government_effectiveness: 72, democracy_index: 7.43, conflict_exposure: 70, international_relations: 71 } },
    // ── Europe de l'Est ──────────────────────────── (WB WGI 2022 -> 0-100, EIU 2022)
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2022, values: { government_effectiveness: 72, democracy_index: 7.97, conflict_exposure: 82, international_relations: 79 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2022, values: { government_effectiveness: 77, democracy_index: 7.96, conflict_exposure: 70, international_relations: 76 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2022, values: { government_effectiveness: 55, democracy_index: 7.04, conflict_exposure: 70, international_relations: 71 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2022, values: { government_effectiveness: 58, democracy_index: 7.07, conflict_exposure: 76, international_relations: 69 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2022, values: { government_effectiveness: 61, democracy_index: 6.64, conflict_exposure: 76, international_relations: 59 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2022, values: { government_effectiveness: 62, democracy_index: 6.50, conflict_exposure: 78, international_relations: 69 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2022, values: { government_effectiveness: 50, democracy_index: 6.45, conflict_exposure: 72, international_relations: 67 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2022, values: { government_effectiveness: 45, democracy_index: 6.53, conflict_exposure: 72, international_relations: 61 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2022, values: { government_effectiveness: 74, democracy_index: 7.41, conflict_exposure: 68, international_relations: 74 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2022, values: { government_effectiveness: 72, democracy_index: 7.28, conflict_exposure: 68, international_relations: 72 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2022, values: { government_effectiveness: 73, democracy_index: 7.48, conflict_exposure: 88, international_relations: 75 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2022, values: { government_effectiveness: 46, democracy_index: 6.12, conflict_exposure: 60, international_relations: 48 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2022, values: { government_effectiveness: 28, democracy_index: 4.84, conflict_exposure: 58, international_relations: 41 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2022, values: { government_effectiveness: 43, democracy_index: 5.68, conflict_exposure: 72, international_relations: 51 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2022, values: { government_effectiveness: 40, democracy_index: 5.78, conflict_exposure: 68, international_relations: 51 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2022, values: { government_effectiveness: 38, democracy_index: 5.38, conflict_exposure: 72, international_relations: 54 } },
    { geoCode: 'XK', geoName: 'Kosovo',         dataYear: 2022, values: { government_effectiveness: 33, democracy_index: 5.05, conflict_exposure: 53, international_relations: 38 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2022, values: { government_effectiveness: 32, democracy_index: 5.56, conflict_exposure: 50, international_relations: 46 } },
    // ── Ex-URSS & Asie centrale ──────────────────── (WB WGI 2022 -> 0-100, EIU 2022)
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2022, values: { government_effectiveness: 36, democracy_index: 2.28, conflict_exposure: 12, international_relations: 10 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2022, values: { government_effectiveness: 40, democracy_index: 5.42, conflict_exposure: 5,  international_relations: 40 } },
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2022, values: { government_effectiveness: 53, democracy_index: 3.08, conflict_exposure: 62, international_relations: 54 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2022, values: { government_effectiveness: 36, democracy_index: 2.10, conflict_exposure: 48, international_relations: 15 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2022, values: { government_effectiveness: 53, democracy_index: 5.12, conflict_exposure: 50, international_relations: 50 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2022, values: { government_effectiveness: 40, democracy_index: 5.38, conflict_exposure: 30, international_relations: 38 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2022, values: { government_effectiveness: 43, democracy_index: 2.59, conflict_exposure: 32, international_relations: 43 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2022, values: { government_effectiveness: 40, democracy_index: 2.01, conflict_exposure: 58, international_relations: 48 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2022, values: { government_effectiveness: 26, democracy_index: 1.59, conflict_exposure: 65, international_relations: 28 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2022, values: { government_effectiveness: 28, democracy_index: 3.50, conflict_exposure: 50, international_relations: 40 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2022, values: { government_effectiveness: 23, democracy_index: 1.85, conflict_exposure: 46, international_relations: 33 } },
    // ── Asie de l'Est & du Sud-Est ───────────────── (WB WGI 2022 -> 0-100, EIU 2022)
    { geoCode: 'CN', geoName: 'China',          dataYear: 2022, values: { government_effectiveness: 60, democracy_index: 1.94, conflict_exposure: 52, international_relations: 54 } },
    { geoCode: 'IN', geoName: 'India',          dataYear: 2022, values: { government_effectiveness: 57, democracy_index: 7.04, conflict_exposure: 42, international_relations: 59 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2022, values: { government_effectiveness: 53, democracy_index: 6.67, conflict_exposure: 58, international_relations: 61 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2022, values: { government_effectiveness: 54, democracy_index: 2.73, conflict_exposure: 65, international_relations: 59 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2022, values: { government_effectiveness: 59, democracy_index: 6.71, conflict_exposure: 60, international_relations: 64 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2022, values: { government_effectiveness: 51, democracy_index: 6.73, conflict_exposure: 48, international_relations: 57 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2022, values: { government_effectiveness: 38, democracy_index: 4.13, conflict_exposure: 28, international_relations: 34 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2022, values: { government_effectiveness: 35, democracy_index: 5.99, conflict_exposure: 50, international_relations: 47 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2022, values: { government_effectiveness: 70, democracy_index: 6.30, conflict_exposure: 72, international_relations: 69 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2022, values: { government_effectiveness: 14, democracy_index: 1.72, conflict_exposure: 10, international_relations: 18 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2022, values: { government_effectiveness: 30, democracy_index: 3.10, conflict_exposure: 62, international_relations: 47 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2022, values: { government_effectiveness: 28, democracy_index: 2.08, conflict_exposure: 68, international_relations: 47 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2022, values: { government_effectiveness: 36, democracy_index: 6.42, conflict_exposure: 78, international_relations: 54 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2022, values: { government_effectiveness: 36, democracy_index: 6.05, conflict_exposure: 50, international_relations: 48 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2022, values: { government_effectiveness: 26, democracy_index: 4.72, conflict_exposure: 55, international_relations: 44 } },
    { geoCode: 'KP', geoName: 'North Korea',    dataYear: 2022, values: { government_effectiveness: 20, democracy_index: 1.08, conflict_exposure: 28, international_relations: 5 } },
    // ── Moyen-Orient ────────────────────────────── (WB WGI 2022 -> 0-100, EIU 2022)
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2022, values: { government_effectiveness: 62, democracy_index: 2.08, conflict_exposure: 38, international_relations: 54 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2022, values: { government_effectiveness: 32, democracy_index: 1.96, conflict_exposure: 25, international_relations: 19 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2022, values: { government_effectiveness: 46, democracy_index: 4.35, conflict_exposure: 38, international_relations: 44 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2022, values: { government_effectiveness: 86, democracy_index: 2.67, conflict_exposure: 72, international_relations: 74 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2022, values: { government_effectiveness: 80, democracy_index: 3.14, conflict_exposure: 70, international_relations: 67 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2022, values: { government_effectiveness: 56, democracy_index: 3.78, conflict_exposure: 60, international_relations: 61 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2022, values: { government_effectiveness: 60, democracy_index: 3.04, conflict_exposure: 72, international_relations: 64 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2022, values: { government_effectiveness: 58, democracy_index: 2.47, conflict_exposure: 58, international_relations: 57 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2022, values: { government_effectiveness: 50, democracy_index: 3.34, conflict_exposure: 48, international_relations: 57 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2022, values: { government_effectiveness: 16, democracy_index: 4.28, conflict_exposure: 28, international_relations: 34 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2022, values: { government_effectiveness: 16, democracy_index: 3.40, conflict_exposure: 18, international_relations: 31 } },
    { geoCode: 'SY', geoName: 'Syria',          dataYear: 2022, values: { government_effectiveness: 6,  democracy_index: 1.43, conflict_exposure: 5,  international_relations: 8 } },
    { geoCode: 'YE', geoName: 'Yemen',          dataYear: 2022, values: { government_effectiveness: 4,  democracy_index: 1.95, conflict_exposure: 5,  international_relations: 11 } },
    { geoCode: 'PS', geoName: 'Palestine',      dataYear: 2022, values: { government_effectiveness: 11, democracy_index: 3.32, conflict_exposure: 12, international_relations: 24 } },
    // ── Amérique du Nord & Caraïbes ──────────────── (WB WGI 2022 -> 0-100, EIU 2022)
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2022, values: { government_effectiveness: 60, democracy_index: 8.22, conflict_exposure: 82, international_relations: 71 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2022, values: { government_effectiveness: 66, democracy_index: 8.55, conflict_exposure: 85, international_relations: 71 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2022, values: { government_effectiveness: 46, democracy_index: 7.10, conflict_exposure: 72, international_relations: 61 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2022, values: { government_effectiveness: 50, democracy_index: 7.24, conflict_exposure: 56, international_relations: 57 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2022, values: { government_effectiveness: 46, democracy_index: 7.10, conflict_exposure: 58, international_relations: 54 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2022, values: { government_effectiveness: 36, democracy_index: 6.40, conflict_exposure: 62, international_relations: 51 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2022, values: { government_effectiveness: 36, democracy_index: 2.78, conflict_exposure: 72, international_relations: 27 } },
    { geoCode: 'HT', geoName: 'Haiti',          dataYear: 2022, values: { government_effectiveness: 7,  democracy_index: 2.72, conflict_exposure: 12, international_relations: 21 } },
    // ── Amérique Latine ──────────────────────────── (WB WGI 2022 -> 0-100, EIU 2022)
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2022, values: { government_effectiveness: 38, democracy_index: 6.78, conflict_exposure: 65, international_relations: 61 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2022, values: { government_effectiveness: 44, democracy_index: 5.25, conflict_exposure: 38, international_relations: 54 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2022, values: { government_effectiveness: 44, democracy_index: 6.85, conflict_exposure: 68, international_relations: 54 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2022, values: { government_effectiveness: 61, democracy_index: 8.22, conflict_exposure: 78, international_relations: 74 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2022, values: { government_effectiveness: 50, democracy_index: 6.72, conflict_exposure: 35, international_relations: 51 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2022, values: { government_effectiveness: 33, democracy_index: 5.72, conflict_exposure: 50, international_relations: 51 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2022, values: { government_effectiveness: 30, democracy_index: 5.70, conflict_exposure: 42, international_relations: 47 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2022, values: { government_effectiveness: 10, democracy_index: 2.24, conflict_exposure: 35, international_relations: 20 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2022, values: { government_effectiveness: 26, democracy_index: 5.50, conflict_exposure: 55, international_relations: 41 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2022, values: { government_effectiveness: 26, democracy_index: 6.24, conflict_exposure: 68, international_relations: 47 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2022, values: { government_effectiveness: 20, democracy_index: 4.85, conflict_exposure: 40, international_relations: 41 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2022, values: { government_effectiveness: 16, democracy_index: 5.04, conflict_exposure: 36, international_relations: 39 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2022, values: { government_effectiveness: 30, democracy_index: 4.48, conflict_exposure: 46, international_relations: 44 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2022, values: { government_effectiveness: 16, democracy_index: 2.56, conflict_exposure: 52, international_relations: 24 } },
    // ── Afrique du Nord ─────────────────────────── (WB WGI 2022 -> 0-100, EIU 2022)
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2022, values: { government_effectiveness: 48, democracy_index: 4.00, conflict_exposure: 55, international_relations: 57 } },
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2022, values: { government_effectiveness: 41, democracy_index: 2.93, conflict_exposure: 35, international_relations: 44 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2022, values: { government_effectiveness: 40, democracy_index: 5.42, conflict_exposure: 62, international_relations: 54 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2022, values: { government_effectiveness: 30, democracy_index: 3.48, conflict_exposure: 48, international_relations: 41 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2022, values: { government_effectiveness: 7,  democracy_index: 1.98, conflict_exposure: 14, international_relations: 21 } },
    // ── Afrique de l'Ouest ──────────────────────── (WB WGI 2022 -> 0-100, EIU 2022)
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2022, values: { government_effectiveness: 29, democracy_index: 4.11, conflict_exposure: 22, international_relations: 37 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2022, values: { government_effectiveness: 40, democracy_index: 6.24, conflict_exposure: 62, international_relations: 57 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2022, values: { government_effectiveness: 38, democracy_index: 5.88, conflict_exposure: 52, international_relations: 54 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2022, values: { government_effectiveness: 26, democracy_index: 3.88, conflict_exposure: 46, international_relations: 47 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2022, values: { government_effectiveness: 14, democracy_index: 3.00, conflict_exposure: 15, international_relations: 26 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2022, values: { government_effectiveness: 11, democracy_index: 3.25, conflict_exposure: 14, international_relations: 20 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2022, values: { government_effectiveness: 14, democracy_index: 3.18, conflict_exposure: 18, international_relations: 24 } },
    { geoCode: 'GN', geoName: 'Guinea',         dataYear: 2022, values: { government_effectiveness: 13, democracy_index: 2.74, conflict_exposure: 36, international_relations: 29 } },
    { geoCode: 'BJ', geoName: 'Benin',          dataYear: 2022, values: { government_effectiveness: 30, democracy_index: 4.96, conflict_exposure: 60, international_relations: 49 } },
    { geoCode: 'TG', geoName: 'Togo',           dataYear: 2022, values: { government_effectiveness: 18, democracy_index: 3.14, conflict_exposure: 55, international_relations: 39 } },
    // ── Afrique de l'Est ────────────────────────── (WB WGI 2022 -> 0-100, EIU 2022)
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2022, values: { government_effectiveness: 43, democracy_index: 5.33, conflict_exposure: 35, international_relations: 44 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2022, values: { government_effectiveness: 34, democracy_index: 3.32, conflict_exposure: 18, international_relations: 29 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2022, values: { government_effectiveness: 26, democracy_index: 4.38, conflict_exposure: 55, international_relations: 47 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2022, values: { government_effectiveness: 26, democracy_index: 4.40, conflict_exposure: 36, international_relations: 37 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2022, values: { government_effectiveness: 50, democracy_index: 3.02, conflict_exposure: 46, international_relations: 47 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2022, values: { government_effectiveness: 16, democracy_index: 3.42, conflict_exposure: 26, international_relations: 34 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2022, values: { government_effectiveness: 14, democracy_index: 4.88, conflict_exposure: 52, international_relations: 37 } },
    { geoCode: 'SO', geoName: 'Somalia',        dataYear: 2022, values: { government_effectiveness: 4,  democracy_index: 1.28, conflict_exposure: 6,  international_relations: 14 } },
    { geoCode: 'SD', geoName: 'Sudan',          dataYear: 2022, values: { government_effectiveness: 5,  democracy_index: 2.42, conflict_exposure: 10, international_relations: 14 } },
    { geoCode: 'SS', geoName: 'South Sudan',    dataYear: 2022, values: { government_effectiveness: 2,  democracy_index: 1.18, conflict_exposure: 6,  international_relations: 11 } },
    { geoCode: 'ER', geoName: 'Eritrea',        dataYear: 2022, values: { government_effectiveness: 11, democracy_index: 1.78, conflict_exposure: 30, international_relations: 14 } },
    { geoCode: 'DJ', geoName: 'Djibouti',       dataYear: 2022, values: { government_effectiveness: 20, democracy_index: 2.48, conflict_exposure: 52, international_relations: 41 } },
    // ── Afrique australe & centrale ──────────────── (WB WGI 2022 -> 0-100, EIU 2022)
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2022, values: { government_effectiveness: 48, democracy_index: 7.05, conflict_exposure: 55, international_relations: 61 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2022, values: { government_effectiveness: 60, democracy_index: 7.52, conflict_exposure: 82, international_relations: 64 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2022, values: { government_effectiveness: 46, democracy_index: 6.42, conflict_exposure: 78, international_relations: 59 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2022, values: { government_effectiveness: 63, democracy_index: 8.08, conflict_exposure: 90, international_relations: 64 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2022, values: { government_effectiveness: 26, democracy_index: 5.58, conflict_exposure: 68, international_relations: 51 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2022, values: { government_effectiveness: 11, democracy_index: 2.98, conflict_exposure: 48, international_relations: 27 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2022, values: { government_effectiveness: 14, democracy_index: 2.88, conflict_exposure: 48, international_relations: 37 } },
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2022, values: { government_effectiveness: 4,  democracy_index: 2.20, conflict_exposure: 8,  international_relations: 21 } },
    { geoCode: 'CG', geoName: 'Congo',          dataYear: 2022, values: { government_effectiveness: 11, democracy_index: 2.85, conflict_exposure: 42, international_relations: 31 } },
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2022, values: { government_effectiveness: 17, democracy_index: 3.32, conflict_exposure: 26, international_relations: 34 } },
    { geoCode: 'TD', geoName: 'Chad',           dataYear: 2022, values: { government_effectiveness: 7,  democracy_index: 1.60, conflict_exposure: 16, international_relations: 21 } },
    { geoCode: 'CF', geoName: 'Central African Republic', dataYear: 2022, values: { government_effectiveness: 2, democracy_index: 1.30, conflict_exposure: 8, international_relations: 14 } },
    // ── Pacifique ────────────────────────────────── (WB WGI 2022 -> 0-100, EIU 2022)
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2022, values: { government_effectiveness: 40, democracy_index: 5.48, conflict_exposure: 82, international_relations: 54 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2022, values: { government_effectiveness: 20, democracy_index: 5.76, conflict_exposure: 46, international_relations: 41 } },
  ],
};

export default geopoliticalRiskModule;
