import type { DomainModule } from '@/lib/domains/types';

const freedomModule: DomainModule = {
  definition: {
    id: 'freedom',
    label: { fr: 'Libertés politiques', en: 'Political Freedom', es: 'Libertades políticas' },
    description: {
      fr: 'Mesure les droits politiques et les libertés civiles dans le monde. Basé sur le rapport Freedom in the World de Freedom House.',
      en: 'Measures political rights and civil liberties worldwide. Based on Freedom House\'s Freedom in the World report.',
      es: 'Mide los derechos políticos y las libertades civiles en el mundo. Basado en el informe Freedom in the World de Freedom House.',
    },
    icon: '🗽',
    group: 'security',
    active: true,
    seedSources: [
      'https://freedomhouse.org/report/freedom-world',
      'https://freedomhouse.org/country/scores',
    ],
    indicators: [
      {
        id: 'freedom_score',
        label: { fr: 'Score de liberté (Freedom House)', en: 'Freedom Score (Freedom House)', es: 'Puntuación de libertad (Freedom House)' },
        description: {
          fr: 'Score composite Freedom House mesurant les droits politiques (40 pts) et les libertés civiles (60 pts). 0 = pas libre, 100 = entièrement libre.',
          en: 'Composite Freedom House score measuring political rights (40 pts) and civil liberties (60 pts). 0 = not free, 100 = fully free.',
        },
        unit: 'index',
        unitLabel: { fr: 'score /100', en: 'score /100', es: 'score /100' },
        direction: 'higher_is_better',
        weight: 4,
        thresholds: { excellent: 85, good: 65, fair: 40, poor: 20 },
        minValue: 0,
        maxValue: 100,
      },
    ],
  },
  seedData: [
    // ── Europe nordique ─────────────────────────────────────────────────── (Freedom in the World 2026)
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2026, values: { freedom_score: 100 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2026, values: { freedom_score: 99 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2026, values: { freedom_score: 99 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2026, values: { freedom_score: 97 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2026, values: { freedom_score: 95 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2026, values: { freedom_score: 96 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2026, values: { freedom_score: 90 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2026, values: { freedom_score: 89 } },
    // ── Europe de l'Ouest ────────────────────────────────────────────────
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2026, values: { freedom_score: 97 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2026, values: { freedom_score: 97 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2026, values: { freedom_score: 95 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2026, values: { freedom_score: 98 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2026, values: { freedom_score: 96 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2026, values: { freedom_score: 94 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2026, values: { freedom_score: 95 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2026, values: { freedom_score: 89 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2026, values: { freedom_score: 92 } },
    // ── Europe du Sud ────────────────────────────────────────────────────
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2026, values: { freedom_score: 96 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2026, values: { freedom_score: 91 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2026, values: { freedom_score: 87 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2026, values: { freedom_score: 85 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2026, values: { freedom_score: 90 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2026, values: { freedom_score: 88 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2026, values: { freedom_score: 97 } },
    // ── Europe centrale & orientale ──────────────────────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2026, values: { freedom_score: 95 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2026, values: { freedom_score: 82 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2026, values: { freedom_score: 88 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2026, values: { freedom_score: 82 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2026, values: { freedom_score: 65 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2026, values: { freedom_score: 83 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2026, values: { freedom_score: 74 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2026, values: { freedom_score: 53 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2026, values: { freedom_score: 54 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2026, values: { freedom_score: 68 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2026, values: { freedom_score: 67 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2026, values: { freedom_score: 69 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2026, values: { freedom_score: 60 } },
    // ── Amérique du Nord & Océanie ────────────────────────────────────────
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2026, values: { freedom_score: 99 } },
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2026, values: { freedom_score: 94 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2026, values: { freedom_score: 97 } },
    { geoCode: 'US', geoName: 'United States',  dataYear: 2026, values: { freedom_score: 81 } },
    // ── Asie de l'Est ────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2026, values: { freedom_score: 96 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2026, values: { freedom_score: 83 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2026, values: { freedom_score: 93 } },
    { geoCode: 'HK', geoName: 'Hong Kong',      dataYear: 2026, values: { freedom_score: 41 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2026, values: { freedom_score: 9 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2026, values: { freedom_score: 84 } },
    // ── Asie du Sud-Est ──────────────────────────────────────────────────
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2026, values: { freedom_score: 48 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2026, values: { freedom_score: 53 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2026, values: { freedom_score: 33 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2026, values: { freedom_score: 56 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2026, values: { freedom_score: 20 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2026, values: { freedom_score: 58 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2026, values: { freedom_score: 22 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2026, values: { freedom_score: 4 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2026, values: { freedom_score: 13 } },
    // ── Asie du Sud ──────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2026, values: { freedom_score: 62 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2026, values: { freedom_score: 63 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2026, values: { freedom_score: 59 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2026, values: { freedom_score: 44 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2026, values: { freedom_score: 32 } },
    { geoCode: 'AF', geoName: 'Afghanistan',    dataYear: 2026, values: { freedom_score: 8 } },
    // ── Asie centrale ────────────────────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2026, values: { freedom_score: 23 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2026, values: { freedom_score: 12 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2026, values: { freedom_score: 25 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2026, values: { freedom_score: 5 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2026, values: { freedom_score: 1 } },
    // ── Moyen-Orient & Afrique du Nord ───────────────────────────────────
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2026, values: { freedom_score: 73 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2026, values: { freedom_score: 18 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2026, values: { freedom_score: 25 } },
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2026, values: { freedom_score: 9 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2026, values: { freedom_score: 12 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2026, values: { freedom_score: 24 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2026, values: { freedom_score: 30 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2026, values: { freedom_score: 34 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2026, values: { freedom_score: 41 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2026, values: { freedom_score: 10 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2026, values: { freedom_score: 31 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2026, values: { freedom_score: 32 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2026, values: { freedom_score: 42 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2026, values: { freedom_score: 31 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2026, values: { freedom_score: 10 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2026, values: { freedom_score: 37 } },
    // ── Ex-URSS (Europe) ─────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2026, values: { freedom_score: 12 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2026, values: { freedom_score: 51 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2026, values: { freedom_score: 7 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2026, values: { freedom_score: 51 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2026, values: { freedom_score: 54 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2026, values: { freedom_score: 6 } },
    // ── Amérique Latine ──────────────────────────────────────────────────
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2026, values: { freedom_score: 95 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2026, values: { freedom_score: 97 } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2026, values: { freedom_score: 91 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2026, values: { freedom_score: 85 } },
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2026, values: { freedom_score: 73 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2026, values: { freedom_score: 69 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2026, values: { freedom_score: 66 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2026, values: { freedom_score: 64 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2026, values: { freedom_score: 82 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2026, values: { freedom_score: 67 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2026, values: { freedom_score: 58 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2026, values: { freedom_score: 63 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2026, values: { freedom_score: 69 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2026, values: { freedom_score: 48 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2026, values: { freedom_score: 47 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2026, values: { freedom_score: 13 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2026, values: { freedom_score: 14 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2026, values: { freedom_score: 9 } },
    { geoCode: 'HT', geoName: 'Haiti',          dataYear: 2026, values: { freedom_score: 22 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2026, values: { freedom_score: 83 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2026, values: { freedom_score: 81 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2026, values: { freedom_score: 42 } },
    // ── Afrique subsaharienne (Est) ──────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2026, values: { freedom_score: 49 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2026, values: { freedom_score: 18 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2026, values: { freedom_score: 28 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2026, values: { freedom_score: 33 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2026, values: { freedom_score: 21 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2026, values: { freedom_score: 42 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2026, values: { freedom_score: 50 } },
    { geoCode: 'SD', geoName: 'Sudan',          dataYear: 2026, values: { freedom_score: 1 } },
    { geoCode: 'SO', geoName: 'Somalia',        dataYear: 2026, values: { freedom_score: 8 } },
    // ── Afrique subsaharienne (Ouest) ────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2026, values: { freedom_score: 44 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2026, values: { freedom_score: 80 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2026, values: { freedom_score: 70 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2026, values: { freedom_score: 46 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2026, values: { freedom_score: 20 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2026, values: { freedom_score: 21 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2026, values: { freedom_score: 27 } },
    { geoCode: 'GN', geoName: 'Guinea',         dataYear: 2026, values: { freedom_score: 28 } },
    { geoCode: 'GM', geoName: 'Gambia',         dataYear: 2026, values: { freedom_score: 51 } },
    { geoCode: 'BJ', geoName: 'Benin',          dataYear: 2026, values: { freedom_score: 61 } },
    { geoCode: 'TG', geoName: 'Togo',           dataYear: 2026, values: { freedom_score: 37 } },
    { geoCode: 'SL', geoName: 'Sierra Leone',   dataYear: 2026, values: { freedom_score: 61 } },
    { geoCode: 'LR', geoName: 'Liberia',        dataYear: 2026, values: { freedom_score: 65 } },
    // ── Afrique subsaharienne (Centre) ───────────────────────────────────
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2026, values: { freedom_score: 15 } },
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2026, values: { freedom_score: 18 } },
    { geoCode: 'CG', geoName: 'Congo',          dataYear: 2026, values: { freedom_score: 17 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2026, values: { freedom_score: 25 } },
    { geoCode: 'TD', geoName: 'Chad',           dataYear: 2026, values: { freedom_score: 15 } },
    // ── Afrique australe ─────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2026, values: { freedom_score: 81 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2026, values: { freedom_score: 75 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2026, values: { freedom_score: 87 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2026, values: { freedom_score: 73 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2026, values: { freedom_score: 53 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2026, values: { freedom_score: 25 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2026, values: { freedom_score: 28 } },
    // ── Afrique du Nord ──────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2026, values: { freedom_score: 18 } },
    // ── Pacifique ────────────────────────────────────────────────────────
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2026, values: { freedom_score: 72 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2026, values: { freedom_score: 61 } },
  ],
  seedDataPrev: [
    // ── Données Freedom in the World 2025 (estimations) ──────────────────
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2025, values: { freedom_score: 100 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2025, values: { freedom_score: 100 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2025, values: { freedom_score: 100 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2025, values: { freedom_score: 97 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2025, values: { freedom_score: 96 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2025, values: { freedom_score: 96 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2025, values: { freedom_score: 90 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2025, values: { freedom_score: 93 } },
    { geoCode: 'US', geoName: 'United States',  dataYear: 2025, values: { freedom_score: 83 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2025, values: { freedom_score: 98 } },
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2025, values: { freedom_score: 95 } },
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2025, values: { freedom_score: 96 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2025, values: { freedom_score: 83 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2025, values: { freedom_score: 94 } },
    { geoCode: 'IN', geoName: 'India',          dataYear: 2025, values: { freedom_score: 66 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2025, values: { freedom_score: 9 } },
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2025, values: { freedom_score: 13 } },
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2025, values: { freedom_score: 73 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2025, values: { freedom_score: 84 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2025, values: { freedom_score: 59 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2025, values: { freedom_score: 32 } },
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2025, values: { freedom_score: 8 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2025, values: { freedom_score: 11 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2025, values: { freedom_score: 84 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2025, values: { freedom_score: 66 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2025, values: { freedom_score: 50 } },
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2025, values: { freedom_score: 82 } },
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2025, values: { freedom_score: 44 } },
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2025, values: { freedom_score: 18 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2025, values: { freedom_score: 57 } },
  ],
};

export default freedomModule;
