import type { DomainModule } from '@/lib/domains/types';

const ecologyModule: DomainModule = {
  definition: {
    id: 'ecology',
    label: { fr: 'Écologie', en: 'Ecology' },
    description: {
      fr: 'Évalue la performance environnementale des pays : émissions de CO₂, part des énergies renouvelables, couverture forestière et qualité de l\'air.',
      en: 'Evaluates environmental performance: CO₂ emissions, renewable energy share, forest coverage and air quality.',
    },
    icon: '🌿',
    group: 'environment',
    active: true,
    seedSources: [
      'https://data.worldbank.org/indicator/EN.ATM.CO2E.PC',
      'https://data.worldbank.org/indicator/EG.ELC.RNEW.ZS',
      'https://data.worldbank.org/indicator/AG.LND.FRST.ZS',
      'https://www.iqair.com/world-air-quality-report',
    ],
    indicators: [
      {
        id: 'co2_per_capita',
        label: { fr: 'Émissions CO₂ par habitant', en: 'CO₂ per capita' },
        unit: 'ratio',
        unitLabel: { fr: 't/hab.', en: 't/cap.' },
        direction: 'lower_is_better',
        weight: 3,
        thresholds: { excellent: 3, good: 6, fair: 10, poor: 15 },
        minValue: 0,
        maxValue: 25,
      },
      {
        id: 'renewables_share',
        label: { fr: 'Énergies renouvelables (% électricité)', en: 'Renewables share (% electricity)' },
        unit: 'percent',
        unitLabel: { fr: '% élec.', en: '% elec.' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 70, good: 45, fair: 25, poor: 10 },
        minValue: 0,
        maxValue: 100,
      },
      {
        id: 'forest_coverage',
        label: { fr: 'Couverture forestière', en: 'Forest coverage' },
        unit: 'percent',
        unitLabel: { fr: '% territoire', en: '% land area' },
        direction: 'higher_is_better',
        weight: 1,
        thresholds: { excellent: 55, good: 35, fair: 20, poor: 8 },
        minValue: 0,
        maxValue: 100,
      },
      {
        id: 'air_quality',
        label: { fr: 'Qualité de l\'air', en: 'Air quality' },
        unit: 'index',
        unitLabel: { fr: 'indice /100', en: 'index /100' },
        direction: 'higher_is_better',
        weight: 2,
        thresholds: { excellent: 88, good: 72, fair: 55, poor: 35 },
        minValue: 0,
        maxValue: 100,
      },
    ],
  },
  seedData: [
    // ── Europe du Nord ──────────────────────────────────────────────────────
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2022, values: { co2_per_capita: 9.1,  renewables_share: 99.9, forest_coverage: 0.5,  air_quality: 98 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2022, values: { co2_per_capita: 7.6,  renewables_share: 98.5, forest_coverage: 37.3, air_quality: 95 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2022, values: { co2_per_capita: 4.1,  renewables_share: 75.6, forest_coverage: 68.9, air_quality: 95 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2022, values: { co2_per_capita: 7.2,  renewables_share: 43.9, forest_coverage: 73.7, air_quality: 96 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2022, values: { co2_per_capita: 6.2,  renewables_share: 77.2, forest_coverage: 14.9, air_quality: 92 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2022, values: { co2_per_capita: 8.3,  renewables_share: 29.2, forest_coverage: 52.9, air_quality: 88 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2022, values: { co2_per_capita: 3.8,  renewables_share: 53.2, forest_coverage: 54.8, air_quality: 87 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2022, values: { co2_per_capita: 4.5,  renewables_share: 37.5, forest_coverage: 35.1, air_quality: 82 } },
    // ── Europe de l'Ouest ───────────────────────────────────────────────────
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2022, values: { co2_per_capita: 7.4,  renewables_share: 75.8, forest_coverage: 46.9, air_quality: 87 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2022, values: { co2_per_capita: 4.1,  renewables_share: 72.8, forest_coverage: 31.6, air_quality: 88 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2022, values: { co2_per_capita: 5.1,  renewables_share: 24.5, forest_coverage: 31.1, air_quality: 82 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2022, values: { co2_per_capita: 8.1,  renewables_share: 41.6, forest_coverage: 32.7, air_quality: 80 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2022, values: { co2_per_capita: 8.4,  renewables_share: 33.9, forest_coverage: 11.0, air_quality: 85 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2022, values: { co2_per_capita: 8.7,  renewables_share: 27.7, forest_coverage: 23.0, air_quality: 78 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2022, values: { co2_per_capita: 14.0, renewables_share: 26.3, forest_coverage: 35.4, air_quality: 84 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2022, values: { co2_per_capita: 8.1,  renewables_share: 40.4, forest_coverage: 11.5, air_quality: 94 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2022, values: { co2_per_capita: 5.5,  renewables_share: 43.5, forest_coverage: 13.0, air_quality: 78 } },
    // ── Europe du Sud ───────────────────────────────────────────────────────
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2022, values: { co2_per_capita: 5.0,  renewables_share: 59.5, forest_coverage: 37.8, air_quality: 85 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2022, values: { co2_per_capita: 5.4,  renewables_share: 46.5, forest_coverage: 36.5, air_quality: 82 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2022, values: { co2_per_capita: 6.0,  renewables_share: 38.2, forest_coverage: 33.9, air_quality: 75 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2022, values: { co2_per_capita: 6.6,  renewables_share: 36.8, forest_coverage: 31.3, air_quality: 80 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2022, values: { co2_per_capita: 3.8,  renewables_share: 12.5, forest_coverage: 1.1,  air_quality: 80 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2022, values: { co2_per_capita: 6.2,  renewables_share: 17.3, forest_coverage: 18.7, air_quality: 82 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2022, values: { co2_per_capita: 6.5,  renewables_share: 35.8, forest_coverage: 61.5, air_quality: 78 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2022, values: { co2_per_capita: 4.7,  renewables_share: 58.5, forest_coverage: 46.7, air_quality: 78 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2022, values: { co2_per_capita: 6.2, renewables_share: 37.0, forest_coverage: 42.7, air_quality: 52 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2022, values: { co2_per_capita: 6.8,  renewables_share: 26.3, forest_coverage: 31.1, air_quality: 55 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2022, values: { co2_per_capita: 4.1,  renewables_share: 58.0, forest_coverage: 61.5, air_quality: 65 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2022, values: { co2_per_capita: 3.9, renewables_share: 28.0, forest_coverage: 39.6, air_quality: 52 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2022, values: { co2_per_capita: 1.6,  renewables_share: 100.0, forest_coverage: 28.8, air_quality: 62 } },
    // ── Europe de l'Est ─────────────────────────────────────────────────────
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2022, values: { co2_per_capita: 3.8,  renewables_share: 52.7, forest_coverage: 29.6, air_quality: 65 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2022, values: { co2_per_capita: 6.5,  renewables_share: 24.5, forest_coverage: 40.6, air_quality: 68 } },
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2022, values: { co2_per_capita: 9.5,  renewables_share: 13.1, forest_coverage: 34.1, air_quality: 72 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2022, values: { co2_per_capita: 8.8,  renewables_share: 17.2, forest_coverage: 30.7, air_quality: 65 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2022, values: { co2_per_capita: 5.3,  renewables_share: 18.4, forest_coverage: 22.9, air_quality: 68 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2022, values: { co2_per_capita: 7.4,  renewables_share: 21.3, forest_coverage: 36.7, air_quality: 60 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2022, values: { co2_per_capita: 2.1,  renewables_share: 15.8, forest_coverage: 12.6, air_quality: 62 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2022, values: { co2_per_capita: 5.8,  renewables_share: 4.8,  forest_coverage: 42.7, air_quality: 70 } },
    // ── Amérique du Nord ────────────────────────────────────────────────────
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2022, values: { co2_per_capita: 13.6, renewables_share: 67.5, forest_coverage: 38.2, air_quality: 88 } },
    { geoCode: 'US', geoName: 'United States',  dataYear: 2022, values: { co2_per_capita: 14.9, renewables_share: 20.7, forest_coverage: 33.9, air_quality: 76 } },
    // ── Amérique Centrale et Caraïbes ───────────────────────────────────────
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2022, values: { co2_per_capita: 3.5,  renewables_share: 28.4, forest_coverage: 32.9, air_quality: 68 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2022, values: { co2_per_capita: 1.1,  renewables_share: 69.5, forest_coverage: 33.0, air_quality: 55 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2022, values: { co2_per_capita: 1.0,  renewables_share: 72.5, forest_coverage: 38.3, air_quality: 58 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2022, values: { co2_per_capita: 1.0,  renewables_share: 74.0, forest_coverage: 12.8, air_quality: 56 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2022, values: { co2_per_capita: 0.8,  renewables_share: 70.5, forest_coverage: 25.9, air_quality: 60 } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2022, values: { co2_per_capita: 1.7,  renewables_share: 98.5, forest_coverage: 59.0, air_quality: 78 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2022, values: { co2_per_capita: 2.4,  renewables_share: 70.8, forest_coverage: 56.6, air_quality: 72 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2022, values: { co2_per_capita: 1.9,  renewables_share: 5.2,  forest_coverage: 32.1, air_quality: 72 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2022, values: { co2_per_capita: 2.2, renewables_share: 16.5, forest_coverage: 43.6, air_quality: 62 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2022, values: { co2_per_capita: 2.5,  renewables_share: 12.0, forest_coverage: 31.1, air_quality: 68 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2022, values: { co2_per_capita: 22.4, renewables_share: 0.5, forest_coverage: 44.1, air_quality: 70 } },
    // ── Amérique du Sud ─────────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2022, values: { co2_per_capita: 2.1,  renewables_share: 83.5, forest_coverage: 59.4, air_quality: 75 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2022, values: { co2_per_capita: 3.7,  renewables_share: 29.0, forest_coverage: 10.2, air_quality: 80 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2022, values: { co2_per_capita: 4.3,  renewables_share: 51.2, forest_coverage: 22.0, air_quality: 78 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2022, values: { co2_per_capita: 1.8,  renewables_share: 68.0, forest_coverage: 55.7, air_quality: 70 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2022, values: { co2_per_capita: 1.6,  renewables_share: 59.0, forest_coverage: 57.8, air_quality: 62 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2022, values: { co2_per_capita: 2.3,  renewables_share: 78.5, forest_coverage: 50.0, air_quality: 65 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2022, values: { co2_per_capita: 3.5,  renewables_share: 63.0, forest_coverage: 52.4, air_quality: 62 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2022, values: { co2_per_capita: 1.8,  renewables_share: 38.5, forest_coverage: 49.1, air_quality: 58 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2022, values: { co2_per_capita: 1.2,  renewables_share: 100.0, forest_coverage: 38.6, air_quality: 68 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2022, values: { co2_per_capita: 2.0,  renewables_share: 94.5, forest_coverage: 10.5, air_quality: 82 } },
    // ── Asie de l'Est ───────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2022, values: { co2_per_capita: 8.5,  renewables_share: 21.7, forest_coverage: 68.4, air_quality: 70 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2022, values: { co2_per_capita: 11.4, renewables_share: 8.2,  forest_coverage: 63.4, air_quality: 55 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2022, values: { co2_per_capita: 12.0, renewables_share: 6.0,  forest_coverage: 60.7, air_quality: 58 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2022, values: { co2_per_capita: 8.1,  renewables_share: 29.0, forest_coverage: 22.0, air_quality: 35 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2022, values: { co2_per_capita: 7.1,  renewables_share: 8.5,  forest_coverage: 8.2,  air_quality: 30 } },
    // ── Asie du Sud-Est ─────────────────────────────────────────────────────
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2022, values: { co2_per_capita: 7.4,  renewables_share: 3.0,  forest_coverage: 22.9, air_quality: 72 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2022, values: { co2_per_capita: 3.7,  renewables_share: 13.0, forest_coverage: 37.1, air_quality: 52 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2022, values: { co2_per_capita: 2.7,  renewables_share: 41.6, forest_coverage: 47.6, air_quality: 45 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2022, values: { co2_per_capita: 2.0,  renewables_share: 16.0, forest_coverage: 49.9, air_quality: 55 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2022, values: { co2_per_capita: 1.3,  renewables_share: 28.1, forest_coverage: 27.4, air_quality: 60 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2022, values: { co2_per_capita: 7.6,  renewables_share: 22.0, forest_coverage: 58.2, air_quality: 58 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2022, values: { co2_per_capita: 0.6,  renewables_share: 50.5, forest_coverage: 42.2, air_quality: 42 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2022, values: { co2_per_capita: 0.6,  renewables_share: 55.0, forest_coverage: 46.3, air_quality: 40 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2022, values: { co2_per_capita: 0.7,  renewables_share: 82.0, forest_coverage: 58.0, air_quality: 42 } },
    // ── Asie du Sud ─────────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2022, values: { co2_per_capita: 1.9,  renewables_share: 22.1, forest_coverage: 23.7, air_quality: 25 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2022, values: { co2_per_capita: 0.5,  renewables_share: 2.5,  forest_coverage: 14.0, air_quality: 20 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2022, values: { co2_per_capita: 0.9,  renewables_share: 32.5, forest_coverage: 5.0,  air_quality: 25 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2022, values: { co2_per_capita: 0.9,  renewables_share: 52.0, forest_coverage: 29.7, air_quality: 55 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2022, values: { co2_per_capita: 0.4,  renewables_share: 99.9, forest_coverage: 25.4, air_quality: 28 } },
    // ── Asie Centrale ───────────────────────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2022, values: { co2_per_capita: 13.5, renewables_share: 4.0,  forest_coverage: 1.2,  air_quality: 58 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2022, values: { co2_per_capita: 3.4,  renewables_share: 10.5, forest_coverage: 7.7,  air_quality: 40 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2022, values: { co2_per_capita: 12.5, renewables_share: 0.1,  forest_coverage: 8.8,  air_quality: 45 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2022, values: { co2_per_capita: 1.6,  renewables_share: 88.0, forest_coverage: 3.3,  air_quality: 48 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2022, values: { co2_per_capita: 0.6,  renewables_share: 96.0, forest_coverage: 2.9,  air_quality: 45 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2022, values: { co2_per_capita: 2.8,  renewables_share: 78.5, forest_coverage: 40.6, air_quality: 68 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2022, values: { co2_per_capita: 2.3,  renewables_share: 33.5, forest_coverage: 11.2, air_quality: 60 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2022, values: { co2_per_capita: 3.7,  renewables_share: 7.8,  forest_coverage: 14.7, air_quality: 55 } },
    // ── Ex-URSS (Europe) ────────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2022, values: { co2_per_capita: 11.0, renewables_share: 19.5, forest_coverage: 49.8, air_quality: 68 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2022, values: { co2_per_capita: 4.1,  renewables_share: 13.5, forest_coverage: 17.6, air_quality: 70 } },
    // ── Moyen-Orient ────────────────────────────────────────────────────────
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2022, values: { co2_per_capita: 14.2, renewables_share: 3.0,  forest_coverage: 1.0,  air_quality: 55 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2022, values: { co2_per_capita: 7.4,  renewables_share: 6.3,  forest_coverage: 6.8,  air_quality: 55 } },
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2022, values: { co2_per_capita: 6.6,  renewables_share: 8.0,  forest_coverage: 7.4,  air_quality: 72 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2022, values: { co2_per_capita: 4.1,  renewables_share: 40.5, forest_coverage: 27.6, air_quality: 68 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2022, values: { co2_per_capita: 20.7, renewables_share: 4.5, forest_coverage: 3.8, air_quality: 58 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2022, values: { co2_per_capita: 35.6, renewables_share: 0.5,  forest_coverage: 0.0,  air_quality: 55 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2022, values: { co2_per_capita: 22.6, renewables_share: 1.0,  forest_coverage: 0.4,  air_quality: 52 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2022, values: { co2_per_capita: 21.5, renewables_share: 0.2,  forest_coverage: 0.7,  air_quality: 50 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2022, values: { co2_per_capita: 15.7, renewables_share: 1.5,  forest_coverage: 0.0,  air_quality: 56 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2022, values: { co2_per_capita: 2.4,  renewables_share: 20.0, forest_coverage: 1.1,  air_quality: 62 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2022, values: { co2_per_capita: 3.5,  renewables_share: 7.0,  forest_coverage: 13.4, air_quality: 55 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2022, values: { co2_per_capita: 4.0,  renewables_share: 4.5,  forest_coverage: 1.9,  air_quality: 38 } },
    // ── Océanie ─────────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2022, values: { co2_per_capita: 14.7, renewables_share: 29.7, forest_coverage: 17.0, air_quality: 90 } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2022, values: { co2_per_capita: 7.2,  renewables_share: 82.7, forest_coverage: 37.8, air_quality: 96 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2022, values: { co2_per_capita: 0.5, renewables_share: 32.0, forest_coverage: 74.1, air_quality: 55 } },
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2022, values: { co2_per_capita: 1.4,  renewables_share: 54.0, forest_coverage: 55.7, air_quality: 80 } },
    // ── Afrique du Nord ─────────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2022, values: { co2_per_capita: 2.2,  renewables_share: 12.5, forest_coverage: 0.1,  air_quality: 38 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2022, values: { co2_per_capita: 1.6,  renewables_share: 32.5, forest_coverage: 11.5, air_quality: 62 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2022, values: { co2_per_capita: 3.7,  renewables_share: 1.2,  forest_coverage: 1.6,  air_quality: 55 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2022, values: { co2_per_capita: 2.6,  renewables_share: 5.5,  forest_coverage: 6.7,  air_quality: 60 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2022, values: { co2_per_capita: 8.5,  renewables_share: 0.5,  forest_coverage: 0.1,  air_quality: 50 } },
    // ── Afrique de l'Ouest ──────────────────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2022, values: { co2_per_capita: 0.6,  renewables_share: 18.0, forest_coverage: 24.7, air_quality: 40 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2022, values: { co2_per_capita: 0.6,  renewables_share: 37.5, forest_coverage: 35.0, air_quality: 55 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2022, values: { co2_per_capita: 0.4,  renewables_share: 32.0, forest_coverage: 8.9,  air_quality: 50 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2022, values: { co2_per_capita: 0.6,  renewables_share: 18.0, forest_coverage: 43.0, air_quality: 48 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2022, values: { co2_per_capita: 0.1,  renewables_share: 37.0, forest_coverage: 3.8,  air_quality: 38 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2022, values: { co2_per_capita: 0.2,  renewables_share: 18.5, forest_coverage: 19.2, air_quality: 40 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2022, values: { co2_per_capita: 0.1,  renewables_share: 14.0, forest_coverage: 1.0,  air_quality: 35 } },
    // ── Afrique de l'Est ────────────────────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2022, values: { co2_per_capita: 0.4,  renewables_share: 80.2, forest_coverage: 6.1,  air_quality: 65 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2022, values: { co2_per_capita: 0.1,  renewables_share: 97.5, forest_coverage: 12.6, air_quality: 68 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2022, values: { co2_per_capita: 0.2,  renewables_share: 52.0, forest_coverage: 48.4, air_quality: 55 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2022, values: { co2_per_capita: 0.1,  renewables_share: 88.0, forest_coverage: 9.7,  air_quality: 50 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2022, values: { co2_per_capita: 0.1,  renewables_share: 48.0, forest_coverage: 18.4, air_quality: 60 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2022, values: { co2_per_capita: 0.1,  renewables_share: 57.0, forest_coverage: 21.4, air_quality: 62 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2022, values: { co2_per_capita: 0.2,  renewables_share: 75.0, forest_coverage: 35.5, air_quality: 50 } },
    { geoCode: 'SD', geoName: 'Sudan',          dataYear: 2022, values: { co2_per_capita: 0.4,  renewables_share: 55.0, forest_coverage: 10.0, air_quality: 35 } },
    // ── Afrique Centrale ────────────────────────────────────────────────────
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2022, values: { co2_per_capita: 0.04, renewables_share: 98.0, forest_coverage: 67.3, air_quality: 45 } },
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2022, values: { co2_per_capita: 0.3,  renewables_share: 71.0, forest_coverage: 39.8, air_quality: 48 } },
    { geoCode: 'CG', geoName: 'Congo',          dataYear: 2022, values: { co2_per_capita: 0.6,  renewables_share: 67.0, forest_coverage: 65.4, air_quality: 50 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2022, values: { co2_per_capita: 2.5,  renewables_share: 55.0, forest_coverage: 89.3, air_quality: 58 } },
    // ── Afrique Australe ────────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2022, values: { co2_per_capita: 6.8,  renewables_share: 11.9, forest_coverage: 7.6,  air_quality: 65 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2022, values: { co2_per_capita: 2.8,  renewables_share: 2.0,  forest_coverage: 19.8, air_quality: 68 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2022, values: { co2_per_capita: 1.6,  renewables_share: 39.0, forest_coverage: 8.0,  air_quality: 72 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2022, values: { co2_per_capita: 0.3,  renewables_share: 85.0, forest_coverage: 59.8, air_quality: 55 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2022, values: { co2_per_capita: 0.7,  renewables_share: 40.0, forest_coverage: 36.4, air_quality: 52 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2022, values: { co2_per_capita: 0.5,  renewables_share: 65.0, forest_coverage: 46.3, air_quality: 48 } },
  ],
  seedDataPrev: [
    // ── Europe du Nord ──────────────────────────────────────────────────────
    // Sources: CO₂ → World Bank EN.GHG.CO2.PC.CE.AR5 (2021), Renewables → World Bank EG.ELC.RNEW.ZS (2021),
    //          Forest → World Bank AG.LND.FRST.ZS (2021), Air quality → kept from editorial index (IQAir-based /100)
    //          Taiwan: not in World Bank — values from Bureau of Energy (MOEA) & Forestry Bureau
    //          Iceland renewables: null in WB — Orkustofnun reports ~100%. Ethiopia renewables: WB 2020 value (95.4%)
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2021, values: { co2_per_capita: 8.5,  renewables_share: 100.0, forest_coverage: 0.5,  air_quality: 97 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2021, values: { co2_per_capita: 8.2,  renewables_share: 99.1,  forest_coverage: 33.5, air_quality: 95 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2021, values: { co2_per_capita: 3.9,  renewables_share: 67.4,  forest_coverage: 68.7, air_quality: 94 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2021, values: { co2_per_capita: 7.1,  renewables_share: 52.9,  forest_coverage: 73.7, air_quality: 95 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2021, values: { co2_per_capita: 5.0,  renewables_share: 79.0,  forest_coverage: 15.7, air_quality: 91 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2021, values: { co2_per_capita: 8.5,  renewables_share: 27.5,  forest_coverage: 53.1, air_quality: 87 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2021, values: { co2_per_capita: 3.6,  renewables_share: 52.5,  forest_coverage: 54.5, air_quality: 86 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2021, values: { co2_per_capita: 4.3,  renewables_share: 36.8,  forest_coverage: 34.8, air_quality: 81 } },
    // ── Europe de l'Ouest ───────────────────────────────────────────────────
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2021, values: { co2_per_capita: 7.4,  renewables_share: 79.8,  forest_coverage: 47.2, air_quality: 86 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2021, values: { co2_per_capita: 4.3,  renewables_share: 68.1,  forest_coverage: 32.2, air_quality: 87 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2021, values: { co2_per_capita: 4.7,  renewables_share: 22.8,  forest_coverage: 32.2, air_quality: 81 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2021, values: { co2_per_capita: 8.1,  renewables_share: 39.8,  forest_coverage: 32.7, air_quality: 79 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2021, values: { co2_per_capita: 8.3,  renewables_share: 33.1,  forest_coverage: 11.0, air_quality: 84 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2021, values: { co2_per_capita: 8.3,  renewables_share: 23.5,  forest_coverage: 22.6, air_quality: 77 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2021, values: { co2_per_capita: 13.1, renewables_share: 89.0,  forest_coverage: 34.5, air_quality: 83 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2021, values: { co2_per_capita: 7.1,  renewables_share: 37.2,  forest_coverage: 11.4, air_quality: 93 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2021, values: { co2_per_capita: 5.0,  renewables_share: 40.2,  forest_coverage: 13.2, air_quality: 77 } },
    // ── Europe du Sud ───────────────────────────────────────────────────────
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2021, values: { co2_per_capita: 3.8,  renewables_share: 64.9,  forest_coverage: 36.2, air_quality: 84 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2021, values: { co2_per_capita: 4.9,  renewables_share: 47.0,  forest_coverage: 37.2, air_quality: 81 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2021, values: { co2_per_capita: 5.6,  renewables_share: 41.0,  forest_coverage: 32.5, air_quality: 74 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2021, values: { co2_per_capita: 5.1,  renewables_share: 40.6,  forest_coverage: 30.3, air_quality: 79 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2021, values: { co2_per_capita: 3.5,  renewables_share: 11.0,  forest_coverage: 1.1,  air_quality: 79 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2021, values: { co2_per_capita: 5.8,  renewables_share: 15.0,  forest_coverage: 18.7, air_quality: 81 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2021, values: { co2_per_capita: 6.3,  renewables_share: 34.2,  forest_coverage: 61.5, air_quality: 77 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2021, values: { co2_per_capita: 4.5,  renewables_share: 69.9,  forest_coverage: 34.7, air_quality: 77 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2021, values: { co2_per_capita: 6.0, renewables_share: 35.0, forest_coverage: 42.7, air_quality: 50 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2021, values: { co2_per_capita: 7.1,  renewables_share: 24.5,  forest_coverage: 31.1, air_quality: 53 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2021, values: { co2_per_capita: 3.8,  renewables_share: 55.0,  forest_coverage: 61.5, air_quality: 64 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2021, values: { co2_per_capita: 3.7, renewables_share: 26.5, forest_coverage: 39.6, air_quality: 50 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2021, values: { co2_per_capita: 1.5,  renewables_share: 100.0, forest_coverage: 28.8, air_quality: 61 } },
    // ── Europe de l'Est ─────────────────────────────────────────────────────
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2021, values: { co2_per_capita: 4.2,  renewables_share: 44.9,  forest_coverage: 30.1, air_quality: 64 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2021, values: { co2_per_capita: 6.7,  renewables_share: 23.6,  forest_coverage: 40.1, air_quality: 67 } },
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2021, values: { co2_per_capita: 9.5,  renewables_share: 14.0,  forest_coverage: 34.7, air_quality: 71 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2021, values: { co2_per_capita: 8.8,  renewables_share: 17.5,  forest_coverage: 31.0, air_quality: 63 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2021, values: { co2_per_capita: 5.3,  renewables_share: 19.1,  forest_coverage: 22.5, air_quality: 66 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2021, values: { co2_per_capita: 7.0,  renewables_share: 22.2,  forest_coverage: 36.0, air_quality: 59 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2021, values: { co2_per_capita: 2.0,  renewables_share: 14.5,  forest_coverage: 12.6, air_quality: 61 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2021, values: { co2_per_capita: 5.7,  renewables_share: 4.5,   forest_coverage: 42.5, air_quality: 69 } },
    // ── Amérique du Nord ────────────────────────────────────────────────────
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2021, values: { co2_per_capita: 14.7, renewables_share: 67.0,  forest_coverage: 39.5, air_quality: 87 } },
    { geoCode: 'US', geoName: 'United States',  dataYear: 2021, values: { co2_per_capita: 14.3, renewables_share: 20.3,  forest_coverage: 33.9, air_quality: 75 } },
    // ── Amérique Centrale et Caraïbes ───────────────────────────────────────
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2021, values: { co2_per_capita: 3.5,  renewables_share: 24.4,  forest_coverage: 33.7, air_quality: 67 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2021, values: { co2_per_capita: 1.1,  renewables_share: 67.0,  forest_coverage: 33.5, air_quality: 54 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2021, values: { co2_per_capita: 1.0,  renewables_share: 70.0,  forest_coverage: 39.0, air_quality: 57 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2021, values: { co2_per_capita: 0.9,  renewables_share: 72.0,  forest_coverage: 12.8, air_quality: 55 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2021, values: { co2_per_capita: 0.8,  renewables_share: 68.0,  forest_coverage: 26.4, air_quality: 59 } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2021, values: { co2_per_capita: 1.6,  renewables_share: 98.8,  forest_coverage: 58.9, air_quality: 77 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2021, values: { co2_per_capita: 2.3,  renewables_share: 68.5,  forest_coverage: 57.0, air_quality: 71 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2021, values: { co2_per_capita: 1.8,  renewables_share: 4.8,   forest_coverage: 31.9, air_quality: 71 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2021, values: { co2_per_capita: 2.1, renewables_share: 15.5, forest_coverage: 43.5, air_quality: 61 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2021, values: { co2_per_capita: 2.4,  renewables_share: 11.0,  forest_coverage: 31.1, air_quality: 67 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2021, values: { co2_per_capita: 21.8, renewables_share: 0.4, forest_coverage: 44.1, air_quality: 69 } },
    // ── Amérique du Sud ─────────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2021, values: { co2_per_capita: 2.4,  renewables_share: 77.4,  forest_coverage: 59.3, air_quality: 74 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2021, values: { co2_per_capita: 4.1,  renewables_share: 25.5,  forest_coverage: 10.4, air_quality: 79 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2021, values: { co2_per_capita: 4.6,  renewables_share: 48.1,  forest_coverage: 24.7, air_quality: 77 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2021, values: { co2_per_capita: 1.8,  renewables_share: 75.1,  forest_coverage: 53.1, air_quality: 69 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2021, values: { co2_per_capita: 1.5,  renewables_share: 56.0,  forest_coverage: 57.9, air_quality: 61 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2021, values: { co2_per_capita: 2.2,  renewables_share: 76.5,  forest_coverage: 50.5, air_quality: 64 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2021, values: { co2_per_capita: 3.3,  renewables_share: 65.0,  forest_coverage: 52.8, air_quality: 61 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2021, values: { co2_per_capita: 1.7,  renewables_share: 36.0,  forest_coverage: 49.5, air_quality: 57 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2021, values: { co2_per_capita: 1.1,  renewables_share: 100.0, forest_coverage: 39.0, air_quality: 67 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2021, values: { co2_per_capita: 1.9,  renewables_share: 93.0,  forest_coverage: 10.3, air_quality: 81 } },
    // ── Asie de l'Est ───────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2021, values: { co2_per_capita: 8.6,  renewables_share: 21.1,  forest_coverage: 68.4, air_quality: 69 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2021, values: { co2_per_capita: 12.3, renewables_share: 6.6,   forest_coverage: 64.3, air_quality: 53 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2021, values: { co2_per_capita: 12.3, renewables_share: 5.5,   forest_coverage: 60.7, air_quality: 57 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2021, values: { co2_per_capita: 8.9,  renewables_share: 28.4,  forest_coverage: 23.6, air_quality: 33 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2021, values: { co2_per_capita: 7.5,  renewables_share: 7.0,   forest_coverage: 8.2,  air_quality: 28 } },
    // ── Asie du Sud-Est ─────────────────────────────────────────────────────
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2021, values: { co2_per_capita: 10.2, renewables_share: 4.0,   forest_coverage: 21.4, air_quality: 71 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2021, values: { co2_per_capita: 3.7,  renewables_share: 19.9,  forest_coverage: 38.8, air_quality: 51 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2021, values: { co2_per_capita: 3.4,  renewables_share: 41.2,  forest_coverage: 47.0, air_quality: 44 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2021, values: { co2_per_capita: 2.2,  renewables_share: 15.5,  forest_coverage: 48.4, air_quality: 54 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2021, values: { co2_per_capita: 1.3,  renewables_share: 22.7,  forest_coverage: 24.2, air_quality: 59 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2021, values: { co2_per_capita: 7.4,  renewables_share: 20.5,  forest_coverage: 58.5, air_quality: 57 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2021, values: { co2_per_capita: 0.5,  renewables_share: 49.0,  forest_coverage: 42.5, air_quality: 41 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2021, values: { co2_per_capita: 0.5,  renewables_share: 52.0,  forest_coverage: 47.0, air_quality: 39 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2021, values: { co2_per_capita: 0.6,  renewables_share: 80.0,  forest_coverage: 58.5, air_quality: 41 } },
    // ── Asie du Sud ─────────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2021, values: { co2_per_capita: 1.8,  renewables_share: 19.1,  forest_coverage: 24.4, air_quality: 23 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2021, values: { co2_per_capita: 0.7,  renewables_share: 1.5,   forest_coverage: 14.5, air_quality: 19 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2021, values: { co2_per_capita: 1.0,  renewables_share: 28.3,  forest_coverage: 4.8,  air_quality: 24 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2021, values: { co2_per_capita: 0.8,  renewables_share: 50.0,  forest_coverage: 29.7, air_quality: 54 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2021, values: { co2_per_capita: 0.4,  renewables_share: 99.9,  forest_coverage: 25.4, air_quality: 27 } },
    // ── Asie Centrale ───────────────────────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2021, values: { co2_per_capita: 12.3, renewables_share: 11.0,  forest_coverage: 1.3,  air_quality: 57 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2021, values: { co2_per_capita: 3.3,  renewables_share: 9.5,   forest_coverage: 7.7,  air_quality: 39 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2021, values: { co2_per_capita: 12.2, renewables_share: 0.1,   forest_coverage: 8.8,  air_quality: 44 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2021, values: { co2_per_capita: 1.5,  renewables_share: 86.0,  forest_coverage: 3.3,  air_quality: 47 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2021, values: { co2_per_capita: 0.5,  renewables_share: 95.0,  forest_coverage: 2.9,  air_quality: 44 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2021, values: { co2_per_capita: 2.7,  renewables_share: 76.0,  forest_coverage: 40.6, air_quality: 67 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2021, values: { co2_per_capita: 2.2,  renewables_share: 31.0,  forest_coverage: 11.2, air_quality: 59 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2021, values: { co2_per_capita: 3.5,  renewables_share: 7.0,   forest_coverage: 14.7, air_quality: 54 } },
    // ── Ex-URSS (Europe) ────────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2021, values: { co2_per_capita: 13.4, renewables_share: 19.2,  forest_coverage: 49.8, air_quality: 67 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2021, values: { co2_per_capita: 4.4,  renewables_share: 12.0,  forest_coverage: 16.7, air_quality: 70 } },
    // ── Moyen-Orient ────────────────────────────────────────────────────────
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2021, values: { co2_per_capita: 19.2, renewables_share: 0.1,   forest_coverage: 0.5,  air_quality: 53 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2021, values: { co2_per_capita: 8.9,  renewables_share: 4.2,   forest_coverage: 6.6,  air_quality: 54 } },
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2021, values: { co2_per_capita: 6.5,  renewables_share: 7.6,   forest_coverage: 6.5,  air_quality: 70 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2021, values: { co2_per_capita: 5.5,  renewables_share: 35.4,  forest_coverage: 29.1, air_quality: 67 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2021, values: { co2_per_capita: 21.8, renewables_share: 3.5, forest_coverage: 3.8, air_quality: 57 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2021, values: { co2_per_capita: 37.0, renewables_share: 0.3,   forest_coverage: 0.0,  air_quality: 54 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2021, values: { co2_per_capita: 23.5, renewables_share: 0.8,   forest_coverage: 0.4,  air_quality: 50 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2021, values: { co2_per_capita: 22.0, renewables_share: 0.1,   forest_coverage: 0.7,  air_quality: 48 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2021, values: { co2_per_capita: 16.2, renewables_share: 1.0,   forest_coverage: 0.0,  air_quality: 55 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2021, values: { co2_per_capita: 2.3,  renewables_share: 17.0,  forest_coverage: 1.1,  air_quality: 61 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2021, values: { co2_per_capita: 3.3,  renewables_share: 6.0,   forest_coverage: 13.4, air_quality: 54 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2021, values: { co2_per_capita: 3.8,  renewables_share: 4.0,   forest_coverage: 1.9,  air_quality: 37 } },
    // ── Océanie ─────────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2021, values: { co2_per_capita: 15.0, renewables_share: 26.7,  forest_coverage: 17.4, air_quality: 89 } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2021, values: { co2_per_capita: 6.8,  renewables_share: 81.4,  forest_coverage: 37.6, air_quality: 95 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2021, values: { co2_per_capita: 0.5, renewables_share: 30.0, forest_coverage: 74.5, air_quality: 54 } },
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2021, values: { co2_per_capita: 1.3,  renewables_share: 52.0,  forest_coverage: 55.7, air_quality: 79 } },
    // ── Afrique du Nord ─────────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2021, values: { co2_per_capita: 2.4,  renewables_share: 12.2,  forest_coverage: 0.0,  air_quality: 37 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2021, values: { co2_per_capita: 2.0,  renewables_share: 19.3,  forest_coverage: 12.9, air_quality: 61 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2021, values: { co2_per_capita: 3.5,  renewables_share: 1.0,   forest_coverage: 1.6,  air_quality: 54 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2021, values: { co2_per_capita: 2.5,  renewables_share: 4.5,   forest_coverage: 6.7,  air_quality: 59 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2021, values: { co2_per_capita: 8.2,  renewables_share: 0.3,   forest_coverage: 0.1,  air_quality: 49 } },
    // ── Afrique de l'Ouest ──────────────────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2021, values: { co2_per_capita: 0.6,  renewables_share: 23.8,  forest_coverage: 23.6, air_quality: 39 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2021, values: { co2_per_capita: 0.6,  renewables_share: 35.5,  forest_coverage: 35.5, air_quality: 54 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2021, values: { co2_per_capita: 0.4,  renewables_share: 30.0,  forest_coverage: 9.2,  air_quality: 49 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2021, values: { co2_per_capita: 0.6,  renewables_share: 16.0,  forest_coverage: 43.3, air_quality: 47 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2021, values: { co2_per_capita: 0.1,  renewables_share: 35.0,  forest_coverage: 3.9,  air_quality: 37 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2021, values: { co2_per_capita: 0.2,  renewables_share: 17.0,  forest_coverage: 19.5, air_quality: 39 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2021, values: { co2_per_capita: 0.1,  renewables_share: 13.0,  forest_coverage: 1.0,  air_quality: 34 } },
    // ── Afrique de l'Est ────────────────────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2021, values: { co2_per_capita: 0.4,  renewables_share: 78.1,  forest_coverage: 6.2,  air_quality: 64 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2021, values: { co2_per_capita: 0.2,  renewables_share: 95.4,  forest_coverage: 15.1, air_quality: 67 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2021, values: { co2_per_capita: 0.2,  renewables_share: 50.0,  forest_coverage: 48.8, air_quality: 54 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2021, values: { co2_per_capita: 0.1,  renewables_share: 86.0,  forest_coverage: 10.0, air_quality: 49 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2021, values: { co2_per_capita: 0.1,  renewables_share: 46.0,  forest_coverage: 18.1, air_quality: 59 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2021, values: { co2_per_capita: 0.1,  renewables_share: 55.0,  forest_coverage: 21.8, air_quality: 61 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2021, values: { co2_per_capita: 0.2,  renewables_share: 73.0,  forest_coverage: 36.0, air_quality: 49 } },
    { geoCode: 'SD', geoName: 'Sudan',          dataYear: 2021, values: { co2_per_capita: 0.4,  renewables_share: 53.0,  forest_coverage: 10.3, air_quality: 34 } },
    // ── Afrique Centrale ────────────────────────────────────────────────────
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2021, values: { co2_per_capita: 0.04, renewables_share: 97.5,  forest_coverage: 67.7, air_quality: 44 } },
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2021, values: { co2_per_capita: 0.3,  renewables_share: 69.0,  forest_coverage: 40.2, air_quality: 47 } },
    { geoCode: 'CG', geoName: 'Congo',          dataYear: 2021, values: { co2_per_capita: 0.6,  renewables_share: 65.0,  forest_coverage: 65.8, air_quality: 49 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2021, values: { co2_per_capita: 2.4,  renewables_share: 53.0,  forest_coverage: 89.5, air_quality: 57 } },
    // ── Afrique Australe ────────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2021, values: { co2_per_capita: 7.3,  renewables_share: 6.4,   forest_coverage: 14.0, air_quality: 64 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2021, values: { co2_per_capita: 2.7,  renewables_share: 1.5,   forest_coverage: 19.8, air_quality: 67 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2021, values: { co2_per_capita: 1.5,  renewables_share: 37.0,  forest_coverage: 8.0,  air_quality: 71 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2021, values: { co2_per_capita: 0.3,  renewables_share: 83.0,  forest_coverage: 60.2, air_quality: 54 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2021, values: { co2_per_capita: 0.7,  renewables_share: 38.0,  forest_coverage: 36.8, air_quality: 51 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2021, values: { co2_per_capita: 0.5,  renewables_share: 63.0,  forest_coverage: 46.7, air_quality: 47 } },
  ],
};

export default ecologyModule;
