import type { DomainModule } from '@/lib/domains/types';

const climateRiskModule: DomainModule = {
  definition: {
    id: 'climate-risk',
    label: { fr: 'Risque climatique', en: 'Climate Risk', es: 'Riesgo climático' },
    description: {
      fr: 'Exposition aux risques climatiques : vulnérabilité, préparation, catastrophes naturelles et adaptation au changement climatique.',
      en: 'Exposure to climate risks: vulnerability, readiness, natural disasters and climate change adaptation.',
      es: 'Exposición a riesgos climáticos: vulnerabilidad, preparación, desastres naturales y adaptación al cambio climático.',
    },
    icon: '🌡️',
    group: 'environment',
    active: true,
    seedSources: [
      'https://gain.nd.edu/our-work/country-index/',
      'https://www.emdat.be/',
      'https://www.climatepolicyinitiative.org/',
    ],
    indicators: [
      {
        id: 'nd_gain_readiness',
        label: { fr: 'Préparation climatique', en: 'Climate readiness', es: 'Preparación climática' },
        unit: 'index',
        unitLabel: { fr: 'score', en: 'score', es: 'score' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 0.65, good: 0.50, fair: 0.38, poor: 0.25 },
        minValue: 0,
        maxValue: 1,
      },
      {
        id: 'climate_vulnerability',
        label: { fr: 'Vulnérabilité climatique', en: 'Climate vulnerability', es: 'Vulnerabilidad climática' },
        unit: 'index',
        unitLabel: { fr: 'score', en: 'score', es: 'score' },
        direction: 'lower_is_better',
        weight: 3,
        thresholds: { excellent: 0.30, good: 0.38, fair: 0.45, poor: 0.55 },
        minValue: 0,
        maxValue: 1,
      },
      {
        id: 'natural_disaster_deaths',
        label: { fr: 'Décès catastrophes naturelles', en: 'Natural disaster deaths', es: 'Muertes por desastres naturales' },
        unit: 'ratio',
        unitLabel: { fr: 'décès/M hab.', en: 'deaths/M pop.', es: 'muertes/M hab.' },
        direction: 'lower_is_better',
        weight: 2,
        thresholds: { excellent: 0.5, good: 2, fair: 8, poor: 25 },
        minValue: 0,
        maxValue: 100,
      },
      {
        id: 'climate_adaptation_spending',
        label: { fr: 'Dépenses adaptation climat', en: 'Climate adaptation spending', es: 'Gasto en adaptación climática' },
        unit: 'percent',
        unitLabel: { fr: '% PIB', en: '% GDP', es: '% PIB' },
        direction: 'higher_is_better',
        weight: 2,
        thresholds: { excellent: 0.5, good: 0.3, fair: 0.15, poor: 0.05 },
        minValue: 0,
        maxValue: 3,
      },
    ],
  },
  seedData: [
    // ── Europe ──────────────────────────────────────────────────────────────
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2023, values: { nd_gain_readiness: 0.74, climate_vulnerability: 0.27, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.42 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2023, values: { nd_gain_readiness: 0.78, climate_vulnerability: 0.28, natural_disaster_deaths: 0.1,  climate_adaptation_spending: 0.45 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2023, values: { nd_gain_readiness: 0.75, climate_vulnerability: 0.29, natural_disaster_deaths: 0.1,  climate_adaptation_spending: 0.38 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2023, values: { nd_gain_readiness: 0.76, climate_vulnerability: 0.29, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.36 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2023, values: { nd_gain_readiness: 0.68, climate_vulnerability: 0.31, natural_disaster_deaths: 0.4,  climate_adaptation_spending: 0.30 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2023, values: { nd_gain_readiness: 0.77, climate_vulnerability: 0.30, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.40 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2023, values: { nd_gain_readiness: 0.76, climate_vulnerability: 0.30, natural_disaster_deaths: 0.2,  climate_adaptation_spending: 0.38 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2023, values: { nd_gain_readiness: 0.58, climate_vulnerability: 0.34, natural_disaster_deaths: 1.2,  climate_adaptation_spending: 0.22 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2023, values: { nd_gain_readiness: 0.52, climate_vulnerability: 0.36, natural_disaster_deaths: 0.3,  climate_adaptation_spending: 0.18 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2023, values: { nd_gain_readiness: 0.45, climate_vulnerability: 0.40, natural_disaster_deaths: 0.8,  climate_adaptation_spending: 0.12 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2023, values: { nd_gain_readiness: 0.60, climate_vulnerability: 0.33, natural_disaster_deaths: 0.5,  climate_adaptation_spending: 0.20 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2023, values: { nd_gain_readiness: 0.69, climate_vulnerability: 0.31, natural_disaster_deaths: 0.1,  climate_adaptation_spending: 0.28 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2023, values: { nd_gain_readiness: 0.57, climate_vulnerability: 0.35, natural_disaster_deaths: 0.8,  climate_adaptation_spending: 0.22 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2023, values: { nd_gain_readiness: 0.67, climate_vulnerability: 0.32, natural_disaster_deaths: 0.3,  climate_adaptation_spending: 0.35 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2023, values: { nd_gain_readiness: 0.55, climate_vulnerability: 0.35, natural_disaster_deaths: 0.6,  climate_adaptation_spending: 0.18 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2023, values: { nd_gain_readiness: 0.72, climate_vulnerability: 0.31, natural_disaster_deaths: 0.1,  climate_adaptation_spending: 0.42 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2023, values: { nd_gain_readiness: 0.62, climate_vulnerability: 0.33, natural_disaster_deaths: 0.2,  climate_adaptation_spending: 0.25 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2023, values: { nd_gain_readiness: 0.70, climate_vulnerability: 0.31, natural_disaster_deaths: 0.2,  climate_adaptation_spending: 0.32 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2023, values: { nd_gain_readiness: 0.48, climate_vulnerability: 0.37, natural_disaster_deaths: 1.5,  climate_adaptation_spending: 0.14 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2023, values: { nd_gain_readiness: 0.50, climate_vulnerability: 0.37, natural_disaster_deaths: 0.2,  climate_adaptation_spending: 0.15 } },
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2023, values: { nd_gain_readiness: 0.56, climate_vulnerability: 0.35, natural_disaster_deaths: 0.2,  climate_adaptation_spending: 0.20 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2023, values: { nd_gain_readiness: 0.52, climate_vulnerability: 0.36, natural_disaster_deaths: 0.3,  climate_adaptation_spending: 0.16 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2023, values: { nd_gain_readiness: 0.49, climate_vulnerability: 0.38, natural_disaster_deaths: 0.4,  climate_adaptation_spending: 0.14 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2023, values: { nd_gain_readiness: 0.44, climate_vulnerability: 0.40, natural_disaster_deaths: 0.5,  climate_adaptation_spending: 0.10 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2023, values: { nd_gain_readiness: 0.73, climate_vulnerability: 0.29, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.35 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2023, values: { nd_gain_readiness: 0.60, climate_vulnerability: 0.33, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.22 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2023, values: { nd_gain_readiness: 0.55, climate_vulnerability: 0.34, natural_disaster_deaths: 0.1,  climate_adaptation_spending: 0.18 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2023, values: { nd_gain_readiness: 0.53, climate_vulnerability: 0.35, natural_disaster_deaths: 0.1,  climate_adaptation_spending: 0.16 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2023, values: { nd_gain_readiness: 0.58, climate_vulnerability: 0.33, natural_disaster_deaths: 0.3,  climate_adaptation_spending: 0.20 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2023, values: { nd_gain_readiness: 0.42, climate_vulnerability: 0.41, natural_disaster_deaths: 0.6,  climate_adaptation_spending: 0.08 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2023, values: { nd_gain_readiness: 0.38, climate_vulnerability: 0.43, natural_disaster_deaths: 0.8,  climate_adaptation_spending: 0.06 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2023, values: { nd_gain_readiness: 0.36, climate_vulnerability: 0.44, natural_disaster_deaths: 0.7,  climate_adaptation_spending: 0.07 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2023, values: { nd_gain_readiness: 0.39, climate_vulnerability: 0.43, natural_disaster_deaths: 0.4,  climate_adaptation_spending: 0.07 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2023, values: { nd_gain_readiness: 0.41, climate_vulnerability: 0.42, natural_disaster_deaths: 0.3,  climate_adaptation_spending: 0.08 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2023, values: { nd_gain_readiness: 0.60, climate_vulnerability: 0.34, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.20 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2023, values: { nd_gain_readiness: 0.55, climate_vulnerability: 0.36, natural_disaster_deaths: 0.1,  climate_adaptation_spending: 0.18 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2023, values: { nd_gain_readiness: 0.32, climate_vulnerability: 0.46, natural_disaster_deaths: 0.5,  climate_adaptation_spending: 0.05 } },

    // ── North America ───────────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',  dataYear: 2023, values: { nd_gain_readiness: 0.65, climate_vulnerability: 0.34, natural_disaster_deaths: 1.5,  climate_adaptation_spending: 0.15 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2023, values: { nd_gain_readiness: 0.71, climate_vulnerability: 0.32, natural_disaster_deaths: 0.4,  climate_adaptation_spending: 0.25 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2023, values: { nd_gain_readiness: 0.40, climate_vulnerability: 0.43, natural_disaster_deaths: 2.5,  climate_adaptation_spending: 0.08 } },

    // ── Central America & Caribbean ─────────────────────────────────────────
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2023, values: { nd_gain_readiness: 0.28, climate_vulnerability: 0.52, natural_disaster_deaths: 4.0,  climate_adaptation_spending: 0.04 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2023, values: { nd_gain_readiness: 0.25, climate_vulnerability: 0.54, natural_disaster_deaths: 6.5,  climate_adaptation_spending: 0.05 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2023, values: { nd_gain_readiness: 0.30, climate_vulnerability: 0.50, natural_disaster_deaths: 3.5,  climate_adaptation_spending: 0.06 } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2023, values: { nd_gain_readiness: 0.48, climate_vulnerability: 0.40, natural_disaster_deaths: 1.0,  climate_adaptation_spending: 0.15 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2023, values: { nd_gain_readiness: 0.42, climate_vulnerability: 0.42, natural_disaster_deaths: 1.2,  climate_adaptation_spending: 0.10 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2023, values: { nd_gain_readiness: 0.38, climate_vulnerability: 0.47, natural_disaster_deaths: 2.0,  climate_adaptation_spending: 0.12 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2023, values: { nd_gain_readiness: 0.44, climate_vulnerability: 0.44, natural_disaster_deaths: 0.8,  climate_adaptation_spending: 0.10 } },
    { geoCode: 'DO', geoName: 'Dominican Republic',  dataYear: 2023, values: { nd_gain_readiness: 0.35, climate_vulnerability: 0.48, natural_disaster_deaths: 3.0,  climate_adaptation_spending: 0.08 } },

    // ── South America ───────────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2023, values: { nd_gain_readiness: 0.40, climate_vulnerability: 0.43, natural_disaster_deaths: 2.0,  climate_adaptation_spending: 0.08 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2023, values: { nd_gain_readiness: 0.38, climate_vulnerability: 0.42, natural_disaster_deaths: 1.2,  climate_adaptation_spending: 0.06 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2023, values: { nd_gain_readiness: 0.52, climate_vulnerability: 0.38, natural_disaster_deaths: 0.8,  climate_adaptation_spending: 0.14 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2023, values: { nd_gain_readiness: 0.36, climate_vulnerability: 0.45, natural_disaster_deaths: 2.5,  climate_adaptation_spending: 0.07 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2023, values: { nd_gain_readiness: 0.34, climate_vulnerability: 0.46, natural_disaster_deaths: 3.0,  climate_adaptation_spending: 0.06 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2023, values: { nd_gain_readiness: 0.22, climate_vulnerability: 0.53, natural_disaster_deaths: 4.0,  climate_adaptation_spending: 0.02 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2023, values: { nd_gain_readiness: 0.33, climate_vulnerability: 0.46, natural_disaster_deaths: 3.2,  climate_adaptation_spending: 0.06 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2023, values: { nd_gain_readiness: 0.50, climate_vulnerability: 0.38, natural_disaster_deaths: 0.5,  climate_adaptation_spending: 0.12 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2023, values: { nd_gain_readiness: 0.30, climate_vulnerability: 0.48, natural_disaster_deaths: 1.5,  climate_adaptation_spending: 0.05 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2023, values: { nd_gain_readiness: 0.26, climate_vulnerability: 0.51, natural_disaster_deaths: 3.5,  climate_adaptation_spending: 0.04 } },

    // ── East Asia ────────────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2023, values: { nd_gain_readiness: 0.66, climate_vulnerability: 0.33, natural_disaster_deaths: 0.8,  climate_adaptation_spending: 0.30 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2023, values: { nd_gain_readiness: 0.64, climate_vulnerability: 0.34, natural_disaster_deaths: 0.5,  climate_adaptation_spending: 0.25 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2023, values: { nd_gain_readiness: 0.42, climate_vulnerability: 0.42, natural_disaster_deaths: 1.8,  climate_adaptation_spending: 0.10 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2023, values: { nd_gain_readiness: 0.62, climate_vulnerability: 0.35, natural_disaster_deaths: 0.6,  climate_adaptation_spending: 0.22 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2023, values: { nd_gain_readiness: 0.32, climate_vulnerability: 0.48, natural_disaster_deaths: 1.5,  climate_adaptation_spending: 0.06 } },

    // ── Southeast Asia ──────────────────────────────────────────────────────
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2023, values: { nd_gain_readiness: 0.73, climate_vulnerability: 0.30, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.35 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2023, values: { nd_gain_readiness: 0.40, climate_vulnerability: 0.44, natural_disaster_deaths: 3.0,  climate_adaptation_spending: 0.10 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2023, values: { nd_gain_readiness: 0.35, climate_vulnerability: 0.48, natural_disaster_deaths: 4.5,  climate_adaptation_spending: 0.12 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2023, values: { nd_gain_readiness: 0.36, climate_vulnerability: 0.46, natural_disaster_deaths: 3.5,  climate_adaptation_spending: 0.08 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2023, values: { nd_gain_readiness: 0.33, climate_vulnerability: 0.50, natural_disaster_deaths: 5.0,  climate_adaptation_spending: 0.10 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2023, values: { nd_gain_readiness: 0.52, climate_vulnerability: 0.39, natural_disaster_deaths: 1.0,  climate_adaptation_spending: 0.14 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2023, values: { nd_gain_readiness: 0.18, climate_vulnerability: 0.58, natural_disaster_deaths: 8.0,  climate_adaptation_spending: 0.03 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2023, values: { nd_gain_readiness: 0.24, climate_vulnerability: 0.54, natural_disaster_deaths: 4.0,  climate_adaptation_spending: 0.06 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2023, values: { nd_gain_readiness: 0.22, climate_vulnerability: 0.55, natural_disaster_deaths: 3.5,  climate_adaptation_spending: 0.05 } },
    { geoCode: 'BN', geoName: 'Brunei',         dataYear: 2023, values: { nd_gain_readiness: 0.55, climate_vulnerability: 0.37, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.12 } },

    // ── South Asia ──────────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2023, values: { nd_gain_readiness: 0.32, climate_vulnerability: 0.50, natural_disaster_deaths: 3.5,  climate_adaptation_spending: 0.08 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2023, values: { nd_gain_readiness: 0.24, climate_vulnerability: 0.55, natural_disaster_deaths: 10.0, climate_adaptation_spending: 0.05 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2023, values: { nd_gain_readiness: 0.25, climate_vulnerability: 0.58, natural_disaster_deaths: 12.0, climate_adaptation_spending: 0.30 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2023, values: { nd_gain_readiness: 0.30, climate_vulnerability: 0.49, natural_disaster_deaths: 4.0,  climate_adaptation_spending: 0.08 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2023, values: { nd_gain_readiness: 0.23, climate_vulnerability: 0.54, natural_disaster_deaths: 7.0,  climate_adaptation_spending: 0.10 } },
    { geoCode: 'AF', geoName: 'Afghanistan',    dataYear: 2023, values: { nd_gain_readiness: 0.12, climate_vulnerability: 0.64, natural_disaster_deaths: 15.0, climate_adaptation_spending: 0.02 } },

    // ── Central Asia ────────────────────────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2023, values: { nd_gain_readiness: 0.40, climate_vulnerability: 0.42, natural_disaster_deaths: 0.8,  climate_adaptation_spending: 0.06 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2023, values: { nd_gain_readiness: 0.30, climate_vulnerability: 0.48, natural_disaster_deaths: 1.0,  climate_adaptation_spending: 0.04 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2023, values: { nd_gain_readiness: 0.25, climate_vulnerability: 0.52, natural_disaster_deaths: 0.5,  climate_adaptation_spending: 0.02 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2023, values: { nd_gain_readiness: 0.28, climate_vulnerability: 0.50, natural_disaster_deaths: 2.0,  climate_adaptation_spending: 0.05 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2023, values: { nd_gain_readiness: 0.22, climate_vulnerability: 0.55, natural_disaster_deaths: 3.5,  climate_adaptation_spending: 0.04 } },

    // ── Middle East ─────────────────────────────────────────────────────────
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2023, values: { nd_gain_readiness: 0.50, climate_vulnerability: 0.40, natural_disaster_deaths: 0.3,  climate_adaptation_spending: 0.10 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2023, values: { nd_gain_readiness: 0.62, climate_vulnerability: 0.36, natural_disaster_deaths: 0.1,  climate_adaptation_spending: 0.18 } },
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2023, values: { nd_gain_readiness: 0.64, climate_vulnerability: 0.34, natural_disaster_deaths: 0.1,  climate_adaptation_spending: 0.22 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2023, values: { nd_gain_readiness: 0.44, climate_vulnerability: 0.41, natural_disaster_deaths: 2.5,  climate_adaptation_spending: 0.10 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2023, values: { nd_gain_readiness: 0.30, climate_vulnerability: 0.48, natural_disaster_deaths: 3.0,  climate_adaptation_spending: 0.04 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2023, values: { nd_gain_readiness: 0.20, climate_vulnerability: 0.56, natural_disaster_deaths: 2.0,  climate_adaptation_spending: 0.03 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2023, values: { nd_gain_readiness: 0.42, climate_vulnerability: 0.43, natural_disaster_deaths: 0.5,  climate_adaptation_spending: 0.08 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2023, values: { nd_gain_readiness: 0.28, climate_vulnerability: 0.48, natural_disaster_deaths: 0.8,  climate_adaptation_spending: 0.04 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2023, values: { nd_gain_readiness: 0.52, climate_vulnerability: 0.39, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.08 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2023, values: { nd_gain_readiness: 0.58, climate_vulnerability: 0.37, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.12 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2023, values: { nd_gain_readiness: 0.54, climate_vulnerability: 0.38, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.10 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2023, values: { nd_gain_readiness: 0.48, climate_vulnerability: 0.40, natural_disaster_deaths: 0.5,  climate_adaptation_spending: 0.08 } },

    // ── North Africa ────────────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2023, values: { nd_gain_readiness: 0.30, climate_vulnerability: 0.48, natural_disaster_deaths: 1.0,  climate_adaptation_spending: 0.06 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2023, values: { nd_gain_readiness: 0.36, climate_vulnerability: 0.44, natural_disaster_deaths: 2.0,  climate_adaptation_spending: 0.10 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2023, values: { nd_gain_readiness: 0.32, climate_vulnerability: 0.46, natural_disaster_deaths: 0.8,  climate_adaptation_spending: 0.05 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2023, values: { nd_gain_readiness: 0.35, climate_vulnerability: 0.44, natural_disaster_deaths: 0.5,  climate_adaptation_spending: 0.08 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2023, values: { nd_gain_readiness: 0.18, climate_vulnerability: 0.54, natural_disaster_deaths: 3.0,  climate_adaptation_spending: 0.02 } },

    // ── Sub-Saharan Africa ──────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2023, values: { nd_gain_readiness: 0.38, climate_vulnerability: 0.45, natural_disaster_deaths: 1.5,  climate_adaptation_spending: 0.06 } },
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2023, values: { nd_gain_readiness: 0.22, climate_vulnerability: 0.54, natural_disaster_deaths: 5.0,  climate_adaptation_spending: 0.03 } },
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2023, values: { nd_gain_readiness: 0.28, climate_vulnerability: 0.50, natural_disaster_deaths: 3.5,  climate_adaptation_spending: 0.08 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2023, values: { nd_gain_readiness: 0.22, climate_vulnerability: 0.55, natural_disaster_deaths: 6.0,  climate_adaptation_spending: 0.08 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2023, values: { nd_gain_readiness: 0.30, climate_vulnerability: 0.48, natural_disaster_deaths: 2.5,  climate_adaptation_spending: 0.06 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2023, values: { nd_gain_readiness: 0.24, climate_vulnerability: 0.53, natural_disaster_deaths: 4.0,  climate_adaptation_spending: 0.05 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2023, values: { nd_gain_readiness: 0.22, climate_vulnerability: 0.54, natural_disaster_deaths: 4.5,  climate_adaptation_spending: 0.05 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2023, values: { nd_gain_readiness: 0.30, climate_vulnerability: 0.50, natural_disaster_deaths: 3.0,  climate_adaptation_spending: 0.12 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2023, values: { nd_gain_readiness: 0.28, climate_vulnerability: 0.50, natural_disaster_deaths: 2.0,  climate_adaptation_spending: 0.07 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2023, values: { nd_gain_readiness: 0.25, climate_vulnerability: 0.52, natural_disaster_deaths: 2.5,  climate_adaptation_spending: 0.05 } },
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2023, values: { nd_gain_readiness: 0.22, climate_vulnerability: 0.54, natural_disaster_deaths: 4.0,  climate_adaptation_spending: 0.04 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2023, values: { nd_gain_readiness: 0.20, climate_vulnerability: 0.56, natural_disaster_deaths: 3.5,  climate_adaptation_spending: 0.03 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2023, values: { nd_gain_readiness: 0.18, climate_vulnerability: 0.58, natural_disaster_deaths: 8.0,  climate_adaptation_spending: 0.04 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2023, values: { nd_gain_readiness: 0.16, climate_vulnerability: 0.60, natural_disaster_deaths: 7.0,  climate_adaptation_spending: 0.03 } },
    { geoCode: 'CD', geoName: 'Democratic Republic of the Congo', dataYear: 2023, values: { nd_gain_readiness: 0.14, climate_vulnerability: 0.62, natural_disaster_deaths: 5.0,  climate_adaptation_spending: 0.02 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2023, values: { nd_gain_readiness: 0.20, climate_vulnerability: 0.56, natural_disaster_deaths: 4.0,  climate_adaptation_spending: 0.03 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2023, values: { nd_gain_readiness: 0.40, climate_vulnerability: 0.44, natural_disaster_deaths: 0.5,  climate_adaptation_spending: 0.08 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2023, values: { nd_gain_readiness: 0.36, climate_vulnerability: 0.46, natural_disaster_deaths: 1.0,  climate_adaptation_spending: 0.06 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2023, values: { nd_gain_readiness: 0.48, climate_vulnerability: 0.40, natural_disaster_deaths: 0.8,  climate_adaptation_spending: 0.12 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2023, values: { nd_gain_readiness: 0.30, climate_vulnerability: 0.48, natural_disaster_deaths: 1.0,  climate_adaptation_spending: 0.04 } },

    // ── Oceania ─────────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2023, values: { nd_gain_readiness: 0.72, climate_vulnerability: 0.32, natural_disaster_deaths: 0.5,  climate_adaptation_spending: 0.28 } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2023, values: { nd_gain_readiness: 0.74, climate_vulnerability: 0.30, natural_disaster_deaths: 0.3,  climate_adaptation_spending: 0.30 } },
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2023, values: { nd_gain_readiness: 0.34, climate_vulnerability: 0.50, natural_disaster_deaths: 5.0,  climate_adaptation_spending: 0.18 } },

    // ── Ex-USSR ─────────────────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2023, values: { nd_gain_readiness: 0.38, climate_vulnerability: 0.42, natural_disaster_deaths: 0.6,  climate_adaptation_spending: 0.04 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2023, values: { nd_gain_readiness: 0.30, climate_vulnerability: 0.46, natural_disaster_deaths: 1.0,  climate_adaptation_spending: 0.05 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2023, values: { nd_gain_readiness: 0.34, climate_vulnerability: 0.42, natural_disaster_deaths: 0.2,  climate_adaptation_spending: 0.04 } },
  ],
  seedDataPrev: [
    // ── Europe ──────────────────────────────────────────────────────────────
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2022, values: { nd_gain_readiness: 0.73, climate_vulnerability: 0.28, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.40 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2022, values: { nd_gain_readiness: 0.77, climate_vulnerability: 0.29, natural_disaster_deaths: 0.1,  climate_adaptation_spending: 0.43 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2022, values: { nd_gain_readiness: 0.74, climate_vulnerability: 0.30, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.36 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2022, values: { nd_gain_readiness: 0.75, climate_vulnerability: 0.30, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.35 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2022, values: { nd_gain_readiness: 0.67, climate_vulnerability: 0.32, natural_disaster_deaths: 0.3,  climate_adaptation_spending: 0.28 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2022, values: { nd_gain_readiness: 0.76, climate_vulnerability: 0.31, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.38 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2022, values: { nd_gain_readiness: 0.75, climate_vulnerability: 0.31, natural_disaster_deaths: 0.1,  climate_adaptation_spending: 0.36 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2022, values: { nd_gain_readiness: 0.57, climate_vulnerability: 0.35, natural_disaster_deaths: 1.5,  climate_adaptation_spending: 0.20 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2022, values: { nd_gain_readiness: 0.51, climate_vulnerability: 0.37, natural_disaster_deaths: 0.2,  climate_adaptation_spending: 0.16 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2022, values: { nd_gain_readiness: 0.44, climate_vulnerability: 0.41, natural_disaster_deaths: 0.6,  climate_adaptation_spending: 0.11 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2022, values: { nd_gain_readiness: 0.59, climate_vulnerability: 0.34, natural_disaster_deaths: 0.6,  climate_adaptation_spending: 0.18 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2022, values: { nd_gain_readiness: 0.68, climate_vulnerability: 0.32, natural_disaster_deaths: 0.1,  climate_adaptation_spending: 0.26 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2022, values: { nd_gain_readiness: 0.56, climate_vulnerability: 0.36, natural_disaster_deaths: 1.0,  climate_adaptation_spending: 0.20 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2022, values: { nd_gain_readiness: 0.66, climate_vulnerability: 0.33, natural_disaster_deaths: 0.4,  climate_adaptation_spending: 0.33 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2022, values: { nd_gain_readiness: 0.54, climate_vulnerability: 0.36, natural_disaster_deaths: 0.8,  climate_adaptation_spending: 0.16 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2022, values: { nd_gain_readiness: 0.71, climate_vulnerability: 0.32, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.40 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2022, values: { nd_gain_readiness: 0.61, climate_vulnerability: 0.34, natural_disaster_deaths: 0.3,  climate_adaptation_spending: 0.23 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2022, values: { nd_gain_readiness: 0.69, climate_vulnerability: 0.32, natural_disaster_deaths: 0.1,  climate_adaptation_spending: 0.30 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2022, values: { nd_gain_readiness: 0.47, climate_vulnerability: 0.38, natural_disaster_deaths: 1.8,  climate_adaptation_spending: 0.12 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2022, values: { nd_gain_readiness: 0.49, climate_vulnerability: 0.38, natural_disaster_deaths: 0.1,  climate_adaptation_spending: 0.14 } },
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2022, values: { nd_gain_readiness: 0.55, climate_vulnerability: 0.36, natural_disaster_deaths: 0.1,  climate_adaptation_spending: 0.18 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2022, values: { nd_gain_readiness: 0.51, climate_vulnerability: 0.37, natural_disaster_deaths: 0.2,  climate_adaptation_spending: 0.15 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2022, values: { nd_gain_readiness: 0.48, climate_vulnerability: 0.39, natural_disaster_deaths: 0.3,  climate_adaptation_spending: 0.13 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2022, values: { nd_gain_readiness: 0.43, climate_vulnerability: 0.41, natural_disaster_deaths: 0.4,  climate_adaptation_spending: 0.09 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2022, values: { nd_gain_readiness: 0.72, climate_vulnerability: 0.30, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.33 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2022, values: { nd_gain_readiness: 0.59, climate_vulnerability: 0.34, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.20 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2022, values: { nd_gain_readiness: 0.54, climate_vulnerability: 0.35, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.17 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2022, values: { nd_gain_readiness: 0.52, climate_vulnerability: 0.36, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.15 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2022, values: { nd_gain_readiness: 0.57, climate_vulnerability: 0.34, natural_disaster_deaths: 0.2,  climate_adaptation_spending: 0.18 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2022, values: { nd_gain_readiness: 0.41, climate_vulnerability: 0.42, natural_disaster_deaths: 0.5,  climate_adaptation_spending: 0.07 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2022, values: { nd_gain_readiness: 0.37, climate_vulnerability: 0.44, natural_disaster_deaths: 0.6,  climate_adaptation_spending: 0.05 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2022, values: { nd_gain_readiness: 0.35, climate_vulnerability: 0.45, natural_disaster_deaths: 0.5,  climate_adaptation_spending: 0.06 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2022, values: { nd_gain_readiness: 0.38, climate_vulnerability: 0.44, natural_disaster_deaths: 0.3,  climate_adaptation_spending: 0.06 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2022, values: { nd_gain_readiness: 0.40, climate_vulnerability: 0.43, natural_disaster_deaths: 0.2,  climate_adaptation_spending: 0.07 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2022, values: { nd_gain_readiness: 0.59, climate_vulnerability: 0.35, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.18 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2022, values: { nd_gain_readiness: 0.54, climate_vulnerability: 0.37, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.16 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2022, values: { nd_gain_readiness: 0.31, climate_vulnerability: 0.47, natural_disaster_deaths: 0.4,  climate_adaptation_spending: 0.04 } },

    // ── North America ───────────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',  dataYear: 2022, values: { nd_gain_readiness: 0.64, climate_vulnerability: 0.35, natural_disaster_deaths: 1.8,  climate_adaptation_spending: 0.13 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2022, values: { nd_gain_readiness: 0.70, climate_vulnerability: 0.33, natural_disaster_deaths: 0.5,  climate_adaptation_spending: 0.23 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2022, values: { nd_gain_readiness: 0.39, climate_vulnerability: 0.44, natural_disaster_deaths: 2.8,  climate_adaptation_spending: 0.07 } },

    // ── Central America & Caribbean ─────────────────────────────────────────
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2022, values: { nd_gain_readiness: 0.27, climate_vulnerability: 0.53, natural_disaster_deaths: 4.5,  climate_adaptation_spending: 0.03 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2022, values: { nd_gain_readiness: 0.24, climate_vulnerability: 0.55, natural_disaster_deaths: 7.0,  climate_adaptation_spending: 0.04 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2022, values: { nd_gain_readiness: 0.29, climate_vulnerability: 0.51, natural_disaster_deaths: 4.0,  climate_adaptation_spending: 0.05 } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2022, values: { nd_gain_readiness: 0.47, climate_vulnerability: 0.41, natural_disaster_deaths: 1.2,  climate_adaptation_spending: 0.14 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2022, values: { nd_gain_readiness: 0.41, climate_vulnerability: 0.43, natural_disaster_deaths: 1.5,  climate_adaptation_spending: 0.09 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2022, values: { nd_gain_readiness: 0.37, climate_vulnerability: 0.48, natural_disaster_deaths: 2.5,  climate_adaptation_spending: 0.11 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2022, values: { nd_gain_readiness: 0.43, climate_vulnerability: 0.45, natural_disaster_deaths: 1.0,  climate_adaptation_spending: 0.09 } },
    { geoCode: 'DO', geoName: 'Dominican Republic',  dataYear: 2022, values: { nd_gain_readiness: 0.34, climate_vulnerability: 0.49, natural_disaster_deaths: 3.5,  climate_adaptation_spending: 0.07 } },

    // ── South America ───────────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2022, values: { nd_gain_readiness: 0.39, climate_vulnerability: 0.44, natural_disaster_deaths: 2.5,  climate_adaptation_spending: 0.07 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2022, values: { nd_gain_readiness: 0.37, climate_vulnerability: 0.43, natural_disaster_deaths: 1.0,  climate_adaptation_spending: 0.05 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2022, values: { nd_gain_readiness: 0.51, climate_vulnerability: 0.39, natural_disaster_deaths: 0.6,  climate_adaptation_spending: 0.13 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2022, values: { nd_gain_readiness: 0.35, climate_vulnerability: 0.46, natural_disaster_deaths: 3.0,  climate_adaptation_spending: 0.06 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2022, values: { nd_gain_readiness: 0.33, climate_vulnerability: 0.47, natural_disaster_deaths: 3.5,  climate_adaptation_spending: 0.05 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2022, values: { nd_gain_readiness: 0.21, climate_vulnerability: 0.54, natural_disaster_deaths: 4.5,  climate_adaptation_spending: 0.02 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2022, values: { nd_gain_readiness: 0.32, climate_vulnerability: 0.47, natural_disaster_deaths: 3.8,  climate_adaptation_spending: 0.05 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2022, values: { nd_gain_readiness: 0.49, climate_vulnerability: 0.39, natural_disaster_deaths: 0.3,  climate_adaptation_spending: 0.11 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2022, values: { nd_gain_readiness: 0.29, climate_vulnerability: 0.49, natural_disaster_deaths: 1.8,  climate_adaptation_spending: 0.04 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2022, values: { nd_gain_readiness: 0.25, climate_vulnerability: 0.52, natural_disaster_deaths: 4.0,  climate_adaptation_spending: 0.03 } },

    // ── East Asia ────────────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2022, values: { nd_gain_readiness: 0.65, climate_vulnerability: 0.34, natural_disaster_deaths: 0.6,  climate_adaptation_spending: 0.28 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2022, values: { nd_gain_readiness: 0.63, climate_vulnerability: 0.35, natural_disaster_deaths: 0.4,  climate_adaptation_spending: 0.23 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2022, values: { nd_gain_readiness: 0.41, climate_vulnerability: 0.43, natural_disaster_deaths: 2.0,  climate_adaptation_spending: 0.09 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2022, values: { nd_gain_readiness: 0.61, climate_vulnerability: 0.36, natural_disaster_deaths: 0.5,  climate_adaptation_spending: 0.20 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2022, values: { nd_gain_readiness: 0.31, climate_vulnerability: 0.49, natural_disaster_deaths: 1.8,  climate_adaptation_spending: 0.05 } },

    // ── Southeast Asia ──────────────────────────────────────────────────────
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2022, values: { nd_gain_readiness: 0.72, climate_vulnerability: 0.31, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.33 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2022, values: { nd_gain_readiness: 0.39, climate_vulnerability: 0.45, natural_disaster_deaths: 3.5,  climate_adaptation_spending: 0.09 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2022, values: { nd_gain_readiness: 0.34, climate_vulnerability: 0.49, natural_disaster_deaths: 5.0,  climate_adaptation_spending: 0.11 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2022, values: { nd_gain_readiness: 0.35, climate_vulnerability: 0.47, natural_disaster_deaths: 4.0,  climate_adaptation_spending: 0.07 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2022, values: { nd_gain_readiness: 0.32, climate_vulnerability: 0.51, natural_disaster_deaths: 6.0,  climate_adaptation_spending: 0.09 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2022, values: { nd_gain_readiness: 0.51, climate_vulnerability: 0.40, natural_disaster_deaths: 1.2,  climate_adaptation_spending: 0.13 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2022, values: { nd_gain_readiness: 0.17, climate_vulnerability: 0.59, natural_disaster_deaths: 9.0,  climate_adaptation_spending: 0.02 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2022, values: { nd_gain_readiness: 0.23, climate_vulnerability: 0.55, natural_disaster_deaths: 4.5,  climate_adaptation_spending: 0.05 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2022, values: { nd_gain_readiness: 0.21, climate_vulnerability: 0.56, natural_disaster_deaths: 4.0,  climate_adaptation_spending: 0.04 } },
    { geoCode: 'BN', geoName: 'Brunei',         dataYear: 2022, values: { nd_gain_readiness: 0.54, climate_vulnerability: 0.38, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.11 } },

    // ── South Asia ──────────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2022, values: { nd_gain_readiness: 0.31, climate_vulnerability: 0.51, natural_disaster_deaths: 4.0,  climate_adaptation_spending: 0.07 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2022, values: { nd_gain_readiness: 0.23, climate_vulnerability: 0.56, natural_disaster_deaths: 12.0, climate_adaptation_spending: 0.04 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2022, values: { nd_gain_readiness: 0.24, climate_vulnerability: 0.59, natural_disaster_deaths: 14.0, climate_adaptation_spending: 0.28 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2022, values: { nd_gain_readiness: 0.29, climate_vulnerability: 0.50, natural_disaster_deaths: 4.5,  climate_adaptation_spending: 0.07 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2022, values: { nd_gain_readiness: 0.22, climate_vulnerability: 0.55, natural_disaster_deaths: 8.0,  climate_adaptation_spending: 0.09 } },
    { geoCode: 'AF', geoName: 'Afghanistan',    dataYear: 2022, values: { nd_gain_readiness: 0.11, climate_vulnerability: 0.65, natural_disaster_deaths: 18.0, climate_adaptation_spending: 0.01 } },

    // ── Central Asia ────────────────────────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2022, values: { nd_gain_readiness: 0.39, climate_vulnerability: 0.43, natural_disaster_deaths: 1.0,  climate_adaptation_spending: 0.05 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2022, values: { nd_gain_readiness: 0.29, climate_vulnerability: 0.49, natural_disaster_deaths: 1.2,  climate_adaptation_spending: 0.03 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2022, values: { nd_gain_readiness: 0.24, climate_vulnerability: 0.53, natural_disaster_deaths: 0.6,  climate_adaptation_spending: 0.02 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2022, values: { nd_gain_readiness: 0.27, climate_vulnerability: 0.51, natural_disaster_deaths: 2.5,  climate_adaptation_spending: 0.04 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2022, values: { nd_gain_readiness: 0.21, climate_vulnerability: 0.56, natural_disaster_deaths: 4.0,  climate_adaptation_spending: 0.03 } },

    // ── Middle East ─────────────────────────────────────────────────────────
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2022, values: { nd_gain_readiness: 0.49, climate_vulnerability: 0.41, natural_disaster_deaths: 0.2,  climate_adaptation_spending: 0.09 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2022, values: { nd_gain_readiness: 0.61, climate_vulnerability: 0.37, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.16 } },
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2022, values: { nd_gain_readiness: 0.63, climate_vulnerability: 0.35, natural_disaster_deaths: 0.1,  climate_adaptation_spending: 0.20 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2022, values: { nd_gain_readiness: 0.43, climate_vulnerability: 0.42, natural_disaster_deaths: 3.0,  climate_adaptation_spending: 0.09 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2022, values: { nd_gain_readiness: 0.29, climate_vulnerability: 0.49, natural_disaster_deaths: 3.5,  climate_adaptation_spending: 0.03 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2022, values: { nd_gain_readiness: 0.19, climate_vulnerability: 0.57, natural_disaster_deaths: 2.5,  climate_adaptation_spending: 0.02 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2022, values: { nd_gain_readiness: 0.41, climate_vulnerability: 0.44, natural_disaster_deaths: 0.3,  climate_adaptation_spending: 0.07 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2022, values: { nd_gain_readiness: 0.27, climate_vulnerability: 0.49, natural_disaster_deaths: 0.5,  climate_adaptation_spending: 0.03 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2022, values: { nd_gain_readiness: 0.51, climate_vulnerability: 0.40, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.07 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2022, values: { nd_gain_readiness: 0.57, climate_vulnerability: 0.38, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.11 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2022, values: { nd_gain_readiness: 0.53, climate_vulnerability: 0.39, natural_disaster_deaths: 0.0,  climate_adaptation_spending: 0.09 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2022, values: { nd_gain_readiness: 0.47, climate_vulnerability: 0.41, natural_disaster_deaths: 0.3,  climate_adaptation_spending: 0.07 } },

    // ── North Africa ────────────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2022, values: { nd_gain_readiness: 0.29, climate_vulnerability: 0.49, natural_disaster_deaths: 0.8,  climate_adaptation_spending: 0.05 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2022, values: { nd_gain_readiness: 0.35, climate_vulnerability: 0.45, natural_disaster_deaths: 2.5,  climate_adaptation_spending: 0.09 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2022, values: { nd_gain_readiness: 0.31, climate_vulnerability: 0.47, natural_disaster_deaths: 0.6,  climate_adaptation_spending: 0.04 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2022, values: { nd_gain_readiness: 0.34, climate_vulnerability: 0.45, natural_disaster_deaths: 0.4,  climate_adaptation_spending: 0.07 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2022, values: { nd_gain_readiness: 0.17, climate_vulnerability: 0.55, natural_disaster_deaths: 3.5,  climate_adaptation_spending: 0.01 } },

    // ── Sub-Saharan Africa ──────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2022, values: { nd_gain_readiness: 0.37, climate_vulnerability: 0.46, natural_disaster_deaths: 2.0,  climate_adaptation_spending: 0.05 } },
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2022, values: { nd_gain_readiness: 0.21, climate_vulnerability: 0.55, natural_disaster_deaths: 6.0,  climate_adaptation_spending: 0.02 } },
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2022, values: { nd_gain_readiness: 0.27, climate_vulnerability: 0.51, natural_disaster_deaths: 4.0,  climate_adaptation_spending: 0.07 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2022, values: { nd_gain_readiness: 0.21, climate_vulnerability: 0.56, natural_disaster_deaths: 7.0,  climate_adaptation_spending: 0.07 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2022, values: { nd_gain_readiness: 0.29, climate_vulnerability: 0.49, natural_disaster_deaths: 3.0,  climate_adaptation_spending: 0.05 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2022, values: { nd_gain_readiness: 0.23, climate_vulnerability: 0.54, natural_disaster_deaths: 4.5,  climate_adaptation_spending: 0.04 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2022, values: { nd_gain_readiness: 0.21, climate_vulnerability: 0.55, natural_disaster_deaths: 5.0,  climate_adaptation_spending: 0.04 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2022, values: { nd_gain_readiness: 0.29, climate_vulnerability: 0.51, natural_disaster_deaths: 3.5,  climate_adaptation_spending: 0.11 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2022, values: { nd_gain_readiness: 0.27, climate_vulnerability: 0.51, natural_disaster_deaths: 2.5,  climate_adaptation_spending: 0.06 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2022, values: { nd_gain_readiness: 0.24, climate_vulnerability: 0.53, natural_disaster_deaths: 3.0,  climate_adaptation_spending: 0.04 } },
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2022, values: { nd_gain_readiness: 0.21, climate_vulnerability: 0.55, natural_disaster_deaths: 4.5,  climate_adaptation_spending: 0.03 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2022, values: { nd_gain_readiness: 0.19, climate_vulnerability: 0.57, natural_disaster_deaths: 4.0,  climate_adaptation_spending: 0.02 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2022, values: { nd_gain_readiness: 0.17, climate_vulnerability: 0.59, natural_disaster_deaths: 9.0,  climate_adaptation_spending: 0.03 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2022, values: { nd_gain_readiness: 0.15, climate_vulnerability: 0.61, natural_disaster_deaths: 8.0,  climate_adaptation_spending: 0.02 } },
    { geoCode: 'CD', geoName: 'Democratic Republic of the Congo', dataYear: 2022, values: { nd_gain_readiness: 0.13, climate_vulnerability: 0.63, natural_disaster_deaths: 6.0,  climate_adaptation_spending: 0.01 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2022, values: { nd_gain_readiness: 0.19, climate_vulnerability: 0.57, natural_disaster_deaths: 4.5,  climate_adaptation_spending: 0.02 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2022, values: { nd_gain_readiness: 0.39, climate_vulnerability: 0.45, natural_disaster_deaths: 0.3,  climate_adaptation_spending: 0.07 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2022, values: { nd_gain_readiness: 0.35, climate_vulnerability: 0.47, natural_disaster_deaths: 0.8,  climate_adaptation_spending: 0.05 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2022, values: { nd_gain_readiness: 0.47, climate_vulnerability: 0.41, natural_disaster_deaths: 1.0,  climate_adaptation_spending: 0.11 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2022, values: { nd_gain_readiness: 0.29, climate_vulnerability: 0.49, natural_disaster_deaths: 0.8,  climate_adaptation_spending: 0.03 } },

    // ── Oceania ─────────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2022, values: { nd_gain_readiness: 0.71, climate_vulnerability: 0.33, natural_disaster_deaths: 0.6,  climate_adaptation_spending: 0.26 } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2022, values: { nd_gain_readiness: 0.73, climate_vulnerability: 0.31, natural_disaster_deaths: 0.4,  climate_adaptation_spending: 0.28 } },
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2022, values: { nd_gain_readiness: 0.33, climate_vulnerability: 0.51, natural_disaster_deaths: 6.0,  climate_adaptation_spending: 0.16 } },

    // ── Ex-USSR ─────────────────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2022, values: { nd_gain_readiness: 0.37, climate_vulnerability: 0.43, natural_disaster_deaths: 0.5,  climate_adaptation_spending: 0.03 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2022, values: { nd_gain_readiness: 0.29, climate_vulnerability: 0.47, natural_disaster_deaths: 0.8,  climate_adaptation_spending: 0.04 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2022, values: { nd_gain_readiness: 0.33, climate_vulnerability: 0.43, natural_disaster_deaths: 0.1,  climate_adaptation_spending: 0.03 } },
  ],
};

export default climateRiskModule;
