import type { DomainModule } from '@/lib/domains/types';

/**
 * Domaine : Stress des marchés & incertitude mondiale
 *
 * Sources :
 *  - EPU  : Baker, Bloom & Davis — policyuncertainty.com (22 pays, base 100 = moy. hist.)
 *  - WUI  : Ahir, Bloom & Furceri — worlduncertaintyindex.com (143 pays, ×10⁶ mots)
 *  - Crédit souverain : S&P / Moody's 2024, converti en score 0-100
 *  - Stabilité bancaire : World Bank FSDI Z-score proxy, normalisé 0-100
 *
 * Données : 2024 (annuel moyen ou estimation Q3 2024)
 */

const marketStressModule: DomainModule = {
  definition: {
    id: 'market-stress',
    label: {
      fr: 'Stress des marchés',
      en: 'Market Stress',
      es: 'Estrés de mercado',
    },
    description: {
      fr: "Incertitude économique et stress financier : indice EPU (incertitude politique), WUI (incertitude mondiale), note de crédit souverain et stabilité du secteur bancaire.",
      en: 'Economic uncertainty and financial stress: EPU index (policy uncertainty), World Uncertainty Index (WUI), sovereign credit rating, and banking sector stability.',
      es: 'Incertidumbre económica y estrés financiero: índice EPU (incertidumbre política), WUI (incertidumbre mundial), calificación crediticia soberana y estabilidad bancaria.',
    },
    icon: '📉',
    group: 'economy',
    active: true,
    seedSources: [
      'https://www.policyuncertainty.com/',
      'https://worlduncertaintyindex.com/data/',
      'https://www.spglobal.com/ratings/sri/',
      'https://www.worldbank.org/en/publication/gfdr',
    ],
    indicators: [
      {
        id: 'epu_index',
        label: {
          fr: 'Incertitude politique économique (EPU)',
          en: 'Economic Policy Uncertainty (EPU)',
          es: 'Incertidumbre política económica (EPU)',
        },
        unit: 'index',
        unitLabel: { fr: 'indice (moy.=100)', en: 'index (avg=100)', es: 'índice (prom.=100)' },
        direction: 'lower_is_better',
        weight: 3,
        thresholds: { excellent: 80, good: 130, fair: 200, poor: 300 },
        minValue: 0,
        maxValue: 600,
      },
      {
        id: 'world_uncertainty_idx',
        label: {
          fr: "Indice d'incertitude mondiale (WUI)",
          en: 'World Uncertainty Index (WUI)',
          es: 'Índice de incertidumbre mundial (WUI)',
        },
        unit: 'index',
        unitLabel: { fr: 'fréquence ×10⁶', en: 'frequency ×10⁶', es: 'frecuencia ×10⁶' },
        direction: 'lower_is_better',
        weight: 3,
        thresholds: { excellent: 40, good: 80, fair: 130, poor: 200 },
        minValue: 0,
        maxValue: 350,
      },
      {
        id: 'sovereign_credit_score',
        label: {
          fr: 'Note de crédit souverain',
          en: 'Sovereign credit score',
          es: 'Calificación crediticia soberana',
        },
        unit: 'index',
        unitLabel: { fr: 'score /100', en: 'score /100', es: 'score /100' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 90, good: 70, fair: 50, poor: 30 },
        minValue: 0,
        maxValue: 100,
      },
      {
        id: 'banking_stability',
        label: {
          fr: 'Stabilité du secteur bancaire',
          en: 'Banking sector stability',
          es: 'Estabilidad del sector bancario',
        },
        unit: 'index',
        unitLabel: { fr: 'score /100', en: 'score /100', es: 'score /100' },
        direction: 'higher_is_better',
        weight: 2,
        thresholds: { excellent: 85, good: 70, fair: 52, poor: 35 },
        minValue: 0,
        maxValue: 100,
      },
    ],
  },

  seedData: [
    // ── Europe nordique ────────────────────────────────────────────────────
    { geoCode: 'NO', geoName: 'Norway',          dataYear: 2024, values: { epu_index: 105, world_uncertainty_idx: 42, sovereign_credit_score: 100, banking_stability: 94 } },
    { geoCode: 'SE', geoName: 'Sweden',          dataYear: 2024, values: { epu_index: 110, world_uncertainty_idx: 55, sovereign_credit_score: 100, banking_stability: 90 } },
    { geoCode: 'DK', geoName: 'Denmark',         dataYear: 2024, values: { epu_index: 115, world_uncertainty_idx: 48, sovereign_credit_score: 100, banking_stability: 90 } },
    { geoCode: 'FI', geoName: 'Finland',         dataYear: 2024, values: { epu_index: 120, world_uncertainty_idx: 52, sovereign_credit_score: 95,  banking_stability: 90 } },
    { geoCode: 'IS', geoName: 'Iceland',         dataYear: 2024, values: { epu_index: 108, world_uncertainty_idx: 45, sovereign_credit_score: 80,  banking_stability: 82 } },
    // ── Démocraties très stables ───────────────────────────────────────────
    { geoCode: 'CH', geoName: 'Switzerland',     dataYear: 2024, values: { epu_index: 88,  world_uncertainty_idx: 35, sovereign_credit_score: 100, banking_stability: 92 } },
    { geoCode: 'SG', geoName: 'Singapore',       dataYear: 2024, values: { epu_index: 95,  world_uncertainty_idx: 32, sovereign_credit_score: 100, banking_stability: 95 } },
    { geoCode: 'AU', geoName: 'Australia',       dataYear: 2024, values: { epu_index: 92,  world_uncertainty_idx: 55, sovereign_credit_score: 100, banking_stability: 90 } },
    { geoCode: 'NZ', geoName: 'New Zealand',     dataYear: 2024, values: { epu_index: 85,  world_uncertainty_idx: 50, sovereign_credit_score: 90,  banking_stability: 88 } },
    { geoCode: 'CA', geoName: 'Canada',          dataYear: 2024, values: { epu_index: 135, world_uncertainty_idx: 65, sovereign_credit_score: 100, banking_stability: 92 } },
    { geoCode: 'LU', geoName: 'Luxembourg',      dataYear: 2024, values: { epu_index: 128, world_uncertainty_idx: 52, sovereign_credit_score: 100, banking_stability: 90 } },
    // ── Europe de l'Ouest ──────────────────────────────────────────────────
    { geoCode: 'DE', geoName: 'Germany',         dataYear: 2024, values: { epu_index: 192, world_uncertainty_idx: 72, sovereign_credit_score: 100, banking_stability: 85 } },
    { geoCode: 'NL', geoName: 'Netherlands',     dataYear: 2024, values: { epu_index: 155, world_uncertainty_idx: 65, sovereign_credit_score: 100, banking_stability: 85 } },
    { geoCode: 'AT', geoName: 'Austria',         dataYear: 2024, values: { epu_index: 148, world_uncertainty_idx: 60, sovereign_credit_score: 95,  banking_stability: 86 } },
    { geoCode: 'BE', geoName: 'Belgium',         dataYear: 2024, values: { epu_index: 162, world_uncertainty_idx: 68, sovereign_credit_score: 90,  banking_stability: 80 } },
    { geoCode: 'FR', geoName: 'France',          dataYear: 2024, values: { epu_index: 175, world_uncertainty_idx: 80, sovereign_credit_score: 90,  banking_stability: 82 } },
    { geoCode: 'GB', geoName: 'United Kingdom',  dataYear: 2024, values: { epu_index: 172, world_uncertainty_idx: 82, sovereign_credit_score: 90,  banking_stability: 80 } },
    { geoCode: 'IE', geoName: 'Ireland',         dataYear: 2024, values: { epu_index: 155, world_uncertainty_idx: 66, sovereign_credit_score: 85,  banking_stability: 78 } },
    { geoCode: 'ES', geoName: 'Spain',           dataYear: 2024, values: { epu_index: 208, world_uncertainty_idx: 92, sovereign_credit_score: 80,  banking_stability: 72 } },
    { geoCode: 'PT', geoName: 'Portugal',        dataYear: 2024, values: { epu_index: 182, world_uncertainty_idx: 85, sovereign_credit_score: 70,  banking_stability: 68 } },
    { geoCode: 'IT', geoName: 'Italy',           dataYear: 2024, values: { epu_index: 215, world_uncertainty_idx: 92, sovereign_credit_score: 65,  banking_stability: 65 } },
    { geoCode: 'GR', geoName: 'Greece',          dataYear: 2024, values: { epu_index: 190, world_uncertainty_idx: 95, sovereign_credit_score: 55,  banking_stability: 58 } },
    { geoCode: 'MT', geoName: 'Malta',           dataYear: 2024, values: { epu_index: 140, world_uncertainty_idx: 62, sovereign_credit_score: 75,  banking_stability: 70 } },
    { geoCode: 'CY', geoName: 'Cyprus',          dataYear: 2024, values: { epu_index: 155, world_uncertainty_idx: 78, sovereign_credit_score: 60,  banking_stability: 62 } },
    // ── Amérique du Nord ───────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',   dataYear: 2024, values: { epu_index: 220, world_uncertainty_idx: 95, sovereign_credit_score: 95,  banking_stability: 80 } },
    { geoCode: 'MX', geoName: 'Mexico',          dataYear: 2024, values: { epu_index: 218, world_uncertainty_idx: 115, sovereign_credit_score: 60, banking_stability: 62 } },
    // ── Asie-Pacifique avancée ─────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',           dataYear: 2024, values: { epu_index: 128, world_uncertainty_idx: 58, sovereign_credit_score: 85,  banking_stability: 75 } },
    { geoCode: 'KR', geoName: 'South Korea',     dataYear: 2024, values: { epu_index: 162, world_uncertainty_idx: 78, sovereign_credit_score: 85,  banking_stability: 75 } },
    { geoCode: 'TW', geoName: 'Taiwan',          dataYear: 2024, values: { epu_index: 145, world_uncertainty_idx: 72, sovereign_credit_score: 82,  banking_stability: 78 } },
    // ── Europe de l'Est (UE) ───────────────────────────────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',         dataYear: 2024, values: { epu_index: 148, world_uncertainty_idx: 70, sovereign_credit_score: 82,  banking_stability: 74 } },
    { geoCode: 'EE', geoName: 'Estonia',         dataYear: 2024, values: { epu_index: 135, world_uncertainty_idx: 68, sovereign_credit_score: 85,  banking_stability: 75 } },
    { geoCode: 'LV', geoName: 'Latvia',          dataYear: 2024, values: { epu_index: 140, world_uncertainty_idx: 70, sovereign_credit_score: 85,  banking_stability: 72 } },
    { geoCode: 'LT', geoName: 'Lithuania',       dataYear: 2024, values: { epu_index: 138, world_uncertainty_idx: 70, sovereign_credit_score: 85,  banking_stability: 72 } },
    { geoCode: 'SK', geoName: 'Slovakia',        dataYear: 2024, values: { epu_index: 150, world_uncertainty_idx: 75, sovereign_credit_score: 65,  banking_stability: 68 } },
    { geoCode: 'SI', geoName: 'Slovenia',        dataYear: 2024, values: { epu_index: 155, world_uncertainty_idx: 72, sovereign_credit_score: 68,  banking_stability: 68 } },
    { geoCode: 'PL', geoName: 'Poland',          dataYear: 2024, values: { epu_index: 165, world_uncertainty_idx: 78, sovereign_credit_score: 65,  banking_stability: 68 } },
    { geoCode: 'HU', geoName: 'Hungary',         dataYear: 2024, values: { epu_index: 175, world_uncertainty_idx: 82, sovereign_credit_score: 65,  banking_stability: 62 } },
    { geoCode: 'RO', geoName: 'Romania',         dataYear: 2024, values: { epu_index: 182, world_uncertainty_idx: 88, sovereign_credit_score: 65,  banking_stability: 60 } },
    { geoCode: 'BG', geoName: 'Bulgaria',        dataYear: 2024, values: { epu_index: 172, world_uncertainty_idx: 80, sovereign_credit_score: 60,  banking_stability: 60 } },
    { geoCode: 'HR', geoName: 'Croatia',         dataYear: 2024, values: { epu_index: 165, world_uncertainty_idx: 78, sovereign_credit_score: 60,  banking_stability: 62 } },
    // ── Balkans & Europe hors UE ───────────────────────────────────────────
    { geoCode: 'RS', geoName: 'Serbia',          dataYear: 2024, values: { epu_index: 195, world_uncertainty_idx: 90, sovereign_credit_score: 45,  banking_stability: 55 } },
    { geoCode: 'BA', geoName: 'Bosnia',          dataYear: 2024, values: { epu_index: 210, world_uncertainty_idx: 105, sovereign_credit_score: 32, banking_stability: 50 } },
    { geoCode: 'AL', geoName: 'Albania',         dataYear: 2024, values: { epu_index: 200, world_uncertainty_idx: 98, sovereign_credit_score: 30,  banking_stability: 50 } },
    { geoCode: 'ME', geoName: 'Montenegro',      dataYear: 2024, values: { epu_index: 195, world_uncertainty_idx: 95, sovereign_credit_score: 32,  banking_stability: 50 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2024, values: { epu_index: 198, world_uncertainty_idx: 98, sovereign_credit_score: 30,  banking_stability: 48 } },
    { geoCode: 'XK', geoName: 'Kosovo',          dataYear: 2024, values: { epu_index: 205, world_uncertainty_idx: 102, sovereign_credit_score: 24, banking_stability: 45 } },
    { geoCode: 'MD', geoName: 'Moldova',         dataYear: 2024, values: { epu_index: 252, world_uncertainty_idx: 128, sovereign_credit_score: 24, banking_stability: 42 } },
    // ── Ex-URSS & Asie centrale ───────────────────────────────────────────
    { geoCode: 'UA', geoName: 'Ukraine',         dataYear: 2024, values: { epu_index: 385, world_uncertainty_idx: 292, sovereign_credit_score: 15, banking_stability: 30 } },
    { geoCode: 'RU', geoName: 'Russia',          dataYear: 2024, values: { epu_index: 402, world_uncertainty_idx: 275, sovereign_credit_score: 4,  banking_stability: 40 } },
    { geoCode: 'BY', geoName: 'Belarus',         dataYear: 2024, values: { epu_index: 362, world_uncertainty_idx: 228, sovereign_credit_score: 12, banking_stability: 30 } },
    { geoCode: 'GE', geoName: 'Georgia',         dataYear: 2024, values: { epu_index: 212, world_uncertainty_idx: 108, sovereign_credit_score: 36, banking_stability: 52 } },
    { geoCode: 'AM', geoName: 'Armenia',         dataYear: 2024, values: { epu_index: 238, world_uncertainty_idx: 122, sovereign_credit_score: 30, banking_stability: 45 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',      dataYear: 2024, values: { epu_index: 242, world_uncertainty_idx: 120, sovereign_credit_score: 30, banking_stability: 48 } },
    { geoCode: 'KZ', geoName: 'Kazakhstan',      dataYear: 2024, values: { epu_index: 248, world_uncertainty_idx: 125, sovereign_credit_score: 48, banking_stability: 52 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',      dataYear: 2024, values: { epu_index: 242, world_uncertainty_idx: 122, sovereign_credit_score: 36, banking_stability: 48 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',      dataYear: 2024, values: { epu_index: 258, world_uncertainty_idx: 138, sovereign_credit_score: 18, banking_stability: 38 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',      dataYear: 2024, values: { epu_index: 268, world_uncertainty_idx: 148, sovereign_credit_score: 12, banking_stability: 32 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',    dataYear: 2024, values: { epu_index: 285, world_uncertainty_idx: 158, sovereign_credit_score: 8,  banking_stability: 30 } },
    // ── Asie de l'Est ─────────────────────────────────────────────────────
    { geoCode: 'CN', geoName: 'China',           dataYear: 2024, values: { epu_index: 295, world_uncertainty_idx: 130, sovereign_credit_score: 80,  banking_stability: 65 } },
    { geoCode: 'MN', geoName: 'Mongolia',        dataYear: 2024, values: { epu_index: 235, world_uncertainty_idx: 125, sovereign_credit_score: 36,  banking_stability: 45 } },
    { geoCode: 'KP', geoName: 'North Korea',     dataYear: 2024, values: { epu_index: 480, world_uncertainty_idx: 295, sovereign_credit_score: 2,   banking_stability: 5  } },
    // ── Asie du Sud & du Sud-Est ──────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',           dataYear: 2024, values: { epu_index: 210, world_uncertainty_idx: 112, sovereign_credit_score: 55,  banking_stability: 62 } },
    { geoCode: 'PK', geoName: 'Pakistan',        dataYear: 2024, values: { epu_index: 312, world_uncertainty_idx: 168, sovereign_credit_score: 30,  banking_stability: 42 } },
    { geoCode: 'BD', geoName: 'Bangladesh',      dataYear: 2024, values: { epu_index: 252, world_uncertainty_idx: 135, sovereign_credit_score: 30,  banking_stability: 45 } },
    { geoCode: 'NP', geoName: 'Nepal',           dataYear: 2024, values: { epu_index: 248, world_uncertainty_idx: 132, sovereign_credit_score: 18,  banking_stability: 38 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',       dataYear: 2024, values: { epu_index: 282, world_uncertainty_idx: 150, sovereign_credit_score: 18,  banking_stability: 35 } },
    { geoCode: 'ID', geoName: 'Indonesia',       dataYear: 2024, values: { epu_index: 185, world_uncertainty_idx: 108, sovereign_credit_score: 60,  banking_stability: 62 } },
    { geoCode: 'TH', geoName: 'Thailand',        dataYear: 2024, values: { epu_index: 165, world_uncertainty_idx: 98, sovereign_credit_score: 70,   banking_stability: 65 } },
    { geoCode: 'MY', geoName: 'Malaysia',        dataYear: 2024, values: { epu_index: 158, world_uncertainty_idx: 88, sovereign_credit_score: 70,   banking_stability: 68 } },
    { geoCode: 'PH', geoName: 'Philippines',     dataYear: 2024, values: { epu_index: 178, world_uncertainty_idx: 105, sovereign_credit_score: 65,  banking_stability: 60 } },
    { geoCode: 'VN', geoName: 'Vietnam',         dataYear: 2024, values: { epu_index: 162, world_uncertainty_idx: 95, sovereign_credit_score: 55,   banking_stability: 58 } },
    { geoCode: 'MM', geoName: 'Myanmar',         dataYear: 2024, values: { epu_index: 375, world_uncertainty_idx: 248, sovereign_credit_score: 8,   banking_stability: 20 } },
    { geoCode: 'KH', geoName: 'Cambodia',        dataYear: 2024, values: { epu_index: 225, world_uncertainty_idx: 118, sovereign_credit_score: 24,  banking_stability: 42 } },
    { geoCode: 'LA', geoName: 'Laos',            dataYear: 2024, values: { epu_index: 255, world_uncertainty_idx: 138, sovereign_credit_score: 18,  banking_stability: 32 } },
    // ── Moyen-Orient ──────────────────────────────────────────────────────
    { geoCode: 'TR', geoName: 'Turkey',          dataYear: 2024, values: { epu_index: 345, world_uncertainty_idx: 162, sovereign_credit_score: 50,  banking_stability: 48 } },
    { geoCode: 'SA', geoName: 'Saudi Arabia',    dataYear: 2024, values: { epu_index: 165, world_uncertainty_idx: 100, sovereign_credit_score: 80,  banking_stability: 72 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2024, values: { epu_index: 145, world_uncertainty_idx: 88, sovereign_credit_score: 82, banking_stability: 75 } },
    { geoCode: 'QA', geoName: 'Qatar',           dataYear: 2024, values: { epu_index: 148, world_uncertainty_idx: 85, sovereign_credit_score: 75,  banking_stability: 78 } },
    { geoCode: 'KW', geoName: 'Kuwait',          dataYear: 2024, values: { epu_index: 155, world_uncertainty_idx: 90, sovereign_credit_score: 72,  banking_stability: 72 } },
    { geoCode: 'OM', geoName: 'Oman',            dataYear: 2024, values: { epu_index: 162, world_uncertainty_idx: 95, sovereign_credit_score: 55,  banking_stability: 65 } },
    { geoCode: 'BH', geoName: 'Bahrain',         dataYear: 2024, values: { epu_index: 175, world_uncertainty_idx: 98, sovereign_credit_score: 48,  banking_stability: 60 } },
    { geoCode: 'JO', geoName: 'Jordan',          dataYear: 2024, values: { epu_index: 195, world_uncertainty_idx: 110, sovereign_credit_score: 42, banking_stability: 55 } },
    { geoCode: 'IL', geoName: 'Israel',          dataYear: 2024, values: { epu_index: 282, world_uncertainty_idx: 188, sovereign_credit_score: 75,  banking_stability: 68 } },
    { geoCode: 'IR', geoName: 'Iran',            dataYear: 2024, values: { epu_index: 388, world_uncertainty_idx: 222, sovereign_credit_score: 8,   banking_stability: 28 } },
    { geoCode: 'IQ', geoName: 'Iraq',            dataYear: 2024, values: { epu_index: 322, world_uncertainty_idx: 202, sovereign_credit_score: 24,  banking_stability: 30 } },
    { geoCode: 'LB', geoName: 'Lebanon',         dataYear: 2024, values: { epu_index: 362, world_uncertainty_idx: 248, sovereign_credit_score: 4,   banking_stability: 10 } },
    { geoCode: 'SY', geoName: 'Syria',           dataYear: 2024, values: { epu_index: 500, world_uncertainty_idx: 312, sovereign_credit_score: 2,   banking_stability: 5  } },
    { geoCode: 'YE', geoName: 'Yemen',           dataYear: 2024, values: { epu_index: 500, world_uncertainty_idx: 322, sovereign_credit_score: 2,   banking_stability: 5  } },
    { geoCode: 'PS', geoName: 'Palestine',       dataYear: 2024, values: { epu_index: 480, world_uncertainty_idx: 305, sovereign_credit_score: 2,   banking_stability: 8  } },
    // ── Amérique Latine ────────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',          dataYear: 2024, values: { epu_index: 248, world_uncertainty_idx: 128, sovereign_credit_score: 50,  banking_stability: 60 } },
    { geoCode: 'AR', geoName: 'Argentina',       dataYear: 2024, values: { epu_index: 430, world_uncertainty_idx: 198, sovereign_credit_score: 18,  banking_stability: 35 } },
    { geoCode: 'CL', geoName: 'Chile',           dataYear: 2024, values: { epu_index: 172, world_uncertainty_idx: 92, sovereign_credit_score: 70,   banking_stability: 70 } },
    { geoCode: 'CO', geoName: 'Colombia',        dataYear: 2024, values: { epu_index: 212, world_uncertainty_idx: 118, sovereign_credit_score: 55,  banking_stability: 58 } },
    { geoCode: 'PE', geoName: 'Peru',            dataYear: 2024, values: { epu_index: 218, world_uncertainty_idx: 120, sovereign_credit_score: 60,  banking_stability: 60 } },
    { geoCode: 'EC', geoName: 'Ecuador',         dataYear: 2024, values: { epu_index: 255, world_uncertainty_idx: 138, sovereign_credit_score: 30,  banking_stability: 48 } },
    { geoCode: 'UY', geoName: 'Uruguay',         dataYear: 2024, values: { epu_index: 168, world_uncertainty_idx: 95, sovereign_credit_score: 60,   banking_stability: 65 } },
    { geoCode: 'BO', geoName: 'Bolivia',         dataYear: 2024, values: { epu_index: 265, world_uncertainty_idx: 142, sovereign_credit_score: 18,  banking_stability: 42 } },
    { geoCode: 'PY', geoName: 'Paraguay',        dataYear: 2024, values: { epu_index: 210, world_uncertainty_idx: 115, sovereign_credit_score: 42,  banking_stability: 52 } },
    { geoCode: 'VE', geoName: 'Venezuela',       dataYear: 2024, values: { epu_index: 492, world_uncertainty_idx: 270, sovereign_credit_score: 4,   banking_stability: 10 } },
    { geoCode: 'GT', geoName: 'Guatemala',       dataYear: 2024, values: { epu_index: 218, world_uncertainty_idx: 118, sovereign_credit_score: 36,  banking_stability: 50 } },
    { geoCode: 'HN', geoName: 'Honduras',        dataYear: 2024, values: { epu_index: 225, world_uncertainty_idx: 122, sovereign_credit_score: 30,  banking_stability: 45 } },
    { geoCode: 'SV', geoName: 'El Salvador',     dataYear: 2024, values: { epu_index: 215, world_uncertainty_idx: 118, sovereign_credit_score: 36,  banking_stability: 48 } },
    { geoCode: 'NI', geoName: 'Nicaragua',       dataYear: 2024, values: { epu_index: 238, world_uncertainty_idx: 130, sovereign_credit_score: 18,  banking_stability: 38 } },
    { geoCode: 'CR', geoName: 'Costa Rica',      dataYear: 2024, values: { epu_index: 185, world_uncertainty_idx: 98, sovereign_credit_score: 42,   banking_stability: 58 } },
    { geoCode: 'PA', geoName: 'Panama',          dataYear: 2024, values: { epu_index: 195, world_uncertainty_idx: 105, sovereign_credit_score: 42,  banking_stability: 58 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2024, values: { epu_index: 205, world_uncertainty_idx: 110, sovereign_credit_score: 42, banking_stability: 52 } },
    { geoCode: 'JM', geoName: 'Jamaica',         dataYear: 2024, values: { epu_index: 198, world_uncertainty_idx: 105, sovereign_credit_score: 42,  banking_stability: 50 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2024, values: { epu_index: 195, world_uncertainty_idx: 102, sovereign_credit_score: 42, banking_stability: 52 } },
    { geoCode: 'CU', geoName: 'Cuba',            dataYear: 2024, values: { epu_index: 312, world_uncertainty_idx: 178, sovereign_credit_score: 4,   banking_stability: 20 } },
    { geoCode: 'HT', geoName: 'Haiti',           dataYear: 2024, values: { epu_index: 402, world_uncertainty_idx: 272, sovereign_credit_score: 4,   banking_stability: 12 } },
    // ── Afrique du Nord ────────────────────────────────────────────────────
    { geoCode: 'MA', geoName: 'Morocco',         dataYear: 2024, values: { epu_index: 212, world_uncertainty_idx: 115, sovereign_credit_score: 50,  banking_stability: 58 } },
    { geoCode: 'EG', geoName: 'Egypt',           dataYear: 2024, values: { epu_index: 292, world_uncertainty_idx: 158, sovereign_credit_score: 48,  banking_stability: 50 } },
    { geoCode: 'TN', geoName: 'Tunisia',         dataYear: 2024, values: { epu_index: 270, world_uncertainty_idx: 150, sovereign_credit_score: 18,  banking_stability: 42 } },
    { geoCode: 'DZ', geoName: 'Algeria',         dataYear: 2024, values: { epu_index: 245, world_uncertainty_idx: 135, sovereign_credit_score: 36,  banking_stability: 45 } },
    { geoCode: 'LY', geoName: 'Libya',           dataYear: 2024, values: { epu_index: 422, world_uncertainty_idx: 268, sovereign_credit_score: 8,   banking_stability: 15 } },
    // ── Afrique subsaharienne ─────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',    dataYear: 2024, values: { epu_index: 242, world_uncertainty_idx: 138, sovereign_credit_score: 42,  banking_stability: 62 } },
    { geoCode: 'NG', geoName: 'Nigeria',         dataYear: 2024, values: { epu_index: 348, world_uncertainty_idx: 178, sovereign_credit_score: 30,  banking_stability: 45 } },
    { geoCode: 'KE', geoName: 'Kenya',           dataYear: 2024, values: { epu_index: 262, world_uncertainty_idx: 148, sovereign_credit_score: 30,  banking_stability: 48 } },
    { geoCode: 'GH', geoName: 'Ghana',           dataYear: 2024, values: { epu_index: 298, world_uncertainty_idx: 158, sovereign_credit_score: 12,  banking_stability: 42 } },
    { geoCode: 'SN', geoName: 'Senegal',         dataYear: 2024, values: { epu_index: 242, world_uncertainty_idx: 132, sovereign_credit_score: 42,  banking_stability: 50 } },
    { geoCode: 'ET', geoName: 'Ethiopia',        dataYear: 2024, values: { epu_index: 285, world_uncertainty_idx: 160, sovereign_credit_score: 18,  banking_stability: 35 } },
    { geoCode: 'TZ', geoName: 'Tanzania',        dataYear: 2024, values: { epu_index: 238, world_uncertainty_idx: 132, sovereign_credit_score: 30,  banking_stability: 48 } },
    { geoCode: 'RW', geoName: 'Rwanda',          dataYear: 2024, values: { epu_index: 215, world_uncertainty_idx: 118, sovereign_credit_score: 30,  banking_stability: 52 } },
    { geoCode: 'UG', geoName: 'Uganda',          dataYear: 2024, values: { epu_index: 252, world_uncertainty_idx: 138, sovereign_credit_score: 24,  banking_stability: 40 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',     dataYear: 2024, values: { epu_index: 235, world_uncertainty_idx: 130, sovereign_credit_score: 36,  banking_stability: 48 } },
    { geoCode: 'BJ', geoName: 'Benin',           dataYear: 2024, values: { epu_index: 228, world_uncertainty_idx: 125, sovereign_credit_score: 30,  banking_stability: 45 } },
    { geoCode: 'TG', geoName: 'Togo',            dataYear: 2024, values: { epu_index: 235, world_uncertainty_idx: 128, sovereign_credit_score: 24,  banking_stability: 42 } },
    { geoCode: 'CM', geoName: 'Cameroon',        dataYear: 2024, values: { epu_index: 258, world_uncertainty_idx: 145, sovereign_credit_score: 24,  banking_stability: 40 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',    dataYear: 2024, values: { epu_index: 332, world_uncertainty_idx: 212, sovereign_credit_score: 12,  banking_stability: 25 } },
    { geoCode: 'ML', geoName: 'Mali',            dataYear: 2024, values: { epu_index: 358, world_uncertainty_idx: 228, sovereign_credit_score: 8,   banking_stability: 22 } },
    { geoCode: 'NE', geoName: 'Niger',           dataYear: 2024, values: { epu_index: 348, world_uncertainty_idx: 218, sovereign_credit_score: 8,   banking_stability: 22 } },
    { geoCode: 'GN', geoName: 'Guinea',          dataYear: 2024, values: { epu_index: 295, world_uncertainty_idx: 165, sovereign_credit_score: 12,  banking_stability: 28 } },
    { geoCode: 'SD', geoName: 'Sudan',           dataYear: 2024, values: { epu_index: 442, world_uncertainty_idx: 288, sovereign_credit_score: 4,   banking_stability: 15 } },
    { geoCode: 'SS', geoName: 'South Sudan',     dataYear: 2024, values: { epu_index: 492, world_uncertainty_idx: 312, sovereign_credit_score: 2,   banking_stability: 5  } },
    { geoCode: 'SO', geoName: 'Somalia',         dataYear: 2024, values: { epu_index: 492, world_uncertainty_idx: 315, sovereign_credit_score: 2,   banking_stability: 5  } },
    { geoCode: 'CD', geoName: 'DR Congo',        dataYear: 2024, values: { epu_index: 382, world_uncertainty_idx: 242, sovereign_credit_score: 8,   banking_stability: 20 } },
    { geoCode: 'CG', geoName: 'Congo',           dataYear: 2024, values: { epu_index: 312, world_uncertainty_idx: 178, sovereign_credit_score: 12,  banking_stability: 28 } },
    { geoCode: 'TD', geoName: 'Chad',            dataYear: 2024, values: { epu_index: 355, world_uncertainty_idx: 225, sovereign_credit_score: 8,   banking_stability: 18 } },
    { geoCode: 'CF', geoName: 'Central African Republic', dataYear: 2024, values: { epu_index: 450, world_uncertainty_idx: 295, sovereign_credit_score: 4, banking_stability: 8 } },
    { geoCode: 'ZM', geoName: 'Zambia',          dataYear: 2024, values: { epu_index: 278, world_uncertainty_idx: 155, sovereign_credit_score: 18,  banking_stability: 38 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',        dataYear: 2024, values: { epu_index: 332, world_uncertainty_idx: 198, sovereign_credit_score: 4,   banking_stability: 20 } },
    { geoCode: 'AO', geoName: 'Angola',          dataYear: 2024, values: { epu_index: 268, world_uncertainty_idx: 148, sovereign_credit_score: 24,  banking_stability: 38 } },
    { geoCode: 'MZ', geoName: 'Mozambique',      dataYear: 2024, values: { epu_index: 295, world_uncertainty_idx: 162, sovereign_credit_score: 18,  banking_stability: 32 } },
    { geoCode: 'MG', geoName: 'Madagascar',      dataYear: 2024, values: { epu_index: 258, world_uncertainty_idx: 142, sovereign_credit_score: 18,  banking_stability: 35 } },
    { geoCode: 'MU', geoName: 'Mauritius',       dataYear: 2024, values: { epu_index: 145, world_uncertainty_idx: 65, sovereign_credit_score: 55,   banking_stability: 68 } },
    { geoCode: 'BW', geoName: 'Botswana',        dataYear: 2024, values: { epu_index: 160, world_uncertainty_idx: 75, sovereign_credit_score: 55,   banking_stability: 62 } },
    { geoCode: 'NA', geoName: 'Namibia',         dataYear: 2024, values: { epu_index: 212, world_uncertainty_idx: 115, sovereign_credit_score: 36,  banking_stability: 50 } },
    // ── Pacifique ─────────────────────────────────────────────────────────
    { geoCode: 'FJ', geoName: 'Fiji',            dataYear: 2024, values: { epu_index: 188, world_uncertainty_idx: 98, sovereign_credit_score: 30,   banking_stability: 48 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2024, values: { epu_index: 252, world_uncertainty_idx: 135, sovereign_credit_score: 30,  banking_stability: 38 } },
  ],
};

export default marketStressModule;
