import type { DomainModule } from '@/lib/domains/types';

const waterBiodiversityModule: DomainModule = {
  definition: {
    id: 'water-biodiversity',
    label: { fr: 'Eau & Biodiversit\u00e9', en: 'Water & Biodiversity', es: 'Agua y Biodiversidad' },
    description: {
      fr: 'Acc\u00e8s \u00e0 l\'eau potable, stress hydrique, esp\u00e8ces menac\u00e9es et protection des \u00e9cosyst\u00e8mes naturels.',
      en: 'Access to safe drinking water, water stress, threatened species and natural ecosystem protection.',
      es: 'Acceso al agua potable, estrés hídrico, especies amenazadas y protección de ecosistemas naturales.',
    },
    icon: '\uD83C\uDF0A',
    group: 'environment',
    active: true,
    seedSources: [
      'https://washdata.org/',
      'https://www.fao.org/aquastat/',
      'https://www.iucnredlist.org/',
      'https://www.protectedplanet.net/',
    ],
    indicators: [
      {
        id: 'safe_water_access',
        label: { fr: 'Acc\u00e8s eau potable', en: 'Safe water access', es: 'Acceso a agua potable' },
        unit: 'percent',
        unitLabel: { fr: '% pop.', en: '% pop.', es: '% pob.' },
        direction: 'higher_is_better',
        weight: 4,
        thresholds: { excellent: 99, good: 95, fair: 85, poor: 70 },
        minValue: 0,
        maxValue: 100,
      },
      {
        id: 'water_stress',
        label: { fr: 'Stress hydrique', en: 'Water stress', es: 'Estrés hídrico' },
        unit: 'percent',
        unitLabel: { fr: '% ress.', en: '% res.', es: '% rec.' },
        direction: 'lower_is_better',
        weight: 3,
        thresholds: { excellent: 10, good: 25, fair: 50, poor: 80 },
        minValue: 0,
        maxValue: 100,
      },
      {
        id: 'threatened_species',
        label: { fr: 'Esp\u00e8ces menac\u00e9es', en: 'Threatened species', es: 'Especies amenazadas' },
        unit: 'percent',
        unitLabel: { fr: '% esp\u00e8ces', en: '% species', es: '% especies' },
        direction: 'lower_is_better',
        weight: 2,
        thresholds: { excellent: 5, good: 12, fair: 20, poor: 35 },
        minValue: 0,
        maxValue: 100,
      },
      {
        id: 'protected_areas',
        label: { fr: 'Aires prot\u00e9g\u00e9es', en: 'Protected areas', es: 'Áreas protegidas' },
        unit: 'percent',
        unitLabel: { fr: '% territ.', en: '% land', es: '% territ.' },
        direction: 'higher_is_better',
        weight: 2,
        thresholds: { excellent: 25, good: 17, fair: 10, poor: 5 },
        minValue: 0,
        maxValue: 100,
      },
    ],
  },
  seedData: [
    // ── Europe ──────────────────────────────────────────────────────────────
    { geoCode: 'IS', geoName: 'Iceland',              dataYear: 2023, values: { safe_water_access: 100,  water_stress: 1,   threatened_species: 6,   protected_areas: 25 } },
    { geoCode: 'NO', geoName: 'Norway',               dataYear: 2023, values: { safe_water_access: 100,  water_stress: 3,   threatened_species: 4,   protected_areas: 17 } },
    { geoCode: 'SE', geoName: 'Sweden',               dataYear: 2023, values: { safe_water_access: 100,  water_stress: 3,   threatened_species: 7,   protected_areas: 15 } },
    { geoCode: 'FI', geoName: 'Finland',              dataYear: 2023, values: { safe_water_access: 100,  water_stress: 3,   threatened_species: 5,   protected_areas: 13 } },
    { geoCode: 'AT', geoName: 'Austria',              dataYear: 2023, values: { safe_water_access: 100,  water_stress: 5,   threatened_species: 13,  protected_areas: 29 } },
    { geoCode: 'DK', geoName: 'Denmark',              dataYear: 2023, values: { safe_water_access: 100,  water_stress: 12,  threatened_species: 8,   protected_areas: 15 } },
    { geoCode: 'CH', geoName: 'Switzerland',           dataYear: 2023, values: { safe_water_access: 100,  water_stress: 5,   threatened_species: 12,  protected_areas: 13 } },
    { geoCode: 'PT', geoName: 'Portugal',             dataYear: 2023, values: { safe_water_access: 99,   water_stress: 18,  threatened_species: 14,  protected_areas: 22 } },
    { geoCode: 'HR', geoName: 'Croatia',              dataYear: 2023, values: { safe_water_access: 99,   water_stress: 3,   threatened_species: 10,  protected_areas: 38 } },
    { geoCode: 'RO', geoName: 'Romania',              dataYear: 2023, values: { safe_water_access: 97,   water_stress: 6,   threatened_species: 9,   protected_areas: 23 } },
    { geoCode: 'FR', geoName: 'France',               dataYear: 2023, values: { safe_water_access: 100,  water_stress: 20,  threatened_species: 15,  protected_areas: 32 } },
    { geoCode: 'IE', geoName: 'Ireland',              dataYear: 2023, values: { safe_water_access: 99,   water_stress: 2,   threatened_species: 6,   protected_areas: 14 } },
    { geoCode: 'ES', geoName: 'Spain',                dataYear: 2023, values: { safe_water_access: 100,  water_stress: 35,  threatened_species: 17,  protected_areas: 28 } },
    { geoCode: 'DE', geoName: 'Germany',              dataYear: 2023, values: { safe_water_access: 100,  water_stress: 20,  threatened_species: 12,  protected_areas: 38 } },
    { geoCode: 'IT', geoName: 'Italy',                dataYear: 2023, values: { safe_water_access: 100,  water_stress: 30,  threatened_species: 16,  protected_areas: 22 } },
    { geoCode: 'NL', geoName: 'Netherlands',          dataYear: 2023, values: { safe_water_access: 100,  water_stress: 10,  threatened_species: 9,   protected_areas: 21 } },
    { geoCode: 'BE', geoName: 'Belgium',              dataYear: 2023, values: { safe_water_access: 100,  water_stress: 30,  threatened_species: 10,  protected_areas: 14 } },
    { geoCode: 'GB', geoName: 'United Kingdom',       dataYear: 2023, values: { safe_water_access: 100,  water_stress: 14,  threatened_species: 8,   protected_areas: 28 } },
    { geoCode: 'GR', geoName: 'Greece',               dataYear: 2023, values: { safe_water_access: 100,  water_stress: 42,  threatened_species: 18,  protected_areas: 35 } },
    { geoCode: 'SK', geoName: 'Slovakia',             dataYear: 2023, values: { safe_water_access: 99,   water_stress: 5,   threatened_species: 8,   protected_areas: 38 } },
    { geoCode: 'CZ', geoName: 'Czechia',              dataYear: 2023, values: { safe_water_access: 100,  water_stress: 12,  threatened_species: 9,   protected_areas: 22 } },
    { geoCode: 'PL', geoName: 'Poland',               dataYear: 2023, values: { safe_water_access: 99,   water_stress: 18,  threatened_species: 8,   protected_areas: 40 } },
    { geoCode: 'HU', geoName: 'Hungary',              dataYear: 2023, values: { safe_water_access: 99,   water_stress: 10,  threatened_species: 10,  protected_areas: 22 } },
    { geoCode: 'BG', geoName: 'Bulgaria',             dataYear: 2023, values: { safe_water_access: 99,   water_stress: 5,   threatened_species: 11,  protected_areas: 35 } },
    { geoCode: 'LU', geoName: 'Luxembourg',           dataYear: 2023, values: { safe_water_access: 100,  water_stress: 4,   threatened_species: 7,   protected_areas: 27 } },
    { geoCode: 'EE', geoName: 'Estonia',              dataYear: 2023, values: { safe_water_access: 99,   water_stress: 4,   threatened_species: 5,   protected_areas: 22 } },
    { geoCode: 'LT', geoName: 'Lithuania',            dataYear: 2023, values: { safe_water_access: 99,   water_stress: 4,   threatened_species: 5,   protected_areas: 18 } },
    { geoCode: 'LV', geoName: 'Latvia',               dataYear: 2023, values: { safe_water_access: 99,   water_stress: 3,   threatened_species: 5,   protected_areas: 18 } },
    { geoCode: 'SI', geoName: 'Slovenia',             dataYear: 2023, values: { safe_water_access: 100,  water_stress: 3,   threatened_species: 11,  protected_areas: 40 } },
    { geoCode: 'RS', geoName: 'Serbia',               dataYear: 2023, values: { safe_water_access: 96,   water_stress: 5,   threatened_species: 9,   protected_areas: 8 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2023, values: { safe_water_access: 95,   water_stress: 3,   threatened_species: 8,   protected_areas: 3 } },
    { geoCode: 'AL', geoName: 'Albania',              dataYear: 2023, values: { safe_water_access: 94,   water_stress: 6,   threatened_species: 10,  protected_areas: 18 } },
    { geoCode: 'MK', geoName: 'North Macedonia',      dataYear: 2023, values: { safe_water_access: 96,   water_stress: 14,  threatened_species: 8,   protected_areas: 10 } },
    { geoCode: 'ME', geoName: 'Montenegro',           dataYear: 2023, values: { safe_water_access: 97,   water_stress: 3,   threatened_species: 9,   protected_areas: 13 } },
    { geoCode: 'MT', geoName: 'Malta',                dataYear: 2023, values: { safe_water_access: 100,  water_stress: 75,  threatened_species: 11,  protected_areas: 35 } },
    { geoCode: 'CY', geoName: 'Cyprus',               dataYear: 2023, values: { safe_water_access: 100,  water_stress: 60,  threatened_species: 10,  protected_areas: 19 } },
    { geoCode: 'MD', geoName: 'Moldova',              dataYear: 2023, values: { safe_water_access: 87,   water_stress: 9,   threatened_species: 6,   protected_areas: 6 } },

    // ── North America ───────────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',        dataYear: 2023, values: { safe_water_access: 99,   water_stress: 42,  threatened_species: 14,  protected_areas: 13 } },
    { geoCode: 'CA', geoName: 'Canada',               dataYear: 2023, values: { safe_water_access: 99,   water_stress: 2,   threatened_species: 8,   protected_areas: 13 } },
    { geoCode: 'MX', geoName: 'Mexico',               dataYear: 2023, values: { safe_water_access: 97,   water_stress: 45,  threatened_species: 18,  protected_areas: 14 } },

    // ── Central America & Caribbean ─────────────────────────────────────────
    { geoCode: 'GT', geoName: 'Guatemala',            dataYear: 2023, values: { safe_water_access: 90,   water_stress: 4,   threatened_species: 14,  protected_areas: 32 } },
    { geoCode: 'HN', geoName: 'Honduras',             dataYear: 2023, values: { safe_water_access: 87,   water_stress: 4,   threatened_species: 13,  protected_areas: 26 } },
    { geoCode: 'SV', geoName: 'El Salvador',          dataYear: 2023, values: { safe_water_access: 91,   water_stress: 12,  threatened_species: 10,  protected_areas: 14 } },
    { geoCode: 'CR', geoName: 'Costa Rica',           dataYear: 2023, values: { safe_water_access: 98,   water_stress: 3,   threatened_species: 15,  protected_areas: 28 } },
    { geoCode: 'PA', geoName: 'Panama',               dataYear: 2023, values: { safe_water_access: 96,   water_stress: 1,   threatened_species: 14,  protected_areas: 26 } },
    { geoCode: 'JM', geoName: 'Jamaica',              dataYear: 2023, values: { safe_water_access: 92,   water_stress: 10,  threatened_species: 18,  protected_areas: 19 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago',  dataYear: 2023, values: { safe_water_access: 97,   water_stress: 18,  threatened_species: 10,  protected_areas: 31 } },
    { geoCode: 'DO', geoName: 'Dominican Republic',   dataYear: 2023, values: { safe_water_access: 93,   water_stress: 28,  threatened_species: 15,  protected_areas: 26 } },

    // ── South America ───────────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',               dataYear: 2023, values: { safe_water_access: 97,   water_stress: 2,   threatened_species: 12,  protected_areas: 30 } },
    { geoCode: 'AR', geoName: 'Argentina',            dataYear: 2023, values: { safe_water_access: 98,   water_stress: 11,  threatened_species: 10,  protected_areas: 9 } },
    { geoCode: 'CL', geoName: 'Chile',                dataYear: 2023, values: { safe_water_access: 100,  water_stress: 35,  threatened_species: 14,  protected_areas: 21 } },
    { geoCode: 'CO', geoName: 'Colombia',             dataYear: 2023, values: { safe_water_access: 97,   water_stress: 3,   threatened_species: 16,  protected_areas: 15 } },
    { geoCode: 'PE', geoName: 'Peru',                 dataYear: 2023, values: { safe_water_access: 92,   water_stress: 4,   threatened_species: 14,  protected_areas: 19 } },
    { geoCode: 'VE', geoName: 'Venezuela',            dataYear: 2023, values: { safe_water_access: 88,   water_stress: 5,   threatened_species: 16,  protected_areas: 54 } },
    { geoCode: 'EC', geoName: 'Ecuador',              dataYear: 2023, values: { safe_water_access: 94,   water_stress: 5,   threatened_species: 20,  protected_areas: 20 } },
    { geoCode: 'UY', geoName: 'Uruguay',              dataYear: 2023, values: { safe_water_access: 100,  water_stress: 4,   threatened_species: 8,   protected_areas: 3 } },
    { geoCode: 'PY', geoName: 'Paraguay',             dataYear: 2023, values: { safe_water_access: 93,   water_stress: 1,   threatened_species: 7,   protected_areas: 8 } },
    { geoCode: 'BO', geoName: 'Bolivia',              dataYear: 2023, values: { safe_water_access: 86,   water_stress: 2,   threatened_species: 11,  protected_areas: 22 } },

    // ── East Asia ───────────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',                dataYear: 2023, values: { safe_water_access: 99,   water_stress: 21,  threatened_species: 18,  protected_areas: 21 } },
    { geoCode: 'KR', geoName: 'South Korea',          dataYear: 2023, values: { safe_water_access: 99,   water_stress: 40,  threatened_species: 10,  protected_areas: 17 } },
    { geoCode: 'CN', geoName: 'China',                dataYear: 2023, values: { safe_water_access: 95,   water_stress: 43,  threatened_species: 13,  protected_areas: 18 } },
    { geoCode: 'TW', geoName: 'Taiwan',               dataYear: 2023, values: { safe_water_access: 99,   water_stress: 30,  threatened_species: 15,  protected_areas: 19 } },
    { geoCode: 'MN', geoName: 'Mongolia',             dataYear: 2023, values: { safe_water_access: 78,   water_stress: 4,   threatened_species: 7,   protected_areas: 21 } },

    // ── Southeast Asia ──────────────────────────────────────────────────────
    { geoCode: 'SG', geoName: 'Singapore',            dataYear: 2023, values: { safe_water_access: 100,  water_stress: 52,  threatened_species: 17,  protected_areas: 5 } },
    { geoCode: 'TH', geoName: 'Thailand',             dataYear: 2023, values: { safe_water_access: 98,   water_stress: 15,  threatened_species: 16,  protected_areas: 19 } },
    { geoCode: 'VN', geoName: 'Vietnam',              dataYear: 2023, values: { safe_water_access: 94,   water_stress: 14,  threatened_species: 17,  protected_areas: 9 } },
    { geoCode: 'ID', geoName: 'Indonesia',            dataYear: 2023, values: { safe_water_access: 90,   water_stress: 15,  threatened_species: 20,  protected_areas: 14 } },
    { geoCode: 'PH', geoName: 'Philippines',          dataYear: 2023, values: { safe_water_access: 93,   water_stress: 21,  threatened_species: 22,  protected_areas: 16 } },
    { geoCode: 'MY', geoName: 'Malaysia',             dataYear: 2023, values: { safe_water_access: 97,   water_stress: 7,   threatened_species: 19,  protected_areas: 20 } },
    { geoCode: 'MM', geoName: 'Myanmar',              dataYear: 2023, values: { safe_water_access: 74,   water_stress: 5,   threatened_species: 15,  protected_areas: 7 } },
    { geoCode: 'KH', geoName: 'Cambodia',             dataYear: 2023, values: { safe_water_access: 74,   water_stress: 2,   threatened_species: 14,  protected_areas: 26 } },
    { geoCode: 'LA', geoName: 'Laos',                 dataYear: 2023, values: { safe_water_access: 78,   water_stress: 2,   threatened_species: 13,  protected_areas: 22 } },
    { geoCode: 'BN', geoName: 'Brunei',               dataYear: 2023, values: { safe_water_access: 100,  water_stress: 1,   threatened_species: 12,  protected_areas: 44 } },

    // ── South Asia ──────────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',                dataYear: 2023, values: { safe_water_access: 88,   water_stress: 66,  threatened_species: 16,  protected_areas: 6 } },
    { geoCode: 'PK', geoName: 'Pakistan',             dataYear: 2023, values: { safe_water_access: 78,   water_stress: 90,  threatened_species: 12,  protected_areas: 12 } },
    { geoCode: 'BD', geoName: 'Bangladesh',           dataYear: 2023, values: { safe_water_access: 58,   water_stress: 8,   threatened_species: 12,  protected_areas: 5 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',            dataYear: 2023, values: { safe_water_access: 92,   water_stress: 25,  threatened_species: 22,  protected_areas: 30 } },
    { geoCode: 'NP', geoName: 'Nepal',                dataYear: 2023, values: { safe_water_access: 82,   water_stress: 6,   threatened_species: 12,  protected_areas: 24 } },
    { geoCode: 'AF', geoName: 'Afghanistan',          dataYear: 2023, values: { safe_water_access: 49,   water_stress: 58,  threatened_species: 7,   protected_areas: 4 } },

    // ── Central Asia ────────────────────────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',           dataYear: 2023, values: { safe_water_access: 93,   water_stress: 23,  threatened_species: 7,   protected_areas: 9 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',           dataYear: 2023, values: { safe_water_access: 87,   water_stress: 95,  threatened_species: 7,   protected_areas: 4 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',         dataYear: 2023, values: { safe_water_access: 82,   water_stress: 100, threatened_species: 6,   protected_areas: 3 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',           dataYear: 2023, values: { safe_water_access: 86,   water_stress: 42,  threatened_species: 5,   protected_areas: 7 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',           dataYear: 2023, values: { safe_water_access: 78,   water_stress: 60,  threatened_species: 6,   protected_areas: 22 } },

    // ── Middle East ─────────────────────────────────────────────────────────
    { geoCode: 'SA', geoName: 'Saudi Arabia',         dataYear: 2023, values: { safe_water_access: 99,   water_stress: 100, threatened_species: 10,  protected_areas: 8 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2023, values: { safe_water_access: 99,   water_stress: 100, threatened_species: 9,   protected_areas: 16 } },
    { geoCode: 'IL', geoName: 'Israel',               dataYear: 2023, values: { safe_water_access: 100,  water_stress: 67,  threatened_species: 15,  protected_areas: 18 } },
    { geoCode: 'TR', geoName: 'Turkey',               dataYear: 2023, values: { safe_water_access: 98,   water_stress: 46,  threatened_species: 14,  protected_areas: 9 } },
    { geoCode: 'IR', geoName: 'Iran',                 dataYear: 2023, values: { safe_water_access: 95,   water_stress: 85,  threatened_species: 12,  protected_areas: 10 } },
    { geoCode: 'IQ', geoName: 'Iraq',                 dataYear: 2023, values: { safe_water_access: 86,   water_stress: 78,  threatened_species: 8,   protected_areas: 2 } },
    { geoCode: 'JO', geoName: 'Jordan',               dataYear: 2023, values: { safe_water_access: 97,   water_stress: 100, threatened_species: 10,  protected_areas: 10 } },
    { geoCode: 'LB', geoName: 'Lebanon',              dataYear: 2023, values: { safe_water_access: 92,   water_stress: 52,  threatened_species: 11,  protected_areas: 3 } },
    { geoCode: 'KW', geoName: 'Kuwait',               dataYear: 2023, values: { safe_water_access: 100,  water_stress: 100, threatened_species: 7,   protected_areas: 2 } },
    { geoCode: 'QA', geoName: 'Qatar',                dataYear: 2023, values: { safe_water_access: 100,  water_stress: 100, threatened_species: 6,   protected_areas: 9 } },
    { geoCode: 'BH', geoName: 'Bahrain',              dataYear: 2023, values: { safe_water_access: 100,  water_stress: 100, threatened_species: 8,   protected_areas: 5 } },
    { geoCode: 'OM', geoName: 'Oman',                 dataYear: 2023, values: { safe_water_access: 93,   water_stress: 90,  threatened_species: 10,  protected_areas: 4 } },

    // ── North Africa ────────────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',                dataYear: 2023, values: { safe_water_access: 98,   water_stress: 100, threatened_species: 10,  protected_areas: 13 } },
    { geoCode: 'MA', geoName: 'Morocco',              dataYear: 2023, values: { safe_water_access: 87,   water_stress: 44,  threatened_species: 12,  protected_areas: 31 } },
    { geoCode: 'DZ', geoName: 'Algeria',              dataYear: 2023, values: { safe_water_access: 93,   water_stress: 65,  threatened_species: 9,   protected_areas: 8 } },
    { geoCode: 'TN', geoName: 'Tunisia',              dataYear: 2023, values: { safe_water_access: 96,   water_stress: 75,  threatened_species: 10,  protected_areas: 9 } },
    { geoCode: 'LY', geoName: 'Libya',                dataYear: 2023, values: { safe_water_access: 85,   water_stress: 100, threatened_species: 8,   protected_areas: 1 } },

    // ── Sub-Saharan Africa ──────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',         dataYear: 2023, values: { safe_water_access: 91,   water_stress: 56,  threatened_species: 13,  protected_areas: 13 } },
    { geoCode: 'NG', geoName: 'Nigeria',              dataYear: 2023, values: { safe_water_access: 72,   water_stress: 10,  threatened_species: 11,  protected_areas: 14 } },
    { geoCode: 'KE', geoName: 'Kenya',                dataYear: 2023, values: { safe_water_access: 63,   water_stress: 26,  threatened_species: 14,  protected_areas: 13 } },
    { geoCode: 'ET', geoName: 'Ethiopia',             dataYear: 2023, values: { safe_water_access: 50,   water_stress: 11,  threatened_species: 10,  protected_areas: 18 } },
    { geoCode: 'GH', geoName: 'Ghana',                dataYear: 2023, values: { safe_water_access: 80,   water_stress: 8,   threatened_species: 9,   protected_areas: 15 } },
    { geoCode: 'TZ', geoName: 'Tanzania',             dataYear: 2023, values: { safe_water_access: 57,   water_stress: 6,   threatened_species: 16,  protected_areas: 38 } },
    { geoCode: 'UG', geoName: 'Uganda',               dataYear: 2023, values: { safe_water_access: 54,   water_stress: 4,   threatened_species: 13,  protected_areas: 16 } },
    { geoCode: 'RW', geoName: 'Rwanda',               dataYear: 2023, values: { safe_water_access: 60,   water_stress: 3,   threatened_species: 10,  protected_areas: 10 } },
    { geoCode: 'SN', geoName: 'Senegal',              dataYear: 2023, values: { safe_water_access: 76,   water_stress: 12,  threatened_species: 10,  protected_areas: 25 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',          dataYear: 2023, values: { safe_water_access: 68,   water_stress: 4,   threatened_species: 11,  protected_areas: 23 } },
    { geoCode: 'CM', geoName: 'Cameroon',             dataYear: 2023, values: { safe_water_access: 63,   water_stress: 1,   threatened_species: 15,  protected_areas: 14 } },
    { geoCode: 'AO', geoName: 'Angola',               dataYear: 2023, values: { safe_water_access: 56,   water_stress: 1,   threatened_species: 9,   protected_areas: 12 } },
    { geoCode: 'MZ', geoName: 'Mozambique',           dataYear: 2023, values: { safe_water_access: 52,   water_stress: 2,   threatened_species: 11,  protected_areas: 26 } },
    { geoCode: 'MG', geoName: 'Madagascar',           dataYear: 2023, values: { safe_water_access: 51,   water_stress: 6,   threatened_species: 30,  protected_areas: 10 } },
    { geoCode: 'CD', geoName: 'DR Congo',             dataYear: 2023, values: { safe_water_access: 43,   water_stress: 1,   threatened_species: 14,  protected_areas: 13 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',             dataYear: 2023, values: { safe_water_access: 62,   water_stress: 20,  threatened_species: 7,   protected_areas: 28 } },
    { geoCode: 'BW', geoName: 'Botswana',             dataYear: 2023, values: { safe_water_access: 79,   water_stress: 9,   threatened_species: 5,   protected_areas: 29 } },
    { geoCode: 'NA', geoName: 'Namibia',              dataYear: 2023, values: { safe_water_access: 82,   water_stress: 7,   threatened_species: 6,   protected_areas: 38 } },
    { geoCode: 'MU', geoName: 'Mauritius',            dataYear: 2023, values: { safe_water_access: 100,  water_stress: 26,  threatened_species: 24,  protected_areas: 5 } },
    { geoCode: 'GA', geoName: 'Gabon',                dataYear: 2023, values: { safe_water_access: 84,   water_stress: 1,   threatened_species: 10,  protected_areas: 21 } },

    // ── Oceania ─────────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',            dataYear: 2023, values: { safe_water_access: 100,  water_stress: 18,  threatened_species: 22,  protected_areas: 21 } },
    { geoCode: 'NZ', geoName: 'New Zealand',          dataYear: 2023, values: { safe_water_access: 100,  water_stress: 4,   threatened_species: 28,  protected_areas: 33 } },
    { geoCode: 'FJ', geoName: 'Fiji',                 dataYear: 2023, values: { safe_water_access: 90,   water_stress: 1,   threatened_species: 14,  protected_areas: 4 } },

    // ── Ex-USSR ─────────────────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',               dataYear: 2023, values: { safe_water_access: 96,   water_stress: 5,   threatened_species: 8,   protected_areas: 12 } },
    { geoCode: 'UA', geoName: 'Ukraine',              dataYear: 2023, values: { safe_water_access: 94,   water_stress: 18,  threatened_species: 8,   protected_areas: 8 } },
    { geoCode: 'BY', geoName: 'Belarus',              dataYear: 2023, values: { safe_water_access: 96,   water_stress: 4,   threatened_species: 5,   protected_areas: 9 } },

    // ── Additional Africa ───────────────────────────────────────────────────
    { geoCode: 'ML', geoName: 'Mali',                 dataYear: 2023, values: { safe_water_access: 47,   water_stress: 8,   threatened_species: 7,   protected_areas: 4 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',         dataYear: 2023, values: { safe_water_access: 48,   water_stress: 7,   threatened_species: 6,   protected_areas: 15 } },
    { geoCode: 'NE', geoName: 'Niger',                dataYear: 2023, values: { safe_water_access: 42,   water_stress: 11,  threatened_species: 5,   protected_areas: 8 } },
    { geoCode: 'TD', geoName: 'Chad',                 dataYear: 2023, values: { safe_water_access: 39,   water_stress: 6,   threatened_species: 6,   protected_areas: 17 } },
    { geoCode: 'MW', geoName: 'Malawi',               dataYear: 2023, values: { safe_water_access: 65,   water_stress: 9,   threatened_species: 10,  protected_areas: 18 } },
    { geoCode: 'ZM', geoName: 'Zambia',               dataYear: 2023, values: { safe_water_access: 58,   water_stress: 3,   threatened_species: 8,   protected_areas: 38 } },
    { geoCode: 'SD', geoName: 'Sudan',                dataYear: 2023, values: { safe_water_access: 58,   water_stress: 100, threatened_species: 8,   protected_areas: 5 } },
    { geoCode: 'SO', geoName: 'Somalia',              dataYear: 2023, values: { safe_water_access: 38,   water_stress: 33,  threatened_species: 10,  protected_areas: 1 } },
    { geoCode: 'SS', geoName: 'South Sudan',          dataYear: 2023, values: { safe_water_access: 35,   water_stress: 3,   threatened_species: 6,   protected_areas: 13 } },
    { geoCode: 'ER', geoName: 'Eritrea',              dataYear: 2023, values: { safe_water_access: 44,   water_stress: 50,  threatened_species: 7,   protected_areas: 5 } },
    { geoCode: 'DJ', geoName: 'Djibouti',             dataYear: 2023, values: { safe_water_access: 63,   water_stress: 45,  threatened_species: 8,   protected_areas: 2 } },
    { geoCode: 'GM', geoName: 'Gambia',               dataYear: 2023, values: { safe_water_access: 75,   water_stress: 4,   threatened_species: 7,   protected_areas: 6 } },
    { geoCode: 'GW', geoName: 'Guinea-Bissau',        dataYear: 2023, values: { safe_water_access: 60,   water_stress: 1,   threatened_species: 8,   protected_areas: 26 } },
    { geoCode: 'GN', geoName: 'Guinea',               dataYear: 2023, values: { safe_water_access: 55,   water_stress: 2,   threatened_species: 13,  protected_areas: 28 } },
    { geoCode: 'SL', geoName: 'Sierra Leone',         dataYear: 2023, values: { safe_water_access: 52,   water_stress: 1,   threatened_species: 11,  protected_areas: 5 } },
    { geoCode: 'LR', geoName: 'Liberia',              dataYear: 2023, values: { safe_water_access: 48,   water_stress: 1,   threatened_species: 14,  protected_areas: 4 } },
    { geoCode: 'TG', geoName: 'Togo',                 dataYear: 2023, values: { safe_water_access: 62,   water_stress: 3,   threatened_species: 7,   protected_areas: 11 } },
    { geoCode: 'BJ', geoName: 'Benin',                dataYear: 2023, values: { safe_water_access: 56,   water_stress: 3,   threatened_species: 7,   protected_areas: 28 } },
    { geoCode: 'CG', geoName: 'Republic of Congo',    dataYear: 2023, values: { safe_water_access: 59,   water_stress: 1,   threatened_species: 9,   protected_areas: 36 } },
    { geoCode: 'CF', geoName: 'Central African Republic', dataYear: 2023, values: { safe_water_access: 37, water_stress: 1, threatened_species: 8,   protected_areas: 18 } },
    { geoCode: 'BI', geoName: 'Burundi',              dataYear: 2023, values: { safe_water_access: 54,   water_stress: 4,   threatened_species: 10,  protected_areas: 7 } },
    { geoCode: 'SZ', geoName: 'Eswatini',             dataYear: 2023, values: { safe_water_access: 68,   water_stress: 28,  threatened_species: 5,   protected_areas: 4 } },
    { geoCode: 'LS', geoName: 'Lesotho',              dataYear: 2023, values: { safe_water_access: 67,   water_stress: 6,   threatened_species: 4,   protected_areas: 1 } },

    // ── Additional Asia & Pacific ───────────────────────────────────────────
    { geoCode: 'GE', geoName: 'Georgia',              dataYear: 2023, values: { safe_water_access: 96,   water_stress: 5,   threatened_species: 9,   protected_areas: 10 } },
    { geoCode: 'AM', geoName: 'Armenia',              dataYear: 2023, values: { safe_water_access: 98,   water_stress: 48,  threatened_species: 8,   protected_areas: 13 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',           dataYear: 2023, values: { safe_water_access: 87,   water_stress: 52,  threatened_species: 7,   protected_areas: 9 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea',     dataYear: 2023, values: { safe_water_access: 43,   water_stress: 1,   threatened_species: 16,  protected_areas: 3 } },
    { geoCode: 'NI', geoName: 'Nicaragua',            dataYear: 2023, values: { safe_water_access: 82,   water_stress: 2,   threatened_species: 10,  protected_areas: 38 } },
    { geoCode: 'CU', geoName: 'Cuba',                 dataYear: 2023, values: { safe_water_access: 96,   water_stress: 18,  threatened_species: 16,  protected_areas: 18 } },
    { geoCode: 'HT', geoName: 'Haiti',                dataYear: 2023, values: { safe_water_access: 54,   water_stress: 14,  threatened_species: 14,  protected_areas: 1 } },
    { geoCode: 'YE', geoName: 'Yemen',                dataYear: 2023, values: { safe_water_access: 55,   water_stress: 100, threatened_species: 10,  protected_areas: 1 } },
    { geoCode: 'SY', geoName: 'Syria',                dataYear: 2023, values: { safe_water_access: 79,   water_stress: 90,  threatened_species: 9,   protected_areas: 1 } },
    { geoCode: 'PS', geoName: 'Palestine',            dataYear: 2023, values: { safe_water_access: 89,   water_stress: 50,  threatened_species: 7,   protected_areas: 2 } },
  ],
  seedDataPrev: [
    // ── Europe ──────────────────────────────────────────────────────────────
    { geoCode: 'IS', geoName: 'Iceland',              dataYear: 2022, values: { safe_water_access: 100,  water_stress: 1,   threatened_species: 6,   protected_areas: 24 } },
    { geoCode: 'NO', geoName: 'Norway',               dataYear: 2022, values: { safe_water_access: 100,  water_stress: 3,   threatened_species: 4,   protected_areas: 17 } },
    { geoCode: 'SE', geoName: 'Sweden',               dataYear: 2022, values: { safe_water_access: 100,  water_stress: 3,   threatened_species: 7,   protected_areas: 15 } },
    { geoCode: 'FI', geoName: 'Finland',              dataYear: 2022, values: { safe_water_access: 100,  water_stress: 3,   threatened_species: 5,   protected_areas: 13 } },
    { geoCode: 'AT', geoName: 'Austria',              dataYear: 2022, values: { safe_water_access: 100,  water_stress: 5,   threatened_species: 13,  protected_areas: 28 } },
    { geoCode: 'DK', geoName: 'Denmark',              dataYear: 2022, values: { safe_water_access: 100,  water_stress: 12,  threatened_species: 8,   protected_areas: 15 } },
    { geoCode: 'CH', geoName: 'Switzerland',           dataYear: 2022, values: { safe_water_access: 100,  water_stress: 5,   threatened_species: 12,  protected_areas: 13 } },
    { geoCode: 'PT', geoName: 'Portugal',             dataYear: 2022, values: { safe_water_access: 99,   water_stress: 17,  threatened_species: 14,  protected_areas: 22 } },
    { geoCode: 'HR', geoName: 'Croatia',              dataYear: 2022, values: { safe_water_access: 99,   water_stress: 3,   threatened_species: 10,  protected_areas: 37 } },
    { geoCode: 'RO', geoName: 'Romania',              dataYear: 2022, values: { safe_water_access: 96,   water_stress: 6,   threatened_species: 9,   protected_areas: 23 } },
    { geoCode: 'FR', geoName: 'France',               dataYear: 2022, values: { safe_water_access: 100,  water_stress: 19,  threatened_species: 15,  protected_areas: 32 } },
    { geoCode: 'IE', geoName: 'Ireland',              dataYear: 2022, values: { safe_water_access: 99,   water_stress: 2,   threatened_species: 6,   protected_areas: 14 } },
    { geoCode: 'ES', geoName: 'Spain',                dataYear: 2022, values: { safe_water_access: 100,  water_stress: 34,  threatened_species: 17,  protected_areas: 28 } },
    { geoCode: 'DE', geoName: 'Germany',              dataYear: 2022, values: { safe_water_access: 100,  water_stress: 20,  threatened_species: 12,  protected_areas: 37 } },
    { geoCode: 'IT', geoName: 'Italy',                dataYear: 2022, values: { safe_water_access: 100,  water_stress: 29,  threatened_species: 16,  protected_areas: 22 } },
    { geoCode: 'NL', geoName: 'Netherlands',          dataYear: 2022, values: { safe_water_access: 100,  water_stress: 10,  threatened_species: 9,   protected_areas: 21 } },
    { geoCode: 'BE', geoName: 'Belgium',              dataYear: 2022, values: { safe_water_access: 100,  water_stress: 30,  threatened_species: 10,  protected_areas: 14 } },
    { geoCode: 'GB', geoName: 'United Kingdom',       dataYear: 2022, values: { safe_water_access: 100,  water_stress: 14,  threatened_species: 8,   protected_areas: 28 } },
    { geoCode: 'GR', geoName: 'Greece',               dataYear: 2022, values: { safe_water_access: 100,  water_stress: 41,  threatened_species: 18,  protected_areas: 35 } },
    { geoCode: 'SK', geoName: 'Slovakia',             dataYear: 2022, values: { safe_water_access: 99,   water_stress: 5,   threatened_species: 8,   protected_areas: 37 } },
    { geoCode: 'CZ', geoName: 'Czechia',              dataYear: 2022, values: { safe_water_access: 100,  water_stress: 12,  threatened_species: 9,   protected_areas: 22 } },
    { geoCode: 'PL', geoName: 'Poland',               dataYear: 2022, values: { safe_water_access: 99,   water_stress: 18,  threatened_species: 8,   protected_areas: 39 } },
    { geoCode: 'HU', geoName: 'Hungary',              dataYear: 2022, values: { safe_water_access: 99,   water_stress: 10,  threatened_species: 10,  protected_areas: 22 } },
    { geoCode: 'BG', geoName: 'Bulgaria',             dataYear: 2022, values: { safe_water_access: 99,   water_stress: 5,   threatened_species: 11,  protected_areas: 35 } },
    { geoCode: 'LU', geoName: 'Luxembourg',           dataYear: 2022, values: { safe_water_access: 100,  water_stress: 4,   threatened_species: 7,   protected_areas: 27 } },
    { geoCode: 'EE', geoName: 'Estonia',              dataYear: 2022, values: { safe_water_access: 99,   water_stress: 4,   threatened_species: 5,   protected_areas: 22 } },
    { geoCode: 'LT', geoName: 'Lithuania',            dataYear: 2022, values: { safe_water_access: 99,   water_stress: 4,   threatened_species: 5,   protected_areas: 18 } },
    { geoCode: 'LV', geoName: 'Latvia',               dataYear: 2022, values: { safe_water_access: 99,   water_stress: 3,   threatened_species: 5,   protected_areas: 18 } },
    { geoCode: 'SI', geoName: 'Slovenia',             dataYear: 2022, values: { safe_water_access: 100,  water_stress: 3,   threatened_species: 11,  protected_areas: 40 } },
    { geoCode: 'RS', geoName: 'Serbia',               dataYear: 2022, values: { safe_water_access: 96,   water_stress: 5,   threatened_species: 9,   protected_areas: 7 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2022, values: { safe_water_access: 95,   water_stress: 3,   threatened_species: 8,   protected_areas: 3 } },
    { geoCode: 'AL', geoName: 'Albania',              dataYear: 2022, values: { safe_water_access: 94,   water_stress: 6,   threatened_species: 10,  protected_areas: 18 } },
    { geoCode: 'MK', geoName: 'North Macedonia',      dataYear: 2022, values: { safe_water_access: 96,   water_stress: 14,  threatened_species: 8,   protected_areas: 10 } },
    { geoCode: 'ME', geoName: 'Montenegro',           dataYear: 2022, values: { safe_water_access: 97,   water_stress: 3,   threatened_species: 9,   protected_areas: 12 } },
    { geoCode: 'MT', geoName: 'Malta',                dataYear: 2022, values: { safe_water_access: 100,  water_stress: 74,  threatened_species: 11,  protected_areas: 35 } },
    { geoCode: 'CY', geoName: 'Cyprus',               dataYear: 2022, values: { safe_water_access: 100,  water_stress: 59,  threatened_species: 10,  protected_areas: 19 } },
    { geoCode: 'MD', geoName: 'Moldova',              dataYear: 2022, values: { safe_water_access: 86,   water_stress: 9,   threatened_species: 6,   protected_areas: 6 } },

    // ── North America ───────────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',        dataYear: 2022, values: { safe_water_access: 99,   water_stress: 42,  threatened_species: 14,  protected_areas: 13 } },
    { geoCode: 'CA', geoName: 'Canada',               dataYear: 2022, values: { safe_water_access: 99,   water_stress: 2,   threatened_species: 8,   protected_areas: 13 } },
    { geoCode: 'MX', geoName: 'Mexico',               dataYear: 2022, values: { safe_water_access: 97,   water_stress: 44,  threatened_species: 18,  protected_areas: 14 } },

    // ── Central America & Caribbean ─────────────────────────────────────────
    { geoCode: 'GT', geoName: 'Guatemala',            dataYear: 2022, values: { safe_water_access: 89,   water_stress: 4,   threatened_species: 14,  protected_areas: 32 } },
    { geoCode: 'HN', geoName: 'Honduras',             dataYear: 2022, values: { safe_water_access: 86,   water_stress: 4,   threatened_species: 13,  protected_areas: 26 } },
    { geoCode: 'SV', geoName: 'El Salvador',          dataYear: 2022, values: { safe_water_access: 90,   water_stress: 12,  threatened_species: 10,  protected_areas: 14 } },
    { geoCode: 'CR', geoName: 'Costa Rica',           dataYear: 2022, values: { safe_water_access: 98,   water_stress: 3,   threatened_species: 15,  protected_areas: 28 } },
    { geoCode: 'PA', geoName: 'Panama',               dataYear: 2022, values: { safe_water_access: 96,   water_stress: 1,   threatened_species: 14,  protected_areas: 25 } },
    { geoCode: 'JM', geoName: 'Jamaica',              dataYear: 2022, values: { safe_water_access: 92,   water_stress: 10,  threatened_species: 18,  protected_areas: 19 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago',  dataYear: 2022, values: { safe_water_access: 97,   water_stress: 18,  threatened_species: 10,  protected_areas: 31 } },
    { geoCode: 'DO', geoName: 'Dominican Republic',   dataYear: 2022, values: { safe_water_access: 93,   water_stress: 27,  threatened_species: 15,  protected_areas: 26 } },

    // ── South America ───────────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',               dataYear: 2022, values: { safe_water_access: 97,   water_stress: 2,   threatened_species: 12,  protected_areas: 30 } },
    { geoCode: 'AR', geoName: 'Argentina',            dataYear: 2022, values: { safe_water_access: 98,   water_stress: 11,  threatened_species: 10,  protected_areas: 9 } },
    { geoCode: 'CL', geoName: 'Chile',                dataYear: 2022, values: { safe_water_access: 100,  water_stress: 34,  threatened_species: 14,  protected_areas: 21 } },
    { geoCode: 'CO', geoName: 'Colombia',             dataYear: 2022, values: { safe_water_access: 97,   water_stress: 3,   threatened_species: 16,  protected_areas: 15 } },
    { geoCode: 'PE', geoName: 'Peru',                 dataYear: 2022, values: { safe_water_access: 91,   water_stress: 4,   threatened_species: 14,  protected_areas: 19 } },
    { geoCode: 'VE', geoName: 'Venezuela',            dataYear: 2022, values: { safe_water_access: 88,   water_stress: 5,   threatened_species: 16,  protected_areas: 54 } },
    { geoCode: 'EC', geoName: 'Ecuador',              dataYear: 2022, values: { safe_water_access: 94,   water_stress: 5,   threatened_species: 20,  protected_areas: 20 } },
    { geoCode: 'UY', geoName: 'Uruguay',              dataYear: 2022, values: { safe_water_access: 100,  water_stress: 4,   threatened_species: 8,   protected_areas: 3 } },
    { geoCode: 'PY', geoName: 'Paraguay',             dataYear: 2022, values: { safe_water_access: 93,   water_stress: 1,   threatened_species: 7,   protected_areas: 8 } },
    { geoCode: 'BO', geoName: 'Bolivia',              dataYear: 2022, values: { safe_water_access: 85,   water_stress: 2,   threatened_species: 11,  protected_areas: 22 } },

    // ── East Asia ───────────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',                dataYear: 2022, values: { safe_water_access: 99,   water_stress: 21,  threatened_species: 18,  protected_areas: 21 } },
    { geoCode: 'KR', geoName: 'South Korea',          dataYear: 2022, values: { safe_water_access: 99,   water_stress: 40,  threatened_species: 10,  protected_areas: 17 } },
    { geoCode: 'CN', geoName: 'China',                dataYear: 2022, values: { safe_water_access: 94,   water_stress: 44,  threatened_species: 13,  protected_areas: 18 } },
    { geoCode: 'TW', geoName: 'Taiwan',               dataYear: 2022, values: { safe_water_access: 99,   water_stress: 30,  threatened_species: 15,  protected_areas: 19 } },
    { geoCode: 'MN', geoName: 'Mongolia',             dataYear: 2022, values: { safe_water_access: 77,   water_stress: 4,   threatened_species: 7,   protected_areas: 21 } },

    // ── Southeast Asia ──────────────────────────────────────────────────────
    { geoCode: 'SG', geoName: 'Singapore',            dataYear: 2022, values: { safe_water_access: 100,  water_stress: 51,  threatened_species: 17,  protected_areas: 5 } },
    { geoCode: 'TH', geoName: 'Thailand',             dataYear: 2022, values: { safe_water_access: 98,   water_stress: 15,  threatened_species: 16,  protected_areas: 19 } },
    { geoCode: 'VN', geoName: 'Vietnam',              dataYear: 2022, values: { safe_water_access: 93,   water_stress: 14,  threatened_species: 17,  protected_areas: 9 } },
    { geoCode: 'ID', geoName: 'Indonesia',            dataYear: 2022, values: { safe_water_access: 89,   water_stress: 15,  threatened_species: 20,  protected_areas: 14 } },
    { geoCode: 'PH', geoName: 'Philippines',          dataYear: 2022, values: { safe_water_access: 93,   water_stress: 21,  threatened_species: 22,  protected_areas: 16 } },
    { geoCode: 'MY', geoName: 'Malaysia',             dataYear: 2022, values: { safe_water_access: 97,   water_stress: 7,   threatened_species: 19,  protected_areas: 20 } },
    { geoCode: 'MM', geoName: 'Myanmar',              dataYear: 2022, values: { safe_water_access: 73,   water_stress: 5,   threatened_species: 15,  protected_areas: 7 } },
    { geoCode: 'KH', geoName: 'Cambodia',             dataYear: 2022, values: { safe_water_access: 73,   water_stress: 2,   threatened_species: 14,  protected_areas: 26 } },
    { geoCode: 'LA', geoName: 'Laos',                 dataYear: 2022, values: { safe_water_access: 77,   water_stress: 2,   threatened_species: 13,  protected_areas: 22 } },
    { geoCode: 'BN', geoName: 'Brunei',               dataYear: 2022, values: { safe_water_access: 100,  water_stress: 1,   threatened_species: 12,  protected_areas: 44 } },

    // ── South Asia ──────────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',                dataYear: 2022, values: { safe_water_access: 87,   water_stress: 66,  threatened_species: 16,  protected_areas: 6 } },
    { geoCode: 'PK', geoName: 'Pakistan',             dataYear: 2022, values: { safe_water_access: 77,   water_stress: 89,  threatened_species: 12,  protected_areas: 12 } },
    { geoCode: 'BD', geoName: 'Bangladesh',           dataYear: 2022, values: { safe_water_access: 57,   water_stress: 8,   threatened_species: 12,  protected_areas: 5 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',            dataYear: 2022, values: { safe_water_access: 91,   water_stress: 25,  threatened_species: 22,  protected_areas: 30 } },
    { geoCode: 'NP', geoName: 'Nepal',                dataYear: 2022, values: { safe_water_access: 81,   water_stress: 6,   threatened_species: 12,  protected_areas: 24 } },
    { geoCode: 'AF', geoName: 'Afghanistan',          dataYear: 2022, values: { safe_water_access: 48,   water_stress: 57,  threatened_species: 7,   protected_areas: 4 } },

    // ── Central Asia ────────────────────────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',           dataYear: 2022, values: { safe_water_access: 93,   water_stress: 23,  threatened_species: 7,   protected_areas: 9 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',           dataYear: 2022, values: { safe_water_access: 86,   water_stress: 95,  threatened_species: 7,   protected_areas: 4 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',         dataYear: 2022, values: { safe_water_access: 81,   water_stress: 100, threatened_species: 6,   protected_areas: 3 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',           dataYear: 2022, values: { safe_water_access: 85,   water_stress: 42,  threatened_species: 5,   protected_areas: 7 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',           dataYear: 2022, values: { safe_water_access: 77,   water_stress: 60,  threatened_species: 6,   protected_areas: 22 } },

    // ── Middle East ─────────────────────────────────────────────────────────
    { geoCode: 'SA', geoName: 'Saudi Arabia',         dataYear: 2022, values: { safe_water_access: 99,   water_stress: 100, threatened_species: 10,  protected_areas: 7 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2022, values: { safe_water_access: 99,   water_stress: 100, threatened_species: 9,   protected_areas: 15 } },
    { geoCode: 'IL', geoName: 'Israel',               dataYear: 2022, values: { safe_water_access: 100,  water_stress: 66,  threatened_species: 15,  protected_areas: 18 } },
    { geoCode: 'TR', geoName: 'Turkey',               dataYear: 2022, values: { safe_water_access: 98,   water_stress: 45,  threatened_species: 14,  protected_areas: 9 } },
    { geoCode: 'IR', geoName: 'Iran',                 dataYear: 2022, values: { safe_water_access: 95,   water_stress: 84,  threatened_species: 12,  protected_areas: 10 } },
    { geoCode: 'IQ', geoName: 'Iraq',                 dataYear: 2022, values: { safe_water_access: 86,   water_stress: 77,  threatened_species: 8,   protected_areas: 2 } },
    { geoCode: 'JO', geoName: 'Jordan',               dataYear: 2022, values: { safe_water_access: 97,   water_stress: 100, threatened_species: 10,  protected_areas: 10 } },
    { geoCode: 'LB', geoName: 'Lebanon',              dataYear: 2022, values: { safe_water_access: 92,   water_stress: 51,  threatened_species: 11,  protected_areas: 3 } },
    { geoCode: 'KW', geoName: 'Kuwait',               dataYear: 2022, values: { safe_water_access: 100,  water_stress: 100, threatened_species: 7,   protected_areas: 2 } },
    { geoCode: 'QA', geoName: 'Qatar',                dataYear: 2022, values: { safe_water_access: 100,  water_stress: 100, threatened_species: 6,   protected_areas: 8 } },
    { geoCode: 'BH', geoName: 'Bahrain',              dataYear: 2022, values: { safe_water_access: 100,  water_stress: 100, threatened_species: 8,   protected_areas: 5 } },
    { geoCode: 'OM', geoName: 'Oman',                 dataYear: 2022, values: { safe_water_access: 93,   water_stress: 89,  threatened_species: 10,  protected_areas: 4 } },

    // ── North Africa ────────────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',                dataYear: 2022, values: { safe_water_access: 98,   water_stress: 100, threatened_species: 10,  protected_areas: 13 } },
    { geoCode: 'MA', geoName: 'Morocco',              dataYear: 2022, values: { safe_water_access: 86,   water_stress: 43,  threatened_species: 12,  protected_areas: 31 } },
    { geoCode: 'DZ', geoName: 'Algeria',              dataYear: 2022, values: { safe_water_access: 93,   water_stress: 64,  threatened_species: 9,   protected_areas: 8 } },
    { geoCode: 'TN', geoName: 'Tunisia',              dataYear: 2022, values: { safe_water_access: 96,   water_stress: 74,  threatened_species: 10,  protected_areas: 9 } },
    { geoCode: 'LY', geoName: 'Libya',                dataYear: 2022, values: { safe_water_access: 85,   water_stress: 100, threatened_species: 8,   protected_areas: 1 } },

    // ── Sub-Saharan Africa ──────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',         dataYear: 2022, values: { safe_water_access: 91,   water_stress: 55,  threatened_species: 13,  protected_areas: 13 } },
    { geoCode: 'NG', geoName: 'Nigeria',              dataYear: 2022, values: { safe_water_access: 71,   water_stress: 10,  threatened_species: 11,  protected_areas: 14 } },
    { geoCode: 'KE', geoName: 'Kenya',                dataYear: 2022, values: { safe_water_access: 62,   water_stress: 26,  threatened_species: 14,  protected_areas: 12 } },
    { geoCode: 'ET', geoName: 'Ethiopia',             dataYear: 2022, values: { safe_water_access: 49,   water_stress: 11,  threatened_species: 10,  protected_areas: 18 } },
    { geoCode: 'GH', geoName: 'Ghana',                dataYear: 2022, values: { safe_water_access: 79,   water_stress: 8,   threatened_species: 9,   protected_areas: 15 } },
    { geoCode: 'TZ', geoName: 'Tanzania',             dataYear: 2022, values: { safe_water_access: 56,   water_stress: 6,   threatened_species: 16,  protected_areas: 38 } },
    { geoCode: 'UG', geoName: 'Uganda',               dataYear: 2022, values: { safe_water_access: 53,   water_stress: 4,   threatened_species: 13,  protected_areas: 16 } },
    { geoCode: 'RW', geoName: 'Rwanda',               dataYear: 2022, values: { safe_water_access: 59,   water_stress: 3,   threatened_species: 10,  protected_areas: 10 } },
    { geoCode: 'SN', geoName: 'Senegal',              dataYear: 2022, values: { safe_water_access: 75,   water_stress: 12,  threatened_species: 10,  protected_areas: 25 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',          dataYear: 2022, values: { safe_water_access: 67,   water_stress: 4,   threatened_species: 11,  protected_areas: 23 } },
    { geoCode: 'CM', geoName: 'Cameroon',             dataYear: 2022, values: { safe_water_access: 62,   water_stress: 1,   threatened_species: 15,  protected_areas: 14 } },
    { geoCode: 'AO', geoName: 'Angola',               dataYear: 2022, values: { safe_water_access: 55,   water_stress: 1,   threatened_species: 9,   protected_areas: 12 } },
    { geoCode: 'MZ', geoName: 'Mozambique',           dataYear: 2022, values: { safe_water_access: 51,   water_stress: 2,   threatened_species: 11,  protected_areas: 26 } },
    { geoCode: 'MG', geoName: 'Madagascar',           dataYear: 2022, values: { safe_water_access: 50,   water_stress: 6,   threatened_species: 30,  protected_areas: 10 } },
    { geoCode: 'CD', geoName: 'DR Congo',             dataYear: 2022, values: { safe_water_access: 42,   water_stress: 1,   threatened_species: 14,  protected_areas: 13 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',             dataYear: 2022, values: { safe_water_access: 61,   water_stress: 20,  threatened_species: 7,   protected_areas: 28 } },
    { geoCode: 'BW', geoName: 'Botswana',             dataYear: 2022, values: { safe_water_access: 78,   water_stress: 9,   threatened_species: 5,   protected_areas: 29 } },
    { geoCode: 'NA', geoName: 'Namibia',              dataYear: 2022, values: { safe_water_access: 81,   water_stress: 7,   threatened_species: 6,   protected_areas: 38 } },
    { geoCode: 'MU', geoName: 'Mauritius',            dataYear: 2022, values: { safe_water_access: 100,  water_stress: 26,  threatened_species: 24,  protected_areas: 5 } },
    { geoCode: 'GA', geoName: 'Gabon',                dataYear: 2022, values: { safe_water_access: 83,   water_stress: 1,   threatened_species: 10,  protected_areas: 21 } },

    // ── Oceania ─────────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',            dataYear: 2022, values: { safe_water_access: 100,  water_stress: 18,  threatened_species: 22,  protected_areas: 21 } },
    { geoCode: 'NZ', geoName: 'New Zealand',          dataYear: 2022, values: { safe_water_access: 100,  water_stress: 4,   threatened_species: 28,  protected_areas: 33 } },
    { geoCode: 'FJ', geoName: 'Fiji',                 dataYear: 2022, values: { safe_water_access: 89,   water_stress: 1,   threatened_species: 14,  protected_areas: 4 } },

    // ── Ex-USSR ─────────────────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',               dataYear: 2022, values: { safe_water_access: 96,   water_stress: 5,   threatened_species: 8,   protected_areas: 12 } },
    { geoCode: 'UA', geoName: 'Ukraine',              dataYear: 2022, values: { safe_water_access: 94,   water_stress: 18,  threatened_species: 8,   protected_areas: 8 } },
    { geoCode: 'BY', geoName: 'Belarus',              dataYear: 2022, values: { safe_water_access: 96,   water_stress: 4,   threatened_species: 5,   protected_areas: 9 } },

    // ── Additional Africa ───────────────────────────────────────────────────
    { geoCode: 'ML', geoName: 'Mali',                 dataYear: 2022, values: { safe_water_access: 46,   water_stress: 8,   threatened_species: 7,   protected_areas: 4 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',         dataYear: 2022, values: { safe_water_access: 47,   water_stress: 7,   threatened_species: 6,   protected_areas: 15 } },
    { geoCode: 'NE', geoName: 'Niger',                dataYear: 2022, values: { safe_water_access: 41,   water_stress: 11,  threatened_species: 5,   protected_areas: 8 } },
    { geoCode: 'TD', geoName: 'Chad',                 dataYear: 2022, values: { safe_water_access: 38,   water_stress: 6,   threatened_species: 6,   protected_areas: 17 } },
    { geoCode: 'MW', geoName: 'Malawi',               dataYear: 2022, values: { safe_water_access: 64,   water_stress: 9,   threatened_species: 10,  protected_areas: 18 } },
    { geoCode: 'ZM', geoName: 'Zambia',               dataYear: 2022, values: { safe_water_access: 57,   water_stress: 3,   threatened_species: 8,   protected_areas: 38 } },
    { geoCode: 'SD', geoName: 'Sudan',                dataYear: 2022, values: { safe_water_access: 57,   water_stress: 100, threatened_species: 8,   protected_areas: 5 } },
    { geoCode: 'SO', geoName: 'Somalia',              dataYear: 2022, values: { safe_water_access: 37,   water_stress: 33,  threatened_species: 10,  protected_areas: 1 } },
    { geoCode: 'SS', geoName: 'South Sudan',          dataYear: 2022, values: { safe_water_access: 34,   water_stress: 3,   threatened_species: 6,   protected_areas: 13 } },
    { geoCode: 'ER', geoName: 'Eritrea',              dataYear: 2022, values: { safe_water_access: 43,   water_stress: 50,  threatened_species: 7,   protected_areas: 5 } },
    { geoCode: 'DJ', geoName: 'Djibouti',             dataYear: 2022, values: { safe_water_access: 62,   water_stress: 45,  threatened_species: 8,   protected_areas: 2 } },
    { geoCode: 'GM', geoName: 'Gambia',               dataYear: 2022, values: { safe_water_access: 74,   water_stress: 4,   threatened_species: 7,   protected_areas: 6 } },
    { geoCode: 'GW', geoName: 'Guinea-Bissau',        dataYear: 2022, values: { safe_water_access: 59,   water_stress: 1,   threatened_species: 8,   protected_areas: 26 } },
    { geoCode: 'GN', geoName: 'Guinea',               dataYear: 2022, values: { safe_water_access: 54,   water_stress: 2,   threatened_species: 13,  protected_areas: 28 } },
    { geoCode: 'SL', geoName: 'Sierra Leone',         dataYear: 2022, values: { safe_water_access: 51,   water_stress: 1,   threatened_species: 11,  protected_areas: 5 } },
    { geoCode: 'LR', geoName: 'Liberia',              dataYear: 2022, values: { safe_water_access: 47,   water_stress: 1,   threatened_species: 14,  protected_areas: 4 } },
    { geoCode: 'TG', geoName: 'Togo',                 dataYear: 2022, values: { safe_water_access: 61,   water_stress: 3,   threatened_species: 7,   protected_areas: 11 } },
    { geoCode: 'BJ', geoName: 'Benin',                dataYear: 2022, values: { safe_water_access: 55,   water_stress: 3,   threatened_species: 7,   protected_areas: 28 } },
    { geoCode: 'CG', geoName: 'Republic of Congo',    dataYear: 2022, values: { safe_water_access: 58,   water_stress: 1,   threatened_species: 9,   protected_areas: 36 } },
    { geoCode: 'CF', geoName: 'Central African Republic', dataYear: 2022, values: { safe_water_access: 36, water_stress: 1, threatened_species: 8,   protected_areas: 18 } },
    { geoCode: 'BI', geoName: 'Burundi',              dataYear: 2022, values: { safe_water_access: 53,   water_stress: 4,   threatened_species: 10,  protected_areas: 7 } },
    { geoCode: 'SZ', geoName: 'Eswatini',             dataYear: 2022, values: { safe_water_access: 67,   water_stress: 28,  threatened_species: 5,   protected_areas: 4 } },
    { geoCode: 'LS', geoName: 'Lesotho',              dataYear: 2022, values: { safe_water_access: 66,   water_stress: 6,   threatened_species: 4,   protected_areas: 1 } },

    // ── Additional Asia & Pacific ───────────────────────────────────────────
    { geoCode: 'GE', geoName: 'Georgia',              dataYear: 2022, values: { safe_water_access: 95,   water_stress: 5,   threatened_species: 9,   protected_areas: 10 } },
    { geoCode: 'AM', geoName: 'Armenia',              dataYear: 2022, values: { safe_water_access: 98,   water_stress: 47,  threatened_species: 8,   protected_areas: 13 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',           dataYear: 2022, values: { safe_water_access: 86,   water_stress: 52,  threatened_species: 7,   protected_areas: 9 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea',     dataYear: 2022, values: { safe_water_access: 42,   water_stress: 1,   threatened_species: 16,  protected_areas: 3 } },
    { geoCode: 'NI', geoName: 'Nicaragua',            dataYear: 2022, values: { safe_water_access: 81,   water_stress: 2,   threatened_species: 10,  protected_areas: 37 } },
    { geoCode: 'CU', geoName: 'Cuba',                 dataYear: 2022, values: { safe_water_access: 96,   water_stress: 18,  threatened_species: 16,  protected_areas: 18 } },
    { geoCode: 'HT', geoName: 'Haiti',                dataYear: 2022, values: { safe_water_access: 53,   water_stress: 14,  threatened_species: 14,  protected_areas: 1 } },
    { geoCode: 'YE', geoName: 'Yemen',                dataYear: 2022, values: { safe_water_access: 54,   water_stress: 100, threatened_species: 10,  protected_areas: 1 } },
    { geoCode: 'SY', geoName: 'Syria',                dataYear: 2022, values: { safe_water_access: 78,   water_stress: 89,  threatened_species: 9,   protected_areas: 1 } },
    { geoCode: 'PS', geoName: 'Palestine',            dataYear: 2022, values: { safe_water_access: 88,   water_stress: 50,  threatened_species: 7,   protected_areas: 2 } },
  ],
};

export default waterBiodiversityModule;
