import type { DomainModule } from '@/lib/domains/types';

const wellbeingModule: DomainModule = {
  definition: {
    id: 'wellbeing',
    label: { fr: 'Bien-être', en: 'Wellbeing', es: 'Bienestar' },
    description: {
      fr: 'Qualité de vie subjective et objective : satisfaction, santé mentale, équilibre vie professionnelle/personnelle et soutien social.',
      en: 'Subjective and objective quality of life: satisfaction, mental health, work-life balance and social support.',
      es: 'Calidad de vida subjetiva y objetiva: satisfacción, salud mental, equilibrio vida laboral/personal y apoyo social.',
    },
    icon: '😊',
    group: 'society',
    active: true,
    seedSources: [
      'https://www.oecdbetterlifeindex.org/',
      'https://worldhappiness.report/',
      'https://www.who.int/health-topics/mental-health',
    ],
    indicators: [
      {
        id: 'life_satisfaction',
        label: { fr: 'Satisfaction de vie', en: 'Life satisfaction', es: 'Satisfacción con la vida' },
        unit: 'index',
        unitLabel: { fr: 'score /10', en: 'score /10', es: 'score /10' },
        direction: 'higher_is_better',
        weight: 4,
        thresholds: { excellent: 7.5, good: 6.5, fair: 5.5, poor: 4.5 },
        minValue: 0,
        maxValue: 10,
      },
      {
        id: 'mental_health_disorders',
        label: { fr: 'Troubles de santé mentale', en: 'Mental health disorders', es: 'Trastornos de salud mental' },
        unit: 'percent',
        unitLabel: { fr: '% population', en: '% population', es: '% población' },
        direction: 'lower_is_better',
        weight: 3,
        thresholds: { excellent: 12, good: 16, fair: 20, poor: 25 },
        minValue: 0,
        maxValue: 40,
      },
      {
        id: 'work_life_balance',
        label: { fr: 'Équilibre vie pro/perso', en: 'Work-life balance', es: 'Equilibrio vida laboral/personal' },
        unit: 'index',
        unitLabel: { fr: 'score /100', en: 'score /100', es: 'score /100' },
        direction: 'higher_is_better',
        weight: 2,
        thresholds: { excellent: 78, good: 65, fair: 50, poor: 35 },
        minValue: 0,
        maxValue: 100,
      },
      {
        id: 'social_support',
        label: { fr: 'Soutien social', en: 'Social support', es: 'Apoyo social' },
        unit: 'index',
        unitLabel: { fr: 'score /100', en: 'score /100', es: 'score /100' },
        direction: 'higher_is_better',
        weight: 2,
        thresholds: { excellent: 90, good: 80, fair: 70, poor: 55 },
        minValue: 0,
        maxValue: 100,
      },
    ],
  },
  seedData: [
    // ── Europe nordique ────────────────────────────────────────────────────
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2023, values: { life_satisfaction: 7.8, mental_health_disorders: 18.9, work_life_balance: 78, social_support: 94 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2023, values: { life_satisfaction: 7.6, mental_health_disorders: 17.3, work_life_balance: 82, social_support: 93 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2023, values: { life_satisfaction: 7.5, mental_health_disorders: 16.0, work_life_balance: 80, social_support: 95 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2023, values: { life_satisfaction: 7.3, mental_health_disorders: 16.5, work_life_balance: 76, social_support: 92 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2023, values: { life_satisfaction: 7.3, mental_health_disorders: 18.4, work_life_balance: 80, social_support: 91 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2023, values: { life_satisfaction: 7.4, mental_health_disorders: 18.7, work_life_balance: 78, social_support: 89 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2023, values: { life_satisfaction: 7.5, mental_health_disorders: 17.2, work_life_balance: 72, social_support: 90 } },
    // ── Europe de l'Ouest ──────────────────────────────────────────────────
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2023, values: { life_satisfaction: 7.3, mental_health_disorders: 17.5, work_life_balance: 70, social_support: 87 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2023, values: { life_satisfaction: 6.9, mental_health_disorders: 21.2, work_life_balance: 68, social_support: 85 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2023, values: { life_satisfaction: 7.1, mental_health_disorders: 16.0, work_life_balance: 67, social_support: 88 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2023, values: { life_satisfaction: 7.0, mental_health_disorders: 17.8, work_life_balance: 60, social_support: 83 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2023, values: { life_satisfaction: 6.7, mental_health_disorders: 20.5, work_life_balance: 65, social_support: 82 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2023, values: { life_satisfaction: 7.0, mental_health_disorders: 18.5, work_life_balance: 72, social_support: 90 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2023, values: { life_satisfaction: 6.8, mental_health_disorders: 22.0, work_life_balance: 60, social_support: 82 } },
    // ── Europe du Sud ────────────────────────────────────────────────────
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2023, values: { life_satisfaction: 6.5, mental_health_disorders: 14.9, work_life_balance: 62, social_support: 88 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2023, values: { life_satisfaction: 6.2, mental_health_disorders: 15.6, work_life_balance: 58, social_support: 84 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2023, values: { life_satisfaction: 5.9, mental_health_disorders: 18.1, work_life_balance: 55, social_support: 80 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2023, values: { life_satisfaction: 5.4, mental_health_disorders: 16.5, work_life_balance: 42, social_support: 72 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2023, values: { life_satisfaction: 6.6, mental_health_disorders: 15.0, work_life_balance: 60, social_support: 85 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2023, values: { life_satisfaction: 6.2, mental_health_disorders: 14.8, work_life_balance: 55, social_support: 80 } },
    // ── Europe de l'Est ────────────────────────────────────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2023, values: { life_satisfaction: 6.7, mental_health_disorders: 16.0, work_life_balance: 55, social_support: 78 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2023, values: { life_satisfaction: 6.3, mental_health_disorders: 17.0, work_life_balance: 50, social_support: 75 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2023, values: { life_satisfaction: 5.6, mental_health_disorders: 18.5, work_life_balance: 45, social_support: 68 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2023, values: { life_satisfaction: 6.2, mental_health_disorders: 16.0, work_life_balance: 50, social_support: 72 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2023, values: { life_satisfaction: 6.0, mental_health_disorders: 15.5, work_life_balance: 48, social_support: 70 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2023, values: { life_satisfaction: 5.8, mental_health_disorders: 16.0, work_life_balance: 45, social_support: 68 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2023, values: { life_satisfaction: 5.0, mental_health_disorders: 16.0, work_life_balance: 40, social_support: 62 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2023, values: { life_satisfaction: 6.5, mental_health_disorders: 15.8, work_life_balance: 58, social_support: 80 } },
    // ── Europe balte ───────────────────────────────────────────────────────
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2023, values: { life_satisfaction: 6.4, mental_health_disorders: 16.5, work_life_balance: 55, social_support: 78 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2023, values: { life_satisfaction: 6.1, mental_health_disorders: 17.2, work_life_balance: 52, social_support: 74 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2023, values: { life_satisfaction: 5.9, mental_health_disorders: 17.0, work_life_balance: 50, social_support: 72 } },
    // ── Balkans ────────────────────────────────────────────────────────────
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2023, values: { life_satisfaction: 5.4, mental_health_disorders: 16.5, work_life_balance: 42, social_support: 66 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2023, values: { life_satisfaction: 5.2, mental_health_disorders: 16.0, work_life_balance: 40, social_support: 64 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2023, values: { life_satisfaction: 5.0, mental_health_disorders: 14.5, work_life_balance: 38, social_support: 60 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2023, values: { life_satisfaction: 5.1, mental_health_disorders: 15.0, work_life_balance: 40, social_support: 62 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2023, values: { life_satisfaction: 5.5, mental_health_disorders: 15.2, work_life_balance: 42, social_support: 65 } },
    // ── Europe de l'Est (hors UE) ──────────────────────────────────────────
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2023, values: { life_satisfaction: 5.0, mental_health_disorders: 17.5, work_life_balance: 38, social_support: 62 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2023, values: { life_satisfaction: 5.3, mental_health_disorders: 18.0, work_life_balance: 42, social_support: 65 } },
    // ── Amérique du Nord ──────────────────────────────────────────────────
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2023, values: { life_satisfaction: 7.0, mental_health_disorders: 20.0, work_life_balance: 68, social_support: 88 } },
    { geoCode: 'US', geoName: 'United States',  dataYear: 2023, values: { life_satisfaction: 6.9, mental_health_disorders: 22.5, work_life_balance: 55, social_support: 85 } },
    // ── Amérique centrale & Caraïbes ──────────────────────────────────────
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2023, values: { life_satisfaction: 6.6, mental_health_disorders: 15.5, work_life_balance: 55, social_support: 80 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2023, values: { life_satisfaction: 6.2, mental_health_disorders: 14.0, work_life_balance: 50, social_support: 76 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2023, values: { life_satisfaction: 6.0, mental_health_disorders: 12.5, work_life_balance: 42, social_support: 72 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2023, values: { life_satisfaction: 5.8, mental_health_disorders: 13.0, work_life_balance: 38, social_support: 70 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2023, values: { life_satisfaction: 5.9, mental_health_disorders: 13.5, work_life_balance: 40, social_support: 70 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2023, values: { life_satisfaction: 5.8, mental_health_disorders: 12.8, work_life_balance: 38, social_support: 68 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2023, values: { life_satisfaction: 5.7, mental_health_disorders: 14.5, work_life_balance: 45, social_support: 72 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2023, values: { life_satisfaction: 5.8, mental_health_disorders: 15.5, work_life_balance: 48, social_support: 74 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2023, values: { life_satisfaction: 5.7, mental_health_disorders: 14.0, work_life_balance: 42, social_support: 72 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2023, values: { life_satisfaction: 5.3, mental_health_disorders: 15.0, work_life_balance: 45, social_support: 74 } },
    { geoCode: 'HT', geoName: 'Haiti',          dataYear: 2023, values: { life_satisfaction: 3.6, mental_health_disorders: 16.0, work_life_balance: 28, social_support: 48 } },
    // ── Amérique du Sud ──────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2023, values: { life_satisfaction: 6.0, mental_health_disorders: 19.0, work_life_balance: 52, social_support: 74 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2023, values: { life_satisfaction: 6.5, mental_health_disorders: 18.0, work_life_balance: 50, social_support: 78 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2023, values: { life_satisfaction: 6.0, mental_health_disorders: 23.0, work_life_balance: 48, social_support: 72 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2023, values: { life_satisfaction: 6.3, mental_health_disorders: 21.0, work_life_balance: 50, social_support: 74 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2023, values: { life_satisfaction: 6.3, mental_health_disorders: 17.0, work_life_balance: 52, social_support: 76 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2023, values: { life_satisfaction: 6.5, mental_health_disorders: 19.5, work_life_balance: 55, social_support: 78 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2023, values: { life_satisfaction: 5.5, mental_health_disorders: 15.5, work_life_balance: 42, social_support: 68 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2023, values: { life_satisfaction: 5.8, mental_health_disorders: 14.5, work_life_balance: 45, social_support: 72 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2023, values: { life_satisfaction: 5.2, mental_health_disorders: 17.0, work_life_balance: 38, social_support: 68 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2023, values: { life_satisfaction: 5.6, mental_health_disorders: 13.0, work_life_balance: 44, social_support: 72 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2023, values: { life_satisfaction: 5.3, mental_health_disorders: 14.0, work_life_balance: 40, social_support: 66 } },
    // ── Océanie ───────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2023, values: { life_satisfaction: 7.1, mental_health_disorders: 21.0, work_life_balance: 70, social_support: 90 } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2023, values: { life_satisfaction: 7.2, mental_health_disorders: 20.5, work_life_balance: 72, social_support: 91 } },
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2023, values: { life_satisfaction: 5.2, mental_health_disorders: 12.5, work_life_balance: 48, social_support: 70 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2023, values: { life_satisfaction: 4.4, mental_health_disorders: 11.5, work_life_balance: 35, social_support: 55 } },
    // ── Asie de l'Est ──────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2023, values: { life_satisfaction: 6.1, mental_health_disorders: 17.0, work_life_balance: 40, social_support: 78 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2023, values: { life_satisfaction: 5.9, mental_health_disorders: 22.0, work_life_balance: 35, social_support: 72 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2023, values: { life_satisfaction: 5.9, mental_health_disorders: 17.0, work_life_balance: 42, social_support: 72 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2023, values: { life_satisfaction: 6.4, mental_health_disorders: 16.0, work_life_balance: 45, social_support: 76 } },
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2023, values: { life_satisfaction: 6.5, mental_health_disorders: 13.0, work_life_balance: 52, social_support: 80 } },
    // ── Asie du Sud-Est ────────────────────────────────────────────────────
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2023, values: { life_satisfaction: 5.6, mental_health_disorders: 15.0, work_life_balance: 52, social_support: 70 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2023, values: { life_satisfaction: 5.8, mental_health_disorders: 14.0, work_life_balance: 50, social_support: 74 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2023, values: { life_satisfaction: 5.5, mental_health_disorders: 12.5, work_life_balance: 48, social_support: 72 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2023, values: { life_satisfaction: 5.5, mental_health_disorders: 13.5, work_life_balance: 42, social_support: 72 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2023, values: { life_satisfaction: 5.3, mental_health_disorders: 12.0, work_life_balance: 45, social_support: 70 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2023, values: { life_satisfaction: 4.0, mental_health_disorders: 13.0, work_life_balance: 35, social_support: 55 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2023, values: { life_satisfaction: 4.5, mental_health_disorders: 12.5, work_life_balance: 38, social_support: 60 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2023, values: { life_satisfaction: 4.8, mental_health_disorders: 12.0, work_life_balance: 40, social_support: 62 } },
    { geoCode: 'BN', geoName: 'Brunei',         dataYear: 2023, values: { life_satisfaction: 6.0, mental_health_disorders: 12.5, work_life_balance: 55, social_support: 78 } },
    // ── Asie du Sud ────────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2023, values: { life_satisfaction: 4.4, mental_health_disorders: 14.0, work_life_balance: 38, social_support: 60 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2023, values: { life_satisfaction: 4.3, mental_health_disorders: 14.5, work_life_balance: 40, social_support: 62 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2023, values: { life_satisfaction: 4.8, mental_health_disorders: 13.0, work_life_balance: 36, social_support: 60 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2023, values: { life_satisfaction: 4.0, mental_health_disorders: 14.0, work_life_balance: 32, social_support: 55 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2023, values: { life_satisfaction: 4.2, mental_health_disorders: 15.0, work_life_balance: 30, social_support: 55 } },
    { geoCode: 'AF', geoName: 'Afghanistan',    dataYear: 2023, values: { life_satisfaction: 1.9, mental_health_disorders: 20.0, work_life_balance: 22, social_support: 38 } },
    // ── Asie centrale ──────────────────────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2023, values: { life_satisfaction: 5.8, mental_health_disorders: 16.0, work_life_balance: 44, social_support: 68 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2023, values: { life_satisfaction: 6.0, mental_health_disorders: 14.0, work_life_balance: 42, social_support: 72 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2023, values: { life_satisfaction: 5.4, mental_health_disorders: 14.5, work_life_balance: 38, social_support: 65 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2023, values: { life_satisfaction: 5.4, mental_health_disorders: 14.0, work_life_balance: 40, social_support: 68 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2023, values: { life_satisfaction: 5.0, mental_health_disorders: 13.5, work_life_balance: 35, social_support: 62 } },
    // ── Caucase ────────────────────────────────────────────────────────────
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2023, values: { life_satisfaction: 5.0, mental_health_disorders: 16.0, work_life_balance: 40, social_support: 62 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2023, values: { life_satisfaction: 5.0, mental_health_disorders: 16.5, work_life_balance: 38, social_support: 60 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2023, values: { life_satisfaction: 5.2, mental_health_disorders: 14.5, work_life_balance: 40, social_support: 64 } },
    // ── Ex-URSS (Europe) ──────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2023, values: { life_satisfaction: 5.5, mental_health_disorders: 19.0, work_life_balance: 42, social_support: 65 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2023, values: { life_satisfaction: 4.8, mental_health_disorders: 22.0, work_life_balance: 40, social_support: 60 } },
    // ── Moyen-Orient ──────────────────────────────────────────────────────
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2023, values: { life_satisfaction: 7.3, mental_health_disorders: 18.0, work_life_balance: 55, social_support: 84 } },
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2023, values: { life_satisfaction: 6.6, mental_health_disorders: 15.0, work_life_balance: 50, social_support: 78 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2023, values: { life_satisfaction: 5.2, mental_health_disorders: 17.0, work_life_balance: 45, social_support: 72 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2023, values: { life_satisfaction: 6.7, mental_health_disorders: 14.5, work_life_balance: 52, social_support: 80 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2023, values: { life_satisfaction: 6.4, mental_health_disorders: 14.0, work_life_balance: 50, social_support: 78 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2023, values: { life_satisfaction: 6.1, mental_health_disorders: 15.0, work_life_balance: 48, social_support: 76 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2023, values: { life_satisfaction: 6.2, mental_health_disorders: 14.5, work_life_balance: 50, social_support: 78 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2023, values: { life_satisfaction: 6.0, mental_health_disorders: 13.5, work_life_balance: 48, social_support: 74 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2023, values: { life_satisfaction: 4.6, mental_health_disorders: 15.5, work_life_balance: 38, social_support: 64 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2023, values: { life_satisfaction: 3.8, mental_health_disorders: 18.0, work_life_balance: 35, social_support: 60 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2023, values: { life_satisfaction: 4.3, mental_health_disorders: 17.5, work_life_balance: 32, social_support: 55 } },
    // ── Afrique du Nord ───────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2023, values: { life_satisfaction: 4.5, mental_health_disorders: 14.0, work_life_balance: 35, social_support: 58 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2023, values: { life_satisfaction: 5.0, mental_health_disorders: 14.5, work_life_balance: 38, social_support: 60 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2023, values: { life_satisfaction: 4.8, mental_health_disorders: 14.0, work_life_balance: 36, social_support: 58 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2023, values: { life_satisfaction: 4.5, mental_health_disorders: 15.0, work_life_balance: 38, social_support: 58 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2023, values: { life_satisfaction: 4.6, mental_health_disorders: 15.5, work_life_balance: 34, social_support: 62 } },
    // ── Afrique subsaharienne (Ouest) ─────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2023, values: { life_satisfaction: 4.9, mental_health_disorders: 14.0, work_life_balance: 42, social_support: 62 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2023, values: { life_satisfaction: 4.8, mental_health_disorders: 13.0, work_life_balance: 40, social_support: 60 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2023, values: { life_satisfaction: 4.6, mental_health_disorders: 12.0, work_life_balance: 38, social_support: 62 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2023, values: { life_satisfaction: 4.7, mental_health_disorders: 12.5, work_life_balance: 36, social_support: 58 } },
    // ── Afrique subsaharienne (Centre) ────────────────────────────────────
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2023, values: { life_satisfaction: 4.5, mental_health_disorders: 12.5, work_life_balance: 35, social_support: 55 } },
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2023, values: { life_satisfaction: 3.5, mental_health_disorders: 13.5, work_life_balance: 28, social_support: 48 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2023, values: { life_satisfaction: 4.6, mental_health_disorders: 13.0, work_life_balance: 38, social_support: 58 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2023, values: { life_satisfaction: 3.8, mental_health_disorders: 13.0, work_life_balance: 32, social_support: 50 } },
    // ── Afrique subsaharienne (Est) ───────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2023, values: { life_satisfaction: 4.8, mental_health_disorders: 14.5, work_life_balance: 40, social_support: 60 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2023, values: { life_satisfaction: 3.8, mental_health_disorders: 12.0, work_life_balance: 35, social_support: 55 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2023, values: { life_satisfaction: 4.0, mental_health_disorders: 12.5, work_life_balance: 34, social_support: 55 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2023, values: { life_satisfaction: 3.9, mental_health_disorders: 12.0, work_life_balance: 36, social_support: 54 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2023, values: { life_satisfaction: 3.8, mental_health_disorders: 13.0, work_life_balance: 32, social_support: 52 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2023, values: { life_satisfaction: 3.7, mental_health_disorders: 12.5, work_life_balance: 30, social_support: 48 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2023, values: { life_satisfaction: 3.6, mental_health_disorders: 12.0, work_life_balance: 32, social_support: 50 } },
    // ── Afrique subsaharienne (Sud) ───────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2023, values: { life_satisfaction: 4.7, mental_health_disorders: 20.0, work_life_balance: 38, social_support: 58 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2023, values: { life_satisfaction: 3.6, mental_health_disorders: 14.5, work_life_balance: 30, social_support: 50 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2023, values: { life_satisfaction: 4.2, mental_health_disorders: 14.0, work_life_balance: 38, social_support: 58 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2023, values: { life_satisfaction: 4.3, mental_health_disorders: 14.0, work_life_balance: 36, social_support: 56 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2023, values: { life_satisfaction: 5.5, mental_health_disorders: 14.0, work_life_balance: 48, social_support: 68 } },
    // ── Afrique subsaharienne (autres) ────────────────────────────────────
    { geoCode: 'SD', geoName: 'Sudan',          dataYear: 2023, values: { life_satisfaction: 3.5, mental_health_disorders: 14.5, work_life_balance: 28, social_support: 45 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2023, values: { life_satisfaction: 3.9, mental_health_disorders: 11.5, work_life_balance: 32, social_support: 52 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2023, values: { life_satisfaction: 3.8, mental_health_disorders: 11.0, work_life_balance: 30, social_support: 50 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2023, values: { life_satisfaction: 3.7, mental_health_disorders: 11.0, work_life_balance: 28, social_support: 48 } },
    { geoCode: 'TD', geoName: 'Chad',           dataYear: 2023, values: { life_satisfaction: 3.3, mental_health_disorders: 12.0, work_life_balance: 26, social_support: 44 } },
    { geoCode: 'MW', geoName: 'Malawi',         dataYear: 2023, values: { life_satisfaction: 3.5, mental_health_disorders: 12.0, work_life_balance: 30, social_support: 50 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2023, values: { life_satisfaction: 3.8, mental_health_disorders: 13.0, work_life_balance: 32, social_support: 52 } },
    { geoCode: 'SO', geoName: 'Somalia',        dataYear: 2023, values: { life_satisfaction: 3.0, mental_health_disorders: 15.0, work_life_balance: 24, social_support: 42 } },
    // ── Asie (autres) ─────────────────────────────────────────────────────
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2023, values: { life_satisfaction: 5.3, mental_health_disorders: 15.0, work_life_balance: 42, social_support: 66 } },
    { geoCode: 'HK', geoName: 'Hong Kong',      dataYear: 2023, values: { life_satisfaction: 5.4, mental_health_disorders: 15.5, work_life_balance: 38, social_support: 74 } },
    // ── Amérique latine (autres) ──────────────────────────────────────────
    { geoCode: 'GY', geoName: 'Guyana',         dataYear: 2023, values: { life_satisfaction: 5.0, mental_health_disorders: 14.0, work_life_balance: 40, social_support: 66 } },
    { geoCode: 'SR', geoName: 'Suriname',       dataYear: 2023, values: { life_satisfaction: 5.1, mental_health_disorders: 14.5, work_life_balance: 42, social_support: 68 } },
    // ── Moyen-Orient (autres) ─────────────────────────────────────────────
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2023, values: { life_satisfaction: 4.6, mental_health_disorders: 17.5, work_life_balance: 38, social_support: 62 } },
    { geoCode: 'YE', geoName: 'Yemen',          dataYear: 2023, values: { life_satisfaction: 3.2, mental_health_disorders: 18.0, work_life_balance: 25, social_support: 40 } },
    { geoCode: 'SY', geoName: 'Syria',          dataYear: 2023, values: { life_satisfaction: 3.0, mental_health_disorders: 20.0, work_life_balance: 24, social_support: 38 } },
    { geoCode: 'PS', geoName: 'Palestine',      dataYear: 2023, values: { life_satisfaction: 3.5, mental_health_disorders: 19.0, work_life_balance: 28, social_support: 52 } },
    // ── Asie du Sud (autres) ──────────────────────────────────────────────
    { geoCode: 'BT', geoName: 'Bhutan',         dataYear: 2023, values: { life_satisfaction: 5.2, mental_health_disorders: 11.5, work_life_balance: 48, social_support: 68 } },
    { geoCode: 'MV', geoName: 'Maldives',       dataYear: 2023, values: { life_satisfaction: 5.0, mental_health_disorders: 13.0, work_life_balance: 45, social_support: 65 } },
  ],
  seedDataPrev: [
    // ── Europe nordique ──────────────────────────────────────────────────── (Sources: WHR 2023 life_satisfaction & social_support (2020-2022 avg); IHME GBD 2021 mental health; OECD BLI work-life balance)
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2022, values: { life_satisfaction: 7.80, mental_health_disorders: 18.8, work_life_balance: 79, social_support: 95 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2022, values: { life_satisfaction: 7.59, mental_health_disorders: 17.0, work_life_balance: 83, social_support: 95 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2022, values: { life_satisfaction: 7.53, mental_health_disorders: 16.2, work_life_balance: 81, social_support: 98 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2022, values: { life_satisfaction: 7.32, mental_health_disorders: 16.4, work_life_balance: 77, social_support: 95 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2022, values: { life_satisfaction: 7.40, mental_health_disorders: 18.2, work_life_balance: 81, social_support: 93 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2022, values: { life_satisfaction: 7.40, mental_health_disorders: 18.9, work_life_balance: 79, social_support: 93 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2022, values: { life_satisfaction: 7.51, mental_health_disorders: 16.8, work_life_balance: 73, social_support: 94 } },
    // ── Europe de l'Ouest ──────────────────────────────────────────────────
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2022, values: { life_satisfaction: 7.10, mental_health_disorders: 17.2, work_life_balance: 71, social_support: 91 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2022, values: { life_satisfaction: 6.81, mental_health_disorders: 20.8, work_life_balance: 69, social_support: 90 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2022, values: { life_satisfaction: 7.23, mental_health_disorders: 15.8, work_life_balance: 68, social_support: 90 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2022, values: { life_satisfaction: 7.03, mental_health_disorders: 17.5, work_life_balance: 61, social_support: 90 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2022, values: { life_satisfaction: 6.66, mental_health_disorders: 20.2, work_life_balance: 66, social_support: 87 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2022, values: { life_satisfaction: 7.04, mental_health_disorders: 18.2, work_life_balance: 73, social_support: 95 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2022, values: { life_satisfaction: 6.80, mental_health_disorders: 21.6, work_life_balance: 61, social_support: 91 } },
    // ── Europe du Sud ────────────────────────────────────────────────────
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2022, values: { life_satisfaction: 6.48, mental_health_disorders: 14.6, work_life_balance: 63, social_support: 92 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2022, values: { life_satisfaction: 6.47, mental_health_disorders: 15.3, work_life_balance: 72, social_support: 88 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2022, values: { life_satisfaction: 6.05, mental_health_disorders: 19.0, work_life_balance: 56, social_support: 87 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2022, values: { life_satisfaction: 5.93, mental_health_disorders: 16.2, work_life_balance: 43, social_support: 76 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2022, values: { life_satisfaction: 6.60, mental_health_disorders: 14.8, work_life_balance: 61, social_support: 87 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2022, values: { life_satisfaction: 6.10, mental_health_disorders: 14.5, work_life_balance: 56, social_support: 82 } },
    // ── Europe de l'Est ────────────────────────────────────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2022, values: { life_satisfaction: 6.92, mental_health_disorders: 15.8, work_life_balance: 56, social_support: 90 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2022, values: { life_satisfaction: 6.26, mental_health_disorders: 16.8, work_life_balance: 51, social_support: 89 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2022, values: { life_satisfaction: 6.04, mental_health_disorders: 18.2, work_life_balance: 46, social_support: 81 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2022, values: { life_satisfaction: 6.33, mental_health_disorders: 15.8, work_life_balance: 51, social_support: 85 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2022, values: { life_satisfaction: 5.99, mental_health_disorders: 15.2, work_life_balance: 49, social_support: 83 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2022, values: { life_satisfaction: 6.59, mental_health_disorders: 15.8, work_life_balance: 46, social_support: 80 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2022, values: { life_satisfaction: 5.47, mental_health_disorders: 15.8, work_life_balance: 41, social_support: 80 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2022, values: { life_satisfaction: 6.46, mental_health_disorders: 15.5, work_life_balance: 59, social_support: 82 } },
    // ── Europe balte ───────────────────────────────────────────────────────
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2022, values: { life_satisfaction: 6.30, mental_health_disorders: 16.2, work_life_balance: 56, social_support: 80 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2022, values: { life_satisfaction: 6.06, mental_health_disorders: 17.0, work_life_balance: 53, social_support: 76 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2022, values: { life_satisfaction: 5.85, mental_health_disorders: 16.8, work_life_balance: 51, social_support: 74 } },
    // ── Balkans ────────────────────────────────────────────────────────────
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2022, values: { life_satisfaction: 5.35, mental_health_disorders: 16.2, work_life_balance: 43, social_support: 68 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2022, values: { life_satisfaction: 5.15, mental_health_disorders: 15.8, work_life_balance: 41, social_support: 66 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2022, values: { life_satisfaction: 4.95, mental_health_disorders: 14.2, work_life_balance: 39, social_support: 62 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2022, values: { life_satisfaction: 5.05, mental_health_disorders: 14.8, work_life_balance: 41, social_support: 64 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2022, values: { life_satisfaction: 5.55, mental_health_disorders: 15.0, work_life_balance: 43, social_support: 67 } },
    // ── Europe de l'Est (hors UE) ──────────────────────────────────────────
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2022, values: { life_satisfaction: 5.10, mental_health_disorders: 17.2, work_life_balance: 39, social_support: 64 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2022, values: { life_satisfaction: 5.40, mental_health_disorders: 17.8, work_life_balance: 43, social_support: 67 } },
    // ── Amérique du Nord ──────────────────────────────────────────────────
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2022, values: { life_satisfaction: 6.96, mental_health_disorders: 20.2, work_life_balance: 69, social_support: 92 } },
    { geoCode: 'US', geoName: 'United States',  dataYear: 2022, values: { life_satisfaction: 6.89, mental_health_disorders: 22.2, work_life_balance: 56, social_support: 90 } },
    // ── Amérique centrale & Caraïbes ──────────────────────────────────────
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2022, values: { life_satisfaction: 6.58, mental_health_disorders: 15.2, work_life_balance: 56, social_support: 82 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2022, values: { life_satisfaction: 6.15, mental_health_disorders: 13.8, work_life_balance: 51, social_support: 78 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2022, values: { life_satisfaction: 6.15, mental_health_disorders: 12.2, work_life_balance: 43, social_support: 74 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2022, values: { life_satisfaction: 5.92, mental_health_disorders: 12.8, work_life_balance: 39, social_support: 72 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2022, values: { life_satisfaction: 5.85, mental_health_disorders: 13.2, work_life_balance: 41, social_support: 72 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2022, values: { life_satisfaction: 5.75, mental_health_disorders: 12.5, work_life_balance: 39, social_support: 70 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2022, values: { life_satisfaction: 5.65, mental_health_disorders: 14.2, work_life_balance: 46, social_support: 74 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2022, values: { life_satisfaction: 5.75, mental_health_disorders: 15.2, work_life_balance: 49, social_support: 76 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2022, values: { life_satisfaction: 5.65, mental_health_disorders: 13.8, work_life_balance: 43, social_support: 74 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2022, values: { life_satisfaction: 5.40, mental_health_disorders: 14.8, work_life_balance: 46, social_support: 76 } },
    { geoCode: 'HT', geoName: 'Haiti',          dataYear: 2022, values: { life_satisfaction: 3.70, mental_health_disorders: 15.8, work_life_balance: 29, social_support: 50 } },
    // ── Amérique du Sud ──────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2022, values: { life_satisfaction: 6.33, mental_health_disorders: 18.8, work_life_balance: 53, social_support: 84 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2022, values: { life_satisfaction: 6.69, mental_health_disorders: 17.8, work_life_balance: 38, social_support: 85 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2022, values: { life_satisfaction: 6.02, mental_health_disorders: 22.8, work_life_balance: 49, social_support: 88 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2022, values: { life_satisfaction: 6.17, mental_health_disorders: 20.8, work_life_balance: 51, social_support: 83 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2022, values: { life_satisfaction: 6.16, mental_health_disorders: 16.8, work_life_balance: 40, social_support: 85 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2022, values: { life_satisfaction: 6.47, mental_health_disorders: 19.2, work_life_balance: 56, social_support: 80 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2022, values: { life_satisfaction: 5.45, mental_health_disorders: 15.2, work_life_balance: 43, social_support: 70 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2022, values: { life_satisfaction: 5.75, mental_health_disorders: 14.2, work_life_balance: 46, social_support: 74 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2022, values: { life_satisfaction: 5.15, mental_health_disorders: 16.8, work_life_balance: 39, social_support: 70 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2022, values: { life_satisfaction: 5.55, mental_health_disorders: 12.8, work_life_balance: 45, social_support: 74 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2022, values: { life_satisfaction: 5.25, mental_health_disorders: 13.8, work_life_balance: 41, social_support: 68 } },
    // ── Océanie ───────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2022, values: { life_satisfaction: 7.10, mental_health_disorders: 21.2, work_life_balance: 71, social_support: 93 } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2022, values: { life_satisfaction: 7.12, mental_health_disorders: 20.6, work_life_balance: 73, social_support: 94 } },
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2022, values: { life_satisfaction: 5.15, mental_health_disorders: 12.2, work_life_balance: 49, social_support: 72 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2022, values: { life_satisfaction: 4.35, mental_health_disorders: 11.2, work_life_balance: 36, social_support: 57 } },
    // ── Asie de l'Est ──────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2022, values: { life_satisfaction: 6.13, mental_health_disorders: 16.8, work_life_balance: 41, social_support: 90 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2022, values: { life_satisfaction: 5.95, mental_health_disorders: 21.8, work_life_balance: 36, social_support: 81 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2022, values: { life_satisfaction: 5.82, mental_health_disorders: 16.8, work_life_balance: 43, social_support: 80 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2022, values: { life_satisfaction: 6.54, mental_health_disorders: 15.8, work_life_balance: 46, social_support: 84 } },
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2022, values: { life_satisfaction: 6.48, mental_health_disorders: 12.8, work_life_balance: 53, social_support: 87 } },
    // ── Asie du Sud-Est ────────────────────────────────────────────────────
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2022, values: { life_satisfaction: 6.01, mental_health_disorders: 14.8, work_life_balance: 53, social_support: 83 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2022, values: { life_satisfaction: 5.75, mental_health_disorders: 13.8, work_life_balance: 51, social_support: 76 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2022, values: { life_satisfaction: 5.45, mental_health_disorders: 12.2, work_life_balance: 49, social_support: 74 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2022, values: { life_satisfaction: 5.45, mental_health_disorders: 13.2, work_life_balance: 43, social_support: 74 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2022, values: { life_satisfaction: 5.25, mental_health_disorders: 11.8, work_life_balance: 46, social_support: 72 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2022, values: { life_satisfaction: 4.10, mental_health_disorders: 12.8, work_life_balance: 36, social_support: 57 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2022, values: { life_satisfaction: 4.45, mental_health_disorders: 12.2, work_life_balance: 39, social_support: 62 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2022, values: { life_satisfaction: 4.75, mental_health_disorders: 11.8, work_life_balance: 41, social_support: 64 } },
    { geoCode: 'BN', geoName: 'Brunei',         dataYear: 2022, values: { life_satisfaction: 5.95, mental_health_disorders: 12.2, work_life_balance: 56, social_support: 80 } },
    // ── Asie du Sud ────────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2022, values: { life_satisfaction: 4.04, mental_health_disorders: 14.0, work_life_balance: 39, social_support: 59 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2022, values: { life_satisfaction: 4.25, mental_health_disorders: 14.2, work_life_balance: 41, social_support: 64 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2022, values: { life_satisfaction: 4.75, mental_health_disorders: 12.8, work_life_balance: 37, social_support: 62 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2022, values: { life_satisfaction: 3.95, mental_health_disorders: 13.8, work_life_balance: 33, social_support: 57 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2022, values: { life_satisfaction: 4.15, mental_health_disorders: 14.8, work_life_balance: 31, social_support: 57 } },
    { geoCode: 'AF', geoName: 'Afghanistan',    dataYear: 2022, values: { life_satisfaction: 1.86, mental_health_disorders: 19.8, work_life_balance: 23, social_support: 40 } },
    // ── Asie centrale ──────────────────────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2022, values: { life_satisfaction: 6.12, mental_health_disorders: 15.8, work_life_balance: 45, social_support: 89 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2022, values: { life_satisfaction: 5.95, mental_health_disorders: 13.8, work_life_balance: 43, social_support: 74 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2022, values: { life_satisfaction: 5.35, mental_health_disorders: 14.2, work_life_balance: 39, social_support: 67 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2022, values: { life_satisfaction: 5.35, mental_health_disorders: 13.8, work_life_balance: 41, social_support: 70 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2022, values: { life_satisfaction: 4.95, mental_health_disorders: 13.2, work_life_balance: 36, social_support: 64 } },
    // ── Caucase ────────────────────────────────────────────────────────────
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2022, values: { life_satisfaction: 4.95, mental_health_disorders: 15.8, work_life_balance: 41, social_support: 64 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2022, values: { life_satisfaction: 4.95, mental_health_disorders: 16.2, work_life_balance: 39, social_support: 62 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2022, values: { life_satisfaction: 5.15, mental_health_disorders: 14.2, work_life_balance: 41, social_support: 66 } },
    // ── Ex-URSS (Europe) ──────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2022, values: { life_satisfaction: 5.66, mental_health_disorders: 18.8, work_life_balance: 43, social_support: 86 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2022, values: { life_satisfaction: 5.07, mental_health_disorders: 20.8, work_life_balance: 44, social_support: 87 } },
    // ── Moyen-Orient ──────────────────────────────────────────────────────
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2022, values: { life_satisfaction: 7.47, mental_health_disorders: 17.8, work_life_balance: 56, social_support: 91 } },
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2022, values: { life_satisfaction: 6.46, mental_health_disorders: 14.8, work_life_balance: 51, social_support: 84 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2022, values: { life_satisfaction: 4.74, mental_health_disorders: 16.8, work_life_balance: 46, social_support: 78 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2022, values: { life_satisfaction: 6.65, mental_health_disorders: 14.2, work_life_balance: 53, social_support: 82 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2022, values: { life_satisfaction: 6.35, mental_health_disorders: 13.8, work_life_balance: 51, social_support: 80 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2022, values: { life_satisfaction: 6.05, mental_health_disorders: 14.8, work_life_balance: 49, social_support: 78 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2022, values: { life_satisfaction: 6.15, mental_health_disorders: 14.2, work_life_balance: 51, social_support: 80 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2022, values: { life_satisfaction: 5.95, mental_health_disorders: 13.2, work_life_balance: 49, social_support: 76 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2022, values: { life_satisfaction: 4.55, mental_health_disorders: 15.2, work_life_balance: 39, social_support: 66 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2022, values: { life_satisfaction: 3.75, mental_health_disorders: 17.8, work_life_balance: 36, social_support: 62 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2022, values: { life_satisfaction: 4.25, mental_health_disorders: 17.2, work_life_balance: 33, social_support: 57 } },
    // ── Afrique du Nord ───────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2022, values: { life_satisfaction: 4.45, mental_health_disorders: 13.8, work_life_balance: 36, social_support: 60 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2022, values: { life_satisfaction: 4.95, mental_health_disorders: 14.2, work_life_balance: 39, social_support: 62 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2022, values: { life_satisfaction: 4.75, mental_health_disorders: 13.8, work_life_balance: 37, social_support: 60 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2022, values: { life_satisfaction: 4.45, mental_health_disorders: 14.8, work_life_balance: 39, social_support: 60 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2022, values: { life_satisfaction: 4.55, mental_health_disorders: 15.2, work_life_balance: 35, social_support: 64 } },
    // ── Afrique subsaharienne (Ouest) ─────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2022, values: { life_satisfaction: 4.98, mental_health_disorders: 13.8, work_life_balance: 43, social_support: 77 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2022, values: { life_satisfaction: 4.75, mental_health_disorders: 12.8, work_life_balance: 41, social_support: 62 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2022, values: { life_satisfaction: 4.55, mental_health_disorders: 11.8, work_life_balance: 39, social_support: 64 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2022, values: { life_satisfaction: 4.65, mental_health_disorders: 12.2, work_life_balance: 37, social_support: 60 } },
    // ── Afrique subsaharienne (Centre) ────────────────────────────────────
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2022, values: { life_satisfaction: 4.45, mental_health_disorders: 12.2, work_life_balance: 36, social_support: 57 } },
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2022, values: { life_satisfaction: 3.45, mental_health_disorders: 13.2, work_life_balance: 29, social_support: 50 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2022, values: { life_satisfaction: 4.55, mental_health_disorders: 12.8, work_life_balance: 39, social_support: 60 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2022, values: { life_satisfaction: 3.75, mental_health_disorders: 12.8, work_life_balance: 33, social_support: 52 } },
    // ── Afrique subsaharienne (Est) ───────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2022, values: { life_satisfaction: 4.58, mental_health_disorders: 14.2, work_life_balance: 41, social_support: 74 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2022, values: { life_satisfaction: 3.75, mental_health_disorders: 11.8, work_life_balance: 36, social_support: 57 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2022, values: { life_satisfaction: 3.95, mental_health_disorders: 12.2, work_life_balance: 35, social_support: 57 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2022, values: { life_satisfaction: 3.85, mental_health_disorders: 11.8, work_life_balance: 37, social_support: 56 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2022, values: { life_satisfaction: 3.75, mental_health_disorders: 12.8, work_life_balance: 33, social_support: 54 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2022, values: { life_satisfaction: 3.65, mental_health_disorders: 12.2, work_life_balance: 31, social_support: 50 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2022, values: { life_satisfaction: 3.55, mental_health_disorders: 11.8, work_life_balance: 33, social_support: 52 } },
    // ── Afrique subsaharienne (Sud) ───────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2022, values: { life_satisfaction: 5.09, mental_health_disorders: 19.8, work_life_balance: 39, social_support: 81 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2022, values: { life_satisfaction: 3.55, mental_health_disorders: 14.2, work_life_balance: 31, social_support: 52 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2022, values: { life_satisfaction: 4.15, mental_health_disorders: 13.8, work_life_balance: 39, social_support: 60 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2022, values: { life_satisfaction: 4.25, mental_health_disorders: 13.8, work_life_balance: 37, social_support: 58 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2022, values: { life_satisfaction: 5.45, mental_health_disorders: 13.8, work_life_balance: 49, social_support: 70 } },
    // ── Afrique subsaharienne (autres) ────────────────────────────────────
    { geoCode: 'SD', geoName: 'Sudan',          dataYear: 2022, values: { life_satisfaction: 3.45, mental_health_disorders: 14.2, work_life_balance: 29, social_support: 47 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2022, values: { life_satisfaction: 3.85, mental_health_disorders: 11.2, work_life_balance: 33, social_support: 54 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2022, values: { life_satisfaction: 3.75, mental_health_disorders: 10.8, work_life_balance: 31, social_support: 52 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2022, values: { life_satisfaction: 3.65, mental_health_disorders: 10.8, work_life_balance: 29, social_support: 50 } },
    { geoCode: 'TD', geoName: 'Chad',           dataYear: 2022, values: { life_satisfaction: 3.25, mental_health_disorders: 11.8, work_life_balance: 27, social_support: 46 } },
    { geoCode: 'MW', geoName: 'Malawi',         dataYear: 2022, values: { life_satisfaction: 3.45, mental_health_disorders: 11.8, work_life_balance: 31, social_support: 52 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2022, values: { life_satisfaction: 3.75, mental_health_disorders: 12.8, work_life_balance: 33, social_support: 54 } },
    { geoCode: 'SO', geoName: 'Somalia',        dataYear: 2022, values: { life_satisfaction: 2.95, mental_health_disorders: 14.8, work_life_balance: 25, social_support: 44 } },
    // ── Asie (autres) ─────────────────────────────────────────────────────
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2022, values: { life_satisfaction: 5.25, mental_health_disorders: 14.8, work_life_balance: 43, social_support: 68 } },
    { geoCode: 'HK', geoName: 'Hong Kong',      dataYear: 2022, values: { life_satisfaction: 5.35, mental_health_disorders: 15.2, work_life_balance: 39, social_support: 76 } },
    // ── Amérique latine (autres) ──────────────────────────────────────────
    { geoCode: 'GY', geoName: 'Guyana',         dataYear: 2022, values: { life_satisfaction: 4.95, mental_health_disorders: 13.8, work_life_balance: 41, social_support: 68 } },
    { geoCode: 'SR', geoName: 'Suriname',       dataYear: 2022, values: { life_satisfaction: 5.05, mental_health_disorders: 14.2, work_life_balance: 43, social_support: 70 } },
    // ── Moyen-Orient (autres) ─────────────────────────────────────────────
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2022, values: { life_satisfaction: 4.55, mental_health_disorders: 17.2, work_life_balance: 39, social_support: 64 } },
    { geoCode: 'YE', geoName: 'Yemen',          dataYear: 2022, values: { life_satisfaction: 3.15, mental_health_disorders: 17.8, work_life_balance: 26, social_support: 42 } },
    { geoCode: 'SY', geoName: 'Syria',          dataYear: 2022, values: { life_satisfaction: 2.95, mental_health_disorders: 19.8, work_life_balance: 25, social_support: 40 } },
    { geoCode: 'PS', geoName: 'Palestine',      dataYear: 2022, values: { life_satisfaction: 3.45, mental_health_disorders: 18.8, work_life_balance: 29, social_support: 54 } },
    // ── Asie du Sud (autres) ──────────────────────────────────────────────
    { geoCode: 'BT', geoName: 'Bhutan',         dataYear: 2022, values: { life_satisfaction: 5.15, mental_health_disorders: 11.2, work_life_balance: 49, social_support: 70 } },
    { geoCode: 'MV', geoName: 'Maldives',       dataYear: 2022, values: { life_satisfaction: 4.95, mental_health_disorders: 12.8, work_life_balance: 46, social_support: 67 } },
  ],
};

export default wellbeingModule;
