import type { DomainModule } from '@/lib/domains/types';

const economicSectorsModule: DomainModule = {
  definition: {
    id: 'economic-sectors',
    label: { fr: 'Secteurs économiques', en: 'Economic Sectors' },
    description: {
      fr: 'Structure économique et compétitivité : PIB par habitant, chômage, part des services et industrie manufacturière.',
      en: 'Economic structure and competitiveness: GDP per capita, unemployment, services share and manufacturing.',
    },
    icon: '🏭',
    group: 'economy',
    active: true,
    seedSources: [
      'https://data.worldbank.org/indicator/NY.GDP.PCAP.PP.CD',
      'https://data.worldbank.org/indicator/SL.UEM.TOTL.ZS',
      'https://data.worldbank.org/indicator/NV.SRV.TOTL.ZS',
    ],
    indicators: [
      {
        id: 'gdp_per_capita',
        label: { fr: 'PIB par habitant (PPA, k$)', en: 'GDP per capita (PPP, k$)' },
        unit: 'currency',
        unitLabel: { fr: 'k$ PPA', en: 'k$ PPP' },
        direction: 'higher_is_better',
        weight: 4,
        thresholds: { excellent: 55, good: 35, fair: 18, poor: 8 },
        minValue: 0,
        maxValue: 150,
      },
      {
        id: 'unemployment_rate',
        label: { fr: 'Taux de chômage', en: 'Unemployment rate' },
        unit: 'percent',
        unitLabel: { fr: '%', en: '%' },
        direction: 'lower_is_better',
        weight: 3,
        thresholds: { excellent: 3.5, good: 5.5, fair: 8.0, poor: 12.0 },
        minValue: 0,
        maxValue: 35,
      },
      {
        id: 'services_share',
        label: { fr: 'Part des services (% PIB)', en: 'Services share (% GDP)' },
        unit: 'percent',
        unitLabel: { fr: '% PIB', en: '% GDP' },
        direction: 'higher_is_better',
        weight: 2,
        thresholds: { excellent: 72, good: 60, fair: 48, poor: 35 },
        minValue: 0,
        maxValue: 90,
      },
      {
        id: 'manufacturing_share',
        label: { fr: 'Part industrie manufacturière (% PIB)', en: 'Manufacturing share (% GDP)' },
        unit: 'percent',
        unitLabel: { fr: '% PIB', en: '% GDP' },
        direction: 'higher_is_better',
        weight: 2,
        thresholds: { excellent: 20, good: 15, fair: 10, poor: 5 },
        minValue: 0,
        maxValue: 45,
      },
    ],
  },
  seedData: [
    // ── Europe nordique & occidentale ────────────────────────────────────────
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2023, values: { gdp_per_capita: 132, unemployment_rate: 4.9,  services_share: 86, manufacturing_share: 5  } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2023, values: { gdp_per_capita: 82,  unemployment_rate: 3.5,  services_share: 70, manufacturing_share: 8  } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2023, values: { gdp_per_capita: 72,  unemployment_rate: 4.1,  services_share: 73, manufacturing_share: 17 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2023, values: { gdp_per_capita: 68,  unemployment_rate: 3.4,  services_share: 73, manufacturing_share: 9  } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2023, values: { gdp_per_capita: 63,  unemployment_rate: 5.0,  services_share: 75, manufacturing_share: 14 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2023, values: { gdp_per_capita: 58,  unemployment_rate: 8.5,  services_share: 72, manufacturing_share: 15 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2023, values: { gdp_per_capita: 63,  unemployment_rate: 3.6,  services_share: 77, manufacturing_share: 12 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2023, values: { gdp_per_capita: 59,  unemployment_rate: 5.0,  services_share: 70, manufacturing_share: 18 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2023, values: { gdp_per_capita: 55,  unemployment_rate: 7.5,  services_share: 72, manufacturing_share: 17 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2023, values: { gdp_per_capita: 57,  unemployment_rate: 2.9,  services_share: 63, manufacturing_share: 22 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2023, values: { gdp_per_capita: 56,  unemployment_rate: 5.5,  services_share: 76, manufacturing_share: 13 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2023, values: { gdp_per_capita: 100, unemployment_rate: 4.3,  services_share: 72, manufacturing_share: 19 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2023, values: { gdp_per_capita: 52,  unemployment_rate: 7.4,  services_share: 78, manufacturing_share: 10 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2023, values: { gdp_per_capita: 53,  unemployment_rate: 4.2,  services_share: 79, manufacturing_share: 10 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2023, values: { gdp_per_capita: 44,  unemployment_rate: 6.7,  services_share: 74, manufacturing_share: 16 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2023, values: { gdp_per_capita: 40,  unemployment_rate: 12.1, services_share: 74, manufacturing_share: 13 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2023, values: { gdp_per_capita: 34,  unemployment_rate: 6.5,  services_share: 75, manufacturing_share: 14 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2023, values: { gdp_per_capita: 29,  unemployment_rate: 11.0, services_share: 79, manufacturing_share: 8  } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2023, values: { gdp_per_capita: 50,  unemployment_rate: 3.5,  services_share: 82, manufacturing_share: 8  } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2023, values: { gdp_per_capita: 42,  unemployment_rate: 5.8,  services_share: 81, manufacturing_share: 5  } },
    // ── Europe de l'Est & Balkans ────────────────────────────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2023, values: { gdp_per_capita: 43,  unemployment_rate: 2.6,  services_share: 61, manufacturing_share: 24 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2023, values: { gdp_per_capita: 36,  unemployment_rate: 2.8,  services_share: 57, manufacturing_share: 21 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2023, values: { gdp_per_capita: 35,  unemployment_rate: 6.0,  services_share: 57, manufacturing_share: 25 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2023, values: { gdp_per_capita: 36,  unemployment_rate: 3.9,  services_share: 56, manufacturing_share: 24 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2023, values: { gdp_per_capita: 30,  unemployment_rate: 5.8,  services_share: 63, manufacturing_share: 14 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2023, values: { gdp_per_capita: 32,  unemployment_rate: 5.6,  services_share: 54, manufacturing_share: 22 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2023, values: { gdp_per_capita: 25,  unemployment_rate: 4.3,  services_share: 62, manufacturing_share: 17 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2023, values: { gdp_per_capita: 42,  unemployment_rate: 3.7,  services_share: 63, manufacturing_share: 22 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2023, values: { gdp_per_capita: 39,  unemployment_rate: 6.4,  services_share: 67, manufacturing_share: 16 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2023, values: { gdp_per_capita: 33,  unemployment_rate: 6.5,  services_share: 68, manufacturing_share: 12 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2023, values: { gdp_per_capita: 38,  unemployment_rate: 6.9,  services_share: 65, manufacturing_share: 17 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2023, values: { gdp_per_capita: 21,  unemployment_rate: 9.5,  services_share: 56, manufacturing_share: 15 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2023, values: { gdp_per_capita: 16, unemployment_rate: 14.0, services_share: 55, manufacturing_share: 14 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2023, values: { gdp_per_capita: 17, unemployment_rate: 14.5, services_share: 57, manufacturing_share: 13 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2023, values: { gdp_per_capita: 16,  unemployment_rate: 11.0, services_share: 50, manufacturing_share: 7  } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2023, values: { gdp_per_capita: 22,  unemployment_rate: 13.0, services_share: 65, manufacturing_share: 5  } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2023, values: { gdp_per_capita: 15,  unemployment_rate: 4.0,  services_share: 60, manufacturing_share: 12 } },
    // ── Amérique du Nord ────────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',  dataYear: 2023, values: { gdp_per_capita: 80,  unemployment_rate: 3.6,  services_share: 77, manufacturing_share: 11 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2023, values: { gdp_per_capita: 55,  unemployment_rate: 5.4,  services_share: 70, manufacturing_share: 10 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2023, values: { gdp_per_capita: 21,  unemployment_rate: 2.8,  services_share: 63, manufacturing_share: 19 } },
    // ── Amérique centrale & Caraïbes ────────────────────────────────────────
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2023, values: { gdp_per_capita: 30,  unemployment_rate: 7.4,  services_share: 75, manufacturing_share: 6  } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2023, values: { gdp_per_capita: 22,  unemployment_rate: 9.3,  services_share: 68, manufacturing_share: 14 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2023, values: { gdp_per_capita: 20, unemployment_rate: 5.5, services_share: 62, manufacturing_share: 14 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2023, values: { gdp_per_capita: 10,  unemployment_rate: 2.7,  services_share: 62, manufacturing_share: 17 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2023, values: { gdp_per_capita: 11,  unemployment_rate: 5.9,  services_share: 61, manufacturing_share: 16 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2023, values: { gdp_per_capita: 6,   unemployment_rate: 7.8,  services_share: 56, manufacturing_share: 17 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2023, values: { gdp_per_capita: 12,  unemployment_rate: 5.2,  services_share: 69, manufacturing_share: 8  } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2023, values: { gdp_per_capita: 28, unemployment_rate: 4.2, services_share: 55, manufacturing_share: 16 } },
    // ── Amérique du Sud ─────────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2023, values: { gdp_per_capita: 17,  unemployment_rate: 7.9,  services_share: 65, manufacturing_share: 11 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2023, values: { gdp_per_capita: 23,  unemployment_rate: 6.2,  services_share: 63, manufacturing_share: 16 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2023, values: { gdp_per_capita: 26,  unemployment_rate: 8.7,  services_share: 64, manufacturing_share: 11 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2023, values: { gdp_per_capita: 16,  unemployment_rate: 10.2, services_share: 58, manufacturing_share: 13 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2023, values: { gdp_per_capita: 14,  unemployment_rate: 6.5,  services_share: 57, manufacturing_share: 13 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2023, values: { gdp_per_capita: 12,  unemployment_rate: 3.8,  services_share: 56, manufacturing_share: 13 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2023, values: { gdp_per_capita: 25,  unemployment_rate: 8.3,  services_share: 66, manufacturing_share: 12 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2023, values: { gdp_per_capita: 14,  unemployment_rate: 6.0,  services_share: 52, manufacturing_share: 19 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2023, values: { gdp_per_capita: 9,   unemployment_rate: 4.5,  services_share: 48, manufacturing_share: 12 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2023, values: { gdp_per_capita: 8,   unemployment_rate: 5.5,  services_share: 50, manufacturing_share: 10 } },
    // ── Océanie ─────────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2023, values: { gdp_per_capita: 60,  unemployment_rate: 3.7,  services_share: 71, manufacturing_share: 6  } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2023, values: { gdp_per_capita: 46,  unemployment_rate: 3.6,  services_share: 69, manufacturing_share: 12 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2023, values: { gdp_per_capita: 4, unemployment_rate: 2.6,  services_share: 38, manufacturing_share: 5  } },
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2023, values: { gdp_per_capita: 13,  unemployment_rate: 4.5,  services_share: 62, manufacturing_share: 10 } },
    // ── Asie de l'Est ───────────────────────────────────────────────────────
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2023, values: { gdp_per_capita: 130, unemployment_rate: 2.1,  services_share: 72, manufacturing_share: 20 } },
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2023, values: { gdp_per_capita: 44,  unemployment_rate: 2.6,  services_share: 73, manufacturing_share: 21 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2023, values: { gdp_per_capita: 49,  unemployment_rate: 2.7,  services_share: 63, manufacturing_share: 26 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2023, values: { gdp_per_capita: 55,  unemployment_rate: 3.5,  services_share: 61, manufacturing_share: 31 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2023, values: { gdp_per_capita: 21,  unemployment_rate: 5.2,  services_share: 53, manufacturing_share: 28 } },
    { geoCode: 'HK', geoName: 'Hong Kong',      dataYear: 2023, values: { gdp_per_capita: 65,  unemployment_rate: 2.9,  services_share: 93, manufacturing_share: 1  } },
    { geoCode: 'MO', geoName: 'Macao',          dataYear: 2023, values: { gdp_per_capita: 45,  unemployment_rate: 2.6,  services_share: 88, manufacturing_share: 2  } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2023, values: { gdp_per_capita: 14,  unemployment_rate: 5.7,  services_share: 48, manufacturing_share: 10 } },
    // ── Asie du Sud-Est ─────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2023, values: { gdp_per_capita: 9,   unemployment_rate: 7.9,  services_share: 50, manufacturing_share: 18 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2023, values: { gdp_per_capita: 14,  unemployment_rate: 5.3,  services_share: 44, manufacturing_share: 21 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2023, values: { gdp_per_capita: 21,  unemployment_rate: 1.0,  services_share: 57, manufacturing_share: 27 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2023, values: { gdp_per_capita: 13,  unemployment_rate: 2.3,  services_share: 42, manufacturing_share: 25 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2023, values: { gdp_per_capita: 10,  unemployment_rate: 4.7,  services_share: 60, manufacturing_share: 19 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2023, values: { gdp_per_capita: 33,  unemployment_rate: 3.6,  services_share: 55, manufacturing_share: 23 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2023, values: { gdp_per_capita: 5,   unemployment_rate: 0.5,  services_share: 38, manufacturing_share: 18 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2023, values: { gdp_per_capita: 5,   unemployment_rate: 2.8,  services_share: 42, manufacturing_share: 22 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2023, values: { gdp_per_capita: 8,   unemployment_rate: 1.5,  services_share: 41, manufacturing_share: 10 } },
    { geoCode: 'BN', geoName: 'Brunei',         dataYear: 2023, values: { gdp_per_capita: 65,  unemployment_rate: 5.1,  services_share: 42, manufacturing_share: 12 } },
    // ── Asie du Sud ─────────────────────────────────────────────────────────
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2023, values: { gdp_per_capita: 6,   unemployment_rate: 6.3,  services_share: 52, manufacturing_share: 13 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2023, values: { gdp_per_capita: 7,   unemployment_rate: 5.3,  services_share: 52, manufacturing_share: 24 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2023, values: { gdp_per_capita: 14,  unemployment_rate: 6.4,  services_share: 58, manufacturing_share: 17 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2023, values: { gdp_per_capita: 4,   unemployment_rate: 5.0,  services_share: 54, manufacturing_share: 5  } },
    // ── Asie centrale ───────────────────────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2023, values: { gdp_per_capita: 29,  unemployment_rate: 4.8,  services_share: 54, manufacturing_share: 12 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2023, values: { gdp_per_capita: 9,   unemployment_rate: 5.6,  services_share: 43, manufacturing_share: 18 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2023, values: { gdp_per_capita: 16,  unemployment_rate: 5.7,  services_share: 42, manufacturing_share: 7  } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2023, values: { gdp_per_capita: 17,  unemployment_rate: 15.6, services_share: 62, manufacturing_share: 9  } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2023, values: { gdp_per_capita: 16,  unemployment_rate: 13.5, services_share: 55, manufacturing_share: 10 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2023, values: { gdp_per_capita: 6,   unemployment_rate: 5.3,  services_share: 51, manufacturing_share: 15 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2023, values: { gdp_per_capita: 4,   unemployment_rate: 6.8,  services_share: 42, manufacturing_share: 14 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2023, values: { gdp_per_capita: 12,  unemployment_rate: 4.0,  services_share: 38, manufacturing_share: 20 } },
    // ── Moyen-Orient & Golfe ────────────────────────────────────────────────
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2023, values: { gdp_per_capita: 58,  unemployment_rate: 4.9,  services_share: 52, manufacturing_share: 12 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2023, values: { gdp_per_capita: 78, unemployment_rate: 2.9, services_share: 56, manufacturing_share: 9 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2023, values: { gdp_per_capita: 112, unemployment_rate: 0.1,  services_share: 50, manufacturing_share: 8  } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2023, values: { gdp_per_capita: 52,  unemployment_rate: 2.1,  services_share: 53, manufacturing_share: 7  } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2023, values: { gdp_per_capita: 54,  unemployment_rate: 1.5,  services_share: 62, manufacturing_share: 14 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2023, values: { gdp_per_capita: 42,  unemployment_rate: 2.3,  services_share: 52, manufacturing_share: 10 } },
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2023, values: { gdp_per_capita: 52,  unemployment_rate: 3.5,  services_share: 73, manufacturing_share: 12 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2023, values: { gdp_per_capita: 11,  unemployment_rate: 21.4, services_share: 64, manufacturing_share: 17 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2023, values: { gdp_per_capita: 12,  unemployment_rate: 12.0, services_share: 75, manufacturing_share: 6  } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2023, values: { gdp_per_capita: 11,  unemployment_rate: 15.5, services_share: 47, manufacturing_share: 3  } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2023, values: { gdp_per_capita: 34,  unemployment_rate: 9.6,  services_share: 54, manufacturing_share: 20 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2023, values: { gdp_per_capita: 14,  unemployment_rate: 10.4, services_share: 50, manufacturing_share: 14 } },
    // ── Ex-URSS (Russie, Ukraine, Biélorussie) ──────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2023, values: { gdp_per_capita: 27,  unemployment_rate: 3.1,  services_share: 55, manufacturing_share: 14 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2023, values: { gdp_per_capita: 14,  unemployment_rate: 19.5, services_share: 60, manufacturing_share: 14 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2023, values: { gdp_per_capita: 22,  unemployment_rate: 3.6,  services_share: 50, manufacturing_share: 22 } },
    // ── Afrique du Nord ─────────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2023, values: { gdp_per_capita: 13,  unemployment_rate: 7.2,  services_share: 55, manufacturing_share: 16 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2023, values: { gdp_per_capita: 9,   unemployment_rate: 12.0, services_share: 52, manufacturing_share: 17 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2023, values: { gdp_per_capita: 12,  unemployment_rate: 11.8, services_share: 46, manufacturing_share: 5  } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2023, values: { gdp_per_capita: 12,  unemployment_rate: 15.2, services_share: 62, manufacturing_share: 16 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2023, values: { gdp_per_capita: 16,  unemployment_rate: 18.5, services_share: 40, manufacturing_share: 4  } },
    // ── Afrique de l'Ouest ──────────────────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2023, values: { gdp_per_capita: 5,   unemployment_rate: 22.0, services_share: 52, manufacturing_share: 12 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2023, values: { gdp_per_capita: 6,   unemployment_rate: 13.4, services_share: 47, manufacturing_share: 10 } },
    { geoCode: 'CI', geoName: "Côte d'Ivoire",  dataYear: 2023, values: { gdp_per_capita: 6,   unemployment_rate: 3.0,  services_share: 44, manufacturing_share: 12 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2023, values: { gdp_per_capita: 4,   unemployment_rate: 6.5,  services_share: 53, manufacturing_share: 14 } },
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2023, values: { gdp_per_capita: 4,   unemployment_rate: 3.6,  services_share: 53, manufacturing_share: 12 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2023, values: { gdp_per_capita: 2,   unemployment_rate: 5.0,  services_share: 40, manufacturing_share: 7  } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2023, values: { gdp_per_capita: 2,   unemployment_rate: 7.4,  services_share: 38, manufacturing_share: 5  } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2023, values: { gdp_per_capita: 1,   unemployment_rate: 0.5,  services_share: 36, manufacturing_share: 6  } },
    { geoCode: 'GN', geoName: 'Guinea',         dataYear: 2023, values: { gdp_per_capita: 3,   unemployment_rate: 5.5,  services_share: 40, manufacturing_share: 10 } },
    // ── Afrique de l'Est ────────────────────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2023, values: { gdp_per_capita: 6,   unemployment_rate: 12.0, services_share: 46, manufacturing_share: 9  } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2023, values: { gdp_per_capita: 3,   unemployment_rate: 18.0, services_share: 38, manufacturing_share: 7  } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2023, values: { gdp_per_capita: 3,   unemployment_rate: 9.5,  services_share: 38, manufacturing_share: 8  } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2023, values: { gdp_per_capita: 3,   unemployment_rate: 9.2,  services_share: 42, manufacturing_share: 9  } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2023, values: { gdp_per_capita: 3,   unemployment_rate: 14.0, services_share: 48, manufacturing_share: 7  } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2023, values: { gdp_per_capita: 2,   unemployment_rate: 4.8,  services_share: 48, manufacturing_share: 13 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2023, values: { gdp_per_capita: 1,   unemployment_rate: 3.5,  services_share: 44, manufacturing_share: 9  } },
    // ── Afrique australe ────────────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2023, values: { gdp_per_capita: 14,  unemployment_rate: 32.0, services_share: 62, manufacturing_share: 13 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2023, values: { gdp_per_capita: 18,  unemployment_rate: 25.0, services_share: 56, manufacturing_share: 6  } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2023, values: { gdp_per_capita: 11,  unemployment_rate: 21.0, services_share: 53, manufacturing_share: 9  } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2023, values: { gdp_per_capita: 4,   unemployment_rate: 12.5, services_share: 54, manufacturing_share: 8  } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2023, values: { gdp_per_capita: 3,   unemployment_rate: 17.0, services_share: 52, manufacturing_share: 10 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2023, values: { gdp_per_capita: 7,   unemployment_rate: 8.5,  services_share: 33, manufacturing_share: 6  } },
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2023, values: { gdp_per_capita: 1,   unemployment_rate: 4.5,  services_share: 35, manufacturing_share: 18 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2023, values: { gdp_per_capita: 25,  unemployment_rate: 6.1,  services_share: 70, manufacturing_share: 12 } },
    // ── Golfe & péninsule arabique (complément) ─────────────────────────────
    { geoCode: 'YE', geoName: 'Yemen',          dataYear: 2023, values: { gdp_per_capita: 2,   unemployment_rate: 13.0, services_share: 48, manufacturing_share: 6  } },
    // ── Asie (compléments) ──────────────────────────────────────────────────
    { geoCode: 'AF', geoName: 'Afghanistan',    dataYear: 2023, values: { gdp_per_capita: 2,   unemployment_rate: 14.0, services_share: 45, manufacturing_share: 12 } },
  ],
  seedDataPrev: [
    // ── Europe nordique & occidentale ──────────────────────────────────────── (World Bank 2022)
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2022, values: { gdp_per_capita: 147, unemployment_rate: 4.6,  services_share: 81, manufacturing_share: 4  } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2022, values: { gdp_per_capita: 125, unemployment_rate: 3.2,  services_share: 42, manufacturing_share: 5  } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2022, values: { gdp_per_capita: 94,  unemployment_rate: 4.1,  services_share: 72, manufacturing_share: 18 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2022, values: { gdp_per_capita: 75,  unemployment_rate: 3.8,  services_share: 64, manufacturing_share: 11 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2022, values: { gdp_per_capita: 79,  unemployment_rate: 4.4,  services_share: 66, manufacturing_share: 13 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2022, values: { gdp_per_capita: 67,  unemployment_rate: 7.4,  services_share: 64, manufacturing_share: 14 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2022, values: { gdp_per_capita: 79,  unemployment_rate: 3.5,  services_share: 69, manufacturing_share: 10 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2022, values: { gdp_per_capita: 72,  unemployment_rate: 5.0,  services_share: 62, manufacturing_share: 17 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2022, values: { gdp_per_capita: 62,  unemployment_rate: 6.7,  services_share: 59, manufacturing_share: 16 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2022, values: { gdp_per_capita: 69,  unemployment_rate: 3.1,  services_share: 63, manufacturing_share: 18 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2022, values: { gdp_per_capita: 69,  unemployment_rate: 5.6,  services_share: 69, manufacturing_share: 13 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2022, values: { gdp_per_capita: 139, unemployment_rate: 4.5,  services_share: 54, manufacturing_share: 37 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2022, values: { gdp_per_capita: 57,  unemployment_rate: 7.3,  services_share: 72, manufacturing_share: 9  } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2022, values: { gdp_per_capita: 59,  unemployment_rate: 3.8,  services_share: 72, manufacturing_share: 8  } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2022, values: { gdp_per_capita: 57,  unemployment_rate: 8.1,  services_share: 65, manufacturing_share: 15 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2022, values: { gdp_per_capita: 51,  unemployment_rate: 13.0, services_share: 68, manufacturing_share: 11 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2022, values: { gdp_per_capita: 45,  unemployment_rate: 6.1,  services_share: 66, manufacturing_share: 12 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2022, values: { gdp_per_capita: 40,  unemployment_rate: 12.4, services_share: 68, manufacturing_share: 10 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2022, values: { gdp_per_capita: 48,  unemployment_rate: 3.0,  services_share: 80, manufacturing_share: 8  } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2022, values: { gdp_per_capita: 40,  unemployment_rate: 6.8,  services_share: 80, manufacturing_share: 5  } },
    // ── Europe de l'Est & Balkans ──────────────────────────────────────────── (World Bank 2022)
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2022, values: { gdp_per_capita: 53,  unemployment_rate: 2.2,  services_share: 60, manufacturing_share: 19 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2022, values: { gdp_per_capita: 47,  unemployment_rate: 2.8,  services_share: 57, manufacturing_share: 18 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2022, values: { gdp_per_capita: 42,  unemployment_rate: 6.1,  services_share: 61, manufacturing_share: 17 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2022, values: { gdp_per_capita: 44,  unemployment_rate: 3.6,  services_share: 58, manufacturing_share: 17 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2022, values: { gdp_per_capita: 42,  unemployment_rate: 6.8,  services_share: 60, manufacturing_share: 12 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2022, values: { gdp_per_capita: 42,  unemployment_rate: 5.6,  services_share: 60, manufacturing_share: 14 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2022, values: { gdp_per_capita: 36,  unemployment_rate: 4.1,  services_share: 60, manufacturing_share: 14 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2022, values: { gdp_per_capita: 41,  unemployment_rate: 4.0,  services_share: 62, manufacturing_share: 21 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2022, values: { gdp_per_capita: 38,  unemployment_rate: 5.6,  services_share: 66, manufacturing_share: 15 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2022, values: { gdp_per_capita: 32,  unemployment_rate: 6.9,  services_share: 67, manufacturing_share: 12 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2022, values: { gdp_per_capita: 37,  unemployment_rate: 5.9,  services_share: 64, manufacturing_share: 16 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2022, values: { gdp_per_capita: 20,  unemployment_rate: 9.8,  services_share: 55, manufacturing_share: 14 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2022, values: { gdp_per_capita: 15, unemployment_rate: 15.2, services_share: 54, manufacturing_share: 14 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2022, values: { gdp_per_capita: 16, unemployment_rate: 14.8, services_share: 56, manufacturing_share: 12 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2022, values: { gdp_per_capita: 15,  unemployment_rate: 11.6, services_share: 49, manufacturing_share: 7  } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2022, values: { gdp_per_capita: 21,  unemployment_rate: 14.7, services_share: 64, manufacturing_share: 5  } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2022, values: { gdp_per_capita: 14,  unemployment_rate: 4.6,  services_share: 59, manufacturing_share: 12 } },
    // ── Amérique du Nord ────────────────────────────────────────────────────── (World Bank 2022)
    { geoCode: 'US', geoName: 'United States',  dataYear: 2022, values: { gdp_per_capita: 78,  unemployment_rate: 3.6,  services_share: 77, manufacturing_share: 11 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2022, values: { gdp_per_capita: 64,  unemployment_rate: 5.3,  services_share: 70, manufacturing_share: 10 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2022, values: { gdp_per_capita: 23,  unemployment_rate: 3.3,  services_share: 58, manufacturing_share: 21 } },
    // ── Amérique centrale & Caraïbes ──────────────────────────────────────── (World Bank 2022)
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2022, values: { gdp_per_capita: 28,  unemployment_rate: 8.2,  services_share: 74, manufacturing_share: 6  } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2022, values: { gdp_per_capita: 21,  unemployment_rate: 11.3, services_share: 67, manufacturing_share: 14 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2022, values: { gdp_per_capita: 19, unemployment_rate: 5.3, services_share: 61, manufacturing_share: 14 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2022, values: { gdp_per_capita: 10,  unemployment_rate: 2.8,  services_share: 61, manufacturing_share: 16 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2022, values: { gdp_per_capita: 10,  unemployment_rate: 6.5,  services_share: 60, manufacturing_share: 16 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2022, values: { gdp_per_capita: 6,   unemployment_rate: 8.6,  services_share: 55, manufacturing_share: 16 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2022, values: { gdp_per_capita: 11,  unemployment_rate: 6.0,  services_share: 68, manufacturing_share: 8  } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2022, values: { gdp_per_capita: 27, unemployment_rate: 4.5, services_share: 54, manufacturing_share: 16 } },
    // ── Amérique du Sud ───────────────────────────────────────────────────── (World Bank 2022)
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2022, values: { gdp_per_capita: 20,  unemployment_rate: 9.2,  services_share: 58, manufacturing_share: 13 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2022, values: { gdp_per_capita: 30,  unemployment_rate: 6.8,  services_share: 54, manufacturing_share: 16 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2022, values: { gdp_per_capita: 31,  unemployment_rate: 8.2,  services_share: 55, manufacturing_share: 9  } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2022, values: { gdp_per_capita: 21,  unemployment_rate: 10.5, services_share: 55, manufacturing_share: 11 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2022, values: { gdp_per_capita: 14,  unemployment_rate: 7.8,  services_share: 56, manufacturing_share: 13 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2022, values: { gdp_per_capita: 12,  unemployment_rate: 3.4,  services_share: 55, manufacturing_share: 13 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2022, values: { gdp_per_capita: 24,  unemployment_rate: 7.9,  services_share: 65, manufacturing_share: 11 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2022, values: { gdp_per_capita: 13,  unemployment_rate: 6.8,  services_share: 51, manufacturing_share: 19 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2022, values: { gdp_per_capita: 9,   unemployment_rate: 4.2,  services_share: 47, manufacturing_share: 12 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2022, values: { gdp_per_capita: 7,   unemployment_rate: 6.4,  services_share: 49, manufacturing_share: 10 } },
    // ── Océanie ─────────────────────────────────────────────────────────────── (World Bank 2022)
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2022, values: { gdp_per_capita: 66,  unemployment_rate: 3.7,  services_share: 63, manufacturing_share: 5  } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2022, values: { gdp_per_capita: 54,  unemployment_rate: 3.3,  services_share: 67, manufacturing_share: 9  } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2022, values: { gdp_per_capita: 4, unemployment_rate: 2.7,  services_share: 37, manufacturing_share: 5  } },
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2022, values: { gdp_per_capita: 12,  unemployment_rate: 4.8,  services_share: 61, manufacturing_share: 10 } },
    // ── Asie de l'Est ─────────────────────────────────────────────────────── (World Bank 2022)
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2022, values: { gdp_per_capita: 143, unemployment_rate: 3.6,  services_share: 72, manufacturing_share: 20 } },
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2022, values: { gdp_per_capita: 47,  unemployment_rate: 2.6,  services_share: 70, manufacturing_share: 20 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2022, values: { gdp_per_capita: 56,  unemployment_rate: 2.9,  services_share: 58, manufacturing_share: 27 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2022, values: { gdp_per_capita: 54,  unemployment_rate: 3.7,  services_share: 60, manufacturing_share: 31 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2022, values: { gdp_per_capita: 23,  unemployment_rate: 5.0,  services_share: 55, manufacturing_share: 26 } },
    { geoCode: 'HK', geoName: 'Hong Kong',      dataYear: 2022, values: { gdp_per_capita: 62,  unemployment_rate: 3.5,  services_share: 93, manufacturing_share: 1  } },
    { geoCode: 'MO', geoName: 'Macao',          dataYear: 2022, values: { gdp_per_capita: 30,  unemployment_rate: 3.0,  services_share: 85, manufacturing_share: 2  } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2022, values: { gdp_per_capita: 13,  unemployment_rate: 6.2,  services_share: 47, manufacturing_share: 10 } },
    // ── Asie du Sud-Est ───────────────────────────────────────────────────── (World Bank 2022)
    { geoCode: 'IN', geoName: 'India',          dataYear: 2022, values: { gdp_per_capita: 9,   unemployment_rate: 4.8,  services_share: 50, manufacturing_share: 13 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2022, values: { gdp_per_capita: 14,  unemployment_rate: 3.5,  services_share: 42, manufacturing_share: 18 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2022, values: { gdp_per_capita: 22,  unemployment_rate: 0.9,  services_share: 56, manufacturing_share: 27 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2022, values: { gdp_per_capita: 14,  unemployment_rate: 1.6,  services_share: 41, manufacturing_share: 25 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2022, values: { gdp_per_capita: 10,  unemployment_rate: 2.6,  services_share: 61, manufacturing_share: 17 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2022, values: { gdp_per_capita: 32,  unemployment_rate: 3.9,  services_share: 54, manufacturing_share: 23 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2022, values: { gdp_per_capita: 5,   unemployment_rate: 0.6,  services_share: 37, manufacturing_share: 17 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2022, values: { gdp_per_capita: 5,   unemployment_rate: 2.5,  services_share: 41, manufacturing_share: 22 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2022, values: { gdp_per_capita: 8,   unemployment_rate: 1.4,  services_share: 40, manufacturing_share: 10 } },
    { geoCode: 'BN', geoName: 'Brunei',         dataYear: 2022, values: { gdp_per_capita: 64,  unemployment_rate: 5.2,  services_share: 41, manufacturing_share: 12 } },
    // ── Asie du Sud ───────────────────────────────────────────────────────── (World Bank 2022)
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2022, values: { gdp_per_capita: 6,   unemployment_rate: 5.3,  services_share: 52, manufacturing_share: 14 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2022, values: { gdp_per_capita: 8,   unemployment_rate: 4.6,  services_share: 51, manufacturing_share: 22 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2022, values: { gdp_per_capita: 13,  unemployment_rate: 7.2,  services_share: 57, manufacturing_share: 17 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2022, values: { gdp_per_capita: 4,   unemployment_rate: 4.8,  services_share: 53, manufacturing_share: 5  } },
    // ── Asie centrale ─────────────────────────────────────────────────────── (World Bank 2022)
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2022, values: { gdp_per_capita: 36,  unemployment_rate: 4.9,  services_share: 53, manufacturing_share: 13 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2022, values: { gdp_per_capita: 8,   unemployment_rate: 5.9,  services_share: 42, manufacturing_share: 18 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2022, values: { gdp_per_capita: 15,  unemployment_rate: 5.9,  services_share: 40, manufacturing_share: 7  } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2022, values: { gdp_per_capita: 16,  unemployment_rate: 17.3, services_share: 61, manufacturing_share: 9  } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2022, values: { gdp_per_capita: 15,  unemployment_rate: 14.2, services_share: 54, manufacturing_share: 10 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2022, values: { gdp_per_capita: 5,   unemployment_rate: 5.4,  services_share: 50, manufacturing_share: 14 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2022, values: { gdp_per_capita: 4,   unemployment_rate: 7.0,  services_share: 41, manufacturing_share: 13 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2022, values: { gdp_per_capita: 11,  unemployment_rate: 4.1,  services_share: 37, manufacturing_share: 20 } },
    // ── Moyen-Orient & Golfe ──────────────────────────────────────────────── (World Bank 2022)
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2022, values: { gdp_per_capita: 72,  unemployment_rate: 5.6,  services_share: 40, manufacturing_share: 15 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2022, values: { gdp_per_capita: 76, unemployment_rate: 3.0, services_share: 55, manufacturing_share: 9 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2022, values: { gdp_per_capita: 110, unemployment_rate: 0.2,  services_share: 48, manufacturing_share: 8  } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2022, values: { gdp_per_capita: 50,  unemployment_rate: 2.2,  services_share: 51, manufacturing_share: 7  } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2022, values: { gdp_per_capita: 52,  unemployment_rate: 1.6,  services_share: 61, manufacturing_share: 14 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2022, values: { gdp_per_capita: 40,  unemployment_rate: 2.4,  services_share: 50, manufacturing_share: 10 } },
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2022, values: { gdp_per_capita: 54,  unemployment_rate: 3.7,  services_share: 70, manufacturing_share: 12 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2022, values: { gdp_per_capita: 11,  unemployment_rate: 22.8, services_share: 63, manufacturing_share: 17 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2022, values: { gdp_per_capita: 11,  unemployment_rate: 11.6, services_share: 74, manufacturing_share: 6  } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2022, values: { gdp_per_capita: 10,  unemployment_rate: 15.8, services_share: 46, manufacturing_share: 3  } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2022, values: { gdp_per_capita: 40,  unemployment_rate: 10.5, services_share: 52, manufacturing_share: 22 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2022, values: { gdp_per_capita: 18,  unemployment_rate: 9.1,  services_share: 45, manufacturing_share: 22 } },
    // ── Ex-URSS (Russie, Ukraine, Biélorussie) ──────────────────────────────── (World Bank 2022)
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2022, values: { gdp_per_capita: 41,  unemployment_rate: 3.9,  services_share: 55, manufacturing_share: 13 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2022, values: { gdp_per_capita: 15,  unemployment_rate: 24.5, services_share: 62, manufacturing_share: 8  } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2022, values: { gdp_per_capita: 21,  unemployment_rate: 3.8,  services_share: 49, manufacturing_share: 22 } },
    // ── Afrique du Nord ───────────────────────────────────────────────────── (World Bank 2022)
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2022, values: { gdp_per_capita: 18,  unemployment_rate: 6.5,  services_share: 51, manufacturing_share: 16 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2022, values: { gdp_per_capita: 9,   unemployment_rate: 9.4,  services_share: 55, manufacturing_share: 16 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2022, values: { gdp_per_capita: 12,  unemployment_rate: 12.4, services_share: 44, manufacturing_share: 5  } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2022, values: { gdp_per_capita: 11,  unemployment_rate: 15.3, services_share: 61, manufacturing_share: 16 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2022, values: { gdp_per_capita: 15,  unemployment_rate: 19.0, services_share: 39, manufacturing_share: 4  } },
    // ── Afrique de l'Ouest ────────────────────────────────────────────────── (World Bank 2022)
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2022, values: { gdp_per_capita: 8,   unemployment_rate: 3.8,  services_share: 51, manufacturing_share: 9  } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2022, values: { gdp_per_capita: 6,   unemployment_rate: 13.7, services_share: 46, manufacturing_share: 10 } },
    { geoCode: 'CI', geoName: "Côte d'Ivoire",  dataYear: 2022, values: { gdp_per_capita: 6,   unemployment_rate: 3.1,  services_share: 43, manufacturing_share: 12 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2022, values: { gdp_per_capita: 4,   unemployment_rate: 6.7,  services_share: 52, manufacturing_share: 14 } },
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2022, values: { gdp_per_capita: 4,   unemployment_rate: 3.7,  services_share: 52, manufacturing_share: 11 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2022, values: { gdp_per_capita: 2,   unemployment_rate: 5.2,  services_share: 39, manufacturing_share: 7  } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2022, values: { gdp_per_capita: 2,   unemployment_rate: 7.6,  services_share: 37, manufacturing_share: 5  } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2022, values: { gdp_per_capita: 1,   unemployment_rate: 0.5,  services_share: 35, manufacturing_share: 6  } },
    { geoCode: 'GN', geoName: 'Guinea',         dataYear: 2022, values: { gdp_per_capita: 3,   unemployment_rate: 5.7,  services_share: 39, manufacturing_share: 10 } },
    // ── Afrique de l'Est ──────────────────────────────────────────────────── (World Bank 2022)
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2022, values: { gdp_per_capita: 6,   unemployment_rate: 5.6,  services_share: 55, manufacturing_share: 8  } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2022, values: { gdp_per_capita: 3,   unemployment_rate: 3.4,  services_share: 37, manufacturing_share: 4  } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2022, values: { gdp_per_capita: 3,   unemployment_rate: 9.7,  services_share: 37, manufacturing_share: 8  } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2022, values: { gdp_per_capita: 3,   unemployment_rate: 9.4,  services_share: 41, manufacturing_share: 9  } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2022, values: { gdp_per_capita: 3,   unemployment_rate: 14.5, services_share: 47, manufacturing_share: 7  } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2022, values: { gdp_per_capita: 2,   unemployment_rate: 4.9,  services_share: 47, manufacturing_share: 13 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2022, values: { gdp_per_capita: 1,   unemployment_rate: 3.6,  services_share: 43, manufacturing_share: 9  } },
    // ── Afrique australe ──────────────────────────────────────────────────── (World Bank 2022)
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2022, values: { gdp_per_capita: 15,  unemployment_rate: 33.3, services_share: 62, manufacturing_share: 12 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2022, values: { gdp_per_capita: 17,  unemployment_rate: 25.4, services_share: 55, manufacturing_share: 6  } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2022, values: { gdp_per_capita: 10,  unemployment_rate: 21.5, services_share: 52, manufacturing_share: 9  } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2022, values: { gdp_per_capita: 4,   unemployment_rate: 12.8, services_share: 53, manufacturing_share: 8  } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2022, values: { gdp_per_capita: 3,   unemployment_rate: 17.5, services_share: 51, manufacturing_share: 10 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2022, values: { gdp_per_capita: 7,   unemployment_rate: 8.8,  services_share: 32, manufacturing_share: 6  } },
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2022, values: { gdp_per_capita: 1,   unemployment_rate: 4.6,  services_share: 34, manufacturing_share: 18 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2022, values: { gdp_per_capita: 24,  unemployment_rate: 6.3,  services_share: 69, manufacturing_share: 12 } },
    // ── Golfe & péninsule arabique (complément) ───────────────────────────── (World Bank 2022)
    { geoCode: 'YE', geoName: 'Yemen',          dataYear: 2022, values: { gdp_per_capita: 2,   unemployment_rate: 13.2, services_share: 47, manufacturing_share: 6  } },
    // ── Asie (compléments) ────────────────────────────────────────────────── (World Bank 2022)
    { geoCode: 'AF', geoName: 'Afghanistan',    dataYear: 2022, values: { gdp_per_capita: 2,   unemployment_rate: 14.4, services_share: 44, manufacturing_share: 12 } },
  ],
};

export default economicSectorsModule;
