import type { DomainModule } from '@/lib/domains/types';

const fiscalModule: DomainModule = {
  definition: {
    id: 'fiscal',
    label: { fr: 'Dette & Pression fiscale', en: 'Debt & Tax Burden' },
    description: {
      fr: 'Viabilité des finances publiques : dette souveraine, pression fiscale, solde budgétaire et espace fiscal disponible.',
      en: 'Public finance sustainability: sovereign debt, tax burden, budget balance and available fiscal space.',
    },
    icon: '📊',
    group: 'economy',
    active: true,
    seedSources: [
      'https://www.imf.org/en/Publications/WEO',
      'https://www.oecd.org/tax/revenue-statistics.htm',
      'https://data.worldbank.org/indicator/GC.DOD.TOTL.GD.ZS',
    ],
    indicators: [
      {
        id: 'public_debt_gdp',
        label: { fr: 'Dette publique (% PIB)', en: 'Public debt (% GDP)' },
        unit: 'percent',
        unitLabel: { fr: '% PIB', en: '% GDP' },
        direction: 'lower_is_better',
        weight: 3,
        thresholds: { excellent: 40, good: 65, fair: 90, poor: 120 },
        minValue: 0,
        maxValue: 300,
      },
      {
        id: 'tax_burden_gdp',
        label: { fr: 'Prélèvements obligatoires (% PIB)', en: 'Tax burden (% GDP)' },
        unit: 'percent',
        unitLabel: { fr: '% PIB', en: '% GDP' },
        direction: 'lower_is_better',
        weight: 2,
        thresholds: { excellent: 25, good: 33, fair: 40, poor: 48 },
        minValue: 0,
        maxValue: 60,
      },
      {
        id: 'budget_balance_gdp',
        label: { fr: 'Solde budgétaire (% PIB)', en: 'Budget balance (% GDP)' },
        unit: 'percent',
        unitLabel: { fr: '% PIB', en: '% GDP' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 1, good: -1.5, fair: -3.5, poor: -6 },
        minValue: -20,
        maxValue: 25,
      },
      {
        id: 'fiscal_space_index',
        label: { fr: 'Espace fiscal', en: 'Fiscal space index' },
        unit: 'index',
        unitLabel: { fr: 'indice /100', en: 'index /100' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 75, good: 55, fair: 38, poor: 22 },
        minValue: 0,
        maxValue: 100,
      },
    ],
  },
  seedData: [
    // ── Europe nordique ────────────────────────────────────────────────────
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2023, values: { public_debt_gdp: 40,  tax_burden_gdp: 43, budget_balance_gdp: 18.5,  fiscal_space_index: 95 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2023, values: { public_debt_gdp: 29,  tax_burden_gdp: 47, budget_balance_gdp: 2.9,   fiscal_space_index: 88 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2023, values: { public_debt_gdp: 31,  tax_burden_gdp: 43, budget_balance_gdp: -0.6,  fiscal_space_index: 85 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2023, values: { public_debt_gdp: 16,  tax_burden_gdp: 27, budget_balance_gdp: 0.8,   fiscal_space_index: 92 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2023, values: { public_debt_gdp: 72,  tax_burden_gdp: 43, budget_balance_gdp: -2.7,  fiscal_space_index: 60 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2023, values: { public_debt_gdp: 62,  tax_burden_gdp: 36, budget_balance_gdp: -3.0,  fiscal_space_index: 62 } },
    // ── Europe de l'Ouest ──────────────────────────────────────────────────
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2023, values: { public_debt_gdp: 24,  tax_burden_gdp: 38, budget_balance_gdp: -0.5,  fiscal_space_index: 88 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2023, values: { public_debt_gdp: 48,  tax_burden_gdp: 39, budget_balance_gdp: -0.6,  fiscal_space_index: 75 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2023, values: { public_debt_gdp: 75,  tax_burden_gdp: 43, budget_balance_gdp: -2.7,  fiscal_space_index: 60 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2023, values: { public_debt_gdp: 66,  tax_burden_gdp: 40, budget_balance_gdp: -2.5,  fiscal_space_index: 68 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2023, values: { public_debt_gdp: 43,  tax_burden_gdp: 22, budget_balance_gdp: 1.7,   fiscal_space_index: 80 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2023, values: { public_debt_gdp: 110, tax_burden_gdp: 46, budget_balance_gdp: -4.9,  fiscal_space_index: 42 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2023, values: { public_debt_gdp: 105, tax_burden_gdp: 44, budget_balance_gdp: -4.4,  fiscal_space_index: 40 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2023, values: { public_debt_gdp: 99,  tax_burden_gdp: 37, budget_balance_gdp: 1.2,   fiscal_space_index: 55 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2023, values: { public_debt_gdp: 107, tax_burden_gdp: 38, budget_balance_gdp: -3.6,  fiscal_space_index: 45 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2023, values: { public_debt_gdp: 101, tax_burden_gdp: 33, budget_balance_gdp: -5.2,  fiscal_space_index: 42 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2023, values: { public_debt_gdp: 140, tax_burden_gdp: 43, budget_balance_gdp: -5.3,  fiscal_space_index: 25 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2023, values: { public_debt_gdp: 163, tax_burden_gdp: 38, budget_balance_gdp: -1.5,  fiscal_space_index: 22 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2023, values: { public_debt_gdp: 50,  tax_burden_gdp: 33, budget_balance_gdp: -4.9,  fiscal_space_index: 58 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2023, values: { public_debt_gdp: 77,  tax_burden_gdp: 35, budget_balance_gdp: 2.1,   fiscal_space_index: 62 } },
    // ── Europe de l'Est ────────────────────────────────────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2023, values: { public_debt_gdp: 44,  tax_burden_gdp: 35, budget_balance_gdp: -3.7,  fiscal_space_index: 62 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2023, values: { public_debt_gdp: 50,  tax_burden_gdp: 36, budget_balance_gdp: -5.1,  fiscal_space_index: 55 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2023, values: { public_debt_gdp: 57,  tax_burden_gdp: 35, budget_balance_gdp: -6.0,  fiscal_space_index: 48 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2023, values: { public_debt_gdp: 73,  tax_burden_gdp: 37, budget_balance_gdp: -6.7,  fiscal_space_index: 38 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2023, values: { public_debt_gdp: 70,  tax_burden_gdp: 37, budget_balance_gdp: -0.7,  fiscal_space_index: 52 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2023, values: { public_debt_gdp: 49,  tax_burden_gdp: 27, budget_balance_gdp: -5.7,  fiscal_space_index: 45 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2023, values: { public_debt_gdp: 22,  tax_burden_gdp: 30, budget_balance_gdp: -1.8,  fiscal_space_index: 72 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2023, values: { public_debt_gdp: 69,  tax_burden_gdp: 37, budget_balance_gdp: -2.5,  fiscal_space_index: 55 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2023, values: { public_debt_gdp: 38,  tax_burden_gdp: 31, budget_balance_gdp: -1.0,  fiscal_space_index: 68 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2023, values: { public_debt_gdp: 44,  tax_burden_gdp: 31, budget_balance_gdp: -2.2,  fiscal_space_index: 62 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2023, values: { public_debt_gdp: 19,  tax_burden_gdp: 33, budget_balance_gdp: -3.4,  fiscal_space_index: 72 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2023, values: { public_debt_gdp: 52,  tax_burden_gdp: 36, budget_balance_gdp: -2.2,  fiscal_space_index: 52 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2023, values: { public_debt_gdp: 31, tax_burden_gdp: 34, budget_balance_gdp: -0.8, fiscal_space_index: 55 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2023, values: { public_debt_gdp: 60,  tax_burden_gdp: 36, budget_balance_gdp: -2.8,  fiscal_space_index: 48 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2023, values: { public_debt_gdp: 42, tax_burden_gdp: 28, budget_balance_gdp: -4.5,  fiscal_space_index: 48 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2023, values: { public_debt_gdp: 62,  tax_burden_gdp: 25, budget_balance_gdp: -2.0,  fiscal_space_index: 45 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2023, values: { public_debt_gdp: 33,  tax_burden_gdp: 26, budget_balance_gdp: -5.0,  fiscal_space_index: 42 } },
    { geoCode: 'XK', geoName: 'Kosovo',         dataYear: 2023, values: { public_debt_gdp: 21,  tax_burden_gdp: 26, budget_balance_gdp: -1.5,  fiscal_space_index: 58 } },
    // ── Amérique du Nord ──────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',  dataYear: 2023, values: { public_debt_gdp: 123, tax_burden_gdp: 27, budget_balance_gdp: -8.8,  fiscal_space_index: 38 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2023, values: { public_debt_gdp: 107, tax_burden_gdp: 33, budget_balance_gdp: -1.6,  fiscal_space_index: 50 } },
    // ── Océanie ───────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2023, values: { public_debt_gdp: 50,  tax_burden_gdp: 29, budget_balance_gdp: 0.2,   fiscal_space_index: 72 } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2023, values: { public_debt_gdp: 46,  tax_burden_gdp: 32, budget_balance_gdp: -2.9,  fiscal_space_index: 68 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2023, values: { public_debt_gdp: 46, tax_burden_gdp: 13, budget_balance_gdp: -4.8, fiscal_space_index: 32 } },
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2023, values: { public_debt_gdp: 80,  tax_burden_gdp: 22, budget_balance_gdp: -6.2,  fiscal_space_index: 28 } },
    // ── Asie de l'Est ───────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2023, values: { public_debt_gdp: 252, tax_burden_gdp: 31, budget_balance_gdp: -3.9,  fiscal_space_index: 20 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2023, values: { public_debt_gdp: 54,  tax_burden_gdp: 28, budget_balance_gdp: -2.3,  fiscal_space_index: 65 } },
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2023, values: { public_debt_gdp: 131, tax_burden_gdp: 14, budget_balance_gdp: 0.5,   fiscal_space_index: 85 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2023, values: { public_debt_gdp: 83,  tax_burden_gdp: 20, budget_balance_gdp: -5.8,  fiscal_space_index: 42 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2023, values: { public_debt_gdp: 28,  tax_burden_gdp: 13, budget_balance_gdp: -1.0,  fiscal_space_index: 82 } },
    { geoCode: 'HK', geoName: 'Hong Kong',      dataYear: 2023, values: { public_debt_gdp: 4,   tax_burden_gdp: 12, budget_balance_gdp: -5.8,  fiscal_space_index: 85 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2023, values: { public_debt_gdp: 48,  tax_burden_gdp: 23, budget_balance_gdp: -2.5,  fiscal_space_index: 48 } },
    // ── Asie du Sud-Est ─────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2023, values: { public_debt_gdp: 83,  tax_burden_gdp: 18, budget_balance_gdp: -5.9,  fiscal_space_index: 35 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2023, values: { public_debt_gdp: 38,  tax_burden_gdp: 11, budget_balance_gdp: -2.3,  fiscal_space_index: 60 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2023, values: { public_debt_gdp: 62,  tax_burden_gdp: 14, budget_balance_gdp: -3.5,  fiscal_space_index: 55 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2023, values: { public_debt_gdp: 37,  tax_burden_gdp: 19, budget_balance_gdp: -3.0,  fiscal_space_index: 62 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2023, values: { public_debt_gdp: 60,  tax_burden_gdp: 16, budget_balance_gdp: -6.2,  fiscal_space_index: 42 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2023, values: { public_debt_gdp: 64,  tax_burden_gdp: 13, budget_balance_gdp: -5.0,  fiscal_space_index: 50 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2023, values: { public_debt_gdp: 39,  tax_burden_gdp: 8,  budget_balance_gdp: -5.3,  fiscal_space_index: 38 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2023, values: { public_debt_gdp: 75,  tax_burden_gdp: 11, budget_balance_gdp: -7.7,  fiscal_space_index: 18 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2023, values: { public_debt_gdp: 115, tax_burden_gdp: 8,  budget_balance_gdp: -8.3,  fiscal_space_index: 10 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2023, values: { public_debt_gdp: 43,  tax_burden_gdp: 19, budget_balance_gdp: -4.5,  fiscal_space_index: 40 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2023, values: { public_debt_gdp: 60,  tax_burden_gdp: 7,  budget_balance_gdp: -6.5,  fiscal_space_index: 20 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2023, values: { public_debt_gdp: 35,  tax_burden_gdp: 18, budget_balance_gdp: -5.0,  fiscal_space_index: 48 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2023, values: { public_debt_gdp: 122, tax_burden_gdp: 12, budget_balance_gdp: -5.5,  fiscal_space_index: 15 } },
    // ── Asie centrale / Caucase ───────────────────────────────────────────
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2023, values: { public_debt_gdp: 35,  tax_burden_gdp: 21, budget_balance_gdp: -4.0,  fiscal_space_index: 52 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2023, values: { public_debt_gdp: 39,  tax_burden_gdp: 25, budget_balance_gdp: -2.5,  fiscal_space_index: 58 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2023, values: { public_debt_gdp: 49,  tax_burden_gdp: 24, budget_balance_gdp: -2.0,  fiscal_space_index: 52 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2023, values: { public_debt_gdp: 20,  tax_burden_gdp: 14, budget_balance_gdp: 3.5,   fiscal_space_index: 72 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2023, values: { public_debt_gdp: 52,  tax_burden_gdp: 22, budget_balance_gdp: -3.8,  fiscal_space_index: 38 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2023, values: { public_debt_gdp: 40,  tax_burden_gdp: 20, budget_balance_gdp: -2.5,  fiscal_space_index: 40 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2023, values: { public_debt_gdp: 8,   tax_burden_gdp: 15, budget_balance_gdp: 0.5,   fiscal_space_index: 65 } },
    // ── Moyen-Orient / Golfe ──────────────────────────────────────────────
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2023, values: { public_debt_gdp: 26,  tax_burden_gdp: 8,  budget_balance_gdp: -1.9,  fiscal_space_index: 80 } },
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2023, values: { public_debt_gdp: 62,  tax_burden_gdp: 34, budget_balance_gdp: -4.1,  fiscal_space_index: 55 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2023, values: { public_debt_gdp: 31,  tax_burden_gdp: 24, budget_balance_gdp: -5.2,  fiscal_space_index: 48 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2023, values: { public_debt_gdp: 30, tax_burden_gdp: 6, budget_balance_gdp: 5.8,  fiscal_space_index: 90 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2023, values: { public_debt_gdp: 42,  tax_burden_gdp: 5,  budget_balance_gdp: 6.3,   fiscal_space_index: 88 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2023, values: { public_debt_gdp: 3,   tax_burden_gdp: 2,  budget_balance_gdp: 11.2,  fiscal_space_index: 95 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2023, values: { public_debt_gdp: 123, tax_burden_gdp: 5,  budget_balance_gdp: -3.2,  fiscal_space_index: 38 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2023, values: { public_debt_gdp: 37,  tax_burden_gdp: 9,  budget_balance_gdp: 2.0,   fiscal_space_index: 72 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2023, values: { public_debt_gdp: 90,  tax_burden_gdp: 18, budget_balance_gdp: -5.5,  fiscal_space_index: 25 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2023, values: { public_debt_gdp: 280, tax_burden_gdp: 6,  budget_balance_gdp: -2.5,  fiscal_space_index: 5  } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2023, values: { public_debt_gdp: 44,  tax_burden_gdp: 10, budget_balance_gdp: -1.8,  fiscal_space_index: 45 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2023, values: { public_debt_gdp: 32,  tax_burden_gdp: 7,  budget_balance_gdp: -4.0,  fiscal_space_index: 42 } },
    // ── Ex-URSS (Europe) ──────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2023, values: { public_debt_gdp: 19,  tax_burden_gdp: 31, budget_balance_gdp: -2.3,  fiscal_space_index: 72 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2023, values: { public_debt_gdp: 88,  tax_burden_gdp: 28, budget_balance_gdp: -16.4, fiscal_space_index: 10 } },
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2023, values: { public_debt_gdp: 24,  tax_burden_gdp: 22, budget_balance_gdp: -2.0,  fiscal_space_index: 70 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2023, values: { public_debt_gdp: 35,  tax_burden_gdp: 30, budget_balance_gdp: -1.5,  fiscal_space_index: 48 } },
    // ── Amérique Latine ────────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2023, values: { public_debt_gdp: 88,  tax_burden_gdp: 33, budget_balance_gdp: -8.9,  fiscal_space_index: 28 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2023, values: { public_debt_gdp: 54,  tax_burden_gdp: 17, budget_balance_gdp: -3.2,  fiscal_space_index: 52 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2023, values: { public_debt_gdp: 88,  tax_burden_gdp: 29, budget_balance_gdp: -4.1,  fiscal_space_index: 15 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2023, values: { public_debt_gdp: 38,  tax_burden_gdp: 22, budget_balance_gdp: -2.4,  fiscal_space_index: 68 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2023, values: { public_debt_gdp: 54,  tax_burden_gdp: 20, budget_balance_gdp: -4.3,  fiscal_space_index: 45 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2023, values: { public_debt_gdp: 33,  tax_burden_gdp: 17, budget_balance_gdp: -2.8,  fiscal_space_index: 60 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2023, values: { public_debt_gdp: 57,  tax_burden_gdp: 14, budget_balance_gdp: -2.0,  fiscal_space_index: 38 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2023, values: { public_debt_gdp: 60,  tax_burden_gdp: 29, budget_balance_gdp: -3.5,  fiscal_space_index: 50 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2023, values: { public_debt_gdp: 33,  tax_burden_gdp: 14, budget_balance_gdp: -3.2,  fiscal_space_index: 55 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2023, values: { public_debt_gdp: 80,  tax_burden_gdp: 20, budget_balance_gdp: -7.8,  fiscal_space_index: 20 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2023, values: { public_debt_gdp: 160, tax_burden_gdp: 8,  budget_balance_gdp: -5.0,  fiscal_space_index: 5  } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2023, values: { public_debt_gdp: 63,  tax_burden_gdp: 24, budget_balance_gdp: -3.0,  fiscal_space_index: 48 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2023, values: { public_debt_gdp: 55,  tax_burden_gdp: 15, budget_balance_gdp: -3.0,  fiscal_space_index: 48 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2023, values: { public_debt_gdp: 44, tax_burden_gdp: 14, budget_balance_gdp: -3.5, fiscal_space_index: 48 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2023, values: { public_debt_gdp: 29,  tax_burden_gdp: 12, budget_balance_gdp: -1.7,  fiscal_space_index: 55 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2023, values: { public_debt_gdp: 47,  tax_burden_gdp: 16, budget_balance_gdp: -3.2,  fiscal_space_index: 38 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2023, values: { public_debt_gdp: 77,  tax_burden_gdp: 18, budget_balance_gdp: -2.8,  fiscal_space_index: 30 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2023, values: { public_debt_gdp: 50,  tax_burden_gdp: 19, budget_balance_gdp: -1.5,  fiscal_space_index: 42 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2023, values: { public_debt_gdp: 82,  tax_burden_gdp: 27, budget_balance_gdp: 0.5,   fiscal_space_index: 35 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2023, values: { public_debt_gdp: 52, tax_burden_gdp: 20, budget_balance_gdp: 2.5, fiscal_space_index: 58 } },
    // ── Afrique du Nord ───────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2023, values: { public_debt_gdp: 95,  tax_burden_gdp: 16, budget_balance_gdp: -7.5,  fiscal_space_index: 22 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2023, values: { public_debt_gdp: 68,  tax_burden_gdp: 22, budget_balance_gdp: -4.4,  fiscal_space_index: 38 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2023, values: { public_debt_gdp: 80,  tax_burden_gdp: 25, budget_balance_gdp: -6.5,  fiscal_space_index: 22 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2023, values: { public_debt_gdp: 48,  tax_burden_gdp: 22, budget_balance_gdp: -4.5,  fiscal_space_index: 42 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2023, values: { public_debt_gdp: 6,   tax_burden_gdp: 5,  budget_balance_gdp: 8.0,   fiscal_space_index: 60 } },
    // ── Afrique subsaharienne ─────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2023, values: { public_debt_gdp: 74,  tax_burden_gdp: 28, budget_balance_gdp: -4.5,  fiscal_space_index: 38 } },
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2023, values: { public_debt_gdp: 42,  tax_burden_gdp: 7,  budget_balance_gdp: -4.8,  fiscal_space_index: 30 } },
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2023, values: { public_debt_gdp: 72,  tax_burden_gdp: 16, budget_balance_gdp: -5.6,  fiscal_space_index: 25 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2023, values: { public_debt_gdp: 85,  tax_burden_gdp: 13, budget_balance_gdp: -5.1,  fiscal_space_index: 18 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2023, values: { public_debt_gdp: 57,  tax_burden_gdp: 13, budget_balance_gdp: -5.2,  fiscal_space_index: 32 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2023, values: { public_debt_gdp: 73,  tax_burden_gdp: 18, budget_balance_gdp: -5.5,  fiscal_space_index: 28 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2023, values: { public_debt_gdp: 40,  tax_burden_gdp: 8,  budget_balance_gdp: -3.8,  fiscal_space_index: 30 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2023, values: { public_debt_gdp: 42,  tax_burden_gdp: 12, budget_balance_gdp: -3.5,  fiscal_space_index: 38 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2023, values: { public_debt_gdp: 48,  tax_burden_gdp: 13, budget_balance_gdp: -5.0,  fiscal_space_index: 32 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2023, values: { public_debt_gdp: 65,  tax_burden_gdp: 16, budget_balance_gdp: -6.8,  fiscal_space_index: 30 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2023, values: { public_debt_gdp: 100, tax_burden_gdp: 20, budget_balance_gdp: -3.5,  fiscal_space_index: 15 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2023, values: { public_debt_gdp: 65,  tax_burden_gdp: 9,  budget_balance_gdp: 0.8,   fiscal_space_index: 35 } },
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2023, values: { public_debt_gdp: 45,  tax_burden_gdp: 12, budget_balance_gdp: -1.8,  fiscal_space_index: 40 } },
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2023, values: { public_debt_gdp: 22,  tax_burden_gdp: 8,  budget_balance_gdp: -2.2,  fiscal_space_index: 38 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2023, values: { public_debt_gdp: 52,  tax_burden_gdp: 10, budget_balance_gdp: -3.2,  fiscal_space_index: 28 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2023, values: { public_debt_gdp: 95,  tax_burden_gdp: 16, budget_balance_gdp: -6.5,  fiscal_space_index: 12 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2023, values: { public_debt_gdp: 19,  tax_burden_gdp: 22, budget_balance_gdp: -0.5,  fiscal_space_index: 72 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2023, values: { public_debt_gdp: 78,  tax_burden_gdp: 20, budget_balance_gdp: -3.8,  fiscal_space_index: 38 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2023, values: { public_debt_gdp: 68,  tax_burden_gdp: 28, budget_balance_gdp: -4.5,  fiscal_space_index: 32 } },
    { geoCode: 'SD', geoName: 'Sudan',          dataYear: 2023, values: { public_debt_gdp: 180, tax_burden_gdp: 5,  budget_balance_gdp: -5.0,  fiscal_space_index: 5  } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2023, values: { public_debt_gdp: 52,  tax_burden_gdp: 15, budget_balance_gdp: -4.8,  fiscal_space_index: 28 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2023, values: { public_debt_gdp: 55,  tax_burden_gdp: 15, budget_balance_gdp: -7.5,  fiscal_space_index: 22 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2023, values: { public_debt_gdp: 50,  tax_burden_gdp: 11, budget_balance_gdp: -6.0,  fiscal_space_index: 25 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2023, values: { public_debt_gdp: 52,  tax_burden_gdp: 14, budget_balance_gdp: 1.5,   fiscal_space_index: 48 } },
    { geoCode: 'MW', geoName: 'Malawi',         dataYear: 2023, values: { public_debt_gdp: 75,  tax_burden_gdp: 14, budget_balance_gdp: -8.5,  fiscal_space_index: 12 } },
  ],
  seedDataPrev: [
    // ── Europe nordique ──────────────────────────── (debt: WB/IMF 2022, tax: OECD Rev Stats 2022, balance: IMF WEO 2022, fiscal_space: composite approx.)
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2022, values: { public_debt_gdp: 43,  tax_burden_gdp: 42.2, budget_balance_gdp: 25.7,  fiscal_space_index: 95 } },
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2022, values: { public_debt_gdp: 30,  tax_burden_gdp: 41.9, budget_balance_gdp: 3.3,   fiscal_space_index: 88 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2022, values: { public_debt_gdp: 33,  tax_burden_gdp: 42.6, budget_balance_gdp: 1.1,   fiscal_space_index: 85 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2022, values: { public_debt_gdp: 17.6, tax_burden_gdp: 27.6, budget_balance_gdp: 1.3,   fiscal_space_index: 93 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2022, values: { public_debt_gdp: 73,  tax_burden_gdp: 42.7, budget_balance_gdp: -0.8,  fiscal_space_index: 62 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2022, values: { public_debt_gdp: 85.1, tax_burden_gdp: 36.1, budget_balance_gdp: -1.3,  fiscal_space_index: 58 } },
    // ── Europe de l'Ouest ──────────────────────────────────────────────────
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2022, values: { public_debt_gdp: 25,  tax_burden_gdp: 38.7, budget_balance_gdp: 0.3,   fiscal_space_index: 88 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2022, values: { public_debt_gdp: 50,  tax_burden_gdp: 39.3, budget_balance_gdp: 0.0,   fiscal_space_index: 75 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2022, values: { public_debt_gdp: 78,  tax_burden_gdp: 43.1, budget_balance_gdp: -3.3,  fiscal_space_index: 55 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2022, values: { public_debt_gdp: 66,  tax_burden_gdp: 39.3, budget_balance_gdp: -2.5,  fiscal_space_index: 65 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2022, values: { public_debt_gdp: 44,  tax_burden_gdp: 21.7, budget_balance_gdp: 1.6,   fiscal_space_index: 80 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2022, values: { public_debt_gdp: 111, tax_burden_gdp: 46.1, budget_balance_gdp: -4.8,  fiscal_space_index: 38 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2022, values: { public_debt_gdp: 105, tax_burden_gdp: 43.6, budget_balance_gdp: -3.5,  fiscal_space_index: 40 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2022, values: { public_debt_gdp: 113, tax_burden_gdp: 36.4, budget_balance_gdp: -0.3,  fiscal_space_index: 48 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2022, values: { public_debt_gdp: 109, tax_burden_gdp: 37.5, budget_balance_gdp: -4.7,  fiscal_space_index: 40 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2022, values: { public_debt_gdp: 101, tax_burden_gdp: 34.3, budget_balance_gdp: -5.5,  fiscal_space_index: 40 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2022, values: { public_debt_gdp: 141, tax_burden_gdp: 42.9, budget_balance_gdp: -8.0,  fiscal_space_index: 22 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2022, values: { public_debt_gdp: 172, tax_burden_gdp: 39.3, budget_balance_gdp: -2.3,  fiscal_space_index: 20 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2022, values: { public_debt_gdp: 53,  tax_burden_gdp: 32.6, budget_balance_gdp: -5.8,  fiscal_space_index: 55 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2022, values: { public_debt_gdp: 86,  tax_burden_gdp: 35.2, budget_balance_gdp: 2.1,   fiscal_space_index: 58 } },
    // ── Europe de l'Est ────────────────────────────────────────────────────
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2022, values: { public_debt_gdp: 44,  tax_burden_gdp: 34.7, budget_balance_gdp: -3.2,  fiscal_space_index: 62 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2022, values: { public_debt_gdp: 49,  tax_burden_gdp: 36.2, budget_balance_gdp: -3.7,  fiscal_space_index: 55 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2022, values: { public_debt_gdp: 57,  tax_burden_gdp: 34.5, budget_balance_gdp: -2.0,  fiscal_space_index: 50 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2022, values: { public_debt_gdp: 75.5, tax_burden_gdp: 36.1, budget_balance_gdp: -6.2,  fiscal_space_index: 36 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2022, values: { public_debt_gdp: 68,  tax_burden_gdp: 37.3, budget_balance_gdp: 0.1,   fiscal_space_index: 52 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2022, values: { public_debt_gdp: 47,  tax_burden_gdp: 27.0, budget_balance_gdp: -6.2,  fiscal_space_index: 42 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2022, values: { public_debt_gdp: 22,  tax_burden_gdp: 30.5, budget_balance_gdp: -2.8,  fiscal_space_index: 72 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2022, values: { public_debt_gdp: 72,  tax_burden_gdp: 36.8, budget_balance_gdp: -3.0,  fiscal_space_index: 52 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2022, values: { public_debt_gdp: 38,  tax_burden_gdp: 30.5, budget_balance_gdp: -0.7,  fiscal_space_index: 68 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2022, values: { public_debt_gdp: 42,  tax_burden_gdp: 31.0, budget_balance_gdp: -4.6,  fiscal_space_index: 58 } },
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2022, values: { public_debt_gdp: 18,  tax_burden_gdp: 33.3, budget_balance_gdp: -0.9,  fiscal_space_index: 75 } },
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2022, values: { public_debt_gdp: 55,  tax_burden_gdp: 36.2, budget_balance_gdp: -3.2,  fiscal_space_index: 48 } },
    { geoCode: 'BA', geoName: 'Bosnia and Herzegovina', dataYear: 2022, values: { public_debt_gdp: 30, tax_burden_gdp: 34.0, budget_balance_gdp: -0.5, fiscal_space_index: 55 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2022, values: { public_debt_gdp: 68,  tax_burden_gdp: 35.5, budget_balance_gdp: -4.8,  fiscal_space_index: 42 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2022, values: { public_debt_gdp: 40, tax_burden_gdp: 27.5, budget_balance_gdp: -4.2,  fiscal_space_index: 48 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2022, values: { public_debt_gdp: 64,  tax_burden_gdp: 25.0, budget_balance_gdp: -3.5,  fiscal_space_index: 42 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2022, values: { public_debt_gdp: 34,  tax_burden_gdp: 26.0, budget_balance_gdp: -3.5,  fiscal_space_index: 42 } },
    { geoCode: 'XK', geoName: 'Kosovo',         dataYear: 2022, values: { public_debt_gdp: 20,  tax_burden_gdp: 25.5, budget_balance_gdp: -0.5,  fiscal_space_index: 60 } },
    // ── Amérique du Nord ──────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',  dataYear: 2022, values: { public_debt_gdp: 121, tax_burden_gdp: 27.6, budget_balance_gdp: -4.1,  fiscal_space_index: 40 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2022, values: { public_debt_gdp: 107, tax_burden_gdp: 33.2, budget_balance_gdp: -0.8,  fiscal_space_index: 52 } },
    // ── Océanie ───────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2022, values: { public_debt_gdp: 57.9, tax_burden_gdp: 29.5, budget_balance_gdp: -1.4,  fiscal_space_index: 68 } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2022, values: { public_debt_gdp: 54,  tax_burden_gdp: 33.8, budget_balance_gdp: -4.0,  fiscal_space_index: 60 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2022, values: { public_debt_gdp: 44, tax_burden_gdp: 12.8, budget_balance_gdp: -3.8, fiscal_space_index: 32 } },
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2022, values: { public_debt_gdp: 84,  tax_burden_gdp: 22.0, budget_balance_gdp: -10.2, fiscal_space_index: 22 } },
    // ── Asie de l'Est ───────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2022, values: { public_debt_gdp: 260, tax_burden_gdp: 34.0, budget_balance_gdp: -6.9,  fiscal_space_index: 18 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2022, values: { public_debt_gdp: 47.6, tax_burden_gdp: 30.3, budget_balance_gdp: -0.8,  fiscal_space_index: 68 } },
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2022, values: { public_debt_gdp: 154, tax_burden_gdp: 13.8, budget_balance_gdp: 2.8,   fiscal_space_index: 85 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2022, values: { public_debt_gdp: 77,  tax_burden_gdp: 21.4, budget_balance_gdp: -7.5,  fiscal_space_index: 38 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2022, values: { public_debt_gdp: 28,  tax_burden_gdp: 12.8, budget_balance_gdp: -0.8,  fiscal_space_index: 82 } },
    { geoCode: 'HK', geoName: 'Hong Kong',      dataYear: 2022, values: { public_debt_gdp: 3,   tax_burden_gdp: 11.5, budget_balance_gdp: -6.0,  fiscal_space_index: 85 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2022, values: { public_debt_gdp: 50,  tax_burden_gdp: 22.5, budget_balance_gdp: 1.2,   fiscal_space_index: 50 } },
    // ── Asie du Sud-Est ─────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2022, values: { public_debt_gdp: 83,  tax_burden_gdp: 17.4, budget_balance_gdp: -9.2,  fiscal_space_index: 30 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2022, values: { public_debt_gdp: 40,  tax_burden_gdp: 11.6, budget_balance_gdp: -2.4,  fiscal_space_index: 60 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2022, values: { public_debt_gdp: 60.3, tax_burden_gdp: 15.6, budget_balance_gdp: -3.6,  fiscal_space_index: 55 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2022, values: { public_debt_gdp: 37,  tax_burden_gdp: 18.7, budget_balance_gdp: -0.6,  fiscal_space_index: 65 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2022, values: { public_debt_gdp: 61,  tax_burden_gdp: 16.1, budget_balance_gdp: -7.3,  fiscal_space_index: 38 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2022, values: { public_debt_gdp: 60,  tax_burden_gdp: 12.5, budget_balance_gdp: -5.6,  fiscal_space_index: 48 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2022, values: { public_debt_gdp: 35,  tax_burden_gdp: 7.8,  budget_balance_gdp: -4.8,  fiscal_space_index: 40 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2022, values: { public_debt_gdp: 72,  tax_burden_gdp: 10.5, budget_balance_gdp: -7.9,  fiscal_space_index: 18 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2022, values: { public_debt_gdp: 128, tax_burden_gdp: 7.5,  budget_balance_gdp: -10.2, fiscal_space_index: 5  } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2022, values: { public_debt_gdp: 42,  tax_burden_gdp: 19.0, budget_balance_gdp: -5.4,  fiscal_space_index: 38 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2022, values: { public_debt_gdp: 55,  tax_burden_gdp: 6.5,  budget_balance_gdp: -6.0,  fiscal_space_index: 22 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2022, values: { public_debt_gdp: 34,  tax_burden_gdp: 17.5, budget_balance_gdp: -4.5,  fiscal_space_index: 48 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2022, values: { public_debt_gdp: 118, tax_burden_gdp: 12.0, budget_balance_gdp: -4.0,  fiscal_space_index: 15 } },
    // ── Asie centrale / Caucase ───────────────────────────────────────────
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2022, values: { public_debt_gdp: 34,  tax_burden_gdp: 20.5, budget_balance_gdp: -4.2,  fiscal_space_index: 50 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2022, values: { public_debt_gdp: 40,  tax_burden_gdp: 25.2, budget_balance_gdp: -2.8,  fiscal_space_index: 55 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2022, values: { public_debt_gdp: 49,  tax_burden_gdp: 23.5, budget_balance_gdp: -2.2,  fiscal_space_index: 52 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2022, values: { public_debt_gdp: 18,  tax_burden_gdp: 14.0, budget_balance_gdp: 8.5,   fiscal_space_index: 78 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2022, values: { public_debt_gdp: 50,  tax_burden_gdp: 21.5, budget_balance_gdp: -0.5,  fiscal_space_index: 42 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2022, values: { public_debt_gdp: 40,  tax_burden_gdp: 19.5, budget_balance_gdp: -2.8,  fiscal_space_index: 40 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2022, values: { public_debt_gdp: 8,   tax_burden_gdp: 15.0, budget_balance_gdp: 1.2,   fiscal_space_index: 65 } },
    // ── Moyen-Orient / Golfe ──────────────────────────────────────────────
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2022, values: { public_debt_gdp: 24,  tax_burden_gdp: 7.5,  budget_balance_gdp: 2.5,   fiscal_space_index: 82 } },
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2022, values: { public_debt_gdp: 61,  tax_burden_gdp: 33.6, budget_balance_gdp: -0.6,  fiscal_space_index: 60 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2022, values: { public_debt_gdp: 35.3, tax_burden_gdp: 23.6, budget_balance_gdp: -0.8,  fiscal_space_index: 55 } },
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2022, values: { public_debt_gdp: 28, tax_burden_gdp: 5.5, budget_balance_gdp: 10.2, fiscal_space_index: 92 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2022, values: { public_debt_gdp: 40,  tax_burden_gdp: 5.0,  budget_balance_gdp: 14.5,  fiscal_space_index: 90 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2022, values: { public_debt_gdp: 3,   tax_burden_gdp: 1.5,  budget_balance_gdp: 19.3,  fiscal_space_index: 96 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2022, values: { public_debt_gdp: 120, tax_burden_gdp: 4.8,  budget_balance_gdp: -2.0,  fiscal_space_index: 40 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2022, values: { public_debt_gdp: 40,  tax_burden_gdp: 8.5,  budget_balance_gdp: 4.5,   fiscal_space_index: 68 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2022, values: { public_debt_gdp: 92,  tax_burden_gdp: 17.5, budget_balance_gdp: -5.8,  fiscal_space_index: 22 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2022, values: { public_debt_gdp: 283, tax_burden_gdp: 6.0,  budget_balance_gdp: -4.0,  fiscal_space_index: 5  } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2022, values: { public_debt_gdp: 46,  tax_burden_gdp: 10.0, budget_balance_gdp: 6.2,   fiscal_space_index: 48 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2022, values: { public_debt_gdp: 33,  tax_burden_gdp: 6.8,  budget_balance_gdp: -3.5,  fiscal_space_index: 42 } },
    // ── Ex-URSS (Europe) ──────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2022, values: { public_debt_gdp: 19.3, tax_burden_gdp: 33.8, budget_balance_gdp: -1.4,  fiscal_space_index: 72 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2022, values: { public_debt_gdp: 78,  tax_burden_gdp: 27.5, budget_balance_gdp: -16.6, fiscal_space_index: 8  } },
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2022, values: { public_debt_gdp: 21.4, tax_burden_gdp: 15.0, budget_balance_gdp: -1.6,  fiscal_space_index: 70 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2022, values: { public_debt_gdp: 38,  tax_burden_gdp: 30.0, budget_balance_gdp: -1.0,  fiscal_space_index: 48 } },
    // ── Amérique Latine ────────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2022, values: { public_debt_gdp: 79.1, tax_burden_gdp: 33.7, budget_balance_gdp: -4.6,  fiscal_space_index: 30 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2022, values: { public_debt_gdp: 44,  tax_burden_gdp: 17.7, budget_balance_gdp: -3.8,  fiscal_space_index: 52 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2022, values: { public_debt_gdp: 85,  tax_burden_gdp: 29.2, budget_balance_gdp: -4.4,  fiscal_space_index: 15 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2022, values: { public_debt_gdp: 38,  tax_burden_gdp: 22.4, budget_balance_gdp: 1.1,   fiscal_space_index: 70 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2022, values: { public_debt_gdp: 70.3, tax_burden_gdp: 19.7, budget_balance_gdp: -5.3,  fiscal_space_index: 40 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2022, values: { public_debt_gdp: 34,  tax_burden_gdp: 16.8, budget_balance_gdp: -1.6,  fiscal_space_index: 62 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2022, values: { public_debt_gdp: 57,  tax_burden_gdp: 14.0, budget_balance_gdp: -1.5,  fiscal_space_index: 38 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2022, values: { public_debt_gdp: 58,  tax_burden_gdp: 28.5, budget_balance_gdp: -3.0,  fiscal_space_index: 52 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2022, values: { public_debt_gdp: 34,  tax_burden_gdp: 13.5, budget_balance_gdp: -3.5,  fiscal_space_index: 52 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2022, values: { public_debt_gdp: 78,  tax_burden_gdp: 20.0, budget_balance_gdp: -7.0,  fiscal_space_index: 22 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2022, values: { public_debt_gdp: 185, tax_burden_gdp: 7.5,  budget_balance_gdp: -3.5,  fiscal_space_index: 5  } },
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2022, values: { public_debt_gdp: 65,  tax_burden_gdp: 23.5, budget_balance_gdp: -3.2,  fiscal_space_index: 45 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2022, values: { public_debt_gdp: 57,  tax_burden_gdp: 14.5, budget_balance_gdp: -3.8,  fiscal_space_index: 45 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2022, values: { public_debt_gdp: 44, tax_burden_gdp: 14.2, budget_balance_gdp: -3.2, fiscal_space_index: 48 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2022, values: { public_debt_gdp: 29,  tax_burden_gdp: 12.2, budget_balance_gdp: -1.6,  fiscal_space_index: 55 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2022, values: { public_debt_gdp: 48,  tax_burden_gdp: 16.0, budget_balance_gdp: -3.8,  fiscal_space_index: 35 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2022, values: { public_debt_gdp: 77,  tax_burden_gdp: 18.0, budget_balance_gdp: -3.0,  fiscal_space_index: 28 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2022, values: { public_debt_gdp: 48,  tax_burden_gdp: 18.5, budget_balance_gdp: -0.8,  fiscal_space_index: 42 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2022, values: { public_debt_gdp: 88,  tax_burden_gdp: 27.0, budget_balance_gdp: -0.2,  fiscal_space_index: 32 } },
    { geoCode: 'TT', geoName: 'Trinidad and Tobago', dataYear: 2022, values: { public_debt_gdp: 52, tax_burden_gdp: 20.0, budget_balance_gdp: 4.5, fiscal_space_index: 60 } },
    // ── Afrique du Nord ───────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2022, values: { public_debt_gdp: 87,  tax_burden_gdp: 14.5, budget_balance_gdp: -6.0,  fiscal_space_index: 22 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2022, values: { public_debt_gdp: 71,  tax_burden_gdp: 22.5, budget_balance_gdp: -5.4,  fiscal_space_index: 35 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2022, values: { public_debt_gdp: 80,  tax_burden_gdp: 24.5, budget_balance_gdp: -7.2,  fiscal_space_index: 20 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2022, values: { public_debt_gdp: 52,  tax_burden_gdp: 21.0, budget_balance_gdp: -3.8,  fiscal_space_index: 40 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2022, values: { public_debt_gdp: 6,   tax_burden_gdp: 5.0,  budget_balance_gdp: 10.0,  fiscal_space_index: 62 } },
    // ── Afrique subsaharienne ─────────────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2022, values: { public_debt_gdp: 76.2, tax_burden_gdp: 27.0, budget_balance_gdp: -4.3,  fiscal_space_index: 35 } },
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2022, values: { public_debt_gdp: 38,  tax_burden_gdp: 7.3,  budget_balance_gdp: -4.5,  fiscal_space_index: 30 } },
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2022, values: { public_debt_gdp: 68,  tax_burden_gdp: 15.5, budget_balance_gdp: -6.2,  fiscal_space_index: 22 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2022, values: { public_debt_gdp: 90,  tax_burden_gdp: 12.0, budget_balance_gdp: -7.5,  fiscal_space_index: 12 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2022, values: { public_debt_gdp: 53,  tax_burden_gdp: 12.5, budget_balance_gdp: -6.5,  fiscal_space_index: 30 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2022, values: { public_debt_gdp: 68,  tax_burden_gdp: 17.5, budget_balance_gdp: -6.0,  fiscal_space_index: 25 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2022, values: { public_debt_gdp: 38,  tax_burden_gdp: 7.5,  budget_balance_gdp: -3.5,  fiscal_space_index: 30 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2022, values: { public_debt_gdp: 40,  tax_burden_gdp: 12.0, budget_balance_gdp: -3.2,  fiscal_space_index: 38 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2022, values: { public_debt_gdp: 48,  tax_burden_gdp: 12.5, budget_balance_gdp: -5.5,  fiscal_space_index: 30 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2022, values: { public_debt_gdp: 62,  tax_burden_gdp: 15.5, budget_balance_gdp: -7.0,  fiscal_space_index: 28 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2022, values: { public_debt_gdp: 102, tax_burden_gdp: 20.0, budget_balance_gdp: -3.8,  fiscal_space_index: 15 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2022, values: { public_debt_gdp: 68,  tax_burden_gdp: 8.5,  budget_balance_gdp: 2.5,   fiscal_space_index: 35 } },
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2022, values: { public_debt_gdp: 44,  tax_burden_gdp: 12.0, budget_balance_gdp: -1.5,  fiscal_space_index: 40 } },
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2022, values: { public_debt_gdp: 18,  tax_burden_gdp: 7.5,  budget_balance_gdp: -1.0,  fiscal_space_index: 42 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2022, values: { public_debt_gdp: 50,  tax_burden_gdp: 10.0, budget_balance_gdp: -2.8,  fiscal_space_index: 28 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2022, values: { public_debt_gdp: 105, tax_burden_gdp: 15.5, budget_balance_gdp: -7.8,  fiscal_space_index: 10 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2022, values: { public_debt_gdp: 20,  tax_burden_gdp: 22.0, budget_balance_gdp: 1.8,   fiscal_space_index: 75 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2022, values: { public_debt_gdp: 80,  tax_burden_gdp: 19.5, budget_balance_gdp: -5.0,  fiscal_space_index: 35 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2022, values: { public_debt_gdp: 68,  tax_burden_gdp: 27.5, budget_balance_gdp: -5.2,  fiscal_space_index: 30 } },
    { geoCode: 'SD', geoName: 'Sudan',          dataYear: 2022, values: { public_debt_gdp: 182, tax_burden_gdp: 5.0,  budget_balance_gdp: -3.5,  fiscal_space_index: 5  } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2022, values: { public_debt_gdp: 50,  tax_burden_gdp: 14.5, budget_balance_gdp: -4.8,  fiscal_space_index: 28 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2022, values: { public_debt_gdp: 52,  tax_burden_gdp: 14.5, budget_balance_gdp: -7.0,  fiscal_space_index: 22 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2022, values: { public_debt_gdp: 48,  tax_burden_gdp: 10.5, budget_balance_gdp: -5.5,  fiscal_space_index: 25 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2022, values: { public_debt_gdp: 50,  tax_burden_gdp: 13.5, budget_balance_gdp: 3.0,   fiscal_space_index: 50 } },
    { geoCode: 'MW', geoName: 'Malawi',         dataYear: 2022, values: { public_debt_gdp: 70,  tax_burden_gdp: 13.5, budget_balance_gdp: -8.0,  fiscal_space_index: 12 } },
  ],
};

export default fiscalModule;
