import type { DomainModule } from '@/lib/domains/types';

const digitalModule: DomainModule = {
  definition: {
    id: 'digital',
    label: { fr: 'Numérique & Innovation', en: 'Digital & Innovation', es: 'Digital e Innovación' },
    description: {
      fr: 'Transformation numérique et capacité d\'innovation : e-gouvernement, cybersécurité, compétences numériques et innovation technologique.',
      en: 'Digital transformation and innovation capacity: e-government, cybersecurity, digital skills and technological innovation.',
      es: 'Transformación digital y capacidad de innovación: gobierno electrónico, ciberseguridad, competencias digitales e innovación tecnológica.',
    },
    icon: '💻',
    group: 'society',
    active: true,
    seedSources: [
      'https://publicadministration.un.org/egovkb/',
      'https://www.itu.int/en/ITU-D/Cybersecurity/Pages/global-cybersecurity-index.aspx',
      'https://www.wipo.int/global_innovation_index/',
    ],
    indicators: [
      {
        id: 'egov_index',
        label: { fr: 'Indice e-gouvernement', en: 'E-Government index', es: 'Índice de gobierno electrónico' },
        unit: 'index',
        unitLabel: { fr: 'score', en: 'score', es: 'score' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 0.85, good: 0.70, fair: 0.55, poor: 0.40 },
        minValue: 0,
        maxValue: 1,
      },
      {
        id: 'cybersecurity_index',
        label: { fr: 'Indice cybersécurité', en: 'Cybersecurity index', es: 'Índice de ciberseguridad' },
        unit: 'index',
        unitLabel: { fr: '/100', en: '/100', es: '/100' },
        direction: 'higher_is_better',
        weight: 2,
        thresholds: { excellent: 90, good: 70, fair: 50, poor: 30 },
        minValue: 0,
        maxValue: 100,
      },
      {
        id: 'digital_skills',
        label: { fr: 'Compétences numériques', en: 'Digital skills', es: 'Competencias digitales' },
        unit: 'index',
        unitLabel: { fr: '/100', en: '/100', es: '/100' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 80, good: 65, fair: 50, poor: 35 },
        minValue: 0,
        maxValue: 100,
      },
      {
        id: 'innovation_index',
        label: { fr: 'Indice d\'innovation', en: 'Innovation index', es: 'Índice de innovación' },
        unit: 'index',
        unitLabel: { fr: '/100', en: '/100', es: '/100' },
        direction: 'higher_is_better',
        weight: 3,
        thresholds: { excellent: 60, good: 45, fair: 30, poor: 18 },
        minValue: 0,
        maxValue: 100,
      },
    ],
  },
  seedData: [
    // ── Europe (Western, Northern, Southern) ───────────────────────────────
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2023, values: { egov_index: 0.97, cybersecurity_index: 92, digital_skills: 78, innovation_index: 62 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2023, values: { egov_index: 0.94, cybersecurity_index: 93, digital_skills: 82, innovation_index: 58 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2023, values: { egov_index: 0.92, cybersecurity_index: 94, digital_skills: 80, innovation_index: 64 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2023, values: { egov_index: 0.93, cybersecurity_index: 92, digital_skills: 79, innovation_index: 58 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2023, values: { egov_index: 0.89, cybersecurity_index: 86, digital_skills: 76, innovation_index: 55 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2023, values: { egov_index: 0.94, cybersecurity_index: 95, digital_skills: 74, innovation_index: 60 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2023, values: { egov_index: 0.93, cybersecurity_index: 92, digital_skills: 78, innovation_index: 60 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2023, values: { egov_index: 0.88, cybersecurity_index: 90, digital_skills: 75, innovation_index: 67 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2023, values: { egov_index: 0.85, cybersecurity_index: 91, digital_skills: 70, innovation_index: 58 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2023, values: { egov_index: 0.88, cybersecurity_index: 90, digital_skills: 62, innovation_index: 55 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2023, values: { egov_index: 0.86, cybersecurity_index: 85, digital_skills: 70, innovation_index: 50 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2023, values: { egov_index: 0.89, cybersecurity_index: 85, digital_skills: 68, innovation_index: 53 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2023, values: { egov_index: 0.82, cybersecurity_index: 84, digital_skills: 64, innovation_index: 52 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2023, values: { egov_index: 0.85, cybersecurity_index: 82, digital_skills: 72, innovation_index: 53 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2023, values: { egov_index: 0.87, cybersecurity_index: 88, digital_skills: 60, innovation_index: 47 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2023, values: { egov_index: 0.82, cybersecurity_index: 80, digital_skills: 55, innovation_index: 44 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2023, values: { egov_index: 0.79, cybersecurity_index: 86, digital_skills: 52, innovation_index: 46 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2023, values: { egov_index: 0.80, cybersecurity_index: 78, digital_skills: 58, innovation_index: 40 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2023, values: { egov_index: 0.75, cybersecurity_index: 72, digital_skills: 55, innovation_index: 38 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2023, values: { egov_index: 0.73, cybersecurity_index: 72, digital_skills: 48, innovation_index: 38 } },
    // ── Europe (Central & Eastern) ─────────────────────────────────────────
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2023, values: { egov_index: 0.91, cybersecurity_index: 90, digital_skills: 72, innovation_index: 50 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2023, values: { egov_index: 0.83, cybersecurity_index: 82, digital_skills: 60, innovation_index: 42 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2023, values: { egov_index: 0.80, cybersecurity_index: 78, digital_skills: 56, innovation_index: 39 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2023, values: { egov_index: 0.79, cybersecurity_index: 78, digital_skills: 52, innovation_index: 41 } },
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2023, values: { egov_index: 0.76, cybersecurity_index: 75, digital_skills: 60, innovation_index: 42 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2023, values: { egov_index: 0.70, cybersecurity_index: 68, digital_skills: 52, innovation_index: 37 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2023, values: { egov_index: 0.72, cybersecurity_index: 70, digital_skills: 50, innovation_index: 38 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2023, values: { egov_index: 0.78, cybersecurity_index: 76, digital_skills: 58, innovation_index: 43 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2023, values: { egov_index: 0.72, cybersecurity_index: 68, digital_skills: 50, innovation_index: 35 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2023, values: { egov_index: 0.65, cybersecurity_index: 62, digital_skills: 38, innovation_index: 32 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2023, values: { egov_index: 0.63, cybersecurity_index: 60, digital_skills: 36, innovation_index: 35 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2023, values: { egov_index: 0.55, cybersecurity_index: 48, digital_skills: 34, innovation_index: 26 } },
    // ── Europe (Balkans) ───────────────────────────────────────────────────
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2023, values: { egov_index: 0.68, cybersecurity_index: 62, digital_skills: 46, innovation_index: 34 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2023, values: { egov_index: 0.62, cybersecurity_index: 55, digital_skills: 42, innovation_index: 31 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2023, values: { egov_index: 0.60, cybersecurity_index: 52, digital_skills: 40, innovation_index: 29 } },
    { geoCode: 'BA', geoName: 'Bosnia & Herzegovina', dataYear: 2023, values: { egov_index: 0.55, cybersecurity_index: 48, digital_skills: 36, innovation_index: 26 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2023, values: { egov_index: 0.58, cybersecurity_index: 50, digital_skills: 38, innovation_index: 27 } },
    { geoCode: 'XK', geoName: 'Kosovo',         dataYear: 2023, values: { egov_index: 0.52, cybersecurity_index: 45, digital_skills: 35, innovation_index: 25 } },
    // ── Europe (Nordic micro-states & others) ──────────────────────────────
    { geoCode: 'LI', geoName: 'Liechtenstein',  dataYear: 2023, values: { egov_index: 0.76, cybersecurity_index: 74, digital_skills: 70, innovation_index: 55 } },
    { geoCode: 'MC', geoName: 'Monaco',         dataYear: 2023, values: { egov_index: 0.74, cybersecurity_index: 70, digital_skills: 68, innovation_index: 42 } },
    { geoCode: 'AD', geoName: 'Andorra',        dataYear: 2023, values: { egov_index: 0.68, cybersecurity_index: 62, digital_skills: 60, innovation_index: 35 } },
    // ── Ex-USSR Europe ─────────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2023, values: { egov_index: 0.78, cybersecurity_index: 72, digital_skills: 55, innovation_index: 36 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2023, values: { egov_index: 0.67, cybersecurity_index: 60, digital_skills: 48, innovation_index: 34 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2023, values: { egov_index: 0.70, cybersecurity_index: 58, digital_skills: 50, innovation_index: 30 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2023, values: { egov_index: 0.72, cybersecurity_index: 62, digital_skills: 45, innovation_index: 30 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2023, values: { egov_index: 0.62, cybersecurity_index: 52, digital_skills: 42, innovation_index: 28 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2023, values: { egov_index: 0.65, cybersecurity_index: 55, digital_skills: 40, innovation_index: 25 } },
    // ── North America ──────────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',  dataYear: 2023, values: { egov_index: 0.92, cybersecurity_index: 97, digital_skills: 72, innovation_index: 61 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2023, values: { egov_index: 0.90, cybersecurity_index: 88, digital_skills: 73, innovation_index: 53 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2023, values: { egov_index: 0.68, cybersecurity_index: 58, digital_skills: 40, innovation_index: 32 } },
    // ── Central America & Caribbean ────────────────────────────────────────
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2023, values: { egov_index: 0.65, cybersecurity_index: 56, digital_skills: 45, innovation_index: 33 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2023, values: { egov_index: 0.60, cybersecurity_index: 50, digital_skills: 40, innovation_index: 28 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2023, values: { egov_index: 0.42, cybersecurity_index: 32, digital_skills: 25, innovation_index: 20 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2023, values: { egov_index: 0.38, cybersecurity_index: 28, digital_skills: 22, innovation_index: 18 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2023, values: { egov_index: 0.48, cybersecurity_index: 38, digital_skills: 28, innovation_index: 22 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2023, values: { egov_index: 0.55, cybersecurity_index: 45, digital_skills: 35, innovation_index: 26 } },
    { geoCode: 'TT', geoName: 'Trinidad & Tobago', dataYear: 2023, values: { egov_index: 0.58, cybersecurity_index: 48, digital_skills: 38, innovation_index: 27 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2023, values: { egov_index: 0.52, cybersecurity_index: 42, digital_skills: 32, innovation_index: 24 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2023, values: { egov_index: 0.35, cybersecurity_index: 25, digital_skills: 30, innovation_index: 20 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2023, values: { egov_index: 0.36, cybersecurity_index: 26, digital_skills: 20, innovation_index: 17 } },
    // ── South America ──────────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2023, values: { egov_index: 0.76, cybersecurity_index: 72, digital_skills: 44, innovation_index: 33 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2023, values: { egov_index: 0.73, cybersecurity_index: 55, digital_skills: 50, innovation_index: 30 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2023, values: { egov_index: 0.78, cybersecurity_index: 68, digital_skills: 55, innovation_index: 37 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2023, values: { egov_index: 0.70, cybersecurity_index: 60, digital_skills: 42, innovation_index: 31 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2023, values: { egov_index: 0.62, cybersecurity_index: 50, digital_skills: 36, innovation_index: 27 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2023, values: { egov_index: 0.38, cybersecurity_index: 22, digital_skills: 30, innovation_index: 19 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2023, values: { egov_index: 0.58, cybersecurity_index: 45, digital_skills: 35, innovation_index: 25 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2023, values: { egov_index: 0.76, cybersecurity_index: 62, digital_skills: 52, innovation_index: 34 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2023, values: { egov_index: 0.48, cybersecurity_index: 38, digital_skills: 30, innovation_index: 22 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2023, values: { egov_index: 0.42, cybersecurity_index: 30, digital_skills: 25, innovation_index: 20 } },
    // ── East Asia ──────────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2023, values: { egov_index: 0.90, cybersecurity_index: 88, digital_skills: 68, innovation_index: 52 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2023, values: { egov_index: 0.95, cybersecurity_index: 96, digital_skills: 75, innovation_index: 56 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2023, values: { egov_index: 0.81, cybersecurity_index: 80, digital_skills: 58, innovation_index: 52 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2023, values: { egov_index: 0.82, cybersecurity_index: 84, digital_skills: 70, innovation_index: 46 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2023, values: { egov_index: 0.52, cybersecurity_index: 40, digital_skills: 35, innovation_index: 22 } },
    // ── Southeast Asia ─────────────────────────────────────────────────────
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2023, values: { egov_index: 0.95, cybersecurity_index: 97, digital_skills: 76, innovation_index: 59 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2023, values: { egov_index: 0.75, cybersecurity_index: 78, digital_skills: 52, innovation_index: 36 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2023, values: { egov_index: 0.68, cybersecurity_index: 65, digital_skills: 45, innovation_index: 35 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2023, values: { egov_index: 0.62, cybersecurity_index: 58, digital_skills: 40, innovation_index: 33 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2023, values: { egov_index: 0.57, cybersecurity_index: 55, digital_skills: 38, innovation_index: 30 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2023, values: { egov_index: 0.55, cybersecurity_index: 48, digital_skills: 35, innovation_index: 28 } },
    { geoCode: 'BN', geoName: 'Brunei',         dataYear: 2023, values: { egov_index: 0.66, cybersecurity_index: 60, digital_skills: 48, innovation_index: 27 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2023, values: { egov_index: 0.38, cybersecurity_index: 28, digital_skills: 22, innovation_index: 18 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2023, values: { egov_index: 0.34, cybersecurity_index: 22, digital_skills: 18, innovation_index: 15 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2023, values: { egov_index: 0.30, cybersecurity_index: 18, digital_skills: 16, innovation_index: 14 } },
    // ── South Asia ─────────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2023, values: { egov_index: 0.65, cybersecurity_index: 68, digital_skills: 42, innovation_index: 39 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2023, values: { egov_index: 0.55, cybersecurity_index: 45, digital_skills: 38, innovation_index: 26 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2023, values: { egov_index: 0.45, cybersecurity_index: 35, digital_skills: 28, innovation_index: 21 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2023, values: { egov_index: 0.40, cybersecurity_index: 32, digital_skills: 25, innovation_index: 22 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2023, values: { egov_index: 0.38, cybersecurity_index: 25, digital_skills: 22, innovation_index: 18 } },
    { geoCode: 'AF', geoName: 'Afghanistan',    dataYear: 2023, values: { egov_index: 0.15, cybersecurity_index: 8, digital_skills: 10, innovation_index: 10 } },
    // ── Central Asia ───────────────────────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2023, values: { egov_index: 0.76, cybersecurity_index: 65, digital_skills: 50, innovation_index: 29 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2023, values: { egov_index: 0.60, cybersecurity_index: 50, digital_skills: 35, innovation_index: 22 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2023, values: { egov_index: 0.50, cybersecurity_index: 38, digital_skills: 30, innovation_index: 20 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2023, values: { egov_index: 0.38, cybersecurity_index: 28, digital_skills: 22, innovation_index: 16 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2023, values: { egov_index: 0.32, cybersecurity_index: 20, digital_skills: 18, innovation_index: 14 } },
    // ── Middle East ────────────────────────────────────────────────────────
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2023, values: { egov_index: 0.90, cybersecurity_index: 96, digital_skills: 65, innovation_index: 42 } },
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2023, values: { egov_index: 0.82, cybersecurity_index: 99, digital_skills: 58, innovation_index: 36 } },
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2023, values: { egov_index: 0.84, cybersecurity_index: 90, digital_skills: 70, innovation_index: 57 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2023, values: { egov_index: 0.72, cybersecurity_index: 70, digital_skills: 48, innovation_index: 37 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2023, values: { egov_index: 0.78, cybersecurity_index: 85, digital_skills: 55, innovation_index: 35 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2023, values: { egov_index: 0.80, cybersecurity_index: 82, digital_skills: 52, innovation_index: 33 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2023, values: { egov_index: 0.72, cybersecurity_index: 72, digital_skills: 48, innovation_index: 30 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2023, values: { egov_index: 0.70, cybersecurity_index: 76, digital_skills: 46, innovation_index: 28 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2023, values: { egov_index: 0.62, cybersecurity_index: 58, digital_skills: 42, innovation_index: 28 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2023, values: { egov_index: 0.48, cybersecurity_index: 38, digital_skills: 40, innovation_index: 26 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2023, values: { egov_index: 0.52, cybersecurity_index: 40, digital_skills: 42, innovation_index: 33 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2023, values: { egov_index: 0.35, cybersecurity_index: 22, digital_skills: 22, innovation_index: 16 } },
    { geoCode: 'YE', geoName: 'Yemen',          dataYear: 2023, values: { egov_index: 0.18, cybersecurity_index: 8, digital_skills: 10, innovation_index: 9 } },
    { geoCode: 'SY', geoName: 'Syria',          dataYear: 2023, values: { egov_index: 0.22, cybersecurity_index: 12, digital_skills: 15, innovation_index: 11 } },
    // ── North Africa ───────────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2023, values: { egov_index: 0.53, cybersecurity_index: 52, digital_skills: 35, innovation_index: 25 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2023, values: { egov_index: 0.56, cybersecurity_index: 58, digital_skills: 38, innovation_index: 28 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2023, values: { egov_index: 0.58, cybersecurity_index: 55, digital_skills: 40, innovation_index: 27 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2023, values: { egov_index: 0.42, cybersecurity_index: 35, digital_skills: 28, innovation_index: 20 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2023, values: { egov_index: 0.30, cybersecurity_index: 18, digital_skills: 20, innovation_index: 14 } },
    // ── Sub-Saharan Africa (West) ──────────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2023, values: { egov_index: 0.38, cybersecurity_index: 28, digital_skills: 25, innovation_index: 18 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2023, values: { egov_index: 0.48, cybersecurity_index: 42, digital_skills: 30, innovation_index: 22 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2023, values: { egov_index: 0.42, cybersecurity_index: 38, digital_skills: 25, innovation_index: 20 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2023, values: { egov_index: 0.38, cybersecurity_index: 35, digital_skills: 22, innovation_index: 18 } },
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2023, values: { egov_index: 0.32, cybersecurity_index: 22, digital_skills: 18, innovation_index: 16 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2023, values: { egov_index: 0.25, cybersecurity_index: 15, digital_skills: 12, innovation_index: 13 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2023, values: { egov_index: 0.22, cybersecurity_index: 14, digital_skills: 11, innovation_index: 12 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2023, values: { egov_index: 0.18, cybersecurity_index: 10, digital_skills: 8, innovation_index: 10 } },
    { geoCode: 'GN', geoName: 'Guinea',         dataYear: 2023, values: { egov_index: 0.22, cybersecurity_index: 12, digital_skills: 10, innovation_index: 12 } },
    { geoCode: 'BJ', geoName: 'Benin',          dataYear: 2023, values: { egov_index: 0.30, cybersecurity_index: 22, digital_skills: 15, innovation_index: 15 } },
    { geoCode: 'TG', geoName: 'Togo',           dataYear: 2023, values: { egov_index: 0.28, cybersecurity_index: 20, digital_skills: 14, innovation_index: 14 } },
    // ── Sub-Saharan Africa (East) ──────────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2023, values: { egov_index: 0.52, cybersecurity_index: 45, digital_skills: 32, innovation_index: 24 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2023, values: { egov_index: 0.38, cybersecurity_index: 30, digital_skills: 20, innovation_index: 17 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2023, values: { egov_index: 0.35, cybersecurity_index: 28, digital_skills: 18, innovation_index: 16 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2023, values: { egov_index: 0.52, cybersecurity_index: 48, digital_skills: 28, innovation_index: 22 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2023, values: { egov_index: 0.27, cybersecurity_index: 12, digital_skills: 15, innovation_index: 15 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2023, values: { egov_index: 0.22, cybersecurity_index: 10, digital_skills: 10, innovation_index: 12 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2023, values: { egov_index: 0.25, cybersecurity_index: 14, digital_skills: 12, innovation_index: 13 } },
    { geoCode: 'SD', geoName: 'Sudan',          dataYear: 2023, values: { egov_index: 0.20, cybersecurity_index: 10, digital_skills: 12, innovation_index: 11 } },
    // ── Sub-Saharan Africa (Southern) ──────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2023, values: { egov_index: 0.60, cybersecurity_index: 55, digital_skills: 40, innovation_index: 31 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2023, values: { egov_index: 0.50, cybersecurity_index: 42, digital_skills: 35, innovation_index: 24 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2023, values: { egov_index: 0.45, cybersecurity_index: 36, digital_skills: 30, innovation_index: 22 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2023, values: { egov_index: 0.62, cybersecurity_index: 55, digital_skills: 42, innovation_index: 30 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2023, values: { egov_index: 0.30, cybersecurity_index: 18, digital_skills: 18, innovation_index: 15 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2023, values: { egov_index: 0.32, cybersecurity_index: 22, digital_skills: 16, innovation_index: 15 } },
    // ── Sub-Saharan Africa (Central) ───────────────────────────────────────
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2023, values: { egov_index: 0.18, cybersecurity_index: 8, digital_skills: 8, innovation_index: 10 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2023, values: { egov_index: 0.28, cybersecurity_index: 18, digital_skills: 15, innovation_index: 14 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2023, values: { egov_index: 0.35, cybersecurity_index: 28, digital_skills: 22, innovation_index: 18 } },
    { geoCode: 'CG', geoName: 'Congo',          dataYear: 2023, values: { egov_index: 0.22, cybersecurity_index: 12, digital_skills: 12, innovation_index: 12 } },
    { geoCode: 'TD', geoName: 'Chad',           dataYear: 2023, values: { egov_index: 0.15, cybersecurity_index: 6, digital_skills: 6, innovation_index: 8 } },
    { geoCode: 'CF', geoName: 'Central African Republic', dataYear: 2023, values: { egov_index: 0.12, cybersecurity_index: 5, digital_skills: 5, innovation_index: 7 } },
    // ── Oceania ────────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2023, values: { egov_index: 0.94, cybersecurity_index: 91, digital_skills: 74, innovation_index: 52 } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2023, values: { egov_index: 0.88, cybersecurity_index: 84, digital_skills: 72, innovation_index: 49 } },
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2023, values: { egov_index: 0.42, cybersecurity_index: 30, digital_skills: 28, innovation_index: 20 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2023, values: { egov_index: 0.25, cybersecurity_index: 12, digital_skills: 12, innovation_index: 12 } },
  ],
  seedDataPrev: [
    // ── Europe (Western, Northern, Southern) ───────────────────────────────
    { geoCode: 'DK', geoName: 'Denmark',        dataYear: 2022, values: { egov_index: 0.96, cybersecurity_index: 91, digital_skills: 77, innovation_index: 61 } },
    { geoCode: 'FI', geoName: 'Finland',        dataYear: 2022, values: { egov_index: 0.93, cybersecurity_index: 92, digital_skills: 81, innovation_index: 57 } },
    { geoCode: 'SE', geoName: 'Sweden',         dataYear: 2022, values: { egov_index: 0.91, cybersecurity_index: 93, digital_skills: 79, innovation_index: 63 } },
    { geoCode: 'NO', geoName: 'Norway',         dataYear: 2022, values: { egov_index: 0.92, cybersecurity_index: 91, digital_skills: 78, innovation_index: 57 } },
    { geoCode: 'IS', geoName: 'Iceland',        dataYear: 2022, values: { egov_index: 0.88, cybersecurity_index: 85, digital_skills: 75, innovation_index: 54 } },
    { geoCode: 'GB', geoName: 'United Kingdom', dataYear: 2022, values: { egov_index: 0.93, cybersecurity_index: 94, digital_skills: 73, innovation_index: 59 } },
    { geoCode: 'NL', geoName: 'Netherlands',    dataYear: 2022, values: { egov_index: 0.92, cybersecurity_index: 91, digital_skills: 77, innovation_index: 59 } },
    { geoCode: 'CH', geoName: 'Switzerland',    dataYear: 2022, values: { egov_index: 0.87, cybersecurity_index: 89, digital_skills: 74, innovation_index: 66 } },
    { geoCode: 'DE', geoName: 'Germany',        dataYear: 2022, values: { egov_index: 0.84, cybersecurity_index: 90, digital_skills: 69, innovation_index: 57 } },
    { geoCode: 'FR', geoName: 'France',         dataYear: 2022, values: { egov_index: 0.87, cybersecurity_index: 89, digital_skills: 61, innovation_index: 54 } },
    { geoCode: 'IE', geoName: 'Ireland',        dataYear: 2022, values: { egov_index: 0.85, cybersecurity_index: 84, digital_skills: 69, innovation_index: 49 } },
    { geoCode: 'AT', geoName: 'Austria',        dataYear: 2022, values: { egov_index: 0.88, cybersecurity_index: 84, digital_skills: 67, innovation_index: 52 } },
    { geoCode: 'BE', geoName: 'Belgium',        dataYear: 2022, values: { egov_index: 0.81, cybersecurity_index: 83, digital_skills: 63, innovation_index: 51 } },
    { geoCode: 'LU', geoName: 'Luxembourg',     dataYear: 2022, values: { egov_index: 0.84, cybersecurity_index: 81, digital_skills: 71, innovation_index: 52 } },
    { geoCode: 'ES', geoName: 'Spain',          dataYear: 2022, values: { egov_index: 0.86, cybersecurity_index: 87, digital_skills: 59, innovation_index: 46 } },
    { geoCode: 'PT', geoName: 'Portugal',       dataYear: 2022, values: { egov_index: 0.81, cybersecurity_index: 79, digital_skills: 54, innovation_index: 43 } },
    { geoCode: 'IT', geoName: 'Italy',          dataYear: 2022, values: { egov_index: 0.78, cybersecurity_index: 85, digital_skills: 51, innovation_index: 45 } },
    { geoCode: 'MT', geoName: 'Malta',          dataYear: 2022, values: { egov_index: 0.79, cybersecurity_index: 77, digital_skills: 57, innovation_index: 39 } },
    { geoCode: 'CY', geoName: 'Cyprus',         dataYear: 2022, values: { egov_index: 0.74, cybersecurity_index: 71, digital_skills: 54, innovation_index: 37 } },
    { geoCode: 'GR', geoName: 'Greece',         dataYear: 2022, values: { egov_index: 0.72, cybersecurity_index: 71, digital_skills: 47, innovation_index: 37 } },
    // ── Europe (Central & Eastern) ─────────────────────────────────────────
    { geoCode: 'EE', geoName: 'Estonia',        dataYear: 2022, values: { egov_index: 0.90, cybersecurity_index: 89, digital_skills: 71, innovation_index: 49 } },
    { geoCode: 'LT', geoName: 'Lithuania',      dataYear: 2022, values: { egov_index: 0.82, cybersecurity_index: 81, digital_skills: 59, innovation_index: 41 } },
    { geoCode: 'LV', geoName: 'Latvia',         dataYear: 2022, values: { egov_index: 0.79, cybersecurity_index: 77, digital_skills: 55, innovation_index: 38 } },
    { geoCode: 'PL', geoName: 'Poland',         dataYear: 2022, values: { egov_index: 0.78, cybersecurity_index: 77, digital_skills: 51, innovation_index: 40 } },
    { geoCode: 'CZ', geoName: 'Czechia',        dataYear: 2022, values: { egov_index: 0.75, cybersecurity_index: 74, digital_skills: 59, innovation_index: 41 } },
    { geoCode: 'SK', geoName: 'Slovakia',       dataYear: 2022, values: { egov_index: 0.69, cybersecurity_index: 67, digital_skills: 51, innovation_index: 36 } },
    { geoCode: 'HU', geoName: 'Hungary',        dataYear: 2022, values: { egov_index: 0.71, cybersecurity_index: 69, digital_skills: 49, innovation_index: 37 } },
    { geoCode: 'SI', geoName: 'Slovenia',       dataYear: 2022, values: { egov_index: 0.77, cybersecurity_index: 75, digital_skills: 57, innovation_index: 42 } },
    { geoCode: 'HR', geoName: 'Croatia',        dataYear: 2022, values: { egov_index: 0.71, cybersecurity_index: 67, digital_skills: 49, innovation_index: 34 } },
    { geoCode: 'RO', geoName: 'Romania',        dataYear: 2022, values: { egov_index: 0.64, cybersecurity_index: 61, digital_skills: 37, innovation_index: 31 } },
    { geoCode: 'BG', geoName: 'Bulgaria',       dataYear: 2022, values: { egov_index: 0.62, cybersecurity_index: 59, digital_skills: 35, innovation_index: 34 } },
    { geoCode: 'MD', geoName: 'Moldova',        dataYear: 2022, values: { egov_index: 0.54, cybersecurity_index: 47, digital_skills: 33, innovation_index: 25 } },
    // ── Europe (Balkans) ───────────────────────────────────────────────────
    { geoCode: 'RS', geoName: 'Serbia',         dataYear: 2022, values: { egov_index: 0.67, cybersecurity_index: 61, digital_skills: 45, innovation_index: 33 } },
    { geoCode: 'ME', geoName: 'Montenegro',     dataYear: 2022, values: { egov_index: 0.61, cybersecurity_index: 54, digital_skills: 41, innovation_index: 30 } },
    { geoCode: 'MK', geoName: 'North Macedonia', dataYear: 2022, values: { egov_index: 0.59, cybersecurity_index: 51, digital_skills: 39, innovation_index: 28 } },
    { geoCode: 'BA', geoName: 'Bosnia & Herzegovina', dataYear: 2022, values: { egov_index: 0.54, cybersecurity_index: 47, digital_skills: 35, innovation_index: 25 } },
    { geoCode: 'AL', geoName: 'Albania',        dataYear: 2022, values: { egov_index: 0.57, cybersecurity_index: 49, digital_skills: 37, innovation_index: 26 } },
    { geoCode: 'XK', geoName: 'Kosovo',         dataYear: 2022, values: { egov_index: 0.51, cybersecurity_index: 44, digital_skills: 34, innovation_index: 24 } },
    // ── Europe (Nordic micro-states & others) ──────────────────────────────
    { geoCode: 'LI', geoName: 'Liechtenstein',  dataYear: 2022, values: { egov_index: 0.75, cybersecurity_index: 73, digital_skills: 69, innovation_index: 54 } },
    { geoCode: 'MC', geoName: 'Monaco',         dataYear: 2022, values: { egov_index: 0.73, cybersecurity_index: 69, digital_skills: 67, innovation_index: 41 } },
    { geoCode: 'AD', geoName: 'Andorra',        dataYear: 2022, values: { egov_index: 0.67, cybersecurity_index: 61, digital_skills: 59, innovation_index: 34 } },
    // ── Ex-USSR Europe ─────────────────────────────────────────────────────
    { geoCode: 'RU', geoName: 'Russia',         dataYear: 2022, values: { egov_index: 0.77, cybersecurity_index: 71, digital_skills: 54, innovation_index: 35 } },
    { geoCode: 'UA', geoName: 'Ukraine',        dataYear: 2022, values: { egov_index: 0.66, cybersecurity_index: 59, digital_skills: 47, innovation_index: 33 } },
    { geoCode: 'BY', geoName: 'Belarus',        dataYear: 2022, values: { egov_index: 0.69, cybersecurity_index: 57, digital_skills: 49, innovation_index: 29 } },
    { geoCode: 'GE', geoName: 'Georgia',        dataYear: 2022, values: { egov_index: 0.71, cybersecurity_index: 61, digital_skills: 44, innovation_index: 29 } },
    { geoCode: 'AM', geoName: 'Armenia',        dataYear: 2022, values: { egov_index: 0.61, cybersecurity_index: 51, digital_skills: 41, innovation_index: 27 } },
    { geoCode: 'AZ', geoName: 'Azerbaijan',     dataYear: 2022, values: { egov_index: 0.64, cybersecurity_index: 54, digital_skills: 39, innovation_index: 24 } },
    // ── North America ──────────────────────────────────────────────────────
    { geoCode: 'US', geoName: 'United States',  dataYear: 2022, values: { egov_index: 0.91, cybersecurity_index: 96, digital_skills: 71, innovation_index: 60 } },
    { geoCode: 'CA', geoName: 'Canada',         dataYear: 2022, values: { egov_index: 0.89, cybersecurity_index: 87, digital_skills: 72, innovation_index: 52 } },
    { geoCode: 'MX', geoName: 'Mexico',         dataYear: 2022, values: { egov_index: 0.67, cybersecurity_index: 57, digital_skills: 39, innovation_index: 31 } },
    // ── Central America & Caribbean ────────────────────────────────────────
    { geoCode: 'CR', geoName: 'Costa Rica',     dataYear: 2022, values: { egov_index: 0.64, cybersecurity_index: 55, digital_skills: 44, innovation_index: 32 } },
    { geoCode: 'PA', geoName: 'Panama',         dataYear: 2022, values: { egov_index: 0.59, cybersecurity_index: 49, digital_skills: 39, innovation_index: 27 } },
    { geoCode: 'GT', geoName: 'Guatemala',      dataYear: 2022, values: { egov_index: 0.41, cybersecurity_index: 31, digital_skills: 24, innovation_index: 19 } },
    { geoCode: 'HN', geoName: 'Honduras',       dataYear: 2022, values: { egov_index: 0.37, cybersecurity_index: 27, digital_skills: 21, innovation_index: 17 } },
    { geoCode: 'SV', geoName: 'El Salvador',    dataYear: 2022, values: { egov_index: 0.47, cybersecurity_index: 37, digital_skills: 27, innovation_index: 21 } },
    { geoCode: 'JM', geoName: 'Jamaica',        dataYear: 2022, values: { egov_index: 0.54, cybersecurity_index: 44, digital_skills: 34, innovation_index: 25 } },
    { geoCode: 'TT', geoName: 'Trinidad & Tobago', dataYear: 2022, values: { egov_index: 0.57, cybersecurity_index: 47, digital_skills: 37, innovation_index: 26 } },
    { geoCode: 'DO', geoName: 'Dominican Republic', dataYear: 2022, values: { egov_index: 0.51, cybersecurity_index: 41, digital_skills: 31, innovation_index: 23 } },
    { geoCode: 'CU', geoName: 'Cuba',           dataYear: 2022, values: { egov_index: 0.34, cybersecurity_index: 24, digital_skills: 29, innovation_index: 19 } },
    { geoCode: 'NI', geoName: 'Nicaragua',      dataYear: 2022, values: { egov_index: 0.35, cybersecurity_index: 25, digital_skills: 19, innovation_index: 16 } },
    // ── South America ──────────────────────────────────────────────────────
    { geoCode: 'BR', geoName: 'Brazil',         dataYear: 2022, values: { egov_index: 0.75, cybersecurity_index: 71, digital_skills: 43, innovation_index: 32 } },
    { geoCode: 'AR', geoName: 'Argentina',      dataYear: 2022, values: { egov_index: 0.72, cybersecurity_index: 54, digital_skills: 49, innovation_index: 29 } },
    { geoCode: 'CL', geoName: 'Chile',          dataYear: 2022, values: { egov_index: 0.77, cybersecurity_index: 67, digital_skills: 54, innovation_index: 36 } },
    { geoCode: 'CO', geoName: 'Colombia',       dataYear: 2022, values: { egov_index: 0.69, cybersecurity_index: 59, digital_skills: 41, innovation_index: 30 } },
    { geoCode: 'PE', geoName: 'Peru',           dataYear: 2022, values: { egov_index: 0.61, cybersecurity_index: 49, digital_skills: 35, innovation_index: 26 } },
    { geoCode: 'VE', geoName: 'Venezuela',      dataYear: 2022, values: { egov_index: 0.37, cybersecurity_index: 21, digital_skills: 29, innovation_index: 18 } },
    { geoCode: 'EC', geoName: 'Ecuador',        dataYear: 2022, values: { egov_index: 0.57, cybersecurity_index: 44, digital_skills: 34, innovation_index: 24 } },
    { geoCode: 'UY', geoName: 'Uruguay',        dataYear: 2022, values: { egov_index: 0.75, cybersecurity_index: 61, digital_skills: 51, innovation_index: 33 } },
    { geoCode: 'PY', geoName: 'Paraguay',       dataYear: 2022, values: { egov_index: 0.47, cybersecurity_index: 37, digital_skills: 29, innovation_index: 21 } },
    { geoCode: 'BO', geoName: 'Bolivia',        dataYear: 2022, values: { egov_index: 0.41, cybersecurity_index: 29, digital_skills: 24, innovation_index: 19 } },
    // ── East Asia ──────────────────────────────────────────────────────────
    { geoCode: 'JP', geoName: 'Japan',          dataYear: 2022, values: { egov_index: 0.89, cybersecurity_index: 87, digital_skills: 67, innovation_index: 51 } },
    { geoCode: 'KR', geoName: 'South Korea',    dataYear: 2022, values: { egov_index: 0.94, cybersecurity_index: 95, digital_skills: 74, innovation_index: 55 } },
    { geoCode: 'CN', geoName: 'China',          dataYear: 2022, values: { egov_index: 0.80, cybersecurity_index: 79, digital_skills: 57, innovation_index: 51 } },
    { geoCode: 'TW', geoName: 'Taiwan',         dataYear: 2022, values: { egov_index: 0.81, cybersecurity_index: 83, digital_skills: 69, innovation_index: 45 } },
    { geoCode: 'MN', geoName: 'Mongolia',       dataYear: 2022, values: { egov_index: 0.51, cybersecurity_index: 39, digital_skills: 34, innovation_index: 21 } },
    // ── Southeast Asia ─────────────────────────────────────────────────────
    { geoCode: 'SG', geoName: 'Singapore',      dataYear: 2022, values: { egov_index: 0.94, cybersecurity_index: 96, digital_skills: 75, innovation_index: 58 } },
    { geoCode: 'MY', geoName: 'Malaysia',       dataYear: 2022, values: { egov_index: 0.74, cybersecurity_index: 77, digital_skills: 51, innovation_index: 35 } },
    { geoCode: 'TH', geoName: 'Thailand',       dataYear: 2022, values: { egov_index: 0.67, cybersecurity_index: 64, digital_skills: 44, innovation_index: 34 } },
    { geoCode: 'VN', geoName: 'Vietnam',        dataYear: 2022, values: { egov_index: 0.61, cybersecurity_index: 57, digital_skills: 39, innovation_index: 32 } },
    { geoCode: 'ID', geoName: 'Indonesia',      dataYear: 2022, values: { egov_index: 0.56, cybersecurity_index: 54, digital_skills: 37, innovation_index: 29 } },
    { geoCode: 'PH', geoName: 'Philippines',    dataYear: 2022, values: { egov_index: 0.54, cybersecurity_index: 47, digital_skills: 34, innovation_index: 27 } },
    { geoCode: 'BN', geoName: 'Brunei',         dataYear: 2022, values: { egov_index: 0.65, cybersecurity_index: 59, digital_skills: 47, innovation_index: 26 } },
    { geoCode: 'KH', geoName: 'Cambodia',       dataYear: 2022, values: { egov_index: 0.37, cybersecurity_index: 27, digital_skills: 21, innovation_index: 17 } },
    { geoCode: 'LA', geoName: 'Laos',           dataYear: 2022, values: { egov_index: 0.33, cybersecurity_index: 21, digital_skills: 17, innovation_index: 14 } },
    { geoCode: 'MM', geoName: 'Myanmar',        dataYear: 2022, values: { egov_index: 0.29, cybersecurity_index: 17, digital_skills: 15, innovation_index: 13 } },
    // ── South Asia ─────────────────────────────────────────────────────────
    { geoCode: 'IN', geoName: 'India',          dataYear: 2022, values: { egov_index: 0.64, cybersecurity_index: 67, digital_skills: 41, innovation_index: 38 } },
    { geoCode: 'LK', geoName: 'Sri Lanka',      dataYear: 2022, values: { egov_index: 0.54, cybersecurity_index: 44, digital_skills: 37, innovation_index: 25 } },
    { geoCode: 'BD', geoName: 'Bangladesh',     dataYear: 2022, values: { egov_index: 0.44, cybersecurity_index: 34, digital_skills: 27, innovation_index: 20 } },
    { geoCode: 'PK', geoName: 'Pakistan',       dataYear: 2022, values: { egov_index: 0.39, cybersecurity_index: 31, digital_skills: 24, innovation_index: 21 } },
    { geoCode: 'NP', geoName: 'Nepal',          dataYear: 2022, values: { egov_index: 0.37, cybersecurity_index: 24, digital_skills: 21, innovation_index: 17 } },
    { geoCode: 'AF', geoName: 'Afghanistan',    dataYear: 2022, values: { egov_index: 0.14, cybersecurity_index: 7, digital_skills: 9, innovation_index: 9 } },
    // ── Central Asia ───────────────────────────────────────────────────────
    { geoCode: 'KZ', geoName: 'Kazakhstan',     dataYear: 2022, values: { egov_index: 0.75, cybersecurity_index: 64, digital_skills: 49, innovation_index: 28 } },
    { geoCode: 'UZ', geoName: 'Uzbekistan',     dataYear: 2022, values: { egov_index: 0.59, cybersecurity_index: 49, digital_skills: 34, innovation_index: 21 } },
    { geoCode: 'KG', geoName: 'Kyrgyzstan',     dataYear: 2022, values: { egov_index: 0.49, cybersecurity_index: 37, digital_skills: 29, innovation_index: 19 } },
    { geoCode: 'TJ', geoName: 'Tajikistan',     dataYear: 2022, values: { egov_index: 0.37, cybersecurity_index: 27, digital_skills: 21, innovation_index: 15 } },
    { geoCode: 'TM', geoName: 'Turkmenistan',   dataYear: 2022, values: { egov_index: 0.31, cybersecurity_index: 19, digital_skills: 17, innovation_index: 13 } },
    // ── Middle East ────────────────────────────────────────────────────────
    { geoCode: 'AE', geoName: 'United Arab Emirates', dataYear: 2022, values: { egov_index: 0.89, cybersecurity_index: 95, digital_skills: 64, innovation_index: 41 } },
    { geoCode: 'SA', geoName: 'Saudi Arabia',   dataYear: 2022, values: { egov_index: 0.81, cybersecurity_index: 98, digital_skills: 57, innovation_index: 35 } },
    { geoCode: 'IL', geoName: 'Israel',         dataYear: 2022, values: { egov_index: 0.83, cybersecurity_index: 89, digital_skills: 69, innovation_index: 56 } },
    { geoCode: 'TR', geoName: 'Turkey',         dataYear: 2022, values: { egov_index: 0.71, cybersecurity_index: 69, digital_skills: 47, innovation_index: 36 } },
    { geoCode: 'QA', geoName: 'Qatar',          dataYear: 2022, values: { egov_index: 0.77, cybersecurity_index: 84, digital_skills: 54, innovation_index: 34 } },
    { geoCode: 'BH', geoName: 'Bahrain',        dataYear: 2022, values: { egov_index: 0.79, cybersecurity_index: 81, digital_skills: 51, innovation_index: 32 } },
    { geoCode: 'KW', geoName: 'Kuwait',         dataYear: 2022, values: { egov_index: 0.71, cybersecurity_index: 71, digital_skills: 47, innovation_index: 29 } },
    { geoCode: 'OM', geoName: 'Oman',           dataYear: 2022, values: { egov_index: 0.69, cybersecurity_index: 75, digital_skills: 45, innovation_index: 27 } },
    { geoCode: 'JO', geoName: 'Jordan',         dataYear: 2022, values: { egov_index: 0.61, cybersecurity_index: 57, digital_skills: 41, innovation_index: 27 } },
    { geoCode: 'LB', geoName: 'Lebanon',        dataYear: 2022, values: { egov_index: 0.47, cybersecurity_index: 37, digital_skills: 39, innovation_index: 25 } },
    { geoCode: 'IR', geoName: 'Iran',           dataYear: 2022, values: { egov_index: 0.51, cybersecurity_index: 39, digital_skills: 41, innovation_index: 32 } },
    { geoCode: 'IQ', geoName: 'Iraq',           dataYear: 2022, values: { egov_index: 0.34, cybersecurity_index: 21, digital_skills: 21, innovation_index: 15 } },
    { geoCode: 'YE', geoName: 'Yemen',          dataYear: 2022, values: { egov_index: 0.17, cybersecurity_index: 7, digital_skills: 9, innovation_index: 8 } },
    { geoCode: 'SY', geoName: 'Syria',          dataYear: 2022, values: { egov_index: 0.21, cybersecurity_index: 11, digital_skills: 14, innovation_index: 10 } },
    // ── North Africa ───────────────────────────────────────────────────────
    { geoCode: 'EG', geoName: 'Egypt',          dataYear: 2022, values: { egov_index: 0.52, cybersecurity_index: 51, digital_skills: 34, innovation_index: 24 } },
    { geoCode: 'MA', geoName: 'Morocco',        dataYear: 2022, values: { egov_index: 0.55, cybersecurity_index: 57, digital_skills: 37, innovation_index: 27 } },
    { geoCode: 'TN', geoName: 'Tunisia',        dataYear: 2022, values: { egov_index: 0.57, cybersecurity_index: 54, digital_skills: 39, innovation_index: 26 } },
    { geoCode: 'DZ', geoName: 'Algeria',        dataYear: 2022, values: { egov_index: 0.41, cybersecurity_index: 34, digital_skills: 27, innovation_index: 19 } },
    { geoCode: 'LY', geoName: 'Libya',          dataYear: 2022, values: { egov_index: 0.29, cybersecurity_index: 17, digital_skills: 19, innovation_index: 13 } },
    // ── Sub-Saharan Africa (West) ──────────────────────────────────────────
    { geoCode: 'NG', geoName: 'Nigeria',        dataYear: 2022, values: { egov_index: 0.37, cybersecurity_index: 27, digital_skills: 24, innovation_index: 17 } },
    { geoCode: 'GH', geoName: 'Ghana',          dataYear: 2022, values: { egov_index: 0.47, cybersecurity_index: 41, digital_skills: 29, innovation_index: 21 } },
    { geoCode: 'SN', geoName: 'Senegal',        dataYear: 2022, values: { egov_index: 0.41, cybersecurity_index: 37, digital_skills: 24, innovation_index: 19 } },
    { geoCode: 'CI', geoName: 'Ivory Coast',    dataYear: 2022, values: { egov_index: 0.37, cybersecurity_index: 34, digital_skills: 21, innovation_index: 17 } },
    { geoCode: 'CM', geoName: 'Cameroon',       dataYear: 2022, values: { egov_index: 0.31, cybersecurity_index: 21, digital_skills: 17, innovation_index: 15 } },
    { geoCode: 'BF', geoName: 'Burkina Faso',   dataYear: 2022, values: { egov_index: 0.24, cybersecurity_index: 14, digital_skills: 11, innovation_index: 12 } },
    { geoCode: 'ML', geoName: 'Mali',           dataYear: 2022, values: { egov_index: 0.21, cybersecurity_index: 13, digital_skills: 10, innovation_index: 11 } },
    { geoCode: 'NE', geoName: 'Niger',          dataYear: 2022, values: { egov_index: 0.17, cybersecurity_index: 9, digital_skills: 7, innovation_index: 9 } },
    { geoCode: 'GN', geoName: 'Guinea',         dataYear: 2022, values: { egov_index: 0.21, cybersecurity_index: 11, digital_skills: 9, innovation_index: 11 } },
    { geoCode: 'BJ', geoName: 'Benin',          dataYear: 2022, values: { egov_index: 0.29, cybersecurity_index: 21, digital_skills: 14, innovation_index: 14 } },
    { geoCode: 'TG', geoName: 'Togo',           dataYear: 2022, values: { egov_index: 0.27, cybersecurity_index: 19, digital_skills: 13, innovation_index: 13 } },
    // ── Sub-Saharan Africa (East) ──────────────────────────────────────────
    { geoCode: 'KE', geoName: 'Kenya',          dataYear: 2022, values: { egov_index: 0.51, cybersecurity_index: 44, digital_skills: 31, innovation_index: 23 } },
    { geoCode: 'TZ', geoName: 'Tanzania',       dataYear: 2022, values: { egov_index: 0.37, cybersecurity_index: 29, digital_skills: 19, innovation_index: 16 } },
    { geoCode: 'UG', geoName: 'Uganda',         dataYear: 2022, values: { egov_index: 0.34, cybersecurity_index: 27, digital_skills: 17, innovation_index: 15 } },
    { geoCode: 'RW', geoName: 'Rwanda',         dataYear: 2022, values: { egov_index: 0.51, cybersecurity_index: 47, digital_skills: 27, innovation_index: 21 } },
    { geoCode: 'ET', geoName: 'Ethiopia',       dataYear: 2022, values: { egov_index: 0.26, cybersecurity_index: 11, digital_skills: 14, innovation_index: 14 } },
    { geoCode: 'MG', geoName: 'Madagascar',     dataYear: 2022, values: { egov_index: 0.21, cybersecurity_index: 9, digital_skills: 9, innovation_index: 11 } },
    { geoCode: 'MZ', geoName: 'Mozambique',     dataYear: 2022, values: { egov_index: 0.24, cybersecurity_index: 13, digital_skills: 11, innovation_index: 12 } },
    { geoCode: 'SD', geoName: 'Sudan',          dataYear: 2022, values: { egov_index: 0.19, cybersecurity_index: 9, digital_skills: 11, innovation_index: 10 } },
    // ── Sub-Saharan Africa (Southern) ──────────────────────────────────────
    { geoCode: 'ZA', geoName: 'South Africa',   dataYear: 2022, values: { egov_index: 0.59, cybersecurity_index: 54, digital_skills: 39, innovation_index: 30 } },
    { geoCode: 'BW', geoName: 'Botswana',       dataYear: 2022, values: { egov_index: 0.49, cybersecurity_index: 41, digital_skills: 34, innovation_index: 23 } },
    { geoCode: 'NA', geoName: 'Namibia',        dataYear: 2022, values: { egov_index: 0.44, cybersecurity_index: 35, digital_skills: 29, innovation_index: 21 } },
    { geoCode: 'MU', geoName: 'Mauritius',      dataYear: 2022, values: { egov_index: 0.61, cybersecurity_index: 54, digital_skills: 41, innovation_index: 29 } },
    { geoCode: 'ZW', geoName: 'Zimbabwe',       dataYear: 2022, values: { egov_index: 0.29, cybersecurity_index: 17, digital_skills: 17, innovation_index: 14 } },
    { geoCode: 'ZM', geoName: 'Zambia',         dataYear: 2022, values: { egov_index: 0.31, cybersecurity_index: 21, digital_skills: 15, innovation_index: 14 } },
    // ── Sub-Saharan Africa (Central) ───────────────────────────────────────
    { geoCode: 'CD', geoName: 'DR Congo',       dataYear: 2022, values: { egov_index: 0.17, cybersecurity_index: 7, digital_skills: 7, innovation_index: 9 } },
    { geoCode: 'AO', geoName: 'Angola',         dataYear: 2022, values: { egov_index: 0.27, cybersecurity_index: 17, digital_skills: 14, innovation_index: 13 } },
    { geoCode: 'GA', geoName: 'Gabon',          dataYear: 2022, values: { egov_index: 0.34, cybersecurity_index: 27, digital_skills: 21, innovation_index: 17 } },
    { geoCode: 'CG', geoName: 'Congo',          dataYear: 2022, values: { egov_index: 0.21, cybersecurity_index: 11, digital_skills: 11, innovation_index: 11 } },
    { geoCode: 'TD', geoName: 'Chad',           dataYear: 2022, values: { egov_index: 0.14, cybersecurity_index: 5, digital_skills: 5, innovation_index: 7 } },
    { geoCode: 'CF', geoName: 'Central African Republic', dataYear: 2022, values: { egov_index: 0.11, cybersecurity_index: 4, digital_skills: 4, innovation_index: 6 } },
    // ── Oceania ────────────────────────────────────────────────────────────
    { geoCode: 'AU', geoName: 'Australia',      dataYear: 2022, values: { egov_index: 0.93, cybersecurity_index: 90, digital_skills: 73, innovation_index: 51 } },
    { geoCode: 'NZ', geoName: 'New Zealand',    dataYear: 2022, values: { egov_index: 0.87, cybersecurity_index: 83, digital_skills: 71, innovation_index: 48 } },
    { geoCode: 'FJ', geoName: 'Fiji',           dataYear: 2022, values: { egov_index: 0.41, cybersecurity_index: 29, digital_skills: 27, innovation_index: 19 } },
    { geoCode: 'PG', geoName: 'Papua New Guinea', dataYear: 2022, values: { egov_index: 0.24, cybersecurity_index: 11, digital_skills: 11, innovation_index: 11 } },
  ],
};

export default digitalModule;
